### ISSUE TITLE
seq2seq example failed

### ISSUE THREAD

**Issue by taineleau** [facebookresearch/ParlAI#1001]
I tried to run the seq2seq example in the tutorial:
```
python examples/train_model.py -t babi:task10k:1 --dict-file /tmp/dict_babi:task10k:1 -bs 32 -vtim 30 -vcut 0.95 -m example_seq2seq --no-cuda -lr 0.01
```

but found `self.map_valid` return 5 values instead of 4. 

```
[ training... ]
Traceback (most recent call last):
  File "examples/train_model.py", line 28, in <module>
    TrainLoop(opt).train()
  File "/private/home/danluchen/ParlAI/parlai/scripts/train_model.py", line 299, in train
    world.parley()
  File "/private/home/danluchen/ParlAI/parlai/core/worlds.py", line 637, in parley
    batch_act = self.batch_act(agent_idx, batch_observations[agent_idx])
  File "/private/home/danluchen/ParlAI/parlai/core/worlds.py", line 610, in batch_act
    batch_actions = a.batch_act(batch_observation)
  File "/private/home/danluchen/ParlAI/parlai/agents/example_seq2seq/example_seq2seq.py", line 236, in batch_act
    xs, ys, labels, valid_inds = self.map_valid(vec_obs)
ValueError: too many values to unpack (expected 4)
```

**Comment by alexholdenmiller** [comment]
Oops this will be fixed in #974
