### ISSUE TITLE
interactive.py example missing files

### ISSUE THREAD

**Issue by santiontanon** [facebookresearch/ParlAI#1173]
Hi I just installed ParlAI, and when trying to run the interactive.py example, it is missing the "crawl-300d-2M.vec" data file. Also, the .opt file refer to specific folders such as "/private/home/edinan/ParlAI/data/models/fasttext_cc_vectors/crawl-300d-2M.vec", so, unless I'm doing something wrong, it's not going to run in anyone else's machine.

**Comment by santiontanon** [comment]
Sure! This is what I did exactly:
- cloned the repo
- python3 setup.py develop
- python3 interactive.py -mf "models:drqa/squad/model"

(here I had to install packages like torch, image, etc. as I was seeing errors)

So, I basically copied the commands from the README files in the repo. After that I got this error message: 

```
[ warning: overriding opt['model_file'] to /Users/santiontanon/research/ParlAI/data/models/drqa/squad/model (previously: /checkpoint/edinan/20180618/drqa_sweep_re_vs_spacy/tok=re_learningrate=0.003_dropoutemb=0.3_dropoutrnn=0.4/model )]
[ Loading model /Users/santiontanon/research/ParlAI/data/models/drqa/squad/model ]
Traceback (most recent call last):
  File "interactive.py", line 26, in <module>
    interactive(opt, print_parser=parser)
  File "/Users/santiontanon/research/ParlAI/parlai/scripts/interactive.py", line 52, in interactive
    agent = create_agent(opt, requireModelExists=True)
  File "/Users/santiontanon/research/ParlAI/parlai/core/agents.py", line 447, in create_agent
    model = load_agent_module(opt)
  File "/Users/santiontanon/research/ParlAI/parlai/core/agents.py", line 342, in load_agent_module
    return model_class(new_opt)
  File "/Users/santiontanon/research/ParlAI/parlai/agents/drqa/drqa.py", line 139, in __init__
    config.set_defaults(self.opt)
  File "/Users/santiontanon/research/ParlAI/parlai/agents/drqa/config.py", line 93, in set_defaults
    raise IOError('No such file: %s' % opt['embedding_file'])
OSError: No such file: /private/home/edinan/ParlAI/data/models/fasttext_cc_vectors/crawl-300d-2M.vec

```
I downloaded the crawl-300d-2M.vec file separately after I saw the error, but looking at the data/models/drqa/squad/model.opt  file, I saw that there are a lot of references to a specific user home folder ("/private/home/edinan"), so, I stopped there.

**Comment by santiontanon** [comment]
Thanks for the quick fix!!!

It moved a bit forward but didn't quite yet work. I modified the config.py file to make it work on my system, but this is what I had to do:
- in config.py I changed line 101 to:
    if opt.get('embedding_type') != 'random' and opt.get('embedding_type') != None:
since for some reason opt['embedding_type'] was None
- But then it goes into the "elif" part of the code, and opt.get('embedding_file') still has a filename referring to /private/home/edinan, so I just manually added a line opt['embedding_file'] = '<the path where I have crawl-300d-2M.vec'. So, I think that path has to be fixed still.

Thanks a lot for the very fast responses! I can make it work now with my little hack, but happy to test again if you do another push, just to see if it works out of the box!

**Comment by emilydinan** [comment]
Yep sorry I realized there was a bug and made a fix after I commented here. Try the latest version!

**Comment by emilydinan** [comment]
Note: to interact with this model, you have to give input in the form of "context \n question"

**Comment by santiontanon** [comment]
yep! That one worked for me!!! Thanks again!
