### ISSUE TITLE
random tries to index a set in tutorial

### ISSUE THREAD

**Issue by erohmensing** [facebookresearch/ParlAI#1398]
In the tutorial code, changing the act function to include a random response when it doesn't know, as described under **Validation and Testing** in `tutorial_basic.rst`:
```def act(self):
    reply = {'id': self.id}
    if 'labels' in self.observation:
        reply['text'] = ', '.join(self.observation['labels'])
    elif 'label_candidates' in self.observation:
        cands = self.observation['label_candidates']
        reply['text'] = random.choice(cands)
    else:
        reply['text'] = "I don't know."
    return reply
```

Creates this error message
```Traceback (most recent call last):
  File "tutorial_agent.py", line 38, in <module>
    world.parley()
  File "/Users/user_name/ParlAI/parlai/core/worlds.py", line 249, in parley
    acts[1] = agents[1].act()
  File "tutorial_agent.py", line 25, in act
    reply['text'] = random.choice(cands)
  File "/Users/user_name/anaconda3/envs/virtualenv/lib/python3.6/random.py", line 261, in choice
    return seq[i]
TypeError: 'set' object does not support indexing
```

But I was able to get `random.choice` to function by changing

> reply['text'] = random.choice(cands)

to

>  reply['text'] = random.choice(tuple(cands))

**Comment by stephenroller** [comment]
Thanks for pointing this out!
