### ISSUE TITLE
Help in Wikipedia Retrieval

### ISSUE THREAD

**Issue by DavidTheWinner** [facebookresearch/ParlAI#1476]
C:\Users\dchen>python -m parlai.scripts.interactive --model tfidf_retriever -mf models:wikipedia_2016-12-21/tfidf_retriever/drqa_docs
Traceback (most recent call last):
  File "C:\Users\dchen\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\dchen\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\users\dchen\~\parlai\parlai\scripts\interactive.py", line 76, in <module>
    interactive(parser.parse_args(print_args=False), print_parser=parser)
  File "c:\users\dchen\~\parlai\parlai\scripts\interactive.py", line 54, in interactive
    agent = create_agent(opt, requireModelExists=True)
  File "c:\users\dchen\~\parlai\parlai\core\agents.py", line 483, in create_agent
    model = load_agent_module(opt)
  File "c:\users\dchen\~\parlai\parlai\core\agents.py", line 320, in load_agent_module
    new_opt = json.load(handle)
  File "C:\Users\dchen\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\dchen\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\dchen\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\dchen\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by stephenroller** [comment]
Honestly we don't make any effort to support Windows, so I can't tell what's wrong. What *looks* wrong is that the download failed and so nothing is being read.

**Comment by stephenroller** [comment]
Closing for now, please reopen if you have more questions.
