### ISSUE TITLE
Cuda Initialization error

### ISSUE THREAD

**Issue by louismartin** [facebookresearch/ParlAI#1531]
It seems that hogwild training causes pytorch to crash.

Repro:
```
python examples/train_model.py -t babi:task1k:1 -mf /tmp/babi_memnn -bs 8 -nt 4 -eps 5 -m memnn
```

Error:
```
Process HogwildProcess-1:
Traceback (most recent call last):
  File "/private/home/louismartin/miniconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/private/home/louismartin/ParlAI/parlai/core/worlds.py", line 757, in run
    world = self.shared['world_class'](self.opt, None, self.shared)
  File "/private/home/louismartin/ParlAI/parlai/core/worlds.py", line 235, in __init__
    self.agents = create_agents_from_shared(shared['agents'])
  File "/private/home/louismartin/ParlAI/parlai/core/agents.py", line 523, in create_agents_from_shared
    agent = create_agent_from_shared(shared_agent)
  File "/private/home/louismartin/ParlAI/parlai/core/agents.py", line 509, in create_agent_from_shared
    a = shared_agent['class'](opt, shared_agent)
  File "/private/home/louismartin/ParlAI/parlai/agents/memnn/memnn.py", line 70, in __init__
    super().__init__(opt, shared)
  File "/private/home/louismartin/ParlAI/parlai/core/torch_ranker_agent.py", line 81, in __init__
    self.model.cuda()
  File "/private/home/louismartin/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 260, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/private/home/louismartin/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/private/home/louismartin/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    param.data = fn(param.data)
  File "/private/home/louismartin/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 260, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: initialization error
... (same for other processes)
```

Works fine when running on one thread:
```
python examples/train_model.py -t babi:task1k:1 -mf /tmp/babi_memnn -bs 8 -nt 1 -eps 5 -m memnn
```

Might be  the same problem as #1269 and probably related to this [pytorch issue](https://github.com/pytorch/pytorch/issues/2517)

- Python 3.6.7
- pytorch 1.0.0
- Parlai commit https://github.com/facebookresearch/ParlAI/tree/c3dd258ec76607054938494f3af04f77e25fd911
- Ubuntu 18.04.1 LTS
- GPUS: 2x Quadro GP100

**Comment by stephenroller** [comment]
You can’t mix Cuda with Hogwild. Add the `—no-cuda true`
