### ISSUE TITLE
Running examples doesn't work

### ISSUE THREAD

**Issue by ArmenAg** [facebookresearch/ParlAI#159]
I installed ParlAI using the installation instructions provided in the readme file. I then tried to run the training example using 

`python examples/train_model.py -m drqa -t squad -bs 32 -mf /tmp/model`

I get the following error message:
```
[ Loading model None ]
Traceback (most recent call last):
  File "examples/train_model.py", line 161, in <module>
    main()
  File "examples/train_model.py", line 93, in main
    agent = create_agent(opt)
  File "/root/ParlAI/parlai/core/agents.py", line 283, in create_agent
    return model_class(opt)
  File "/root/ParlAI/parlai/agents/drqa/drqa.py", line 139, in __init__
    self._init_from_saved(opt['pretrained_model'])
  File "/root/ParlAI/parlai/agents/drqa/drqa.py", line 161, in _init_from_saved
    map_location=lambda storage, loc: storage
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 229, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 362, in _load
    return legacy_load(f)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 297, in legacy_load
    with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT)) as tar, \
  File "/usr/local/anaconda3/lib/python3.6/tarfile.py", line 1553, in open
    raise ValueError("nothing to open")
ValueError: nothing to open
```
It seems to me that even though `--pretrained_model` is set to None, the code in drqa.py still tries to run it. I tried changing the condition in drqa.py to 
```
if 'pretrained_model' in self.opt and self.opt['pretrained_model']:
```
But similar errors start popping up:
```
Traceback (most recent call last):
  File "examples/train_model.py", line 161, in <module>
    main()
...
    with open(opt['embedding_file']) as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Is there something wrong with the argument parser? Or do the conditionals need to be updated?

**Comment by alexholdenmiller** [comment]
Sorry that should be fixed in #157!

**Comment by alexholdenmiller** [comment]
We just made a change to the params and had a few bugs left over from that change.

**Comment by ArmenAg** [comment]
Perfect thanks!
