### ISSUE TITLE
Empty training examples throwing runtime error

### ISSUE THREAD

**Issue by odemasi** [facebookresearch/ParlAI#1592]
I'm getting an error with the OpenSubtitles (2009 and 2018) and the Cornell Movie datasets with length 0 examples being loaded. My guess is that there are empty messages in the datasets, which could easily be removed with some preprocessing or a flag to avoid such examples. However, I'm having trouble finding such a flag and would appreciate any help you can provide. I do not have this issue arise on other datasets that I have explored so far. 

I'm a bit puzzled as to why others haven't seemed to run into this problem and was hoping you could help point me in the right direction, especially if I'm missing an easy fix. Thanks.

**Error:**
```
Traceback (most recent call last):
 File "examples/train_model.py", line 16, in <module>
   TrainLoop(opt).train()
 File "/data/odemasi/packages/ParlAI/parlai/scripts/train_model.py", line 523, in train
   world.parley()
 File "/data/odemasi/packages/ParlAI/parlai/core/worlds.py", line 654, in parley
   batch_act = self.batch_act(agent_idx, batch_observations[agent_idx])
 File "/data/odemasi/packages/ParlAI/parlai/core/worlds.py", line 627, in batch_act
   batch_actions = a.batch_act(batch_observation)
 File "/data/odemasi/packages/ParlAI/parlai/core/torch_agent.py", line 1206, in batch_act
   output = self.train_step(batch)
 File "/data/odemasi/packages/ParlAI/parlai/core/torch_generator_agent.py", line 478, in train_step
   raise e
 File "/data/odemasi/packages/ParlAI/parlai/core/torch_generator_agent.py", line 454, in train_step
   scores, preds, _ = self.model(batch.text_vec, batch.label_vec)
 File "/data/odemasi/anaconda3/envs/parlai_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
   result = self.forward(*input, **kwargs)
 File "/data/odemasi/packages/ParlAI/parlai/core/torch_generator_agent.py", line 214, in forward
   encoder_states = prev_enc if prev_enc is not None else self.encoder(xs)
 File "/data/odemasi/anaconda3/envs/parlai_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
   result = self.forward(*input, **kwargs)
 File "/data/odemasi/packages/ParlAI/parlai/agents/seq2seq/modules.py", line 226, in forward
   xes = pack_padded_sequence(xes, x_lens, batch_first=True)
 File "/data/odemasi/anaconda3/envs/parlai_venv/lib/python3.7/site-packages/torch/nn/utils/rnn.py", line 148, in pack_padded_sequence
   return PackedSequence(torch._C._VariableFunctions._pack_padded_sequence(input, lengths, batch_first))
RuntimeError: Length of all samples has to be greater than 0, but found an element in 'lengths' that is <= 0
```

**Resulted from:**
python examples/train_model.py \
-t cornell_movie \
-bs 32 \
--hiddensize 1024 \
--dict-minfreq 2 \
--dict-lower True \
--dict-file cornell_dict \
-m seq2seq \
-mf cornell_seq2seq

**Comment by stephenroller** [comment]
Thanks for reporting. How long does it usually take before you hit this bug?

**Comment by odemasi** [comment]
It comes up very quickly. It's obviously within the first epoch and for the
Cornell dataset it is within the first few minutes of training.
