### ISSUE TITLE
[MTurk] Worker ID joined with itself

### ISSUE THREAD

**Issue by ethanjperez** [facebookresearch/ParlAI#1619]
For ~1-2% of my HITs, I'm finding that the worker ID has the form "WORKERID,WORKERID" instead of simply "WORKERID". In such cases, the worker ID is like this by the time I enter the parley() call of my MTurkOnboardWorld (the earliest I print the ID). The data collection continues normal until the end of the HIT, when the program tries to call AssociateQualificationWithWorker(), which throws an error because the Worker ID is not in the expected regex format. In this case, the HIT simply freezes, and the worker is unable to finish the HIT.

This recently happened with the same worker twice in a row, which would be unlikely unless the issue is worker-dependent.

I've based my Turk task off the QA Data Collection demo, but I am not altering mturk_agent.worker_id in my code (as far as I am aware).

Here is an example stack trace (my code printed the first line):
```bash
AMA18W8F60Y2J,AMA18W8F60Y2J | task_rating: 6 | feedback: some questions make no sense
Exception in thread task-t_14:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "~/ParlAI/parlai/mturk/core/mturk_manager.py", line 1176, in _task_function
    task_function(mturk_manager=self, opt=opt, workers=agents)
  File "parlai/mturk/tasks/context_evaluator/run.py", line 169, in run_conversation
    world.shutdown()
  File "~/ParlAI/parlai/mturk/tasks/context_evaluator/worlds.py", line 460, in shutdown
    self.task.shutdown()
  File "/misc/vlgscratch4/ChoGroup/perez/ParlAI/parlai/mturk/core/agents.py", line 632, in shutdown
    self.mturk_manager.mark_workers_done([self])
  File "/misc/vlgscratch4/ChoGroup/perez/ParlAI/parlai/mturk/core/mturk_manager.py", line 1417, in mark_workers_done
    self.unique_qual_name,
  File "~/ParlAI/parlai/mturk/core/mturk_manager.py", line 1740, in give_worker_qualification
    self.is_sandbox)
  File "~/ParlAI/parlai/mturk/core/mturk_utils.py", line 265, in give_worker_qualification
    SendNotification=False
  File "/home/$USER/.local/lib/python3.6/site-packages/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/$USER/.local/lib/python3.6/site-packages/botocore/client.py", line 623, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the AssociateQualificationWithWorker operation: 1 validation erro
r detected: Value 'AMA18W8F60Y2J,AMA18W8F60Y2J' at 'workerId' failed to satisfy constraint: Member must satisfy regular expression pattern: ^A[A-Z0-9]+
$
```

**Comment by JackUrb** [comment]
My first guess is that someone is using some scripting that is altering the parameters passed by MTurk created URLs - the fix is adding validation here:
https://github.com/facebookresearch/ParlAI/blob/cf8b1def376ad751842b0ed8b27982b0e130b817/parlai/mturk/core/react_server/server/server.js#L259

**Comment by ethanjperez** [comment]
Just seeing this - thanks for finding the issue! How do I add validation exactly?

**Comment by JackUrb** [comment]
It would be ensuring that that line contains a proper workerID. I'm not sure what the clear path for doing so would be or what the action is for if validation fails, but all the issues come downstream from there.

**Comment by JackUrb** [comment]
This is fixed in the `dev` version of ParlAI-MTurk using the `fix_worker_id` function, and will be merged into the main folder soon.
