### ISSUE TITLE
No module named 'parlai_internal'

### ISSUE THREAD

**Issue by jazzminewang** [facebookresearch/ParlAI#1620]
https://parl.ai/projects/wizard_of_wikipedia/

When running ```python projects/wizard_of_wikipedia/scripts/eval_retrieval_model.py``` I get the following error:

```
Traceback (most recent call last):
  File "projects/wizard_of_wikipedia/scripts/eval_retrieval_model.py", line 48, in <module>
    eval_model(parser)
  File "/home/ml/jwang301/Development/ParlAI/parlai/scripts/eval_model.py", line 68, in eval_model
    agent = create_agent(opt, requireModelExists=True)
  File "/home/ml/jwang301/Development/ParlAI/parlai/core/agents.py", line 554, in create_agent
    model = load_agent_module(opt)
  File "/home/ml/jwang301/Development/ParlAI/parlai/core/agents.py", line 407, in load_agent_module
    model_class = get_agent_module(new_opt['model'])
  File "/home/ml/jwang301/Development/ParlAI/parlai/core/agents.py", line 516, in get_agent_module
    my_module = importlib.import_module(module_name)
  File "/home/ml/jwang301/anaconda2/envs/ParlAI/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'parlai_internal'
```

I'm assuming this is accidental since the wiki is public.

**Comment by emilydinan** [comment]
Hi @jazzminewang -- thanks for flagging this. Should be fixed by #1625.
