### ISSUE TITLE
API call errors for a few minutes only

### ISSUE THREAD

**Issue by ethanjperez** [facebookresearch/ParlAI#1686]
**Bug description**
For a period of ~5-10 minutes, two of my HITs simultaneously began to throw an error when calling making API calls through botocore (i.e., when giving a worker qualification at the end of a task). This period occurred in the middle of the HITs; both HITs were not throwing this error before or after this chunk of time. Perhaps some server/API calls were down/broken for a period of time?

These HITs are based off the QADataCollection demo. I have previously run these without any errors. I did not alter any API-calling code; I only call the ParlAI interface functions for those. You can find my code [here](https://github.com/ethanjperez/ParlAI/tree/master/parlai/mturk/tasks/context_evaluator).

Here's an example of the main error message I received:
```bash
Exception in thread task-t_1:
Traceback (most recent call last):
  File "/home/$USER/.conda/envs/parlai/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/$USER/.conda/envs/parlai/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "~/ParlAI/parlai/mturk/core/mturk_manager.py", line 1176, in _task_function
    task_function(mturk_manager=self, opt=opt, workers=agents)
  File "parlai/mturk/tasks/context_evaluator/run.py", line 168, in run_conversation
    world.shutdown()
  File "~/ParlAI/parlai/mturk/tasks/context_evaluator/worlds.py", line 457, in shutdown
    self.mturk_agent.shutdown()
  File "~/ParlAI/parlai/mturk/core/agents.py", line 632, in shutdown
    self.mturk_manager.mark_workers_done([self])
  File "~/ParlAI/parlai/mturk/core/mturk_manager.py", line 1417, in mark_workers_done
    self.unique_qual_name,
  File "~/ParlAI/parlai/mturk/core/mturk_manager.py", line 1729, in give_worker_qualification
    qual_id = mturk_utils.find_qualification(qual_name, self.is_sandbox)
  File "~/ParlAI/parlai/mturk/core/mturk_utils.py", line 194, in find_qualification
    MustBeOwnedByCaller=True,
  File "/home/$USER/.local/lib/python3.6/site-packages/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/$USER/.local/lib/python3.6/site-packages/botocore/client.py", line 623, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ServiceFault: An error occurred (ServiceFault) when calling the ListQualificationTypes operation (reached max retries: 4): There
was an error with this request. (System error code: 1013 1556728540895)
```

Here's an example of another error message I saw exactly once:
```bash
Exception in thread Hit-Status-Thread:
Traceback (most recent call last):
  File "/home/$USER/.conda/envs/parlai/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/$USER/.conda/envs/parlai/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "~/ParlAI/parlai/mturk/core/mturk_manager.py", line 289, in update_status
    hit = self.get_hit(hit_id)
  File "~/ParlAI/parlai/mturk/core/mturk_manager.py", line 1628, in get_hit
    hit = client.get_hit(HITId=hit_id)
  File "/home/$USER/.local/lib/python3.6/site-packages/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/$USER/.local/lib/python3.6/site-packages/botocore/client.py", line 623, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ServiceFault: An error occurred (ServiceFault) when calling the GetHIT operation (reached max retries: 4): There was an error with this request. (System error code: 1000 1556728514072)
```

**Comment by ethanjperez** [comment]
Here's a screenshot one worker sent me. This worker completed the task, so task made an API call to give this worker a completed-task qualification. This call threw an error, so the "Submit this HIT" button never appeared after the final message ("Thanks for your help!").

![Screenshot 1](https://user-images.githubusercontent.com/6402205/57031372-987db900-6c15-11e9-8b38-88dac13c2428.png)

**Comment by JackUrb** [comment]
Hm this is a pretty hard one to fix on our current framework, and is so far has been incredibly transient. I'm putting some work into improving the types and frequency of queries to Amazon for HIT status, but that change isn't likely to roll out until next month.

**Comment by ethanjperez** [comment]
Okay cool, good to know this, thanks!
