### ISSUE TITLE
Obselete download link for CLEVR Dataset

### ISSUE THREAD

**Issue by james-assiene** [facebookresearch/ParlAI#1815]
Apparently, the current link to CLEVR in the source code is "https://s3-us-west-1.amazonaws.com/clevr/CLEVR_v1.0.zip" that returns the message "All access to this object has been disabled"

When I try to execute the following line of code

`!python ~/ParlAI/examples/display_data.py -t clevr`

I obtain

```
[creating task(s): clevr]
[building data: /root/ParlAI/data/CLEVR]
[ downloading: https://s3-us-west-1.amazonaws.com/clevr/CLEVR_v1.0.zip to /root/ParlAI/data/CLEVR/CLEVR_v1.0.zip ]
Downloading CLEVR_v1.0.zip: 0.00B [00:00, ?B/s]
unpacking CLEVR_v1.0.zip
Traceback (most recent call last):
  File "/root/ParlAI/parlai/core/agents.py", line 819, in _create_task_agents
    task_agents = my_module.create_agent(opt)
AttributeError: module 'parlai.tasks.clevr.agents' has no attribute 'create_agent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/ParlAI/examples/display_data.py", line 22, in <module>
    display_data(opt)
  File "/root/ParlAI/parlai/scripts/display_data.py", line 42, in display_data
    world = create_task(opt, agent)
  File "/root/ParlAI/parlai/core/worlds.py", line 1151, in create_task
    world = create_task_world(opt, user_agents, default_world=default_world)
  File "/root/ParlAI/parlai/core/worlds.py", line 1108, in create_task_world
    opt, user_agents, default_world=default_world
  File "/root/ParlAI/parlai/core/worlds.py", line 1068, in _get_task_world
    task_agents = _create_task_agents(opt)
  File "/root/ParlAI/parlai/core/agents.py", line 822, in _create_task_agents
    return create_task_agent_from_taskname(opt)
  File "/root/ParlAI/parlai/core/agents.py", line 776, in create_task_agent_from_taskname
    task_agents = teacher_class(opt)
  File "/root/ParlAI/parlai/tasks/clevr/agents.py", line 45, in __init__
    data_path, self.images_path = _path(opt)
  File "/root/ParlAI/parlai/tasks/clevr/agents.py", line 15, in _path
    build(opt)
  File "/root/ParlAI/parlai/tasks/clevr/build.py", line 28, in build
    build_data.untar(dpath, fname)
  File "/root/ParlAI/parlai/core/build_data.py", line 180, in untar
    shutil.unpack_archive(fullpath, path)
  File "/usr/lib/python3.6/shutil.py", line 983, in unpack_archive
    func(filename, extract_dir, **kwargs)
  File "/usr/lib/python3.6/shutil.py", line 883, in _unpack_zipfile
    raise ReadError("%s is not a zip file" % filename)
shutil.ReadError: /root/ParlAI/data/CLEVR/CLEVR_v1.0.zip is not a zip file
```

I found the following working link on CLEVR webpage (https://cs.stanford.edu/people/jcjohns/clevr/):

https://dl.fbaipublicfiles.com/clevr/CLEVR_v1.0.zip

**Comment by stephenroller** [comment]
Thank you for pointing this out!
