### ISSUE TITLE
Talk interactively to the generative WoW model

### ISSUE THREAD

**Issue by abisee** [facebookresearch/ParlAI#1882]
Is there a way I can talk to the **generative** Wizard of Wikipedia model interactively? There's a command provided for the retrieval model in the [project README](https://parl.ai/projects/wizard_of_wikipedia/), but none for the generative model.

I tried the following:

`python examples/interactive.py -mf models:wizard_of_wikipedia/end2end_generator/model -t wizard_of_wikipedia`

but that gave the following error:

```
Please choose one of the following topics by typing A, B, C, ..., etc. :

A: Art
B: Graphic design
C: Tokyo
D: Author
E: [NO TOPIC]

Enter Your Message: C
[ Your chosen topic is: Tokyo ]
Enter Your Message: I've never been to Japan, have you?
Traceback (most recent call last):
  File "examples/interactive.py", line 18, in <module>
    interactive(opt, print_parser=parser)
  File "/juice/scr/scr101/scr/abisee/ParlAI/parlai/scripts/interactive.py", line 79, in interactive
    world.parley()
  File "/juice/scr/scr101/scr/abisee/ParlAI/parlai/tasks/wizard_of_wikipedia/worlds.py", line 93, in parley
    self.acts[1] = self.model_agent.act()
  File "/juice/scr/scr101/scr/abisee/ParlAI/parlai/core/torch_agent.py", line 1662, in act
    return self.batch_act([self.observation])[0]
  File "/juice/scr/scr101/scr/abisee/ParlAI/parlai/core/torch_agent.py", line 1683, in batch_act
    batch = self.batchify(observations)
  File "/juice/scr/scr101/scr/abisee/ParlAI/projects/wizard_of_wikipedia/generator/agents.py", line 211, in batchify
    obs_know = self._parse_knowledge(obs)
  File "/juice/scr/scr101/scr/abisee/ParlAI/projects/wizard_of_wikipedia/generator/agents.py", line 172, in _parse_knowledge
    obs['title'], TOKEN_KNOWLEDGE, obs['checked_sentence']
KeyError: 'title'
```

Thanks!

**Comment by stephenroller** [comment]
Thanks for filing Abi. We’ll look at it soon. Something must be wrong with the insertion of the title into the observation.

**Comment by emilydinan** [comment]
Thanks for pointing this out Abi! The problem is that the generative and retrieval models expect the data in different formats, and I had set up the interactive world with only the retrieval model in mind. Will work on a fix.

**Comment by emilydinan** [comment]
Upon taking a closer look, this requires a slightly bigger change, as we have to connect the generative model with the TFIDF-retriever in the manner this was done for the retrieval model. Will sync with @stephenroller on this.
