### ISSUE TITLE
QuickStart instructions yield AttributeError: 'MemnnAgent' object has no attribute 'vocab_candidate_encs'

### ISSUE THREAD

**Issue by pringshia** [facebookresearch/ParlAI#1920]
**Bug description**

When going through the [ParlAI quickstart](https://parl.ai/docs/tutorial_quick.html#view-a-task-train-a-model
), I get the following error:
```python
Traceback (most recent call last):
  File "examples/display_model.py", line 16, in <module>
    display_model(opt)
  File "/root/ParlAI/parlai/scripts/display_model.py", line 44, in display_model
    world.parley()
  File "/root/ParlAI/parlai/core/worlds.py", line 274, in parley
    acts[1] = agents[1].act()
  File "/root/ParlAI/parlai/core/torch_agent.py", line 1674, in act
    return self.batch_act([self.observation])[0]
  File "/root/ParlAI/parlai/core/torch_agent.py", line 1703, in batch_act
    output = self.eval_step(batch)
  File "/root/ParlAI/parlai/core/torch_ranker_agent.py", line 383, in eval_step
    cand_encs = self.vocab_candidate_encs
AttributeError: 'MemnnAgent' object has no attribute 'vocab_candidate_encs'
```

when running:
```bash
# display predictions for model save at specified file on bAbI task 1
python examples/display_model.py -t babi:task10k:1 -mf /tmp/babi_memnn -ecands vocab

```

**Comment by stephenroller** [comment]
This looks like a TRA issue. Need review.

**Comment by lolipopshock** [comment]
After you update the repo (`git fetch; git pull`), the issue is fixed. But [this issues](https://github.com/facebookresearch/ParlAI/issues/1954) still remains.
