### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'force_set'

### ISSUE THREAD

**Issue by linohan** [facebookresearch/ParlAI#1936]
**Bug description**
When I try the pretrained model of Self-feeding Chatbot, by `python projects/self_feeding/interactive.py --model-file zoo:self_feeding/hh131k_hb60k_fb60k_st1k/model --no-cuda`, error occurs: AttributeError: 'dict' object has no attribute 'force_set'

**Logs**
Please paste the command line output:

```
Enter Your Message: hello
Traceback (most recent call last):
  File "projects/self_feeding/interactive.py", line 87, in <module>
    interactive(parser.parse_args(print_args=False), print_parser=parser)
  File "projects/self_feeding/interactive.py", line 78, in interactive
    world.parley()
  File "/home/han/Github/ParlAI/parlai/core/worlds.py", line 273, in parley
    agents[1].observe(validate(acts[0]))
  File "/home/han/Github/ParlAI/projects/self_feeding/self_feeding_agent.py", line 370, in observe
    observation.force_set(
AttributeError: 'dict' object has no attribute 'force_set'
```

**Additional context**
Add any other context about the problem here. (like proxy settings, network setup, overall goals, etc.)

**Comment by emilydinan** [comment]
Thanks for the bug report! Should be fixed by  #1939.
