### ISSUE TITLE
Change image_mode choice 'none' to 'no_image_model' across ParlAI

### ISSUE THREAD

**Issue by mwillwork** [facebookresearch/ParlAI#1946]
Right now many teachers for image related tasks use image_mode == 'none', but this is bad practice. One should not use string-like versions of other types (i.e. None). We would like to change this to the constant 'no_image_model' and confirm that image teachers still work properly.

Run each image related task via the command at the top of the teacher if present or modify the documentation, with help from a team member, to insert a run command and then proceed.

**Comment by domrigoglioso** [comment]
I tried running `python examples/train_model.py -t flickr30k -mf /tmp/flickr_test -m memnn` without any changes to test what the training of an image related task would look like and I get the following error traceback:
```
Traceback (most recent call last):
  File "examples/train_model.py", line 16, in <module>
    TrainLoop(opt).train()
  File "/home/dom/Documents/ParlAI/parlai/scripts/train_model.py", line 706, in train
    world.parley()
  File "/home/dom/Documents/ParlAI/parlai/core/worlds.py", line 285, in parley
    acts[1] = agents[1].act()
  File "/home/dom/Documents/ParlAI/parlai/core/torch_agent.py", line 1723, in act
    return self.batch_act([self.observation])[0]
  File "/home/dom/Documents/ParlAI/parlai/core/torch_agent.py", line 1747, in batch_act
    output = self.train_step(batch)
  File "/home/dom/Documents/ParlAI/parlai/core/torch_ranker_agent.py", line 342, in train_step
    else batch.image.size(0)
AttributeError: 'list' object has no attribute 'size'
```
I also tried the same command but with `-t mnist_qa` which runs fine, so I think it could just be an issue with flickr30k, although I haven't tried it on any other visual tasks yet.
