### ISSUE TITLE
Quickstart AttributeError: 'HogwildWorld' object has no attribute 'acts'

### ISSUE THREAD

**Issue by yujie-tao** [facebookresearch/ParlAI#1954]
**Bug description**
When going through the ParlAI [quickstart](https://parl.ai/docs/tutorial_quick.html#install), I got the following error:

``` python
Traceback (most recent call last):
  File "examples/interactive.py", line 18, in <module>
    interactive(opt, print_parser=parser)
  File "/root/ParlAI/parlai/scripts/interactive.py", line 68, in interactive
    agent = create_agent(opt, requireModelExists=True)
  File "/root/ParlAI/parlai/core/agents.py", line 683, in create_agent
    model = load_agent_module(opt)
  File "/root/ParlAI/parlai/core/agents.py", line 548, in load_agent_module
    return model_class(new_opt)
  File "/root/ParlAI/parlai/agents/memnn/memnn.py", line 86, in __init__
    super().__init__(opt, shared)
  File "/root/ParlAI/parlai/core/torch_ranker_agent.py", line 135, in __init__
    super().__init__(opt, shared)
  File "/Users/skytao/Desktop/Machine Learning/ParlAI/parlai/core/torch_agent.py", line 737, in __init__
    self.set_interactive_mode(opt['interactive_mode'], shared)
  File "/root/ParlAI/parlai/core/torch_ranker_agent.py", line 206, in set_interactive_mode
    path = self.get_task_candidates_path()
  File "/root/ParlAI/parlai/core/torch_ranker_agent.py", line 230, in get_task_candidates_path
    build_cands(opt)
  File "/root/Machine Learning/ParlAI/parlai/scripts/build_candidates.py", line 47, in build_cands
    acts = world.get_acts()[0]
  File "/root/Machine Learning/ParlAI/parlai/core/worlds.py", line 162, in get_acts
    return self.acts
AttributeError: 'HogwildWorld' object has no attribute 'acts'
```

**While running**
```python
python examples/interactive.py -mf /tmp/babi_memnn -ecands vocab
```

**Comment by stephenroller** [comment]
Thanks for filing
