### ISSUE TITLE
Legacy seq2seq doesn't output version requirement

### ISSUE THREAD

**Issue by klshuster** [facebookresearch/ParlAI#1999]
**Bug description**
Attempting to evaluate the pretrained seq2seq convai2 model results in a bug.

**Reproduction steps**
`python examples/eval_model.py -mf models:convai2/seq2seq/convai2_self_seq2seq_model -t convai2`

**Expected behavior**
The model evaluates

**Logs**
Please paste the command line output:

```
python examples/eval_model.py -mf models:convai2/seq2seq/convai2_self_seq2seq_model -t convai2
[ warning: overriding opt['model_file'] to /Users/kshuster/ParlAI/data/models/convai2/seq2seq/convai2_self_seq2seq_model (previously: /Users/edinan/ParlAI/data/models/convai2/seq2seq/convai2_self_seq2seq_model )]
[ warning: overriding opt['task'] to convai2 (previously: convai2:self:no_cands )]
Traceback (most recent call last):
  File "examples/eval_model.py", line 17, in <module>
    eval_model(opt, print_parser=parser)
  File "/Users/kshuster/ParlAI/parlai/scripts/eval_model.py", line 108, in eval_model
    agent = create_agent(opt, requireModelExists=True)
  File "/Users/kshuster/ParlAI/parlai/core/agents.py", line 683, in create_agent
    model = load_agent_module(opt)
  File "/Users/kshuster/ParlAI/parlai/core/agents.py", line 502, in load_agent_module
    new_opt = model_class.upgrade_opt(new_opt)
  File "/Users/kshuster/ParlAI/parlai/core/torch_generator_agent.py", line 248, in upgrade_opt
    assert 'beam_size' in opt_from_disk
AssertionError
```

**Comment by stephenroller** [comment]
Why has this not been picked up by the gpu nightly test?

**Comment by klshuster** [comment]
No idea, but I can still repro on master

**Comment by stephenroller** [comment]
It's because it needs `-m legacy:seq2seq:0`

**Comment by stephenroller** [comment]
So the real problem is the version checker isn't occurring early enough.

I'd really like to just get rid of the legacy copies.
