### ISSUE TITLE
trouble using --responder-model-file in wizard_of_wikipedia/interactive_retrieval

### ISSUE THREAD

**Issue by tycho01** [facebookresearch/ParlAI#2090]
I was trying out the interactive session for Wizards of Wikipedia.

I started with the suggested command from the readme:
`python examples/interactive.py -m projects:wizard_of_wikipedia:interactive_retrieval -t wizard_of_wikipedia`

This worked okay. Yay!
I wanted to use my own model, but for testing purposes first plugged in the [default path](https://github.com/facebookresearch/ParlAI/blob/14c5b8958f6159855ade7b724e2796006d9427df/projects/wizard_of_wikipedia/interactive_retrieval/interactive_retrieval.py#L62-L66) of `models:wizard_of_wikipedia/full_dialogue_retrieval_model/model` again instead:

```
lgpu0206@login-gpu1:~/ir2/ParlAI$ python examples/interactive.py -m projects:wizard_of_wikipedia:interactive_retrieval -t wizard_of_wikipedia --responder-model-file="models:wizard_of_wikipedia/full_dialogue_retrieval_model/model"
> /home/lgpu0206/ir2/ParlAI/examples/interactive.py(9)<module>()
-> """
/home/lgpu0206/ir2/ParlAI/parlai/agents/transformer/modules.py:32: UserWarning: Installing APEX can give a significant speed boost.
  warn_once("Installing APEX can give a significant speed boost.")
[ optional arguments: ] 
[  display_examples: False ]
[  display_ignore_fields: label_candidates,text_candidates ]
[  display_prettify: False ]
[  interactive_task: True ]
[  share_word_embeddings: True ]
[ Main ParlAI Arguments: ] 
[  batchsize: 1 ]
[  datapath: /home/lgpu0206/ir2/ParlAI/data ]
[  datatype: train ]
[  download_path: /home/lgpu0206/ir2/ParlAI/downloads ]
[  hide_labels: False ]
[  image_mode: raw ]
[  init_opt: None ]
[  multitask_weights: [1] ]
[  numthreads: 1 ]
[  show_advanced_args: False ]
[  task: wizard_of_wikipedia ]
[ ParlAI Model Arguments: ] 
[  dict_class: None ]
[  init_model: None ]
[  model: projects:wizard_of_wikipedia:interactive_retrieval ]
[  model_file: None ]
[ Local Human Arguments: ] 
[  local_human_candidates_file: None ]
[  single_turn: False ]
[ ParlAI Image Preprocessing Arguments: ] 
[  image_cropsize: 224 ]
[  image_size: 256 ]
[ Wizard Dialog Knowledge arguments: ] 
[  include_checked_sentence: True ]
[  include_knowledge: True ]
[  include_knowledge_separator: False ]
[  label_type: response ]
[  num_topics: 5 ]
[ TorchAgent Arguments: ] 
[  add_p1_after_newln: False ]
[  delimiter:   ]
[  embedding_projection: random ]
[  embedding_type: random ]
[  fp16: False ]
[  gpu: -1 ]
[  history_size: -1 ]
[  interactive_mode: True ]
[  label_truncate: None ]
[  no_cuda: False ]
[  person_tokens: False ]
[  rank_candidates: False ]
[  split_lines: False ]
[  text_truncate: None ]
[  truncate: 1024 ]
[  use_reply: label ]
[ Optimizer Arguments: ] 
[  adam_eps: 1e-08 ]
[  betas: (0.9, 0.999) ]
[  gradient_clip: 0.1 ]
[  learningrate: 0.0008 ]
[  momentum: 0 ]
[  nesterov: True ]
[  nus: (0.7,) ]
[  optimizer: adamax ]
[  weight_decay: None ]
[ Learning Rate Scheduler: ] 
[  lr_scheduler: reduceonplateau ]
[  lr_scheduler_decay: 0.5 ]
[  lr_scheduler_patience: 3 ]
[  update_freq: 1 ]
[  warmup_rate: 0.0001 ]
[  warmup_updates: -1 ]
[ TorchRankerAgent: ] 
[  candidates: batch ]
[  cap_num_predictions: 100 ]
[  encode_candidate_vecs: True ]
[  eval_candidates: inline ]
[  fixed_candidate_vecs: reuse ]
[  fixed_candidates_path: None ]
[  ignore_bad_candidates: False ]
[  init_model: None ]
[  rank_top_k: -1 ]
[  repeat_blocking_heuristic: True ]
[  train_predict: False ]
[ Transformer Arguments: ] 
[  activation: relu ]
[  attention_dropout: 0.0 ]
[  data_parallel: False ]
[  dropout: 0.0 ]
[  embedding_size: 300 ]
[  embeddings_scale: True ]
[  ffn_size: 300 ]
[  learn_embeddings: True ]
[  learn_positional_embeddings: False ]
[  memory_attention: sqrt ]
[  n_heads: 2 ]
[  n_layers: 2 ]
[  n_positions: None ]
[  n_segments: 0 ]
[  normalize_sent_emb: False ]
[  output_scaling: 1.0 ]
[  reduction_type: mean ]
[  relu_dropout: 0.0 ]
[  share_encoders: True ]
[  use_memories: False ]
[  variant: aiayn ]
[  wrap_memory_encoder: False ]
[ Dictionary Arguments: ] 
[  bpe_debug: False ]
[  dict_endtoken: __end__ ]
[  dict_file: None ]
[  dict_initpath: None ]
[  dict_language: english ]
[  dict_lower: False ]
[  dict_max_ngram_size: -1 ]
[  dict_maxtokens: -1 ]
[  dict_minfreq: 0 ]
[  dict_nulltoken: __null__ ]
[  dict_starttoken: __start__ ]
[  dict_textfields: text,labels ]
[  dict_tokenizer: re ]
[  dict_unktoken: __unk__ ]
[ Wizard Transformer Ranker Arguments: ] 
[  chosen_sentence: False ]
[  knowledge_dropout: 0.7 ]
[  knowledge_truncate: 50 ]
[  legacy: False ]
[  use_knowledge: True ]
[ WizardRetrievalInteractive Arguments: ] 
[  debug: False ]
[  get_unique: True ]
[  num_retrieved: 7 ]
[  responder_model_file: models:wizard-of-wikipedia/full-dialogue-retrieval-model/model ]
[  retriever_model_file: models:wikipedia_full/tfidf_retriever/model ]
[ Current ParlAI commit: 84ecfc40c3844ea00eb94a4c96b354624bfe221f ]
[ no model with opt yet at: /home/lgpu0206/ir2/ParlAI/data/models/wizard-of-wikipedia/full-dialogue-retrieval-model/model(.opt) ]
[WizardTransformerRanker: full interactive mode on.]
Total parameters: 2649300
Trainable parameters:  2349300
[ Loading fixed candidate set from /home/lgpu0206/ir2/ParlAI/data/models/wizard_of_wikipedia/full_dialogue_retrieval_model/wizard_cands.txt ]
[ Vectorizing fixed candidate set (147 batch(es) of up to 512) ]
100%|███████████████████████████████████████████████████████████████████████████████| 147/147 [00:03<00:00, 46.41it/s]
[ Saving fixed candidate set vectors to /home/lgpu0206/ir2/ParlAI/data/models/wizard-of-wikipedia/full-dialogue-retrieval-model/model.wizard_cands.vecs ]
Traceback (most recent call last):
  File "/sw/arch/Debian9/EB_production/2019/software/Anaconda3/2018.12/lib/python3.7/pdb.py", line 1697, in main
    pdb._runscript(mainpyfile)
  File "/sw/arch/Debian9/EB_production/2019/software/Anaconda3/2018.12/lib/python3.7/pdb.py", line 1566, in _runscript
    self.run(statement)
  File "/sw/arch/Debian9/EB_production/2019/software/Anaconda3/2018.12/lib/python3.7/bdb.py", line 585, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/lgpu0206/ir2/ParlAI/examples/interactive.py", line 9, in <module>
    """
  File "/home/lgpu0206/ir2/ParlAI/parlai/scripts/interactive.py", line 68, in interactive
    agent = create_agent(opt, requireModelExists=True)
  File "/home/lgpu0206/ir2/ParlAI/parlai/core/agents.py", line 694, in create_agent
    model = model_class(opt)
  File "/home/lgpu0206/ir2/ParlAI/projects/wizard_of_wikipedia/interactive_retrieval/interactive_retrieval.py", line 39, in __init__
    self._set_up_responder(opt)
  File "/home/lgpu0206/ir2/ParlAI/projects/wizard_of_wikipedia/interactive_retrieval/interactive_retrieval.py", line 119, in _set_up_responder
    self.responder = create_agent(responder_opts)
  File "/home/lgpu0206/ir2/ParlAI/parlai/core/agents.py", line 694, in create_agent
    model = model_class(opt)
  File "/home/lgpu0206/ir2/ParlAI/projects/wizard_of_wikipedia/wizard_transformer_ranker/wizard_transformer_ranker.py", line 65, in __init__
    super().__init__(opt, shared)
  File "/home/lgpu0206/ir2/ParlAI/parlai/agents/transformer/transformer.py", line 178, in __init__
    super().__init__(opt, shared)
  File "/home/lgpu0206/ir2/ParlAI/parlai/core/torch_ranker_agent.py", line 172, in __init__
    self.set_fixed_candidates(shared)
  File "/home/lgpu0206/ir2/ParlAI/parlai/core/torch_ranker_agent.py", line 837, in set_fixed_candidates
    self._save_candidates(vecs, vecs_path)
  File "/home/lgpu0206/ir2/ParlAI/parlai/core/torch_ranker_agent.py", line 891, in _save_candidates
    with open(path, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/lgpu0206/ir2/ParlAI/data/models/wizard-of-wikipedia/full-dialogue-retrieval-model/model.wizard_cands.vecs'
```

As it turns out, `argparse` replaces the underscores in the parameter by dashes, as reported e.g. [here](https://stackoverflow.com/questions/16174992/cant-get-argparse-to-read-quoted-string-with-dashes-in-it).

As a temp monkey-patch, I patching in a `.replace('-', '_')` at `model_dir` [here](https://github.com/facebookresearch/ParlAI/blob/c900689d1be99e553bf955973a036f45085c044c/parlai/core/torch_ranker_agent.py#L831), expecting the command should now behave as the original.
It did not:

```
lgpu0206@login-gpu1:~/ir2/ParlAI$ python examples/interactive.py -m projects:wizard_of_wikipedia:interactive_retrieval -t wizard_of_wikipedia --responder-model-file="models:wizard_of_wikipedia/full_dialogue_retrieval_model/model"
> /home/lgpu0206/ir2/ParlAI/examples/interactive.py(9)<module>()
-> """
/home/lgpu0206/ir2/ParlAI/parlai/agents/transformer/modules.py:32: UserWarning: Installing APEX can give a significant speed boost.
  warn_once("Installing APEX can give a significant speed boost.")
[ optional arguments: ] 
[  display_examples: False ]
[  display_ignore_fields: label_candidates,text_candidates ]
[  display_prettify: False ]
[  interactive_task: True ]
[  share_word_embeddings: True ]
[ Main ParlAI Arguments: ] 
[  batchsize: 1 ]
[  datapath: /home/lgpu0206/ir2/ParlAI/data ]
[  datatype: train ]
[  download_path: /home/lgpu0206/ir2/ParlAI/downloads ]
[  hide_labels: False ]
[  image_mode: raw ]
[  init_opt: None ]
[  multitask_weights: [1] ]
[  numthreads: 1 ]
[  show_advanced_args: False ]
[  task: wizard_of_wikipedia ]
[ ParlAI Model Arguments: ] 
[  dict_class: None ]
[  init_model: None ]
[  model: projects:wizard_of_wikipedia:interactive_retrieval ]
[  model_file: None ]
[ Local Human Arguments: ] 
[  local_human_candidates_file: None ]
[  single_turn: False ]
[ ParlAI Image Preprocessing Arguments: ] 
[  image_cropsize: 224 ]
[  image_size: 256 ]
[ Wizard Dialog Knowledge arguments: ] 
[  include_checked_sentence: True ]
[  include_knowledge: True ]
[  include_knowledge_separator: False ]
[  label_type: response ]
[  num_topics: 5 ]
[ TorchAgent Arguments: ] 
[  add_p1_after_newln: False ]
[  delimiter:   ]
[  embedding_projection: random ]
[  embedding_type: random ]
[  fp16: False ]
[  gpu: -1 ]
[  history_size: -1 ]
[  interactive_mode: True ]
[  label_truncate: None ]
[  no_cuda: False ]
[  person_tokens: False ]
[  rank_candidates: False ]
[  split_lines: False ]
[  text_truncate: None ]
[  truncate: 1024 ]
[  use_reply: label ]
[ Optimizer Arguments: ] 
[  adam_eps: 1e-08 ]
[  betas: (0.9, 0.999) ]
[  gradient_clip: 0.1 ]
[  learningrate: 0.0008 ]
[  momentum: 0 ]
[  nesterov: True ]
[  nus: (0.7,) ]
[  optimizer: adamax ]
[  weight_decay: None ]
[ Learning Rate Scheduler: ] 
[  lr_scheduler: reduceonplateau ]
[  lr_scheduler_decay: 0.5 ]
[  lr_scheduler_patience: 3 ]
[  update_freq: 1 ]
[  warmup_rate: 0.0001 ]
[  warmup_updates: -1 ]
[ TorchRankerAgent: ] 
[  candidates: batch ]
[  cap_num_predictions: 100 ]
[  encode_candidate_vecs: True ]
[  eval_candidates: inline ]
[  fixed_candidate_vecs: reuse ]
[  fixed_candidates_path: None ]
[  ignore_bad_candidates: False ]
[  init_model: None ]
[  rank_top_k: -1 ]
[  repeat_blocking_heuristic: True ]
[  train_predict: False ]
[ Transformer Arguments: ] 
[  activation: relu ]
[  attention_dropout: 0.0 ]
[  data_parallel: False ]
[  dropout: 0.0 ]
[  embedding_size: 300 ]
[  embeddings_scale: True ]
[  ffn_size: 300 ]
[  learn_embeddings: True ]
[  learn_positional_embeddings: False ]
[  memory_attention: sqrt ]
[  n_heads: 2 ]
[  n_layers: 2 ]
[  n_positions: None ]
[  n_segments: 0 ]
[  normalize_sent_emb: False ]
[  output_scaling: 1.0 ]
[  reduction_type: mean ]
[  relu_dropout: 0.0 ]
[  share_encoders: True ]
[  use_memories: False ]
[  variant: aiayn ]
[  wrap_memory_encoder: False ]
[ Dictionary Arguments: ] 
[  bpe_debug: False ]
[  dict_endtoken: __end__ ]
[  dict_file: None ]
[  dict_initpath: None ]
[  dict_language: english ]
[  dict_lower: False ]
[  dict_max_ngram_size: -1 ]
[  dict_maxtokens: -1 ]
[  dict_minfreq: 0 ]
[  dict_nulltoken: __null__ ]
[  dict_starttoken: __start__ ]
[  dict_textfields: text,labels ]
[  dict_tokenizer: re ]
[  dict_unktoken: __unk__ ]
[ Wizard Transformer Ranker Arguments: ] 
[  chosen_sentence: False ]
[  knowledge_dropout: 0.7 ]
[  knowledge_truncate: 50 ]
[  legacy: False ]
[  use_knowledge: True ]
[ WizardRetrievalInteractive Arguments: ] 
[  debug: False ]
[  get_unique: True ]
[  num_retrieved: 7 ]
[  responder_model_file: models:wizard-of-wikipedia/full-dialogue-retrieval-model/model ]
[  retriever_model_file: models:wikipedia_full/tfidf_retriever/model ]
[ Current ParlAI commit: 84ecfc40c3844ea00eb94a4c96b354624bfe221f ]
[ no model with opt yet at: /home/lgpu0206/ir2/ParlAI/data/models/wizard-of-wikipedia/full-dialogue-retrieval-model/model(.opt) ]
[WizardTransformerRanker: full interactive mode on.]
Total parameters: 2649300
Trainable parameters:  2349300
[ Loading fixed candidate set from /home/lgpu0206/ir2/ParlAI/data/models/wizard_of_wikipedia/full_dialogue_retrieval_model/wizard_cands.txt ]
[ Loading fixed candidate set vectors from /home/lgpu0206/ir2/ParlAI/data/models/wizard_of_wikipedia/full_dialogue_retrieval_model/model.wizard_cands.vecs ]
[ Encoding fixed candidates set from (294 batch(es) of up to 256) ]
  0%|                                                                                         | 0/294 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/sw/arch/Debian9/EB_production/2019/software/Anaconda3/2018.12/lib/python3.7/pdb.py", line 1697, in main
    pdb._runscript(mainpyfile)
  File "/sw/arch/Debian9/EB_production/2019/software/Anaconda3/2018.12/lib/python3.7/pdb.py", line 1566, in _runscript
    self.run(statement)
  File "/sw/arch/Debian9/EB_production/2019/software/Anaconda3/2018.12/lib/python3.7/bdb.py", line 585, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/lgpu0206/ir2/ParlAI/examples/interactive.py", line 9, in <module>
    """
  File "/home/lgpu0206/ir2/ParlAI/parlai/scripts/interactive.py", line 68, in interactive
    agent = create_agent(opt, requireModelExists=True)
  File "/home/lgpu0206/ir2/ParlAI/parlai/core/agents.py", line 694, in create_agent
    model = model_class(opt)
  File "/home/lgpu0206/ir2/ParlAI/projects/wizard_of_wikipedia/interactive_retrieval/interactive_retrieval.py", line 39, in __init__
    self._set_up_responder(opt)
  File "/home/lgpu0206/ir2/ParlAI/projects/wizard_of_wikipedia/interactive_retrieval/interactive_retrieval.py", line 118, in _set_up_responder
    self.responder = create_agent(responder_opts)
  File "/home/lgpu0206/ir2/ParlAI/parlai/core/agents.py", line 694, in create_agent
    model = model_class(opt)
  File "/home/lgpu0206/ir2/ParlAI/projects/wizard_of_wikipedia/wizard_transformer_ranker/wizard_transformer_ranker.py", line 65, in __init__
    super().__init__(opt, shared)
  File "/home/lgpu0206/ir2/ParlAI/parlai/agents/transformer/transformer.py", line 178, in __init__
    super().__init__(opt, shared)
  File "/home/lgpu0206/ir2/ParlAI/parlai/core/torch_ranker_agent.py", line 172, in __init__
    self.set_fixed_candidates(shared)
  File "/home/lgpu0206/ir2/ParlAI/parlai/core/torch_ranker_agent.py", line 852, in set_fixed_candidates
    encs = self._make_candidate_encs(self.fixed_candidate_vecs)
  File "/home/lgpu0206/ir2/ParlAI/parlai/core/torch_ranker_agent.py", line 928, in _make_candidate_encs
    cand_encs.append(self.encode_candidates(vec_batch))
  File "/home/lgpu0206/ir2/ParlAI/parlai/agents/transformer/transformer.py", line 237, in encode_candidates
    _, cands = self.model(xs=None, mems=None, cands=padded_cands)
  File "/home/lgpu0206/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lgpu0206/ir2/ParlAI/parlai/agents/transformer/modules.py", line 262, in forward
    cands_h = self.encode_cand(cands)
  File "/home/lgpu0206/ir2/ParlAI/parlai/agents/transformer/modules.py", line 217, in encode_cand
    encoded = self.cand_encoder(words)
  File "/home/lgpu0206/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lgpu0206/ir2/ParlAI/parlai/agents/transformer/modules.py", line 306, in forward
    return self.mlp(self.transformer(*args))
  File "/home/lgpu0206/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lgpu0206/ir2/ParlAI/parlai/agents/transformer/modules.py", line 475, in forward
    tensor = self.embeddings(input)
  File "/home/lgpu0206/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lgpu0206/.local/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 114, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/home/lgpu0206/.local/lib/python3.7/site-packages/torch/nn/functional.py", line 1484, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: index out of range: Tried to access index 5 out of table with 2 rows. at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:418
```

A `weight.shape` there yielded a `torch.Size([3, 300])`, so maybe that's what it was about.
At this point I'm feeling quite confused though. What might cause this discrepancy, using a command that should seemingly work identical to the default?

**Comment by emilydinan** [comment]
Hi @tycho01 -- I'm having trouble reproducing. It seems as though you may have corrupted some of the files in `/home/lgpu0206/ir2/ParlAI/data/models/wizard_of_wikipedia/full_dialogue_retrieval_model/`, as it shouldn't be trying to encode the vectors again. 

Can you try deleting that folder and then running the following command? :
`python examples/interactive.py -m projects:wizard_of_wikipedia:interactive_retrieval -t wizard_of_wikipedia --responder-model-file zoo:wizard_of_wikipedia/full_dialogue_retrieval_model/model`

**Comment by tycho01** [comment]
it seems that did it. thank you for your assistance! :)
