### ISSUE TITLE
[WoW] eval on retrieval model: No module named 'parlai_internal'

### ISSUE THREAD

**Issue by KiaraGrouwstra** [facebookresearch/ParlAI#2102]
**Bug description**
Running eval on the retrieval model for WoW, I am met with a module error.

**Reproduction steps**
```
$ python examples/eval_model.py -t wizard_of_wikipedia:generator:topic_split -mf models:wizard_of_wikipedia/full_dialogue_retrieval_model/model
Traceback (most recent call last):
  File "examples/eval_model.py", line 16, in <module>
    opt = parser.parse_args(print_args=False)
  File "/home/lgpu0206/ir2/ParlAI/parlai/core/params.py", line 992, in parse_args
    self.add_extra_args(args)
  File "/home/lgpu0206/ir2/ParlAI/parlai/core/params.py", line 834, in add_extra_args
    self.add_model_subargs(model)
  File "/home/lgpu0206/ir2/ParlAI/parlai/core/params.py", line 739, in add_model_subargs
    agent = get_agent_module(model)
  File "/home/lgpu0206/ir2/ParlAI/parlai/core/agents.py", line 638, in get_agent_module
    my_module = importlib.import_module(module_name)
  File "/sw/arch/Debian9/EB_production/2019/software/Anaconda3/2018.12/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'parlai_internal'
```

A similar error was reported at #1620, but the applied fix at #1625 apparently has not fixed the error for this case...
When evaluating the `end2end_generator` model instead I do not get this error, only for the `full_dialogue_retrieval_model`.

**Comment by stephenroller** [comment]
Temporary fix:  add `-m projects:wizard_of_wikipedia:wizard_transformer_ranker` to you command line args.

**Comment by tycho01** [comment]
That did it -- thanks! :tada:

**Comment by stephenroller** [comment]
reopening because we should patch that opt file.

**Comment by namanahuja** [comment]
Facing the same issue. When I append the proposed fix I get:

RuntimeError: Error(s) in loading state_dict for TransformerMemNetModel:
	size mismatch for context_encoder.position_embeddings.weight: copying a param with shape torch.Size([1000, 300]) from checkpoint, the shape in current model is torch.Size([150, 300]).
........
