### ISSUE TITLE
Bad git executable.

### ISSUE THREAD

**Issue by salama4** [facebookresearch/ParlAI#2118]
when i type (python examples/display_data.py -t squad) in the cmd or any Any semi line i get 
Traceback (most recent call last):
  File "D:\Programs\PYTHON\python-master\lib\site-packages\git\__init__.py", line 83, in <module>
    refresh()
  File "D:\Programs\PYTHON\python-master\lib\site-packages\git\__init__.py", line 73, in refresh
    if not Git.refresh(path=path):
  File "D:\Programs\PYTHON\python-master\lib\site-packages\git\cmd.py", line 287, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/display_data.py", line 12, in <module>
    from parlai.scripts.display_data import display_data, setup_args
  File "d:\programs\python\thesis\parlai-master\parlai\parlai\scripts\display_data.py", line 20, in <module>
    from parlai.core.params import ParlaiParser
  File "d:\programs\python\thesis\parlai-master\parlai\parlai\core\params.py", line 14, in <module>
    import git
  File "D:\Programs\PYTHON\python-master\lib\site-packages\git\__init__.py", line 85, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc))
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

**Comment by stephenroller** [comment]
That looks like a problem with git python and maybe your git installation; we don't support Windows right now. I recommend you get a virtual machine running Ubuntu or similar. If you do figure out the issue, please post the solution here.
