### ISSUE TITLE
Giving instant bonus to MTurk workers, not working?

### ISSUE THREAD

**Issue by josharnoldjosh** [facebookresearch/ParlAI#2154]
Hello, in `run.py` in the `def run_conversation(mturk_manager, opt, workers):` function this is how I give a bonus to workers, however, I get an error saying `failed to pay bonus, the assignment ID does not exist`. Am I doing anything wrong?

```python
        def run_conversation(mturk_manager, opt, workers):
            world = MultiRoleAgentWorld(opt=opt, mturk_agents=workers)
            # run the world to completion
            while not world.episode_done():
                world.parley()

            # review & shutdown
            world.review_work()            
            print("Conversation complete!")

            # A folder to pay bonus later
            if not os.path.exists('/home/jarnold9/ParlAI/parlai/mturk/tasks/react_task_demo/gan_draw/pay_bonus_later/'):
                os.makedirs('/home/jarnold9/ParlAI/parlai/mturk/tasks/react_task_demo/gan_draw/pay_bonus_later/')
            
            # Decide to pay bonus or not
            if (world.should_pay_bonus == True):
                print("Image threshold met! Paying bonus!")
                for ag in workers:
                    if not opt['is_sandbox']:
                        try:
                            mturk_manager.pay_bonus(ag.worker_id, BONUS_PAY_AMOUNT, ag.assignment_id, "Successfully recreated an image to a high enough quality.", ag.assignment_id)
                        except Exception as error:
                            print("Uh oh. There was an error paying a bonus.")
                            try:
                                with open('/home/jarnold9/ParlAI/parlai/mturk/tasks/react_task_demo/gan_draw/pay_bonus_later/'+ag.assignment_id+".txt", 'w') as f:
                                    f.writelines([workers[0].worker_id+"\n", workers[1].worker_id])
                            except:
                                pass
            else:
                print("Failed to create the image to a high enough quality. Not paying bonus.")

            world.shutdown()

            # Return the contents for saving
            return world.prep_save_data(workers)
```

**Comment by JackUrb** [comment]
In order to pay a bonus, you'll need to approve the assignment first. I _think_ this is probably the problem.

**Comment by josharnoldjosh** [comment]
I do `world.review_work()` right before in which I approve the work, and the function for that is:

```python
    def review_work(self):        
        global review_agent
        def review_agent(ag):           
            if hasattr(ag, 'not_approve'):
                pass
            else:
                ag.approve_work()
        Parallel(n_jobs=len(self.mturk_agents), backend='threading')(delayed(review_agent)(agent) for agent in self.mturk_agents)
```

**Comment by josharnoldjosh** [comment]
Also, what is the order we should call `world.shutdown(), world.review_work()` and also paying the bonus straight after?

**Comment by josharnoldjosh** [comment]
Here is the error I get. `An error occurred (RequestError) when calling the SendBonus operation: Assignment 3RXCAC0YXXXXXXXXXXXXXXX does not exist. (1573795483091)` I have also tried just simply calling `agent.approve_work()` before trying to send the bonus. What may be calling this? I used the exact same previous code on a task and it seemed to work? Thanks!

**Comment by josharnoldjosh** [comment]
Perhaps this has something to do with it. I get this error randomly in my logs:

```
Exception in thread Hit-Status-Thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jarnold9/ParlAI/parlai/mturk/core/mturk_manager.py", line 308, in update_status
    hit = self.get_hit(hit_id)
  File "/home/jarnold9/ParlAI/parlai/mturk/core/mturk_manager.py", line 1675, in get_hit
    hit = client.get_hit(HITId=hit_id)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ThrottlingException) when calling the GetHIT operation (reached max retries: 4): Rate exceeded
```

**Comment by JackUrb** [comment]
Closing this as it's likely a stale issue.

Some analysis here - `agent.shutdown()` needs to be called before `approve_work`, and `approve_work` needs to be called before `send_bonus`.

I hope you were able to work this out!
