### ISSUE TITLE
ZeroDivisionError when using display data

### ISSUE THREAD

**Issue by liloup1789** [facebookresearch/ParlAI#2255]
Use this to open other questions or issues, and provide context here.
Hello, I have an issue with the examples/display_daya.py code when I use it with the demo of the https://parl.ai/docs/tutorial_task.html : 

> text:hello how are you today?   labels:i'm great thanks! what are you doing?
text:i've just been biking.     labels:oh nice, i haven't got on a bike in years!       episode_done:True

I created a build.py as recommended and an agents.py : 
`def _path(opt, filtered):
    # build the data if it does not exist
    build(opt)

    # set up path to data (specific to each dataset)
    print(opt['datapath'])
    dt = opt['datatype'].split(':')[0]
    print(dt)
    # print(os.path.join(opt['datapath'], 'cologne', 'pmctestparlai.txt'))
    return os.path.join(opt['datapath'], 'cologne', 'test_demo.txt')

class DefaultTeacher(ParlAIDialogTeacher):
    def __init__(self, opt, shared=None):
        super().__init__(opt, shared)
        opt = copy.deepcopy(opt)

        # get datafile
        opt['datafile'] = _path(opt, '')`

but when I run 

> examples/display_data.py -t cologne 

I have this error log : 
`Traceback (most recent call last):
  File "display_data.py", line 23, in <module>
    display_data(opt)
  File "/home/schaub/Documents/Akio/dev_parlai/parlai/parlai/scripts/display_data.py", line 47, in display_data
    world.parley()
  File "/home/schaub/Documents/Akio/dev_parlai/parlai/parlai/core/worlds.py", line 332, in parley
    acts[0] = agents[0].act()
  File "/home/schaub/Documents/Akio/dev_parlai/parlai/parlai/core/teachers.py", line 417, in act
    action, self.epochDone = self.next_example()
  File "/home/schaub/Documents/Akio/dev_parlai/parlai/parlai/core/teachers.py", line 282, in next_example
    self.episode_idx = self.next_episode_idx()
  File "/home/schaub/Documents/Akio/dev_parlai/parlai/parlai/core/teachers.py", line 269, in next_episode_idx
    self.index.value %= num_eps
ZeroDivisionError: integer division or modulo by zero
`

Any ideas ?

**Comment by stephenroller** [comment]
It's looking like it's interpreting the file has having no episodes, which is a bit strange. Do you lack `episode_done` in any of your examples? Can you share the contents of the file? Do you lack a newline on the last line of the file?

**Comment by liloup1789** [comment]
This is the content of test_demo.txt

> text:hello how are you today?   labels:i'm great thanks! what are you doing?
text:i've just been biking.     labels:oh nice, i haven't got on a bike in years!       episode_done:True


I just want to create a demo task to understand all the process. It is from the docs page, I assumed it was operational. 

this is my build.py : 

`import parlai.core.build_data as build_data
import os

def build(opt):
    # get path to data directory
    dpath = os.path.join(opt['datapath'], 'cologne')
    print(dpath)
    # define version if any
    version = 'None'


    # check if data had been previously built
    if not build_data.built(dpath, version_string=version):
        from shutil import copyfile
        print('[building data: ' + dpath + ']')

        # make a clean directory if needed
        if build_data.built(dpath):
            # an older version exists, so remove these outdated files.
            build_data.remove_dir(dpath)
        build_data.make_dir(dpath)

        copyfile("/home/schaub/Documents/Akio/dev_parlai/parlai/data/PMC/test_demo.txt","/home/schaub/Documents/Akio/dev_parlai/parlai/data/cologne/test_demo.txt")
        # mark the data as built
        build_data.mark_done(dpath, version_string=version)`

**Comment by liloup1789** [comment]
What is weird is that is works well when I do : 

`python display_data.py -t fromfile:parlaiformat --fromfile-datapath ../data/cologne/test_demo.txt 
`

**Comment by liloup1789** [comment]
Hey, 
I solved the problem, I needed to implement the setup_data() inside my agents.py 

BUT I have a new problem now : 
when  I try to use train_model.py, it works fine with the seq2seq model. 
But when I use memnn model I have this log error : 

`/home/schaub/Documents/Akio/dev_parlai/parlai/parlai/core/torch_ranker_agent.py:645: UserWarning: [ Executing train mode with provided inline set of candidates ]
  '[ Executing {} mode with provided inline set of candidates ]'.format(mode)
Traceback (most recent call last):
  File "train_model.py", line 17, in <module>
    TrainLoop(opt).train()
  File "/home/schaub/Documents/Akio/dev_parlai/parlai/parlai/scripts/train_model.py", line 723, in train
    world.parley()
  File "/home/schaub/Documents/Akio/dev_parlai/parlai/parlai/core/worlds.py", line 333, in parley
    acts[1] = agents[1].act()
  File "/home/schaub/Documents/Akio/dev_parlai/parlai/parlai/core/torch_agent.py", line 1760, in act
    return self.batch_act([self.observation])[0]
  File "/home/schaub/Documents/Akio/dev_parlai/parlai/parlai/core/torch_agent.py", line 1787, in batch_act
    output = self.train_step(batch)
  File "/home/schaub/Documents/Akio/dev_parlai/parlai/parlai/core/torch_ranker_agent.py", line 380, in train_step
    batch, source=self.candidates, mode='train'
  File "/home/schaub/Documents/Akio/dev_parlai/parlai/parlai/core/torch_ranker_agent.py", line 652, in _build_candidates
    "".format(m='candidates' if mode == 'train' else 'eval-candidates')
ValueError: If using candidate source 'inline', then batch.candidate_vecs cannot be None. If your task does not have inline candidates, consider using one of --candidates={'batch','fixed','vocab'}.
`
I figured out that the torch ranker needed explicit candidate list but I don't want to touch the code until I ask you
Any idea ?

**Comment by stephenroller** [comment]
If you add a label_candidates field to your teacher it will use them. Otherwise -cands batch will serve you well

**Comment by stephenroller** [comment]
Closing due to inactivity, feel free to reopen.
