### ISSUE TITLE
Unsupported pickle protocol 5

### ISSUE THREAD

**Issue by FelixLabelle** [facebookresearch/ParlAI#2267]
I tried running the QA data example (python run.py -nc 2 -r 0.00) and get the following error:
[ optional arguments: ] 
[  datapath: /home/dialcrowd/ParlAI/data ]
[ Mechanical Turk: ] 
[  allowed_conversations: 0 ]
[  block_qualification: None ]
[  count_complete: False ]
[  disconnect_qualification: None ]
[  hard_block: False ]
[  heroku_team: None ]
[  hobby: False ]
[  is_debug: False ]
[  is_sandbox: True ]
[  local: False ]
[  log_level: 20 ]
[  max_connections: 30 ]
[  max_hits_per_worker: 0 ]
[  max_time: 0 ]
[  max_time_qual: None ]
[  min_messages: 0 ]
[  mturk_log_path: /home/dialcrowd/ParlAI/logs/mturk ]
[  num_conversations: 2 ]
[  reward: 0.0 ]
[  task: None ]
[  tmp_dir: None ]
[  unique_qual_name: None ]
[  unique_worker: False ]
[  verbose: False ]
[ Current ParlAI commit: d3964886a7eae7c7c6921c6d676e216240cd030e ]
Traceback (most recent call last):
  File "run.py", line 128, in <module>
    main()
  File "run.py", line 48, in main
    mturk_manager = MTurkManager(opt=opt, mturk_agent_ids=[mturk_agent_id], use_db=True)
  File "/home/dialcrowd/ParlAI/parlai/mturk/core/mturk_manager.py", line 159, in __init__
    self.worker_manager = WorkerManager(self, opt)
  File "/home/dialcrowd/ParlAI/parlai/mturk/core/worker_manager.py", line 114, in __init__
    self.load_disconnects()
  File "/home/dialcrowd/ParlAI/parlai/mturk/core/worker_manager.py", line 218, in load_disconnects
    old_disconnects = pickle.load(f)
ValueError: unsupported pickle protocol: 5

The environment in question uses:
Python 3.6 & 3.7 (Several environments were tried)
Pytorch 1.1,1.2,1.3
Ubuntu 18.04
Conda 4.7.12

**Comment by JackUrb** [comment]
Hi @FelixLabelle - thanks for reaching out. I've never really seen this before though, can you try deleting the disconnects.pickle file from the parlai/mturk/core` directory?

**Comment by stephenroller** [comment]
Closing due to inactivity. Please feel free to repoen.
