### ISSUE TITLE
projects/convai2/interactive.py not using new message force_set feature

### ISSUE THREAD

**Issue by jsedoc** [facebookresearch/ParlAI#2277]
**Bug description**
The code hasn't been updated for the force_set.

**Reproduction steps**
python projects/convai2/interactive.py -mf models:convai2/seq2seq/convai2_self_seq2seq_model -m legacy:seq2seq:0 --no_cuda

**Expected behavior**
to just chat

**Logs**

```
Traceback (most recent call last):
  File "projects/convai2/interactive.py", line 126, in <module>
    interactive(parser.parse_args(print_args=False), print_parser=parser)
  File "projects/convai2/interactive.py", line 105, in interactive
    acts[0]['text'] = bot_persona + acts[0].get('text', 'hi')
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/parlai-0.1.0-py3.6.egg/parlai/core/message.py", line 26, in __setitem__
    'please use the function `force_set(key, value)`.'.format(key)
RuntimeError: Message already contains key `text`. If this was intentional, please use the function `force_set(key, value)`.
```

**Additional context**
possible fix
```
index 61ead742..9d478d75 100644
--- a/projects/convai2/interactive.py
+++ b/projects/convai2/interactive.py
@@ -102,7 +102,8 @@ def interactive(opt, print_parser=None):
         acts[0] = agents[0].act()
         # add the persona on to the first message
         if cnt == 0:
-            acts[0]['text'] = bot_persona + acts[0].get('text', 'hi')
+            #acts[0]['text'] = bot_persona + acts[0].get('text', 'hi')
+            acts[0].force_set('text',bot_persona + acts[0].get('text', 'hi'))
         agents[1].observe(acts[0])

```

**Comment by stephenroller** [comment]
Yes, that's the correct patch. Feel free to submit (deleting the comment out line of course).
