### ISSUE TITLE
KeyError: 'fromfile_datatype_extension'

### ISSUE THREAD

**Issue by XuZhengzhuo** [facebookresearch/ParlAI#2305]
**Bug description**
Please enter a clear and concise description of what the bug is.
I am making the data myself. When create `word2count.pkl`:, 
```
$ python projects/controllable_dialogue/controllable_seq2seq/nidf.py
```
I got this problem:
```
Traceback (most recent call last):
  File "/Users/sincerexu/ParlAI/parlai/core/worlds.py", line 1282, in _create_task_agents
    task_agents = my_module.create_agents(opt, task)  # type: ignore
AttributeError: module 'parlai.tasks.fromfile.agents' has no attribute 'create_agents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "projects/controllable_dialogue/controllable_seq2seq/arora.py", line 414, in <module>
    learn_arora(opt)
  File "projects/controllable_dialogue/controllable_seq2seq/arora.py", line 313, in learn_arora
    opt, count_inputs=False
  File "projects/controllable_dialogue/controllable_seq2seq/arora.py", line 254, in get_word_counts
    world = create_task(opt, agent)
  File "/Users/sincerexu/ParlAI/parlai/core/worlds.py", line 1386, in create_task
    world = create_task_world(opt, user_agents, default_world=default_world)
  File "/Users/sincerexu/ParlAI/parlai/core/worlds.py", line 1344, in create_task_world
    opt, user_agents, default_world=default_world
  File "/Users/sincerexu/ParlAI/parlai/core/worlds.py", line 1292, in _get_task_world
    task_agents = _create_task_agents(opt)
  File "/Users/sincerexu/ParlAI/parlai/core/worlds.py", line 1285, in _create_task_agents
    return create_task_agent_from_taskname(opt)
  File "/Users/sincerexu/ParlAI/parlai/core/agents.py", line 884, in create_task_agent_from_taskname
    task_agents = teacher_class(opt)
  File "/Users/sincerexu/ParlAI/parlai/tasks/fromfile/agents.py", line 80, in __init__
    if self.opt['fromfile_datatype_extension']:
KeyError: 'fromfile_datatype_extension'
```
What is going wrong?
The same situation  occurs:
```
$ python projects/controllable_dialogue/controllable_seq2seq/arora.py
```
I'll be grateful if u can help me.

**Comment by stephenroller** [comment]
What we’re you hoping/expecting?

To be honest, this looks like one of these leftover hacks from when the research was still very experimental. We can try to reason backwards.

**Comment by wxjttxs** [comment]
the same error, do you solve it now? if so, could you share it, thank you so much

**Comment by stephenroller** [comment]
I think if you added this line:

```
opt['fromfile_datatype_extension'] = False
```
to here:
https://github.com/facebookresearch/ParlAI/blob/aa418701c49e8c3a912897496978d687f1897097/projects/controllable_dialogue/controllable_seq2seq/arora.py#L304

It might work. Please tell me if that works or not.

**Comment by stephenroller** [comment]
Closing due to inactivity.
