### ISSUE TITLE
LIGHT Adventure Game Error - No module named 'parlai_internal'

### ISSUE THREAD

**Issue by impulsecorp** [facebookresearch/ParlAI#2310]
I am trying to run the LIGHT text adventure game in interactive mode (to play it) like this: 
python3 examples/interactive.py -mf "models:light/biranker_dialogue/model"
but get this error:   ModuleNotFoundError: No module named 'parlai_internal'
It seems related to having a parlai_internal folder (see https://github.com/facebookresearch/ParlAI/tree/master/example_parlai_internal) but creating that folder did not fix it, as it still is looking for the light_dialog project there (it gives this error:  ModuleNotFoundError: No module named 'parlai_internal.tasks.light_dialog').

This is the same error as a user got for WoW at https://github.com/facebookresearch/ParlAI/issues/2102 .

The full error is:
[ Current ParlAI commit: 45377d56ec3d5e8c1cfa2a1f8ecae9adf61ca208 ]
[ warning: overriding opt['model_file'] to /home/ubuntu/ParlAI/data/models/light/biranker_dialogue/model (previously: /checkpoint/jase/20190226/bert_try1/t=internal:lightdialog:lightlabeltype=speech_jobid=1/model )]
Dictionary: loading dictionary from /home/ubuntu/ParlAI/data/models/light/biranker_dialogue/model.dict
[ num words =  33796 ]
[BiEncoderRanker: full interactive mode on.]
[ *** building candidates file as they do not exist: /home/ubuntu/ParlAI/data/models/light/biranker_dialogue/model.cands-internal:light_dialog:light_label_type=speech.cands *** ]
[creating task(s): internal:light_dialog:light_label_type=speech]
Traceback (most recent call last):
  File "examples/interactive.py", line 19, in <module>
    interactive(opt, print_parser=parser)
  File "/home/ubuntu/ParlAI/parlai/scripts/interactive.py", line 69, in interactive
    agent = create_agent(opt, requireModelExists=True)
  File "/home/ubuntu/ParlAI/parlai/core/agents.py", line 738, in create_agent
    model = load_agent_module(opt)
  File "/home/ubuntu/ParlAI/parlai/core/agents.py", line 603, in load_agent_module
    return model_class(new_opt)
  File "/home/ubuntu/ParlAI/parlai/agents/bert_ranker/bi_encoder_ranker.py", line 48, in __init__
    super().__init__(opt, shared)
  File "/home/ubuntu/ParlAI/parlai/core/torch_ranker_agent.py", line 160, in __init__
    super().__init__(opt, shared)
  File "/home/ubuntu/ParlAI/parlai/core/torch_agent.py", line 726, in __init__
    self.set_interactive_mode(opt['interactive_mode'], shared)
  File "/home/ubuntu/ParlAI/parlai/core/torch_ranker_agent.py", line 235, in set_interactive_mode
    path = self.get_task_candidates_path()
  File "/home/ubuntu/ParlAI/parlai/core/torch_ranker_agent.py", line 258, in get_task_candidates_path
    build_cands(opt)
  File "/home/ubuntu/ParlAI/parlai/scripts/build_candidates.py", line 31, in build_cands
    world = create_task(opt, agent)
  File "/home/ubuntu/ParlAI/parlai/core/worlds.py", line 1386, in create_task
    world = create_task_world(opt, user_agents, default_world=default_world)
  File "/home/ubuntu/ParlAI/parlai/core/worlds.py", line 1344, in create_task_world
    opt, user_agents, default_world=default_world
  File "/home/ubuntu/ParlAI/parlai/core/worlds.py", line 1292, in _get_task_world
    task_agents = _create_task_agents(opt)
  File "/home/ubuntu/ParlAI/parlai/core/worlds.py", line 1278, in _create_task_agents
    my_module = importlib.import_module(module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'parlai_internal'

**Comment by emilydinan** [comment]
Hi -- thanks for flagging! The quickest fix is to run that command with the flag `-t light_dialog`. Leaving this issue open as the opt file for this model needs to change.

**Comment by impulsecorp** [comment]
That worked. After around 7 hours (on a Linux CPU server) of encoding the fixed candidates, it gave me the "Enter Your Message:" prompt and I then had a conversation with it. But it did not give me the persona/item/setting info as shown at https://parl.ai/projects/light/ so I did not know what to say to it. 

Here's my conversation with it:

[  type_optimization: all_encoder_layers ]
Enter Your Message: Fight me
/home/ubuntu/ParlAI/parlai/core/torch_ranker_agent.py:699: UserWarning: [ Executing eval mode with a common set of fixed candidates (n = 109476). ]
  "(n = {}). ]".format(mode, len(self.fixed_candidates))
[BiEncoderRanker]: Kill me...
Enter Your Message: Are you human
[BiEncoderRanker]: No I am real.
Enter Your Message: Find the gold
[BiEncoderRanker]: Gold! Please I beg you
Enter Your Message: I will give you money
[BiEncoderRanker]: I will give you 100 gold coins!
Enter Your Message: Yes, give them to me
[BiEncoderRanker]: Well here, give them this on my behalf!
Enter Your Message: Are you hungry
[BiEncoderRanker]: No, I hunger not when I am on duty, peasant!
Enter Your Message: I will kill the king
[BiEncoderRanker]: Eat well idiot! For it is the gallows for you! I will find my way to Paris on my own. See you in the next life peasant!

**Comment by JackUrb** [comment]
Hi @impulsecorp - The format we provide the models is as displayed in Figure 2 of the appendix of [our paper](https://arxiv.org/pdf/1903.03094.pdf) (page 12). The plaintext locations and personas you can pick from are in the `PARLAI_ROOT/data/light_dialogue/light_environment.pkl` file. We're working on an easier-to-use method for managing personas and settings for this model, and on pre-packaging the encodings so that you don't have to calculate them manually.

**Comment by jaseweston** [comment]
If you do:

 python3 examples/interactive.py -mf "models:light/biranker_dialogue/model" -t light_dialog:simple

You should get the persona/objects/setting info.
The only issue is that model wasn't trained exactly on that input, but it should still work:

[persona]:  _task_speech
_setting_name Bazaar Gambling, Bazaar
_setting_desc the gambling area reeks of alcohol and other indistinguishably bad smells. It is not a good area to hang around in, as there are people that eye you up and down.
_partner_name the king's mother who sits at their side.
_self_name wise men
_self_persona I am a wise men.

Enter Your Message: hello there!
[BiEncoderRanker]: Good morning friend. What brings you here. I came to reflect on financial situation.
Enter Your Message: What's going on?
[BiEncoderRanker]: I think I need some of your wise counsel, economist. We need to discuss our kingdom's finances.
Enter Your Message: Do you think we should raise taxes?
[BiEncoderRanker]: Perhaps we...INCREASE taxes...but tell people we're reducing them?

**Comment by stephenroller** [comment]
Closing this as it looks resolved, but please feel free to repoen if you have more questions.
