### ISSUE TITLE
Can't resolve 'custom_built_frontend'

### ISSUE THREAD

**Issue by josharnoldjosh** [facebookresearch/ParlAI#2321]
I get this error when I try to run the _react_custom_with_deps_ task:

```
ERROR in ./dev/app.jsx
Module not found: Error: Can't resolve 'custom_built_frontend' in '/home/jarnold9/ParlAI/parlai/mturk/tmp/heroku_server_731ce34e-reactcustomwithdeps/dev'
 @ ./dev/app.jsx 29:0-58 37:16-37 38:24-45
 @ ./dev/main.js
```

My steps to produce it are:

`git clone https://github.com/facebookresearch/ParlAI.git ~/ParlAI`
`sudo python3 setup.py develop`
`cd frontend/; sudo npm install --save`
`sudo run.py` (after changing directories of course into _react_custom_with_deps_)

The reason I use sudo is because if I try to run `python3 setup.py develop` on the linux server, it says: 

```
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/test-easy-install-14994.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.6/dist-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.readthedocs.io/en/latest/easy_install.html

Please make the appropriate changes for your system and try again.
```

**Comment by stephenroller** [comment]
You need to create a virtualenv or a conda environment to install parlai without sudo. I highly recommend that.

This maybe looks like an old task not using the big frontend. Can you check @JackUrb?

**Comment by josharnoldjosh** [comment]
@stephenroller I installed via virtualenv, and i get this error (i didn't use sudo in any of my installation commands):

This is with the personchat_chat task. I haven't been able to run a task successfully yet. Is there something wrong with my system?

```
Creating HITs...
You should be calling `ready_to_accept_workers` before `create_hits` to ensure that the socket is connected beforehits are added. This will be enforced in future versions.
Expiring all unassigned HITs...
Expiring all unassigned HITs...
Heroku: Deleting server: jarnold9-8a86e62a-personachatb
Destroying jarnold9-8a86e62a-personachatb (including all add-ons)... done
Traceback (most recent call last):
  File "run.py", line 147, in <module>
    main()
  File "run.py", line 87, in main
    mturk_manager.create_hits()
  File "/home/jarnold9/ParlAI/parlai/mturk/core/mturk_manager.py", line 1727, in create_hits
    qualifications=qualifications,
  File "/home/jarnold9/ParlAI/parlai/mturk/core/mturk_manager.py", line 1659, in create_additional_hits
    qualifications = self.get_qualification_list(qualifications)
  File "/home/jarnold9/ParlAI/parlai/mturk/core/mturk_manager.py", line 1646, in get_qualification_list
    shared_utils.print_and_log('Qualifications are not set in sandbox mode.')
TypeError: print_and_log() missing 1 required positional argument: 'message'
```

**Comment by stephenroller** [comment]
Ahh yes this is another issue. @emilydinan do you know what's going on in this, you were the one that committed #2276.

**Comment by josharnoldjosh** [comment]
For some reason, when I restore a previous commit on MacOSX it works fine but on my Ubuntu server it doesn't work.
