### ISSUE TITLE
ImportError when using pretrained transformers

### ISSUE THREAD

**Issue by zhongpeixiang** [facebookresearch/ParlAI#2347]
**Bug description**
```
Traceback (most recent call last):
  File "examples/interactive.py", line 19, in <module>
    interactive(opt, print_parser=parser)
  File "/home/peixiang/ParlAI/parlai/scripts/interactive.py", line 69, in interactive
    agent = create_agent(opt, requireModelExists=True)
  File "/home/peixiang/ParlAI/parlai/core/agents.py", line 388, in create_agent
    model = create_agent_from_opt_file(opt)
  File "/home/peixiang/ParlAI/parlai/core/agents.py", line 343, in create_agent_from_opt_file
    return model_class(new_opt)
  File "/home/peixiang/ParlAI/parlai/agents/transformer/polyencoder.py", line 100, in __init__
    super().__init__(opt, shared)
  File "/home/peixiang/ParlAI/parlai/core/torch_ranker_agent.py", line 175, in __init__
    self.model = self.build_model()
  File "/home/peixiang/ParlAI/parlai/agents/transformer/polyencoder.py", line 117, in build_model
    return PolyEncoderModule(self.opt, self.dict, self.NULL_IDX)
  File "/home/peixiang/ParlAI/parlai/agents/transformer/polyencoder.py", line 221, in __init__
    self.encoder_ctxt = self.get_encoder(opt, dict, null_idx, 'none_with_pos_embs')
  File "/home/peixiang/ParlAI/parlai/agents/transformer/polyencoder.py", line 307, in get_encoder
    output_scaling=opt['output_scaling'],
  File "/home/peixiang/ParlAI/parlai/agents/transformer/modules.py", line 456, in __init__
    self.norm_embeddings = LayerNorm(self.dim, eps=LAYER_NORM_EPS)
  File "/home/peixiang/anaconda3/lib/python3.7/site-packages/apex/normalization/fused_layer_norm.py", line 133, in __init__
    fused_layer_norm_cuda = importlib.import_module("fused_layer_norm_cuda")
  File "/home/peixiang/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/peixiang/anaconda3/lib/python3.7/site-packages/fused_layer_norm_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at7getTypeERKNS_6TensorE
```

**Reproduction steps**
```
python examples/interactive.py -m transformer/polyencoder \
    -mf zoo:pretrained_transformers/model_poly/model \
    --encode-candidate-vecs true \
    --eval-candidates fixed  \
    --fixed-candidates-path data/models/pretrained_transformers/convai_trainset_cands.txt
```

**Additional context**
Environment: Ubuntu 18.04, Python 3.7, PyTorch 1.2, Cuda 1.1

**Comment by zhongpeixiang** [comment]
I'm not sure if it is due to https://github.com/huggingface/transformers/issues/1093

**Comment by stephenroller** [comment]
It might be. It looks like there was a second part of the stack trace (an exception during catching an exception). Is it possible for you to paste that?

I suspect it is that you need to install apex. This is a long-standing bug: It’s very difficult to convince pickle it’s okay that the user doesn’t have this module on their system.

**Comment by stephenroller** [comment]
Actually, your situation looks like this isn't the case. You have apex installed, it's just compiled for the wrong environment.

Please reinstall it within your current environment. Make sure you provide the ` --cuda_ext  --cpp_ext` flags. Any problems you have should try to be addressed by the [APEX. team](https://github.com/NVIDIA/apex/).

Closing, but if you need to ask more questions it's okay.
