### ISSUE TITLE
Fb Messenger deployment tutorial

### ISSUE THREAD

**Issue by liloup1789** [facebookresearch/ParlAI#2357]
Hello, 
is there any tutorial for implementing a bot on fb messenger ? To test and/or interact with it in a lifelong learning fashion ? 

When I click on the link `https://parl.ai/docs/tutorial_messenger.html` from the README.md page, I get a 404 error 
Thanks

**Comment by liloup1789** [comment]
And when i run the run.py script, I have this error : 
`python parlai/chat_service/services/messenger/run.py --config-path parlai/chat_service/tasks/chatbot/config.yml 
[ optional arguments: ] 
[  datapath: /home/tf/Documents/Leon/parlai/ParlAI/data ]
[ Chat Services: ] 
[  config_path: parlai/chat_service/tasks/chatbot/config.yml ]
[  is_debug: False ]
[  password: None ]
[ Facebook Messenger: ] 
[  bypass_server_setup: False ]
[  force_page_token: False ]
[  local: False ]
[  log_level: 20 ]
[  verbose: False ]
[ Current ParlAI commit: 2927c796d1fdb0d5b396bd6bd514d3713fda4fd3 ]
/home/tf/Documents/Leon/parlai/ParlAI/parlai/chat_service/core/shared_utils.py:191: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  cfg = yaml.load(f.read())

You are going to allow people on Facebook to be agents in ParlAI.
During this process, Internet connection is required, and you should turn off your computer's auto-sleep feature.

Please press Enter to continue... 

Setting up Messenger webhook...
Heroku: Collecting files...
Traceback (most recent call last):
  File "parlai/chat_service/services/messenger/run.py", line 47, in <module>
    run(opt)
  File "parlai/chat_service/services/messenger/run.py", line 32, in run
    manager = MessengerManager(opt)
  File "/home/tf/Documents/Leon/parlai/ParlAI/parlai/chat_service/services/messenger/messenger_manager.py", line 43, in __init__
    self._complete_setup()
  File "/home/tf/Documents/Leon/parlai/ParlAI/parlai/chat_service/services/messenger/messenger_manager.py", line 61, in _complete_setup
    self.setup_server()
  File "/home/tf/Documents/Leon/parlai/ParlAI/parlai/chat_service/services/messenger/messenger_manager.py", line 199, in setup_server
    self.server_task_name, local=self.opt['local']
  File "/home/tf/Documents/Leon/parlai/ParlAI/parlai/chat_service/core/server_utils.py", line 288, in setup_server
    return setup_heroku_server(task_name)
  File "/home/tf/Documents/Leon/parlai/ParlAI/parlai/chat_service/core/server_utils.py", line 89, in setup_heroku_server
    shutil.copytree(server_source_directory_path, heroku_server_directory_path)
  File "/home/tf/miniconda3/envs/parlai/lib/python3.6/shutil.py", line 315, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: '/home/tf/Documents/Leon/parlai/ParlAI/parlai/chat_service/core/server'`

**Comment by stephenroller** [comment]
Looks like we renamed the page and failed to update the link. Here's the updated link: https://parl.ai/docs/tutorial_chat_service.html. I'll let @klshuster take over any further questions you might have.

**Comment by klshuster** [comment]
#2366 should fix the error you are having. please reopen if the issue persists after pulling from master.
