### ISSUE TITLE
Getting error when running examples/display_data.py

### ISSUE THREAD

**Issue by tibnb545** [facebookresearch/ParlAI#2514]
**Bug description**
After running 
```
git clone https://github.com/facebookresearch/ParlAI.git
cd ParlAI; python setup.py develop
```
to install ParlAI, when trying to run the first example script 
```
python examples/display_data.py -t babi:task1k:1
```
there is an error which is shown below.

**Logs**

```
Traceback (most recent call last):
  File "examples/display_data.py", line 23, in <module>
    display_data(opt)
  File "/home/user1/ParlAI/parlai/scripts/display_data.py", line 46, in display_data
    world.parley()
  File "/home/user1/ParlAI/parlai/core/worlds.py", line 342, in parley
    agents[0].observe(validate(acts[1]))
  File "/home/user1/ParlAI/parlai/core/teachers.py", line 444, in observe
    self.metrics.evaluate_response(observation, self.lastY)
  File "/home/user1/ParlAI/parlai/core/metrics.py", line 714, in evaluate_response
    self.add(f'bleu-{k}', BleuMetric.compute(prediction, labels, k))
  File "/home/user1/ParlAI/parlai/core/metrics.py", line 585, in add
    self._data[key] = self._data.get(key) + value
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'
```

**Comment by stephenroller** [comment]
Thanks for reporting.

I suspect the issue is that nltk isn’t installed, but the system should work around that.

**Comment by tgmerritt** [comment]
Having similar issue - 

```
Traceback (most recent call last):
  File "/Users/tyler/.pyenv/versions/3.7.2/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Users/tyler/ParlAI/parlai/core/worlds.py", line 1322, in run
    world.parley()
  File "/Users/tyler/ParlAI/parlai/core/worlds.py", line 349, in parley
    agents[0].observe(validate(acts[1]))
  File "/Users/tyler/ParlAI/parlai/core/teachers.py", line 445, in observe
    self.metrics.evaluate_response(observation, self.lastY)
  File "/Users/tyler/ParlAI/parlai/core/metrics.py", line 722, in evaluate_response
    self.add(f'bleu-{k}', BleuMetric.compute(prediction, labels, k))
  File "/Users/tyler/ParlAI/parlai/core/metrics.py", line 591, in add
    self._buffer[key] = self._buffer.get(key) + value
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'
```


Running `python examples/train_model.py -t babi:task10k:1 -mf /tmp/babi_memnn -bs 1 -nt 4 -eps 5 -m memnn --no-cuda` from the Quick Start guide

The training hasn't errored out just yet ~

**Comment by Meai1** [comment]
I have the same problem, I created a virtual environment for python so I dont see how this can be a problem at my end. The only thing that I had to do that I dont see in the readme or tutorial is that it was complaining about torch not being found so I installed it like this: `pip install torch torchvision`
I also installed torchtext via pip because I think I saw a message about that being missing as well, nothing changed though.
```
(myproject) pc@linux-a7b0:~/workarea/ParlAI> python -m parlai.scripts.display_data -t squad
[creating task(s): squad]
loading: /home/pc/workarea/ParlAI/data/SQuAD/train-v1.1.json
Traceback (most recent call last):
  File "/home/pc/.pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/pc/.pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/pc/workarea/ParlAI/parlai/scripts/display_data.py", line 113, in <module>
    DisplayData.main()
  File "/home/pc/workarea/ParlAI/parlai/scripts/script.py", line 79, in main
    return cls._run_args(None)
  File "/home/pc/workarea/ParlAI/parlai/scripts/script.py", line 66, in _run_args
    script.run()
  File "/home/pc/workarea/ParlAI/parlai/scripts/display_data.py", line 108, in run
    return display_data(self.opt)
  File "/home/pc/workarea/ParlAI/parlai/scripts/display_data.py", line 75, in display_data
    world.parley()
  File "/home/pc/workarea/ParlAI/parlai/core/worlds.py", line 349, in parley
    agents[0].observe(validate(acts[1]))
  File "/home/pc/workarea/ParlAI/parlai/core/teachers.py", line 445, in observe
    self.metrics.evaluate_response(observation, self.lastY)
  File "/home/pc/workarea/ParlAI/parlai/core/metrics.py", line 722, in evaluate_response
    self.add(f'bleu-{k}', BleuMetric.compute(prediction, labels, k))
  File "/home/pc/workarea/ParlAI/parlai/core/metrics.py", line 593, in add
    self._data[key] = self._data.get(key) + value
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'
```

**Comment by stephenroller** [comment]
What version of python were you on?

**Comment by Meai** [comment]
3.8.2

**Comment by stephenroller** [comment]
Still needs to be fixed.
