### ISSUE TITLE
Poly-encoder fine-tuning load error

### ISSUE THREAD

**Issue by sseol11** [facebookresearch/ParlAI#2539]
I fine-tuned poly-encoder model using my data. 
Also, I created new task as covid19 same as wikiqa task.
The training script as follows:

`python -u examples/train_model.py \
  --init-model zoo:pretrained_transformers/poly_model_huge_reddit/model \
  -t covid19 \
  --model transformer/polyencoder --batchsize 64 --eval-batchsize 10 \
  --warmup_updates 100 --lr-scheduler-patience 0 --lr-scheduler-decay 0.4 \
  -lr 5e-05 --data-parallel True --history-size 20 --label-truncate 72 \
  --text-truncate 360 --num-epochs 8.0 --max_train_time 200000 -veps 0.5 \
  -vme 8000 --validation-metric accuracy --validation-metric-mode max \
  --save-after-valid True --log_every_n_secs 20 --candidates batch --fp16 True \
  --dict-tokenizer bpe --dict-lower True --optimizer adamax --output-scaling 0.06 \
  --variant xlm --reduction-type mean --share-encoders False \
  --learn-positional-embeddings True --n-layers 12 --n-heads 12 --ffn-size 3072 \
  --attention-dropout 0.1 --relu-dropout 0.0 --dropout 0.1 --n-positions 1024 \
  --embedding-size 768 --activation gelu --embeddings-scale False --n-segments 2 \
  --learn-embeddings True --polyencoder-type codes --poly-n-codes 64 \
  --poly-attention-type basic --dict-endtoken __start__ \
  --model-file fine_tuning_model2/poly_encoder_covid19`

but the final step `[ task solved! stopping. ]` during the fine-tuning, it occurred error message like this: 

```
[ saving model checkpoint: fine_tuning_model_ver2/poly_encoder_covid19.checkpoint ]
[ new best accuracy: 1 (previous best was 0.9828) ]
[ saving best valid model: fine_tuning_model_ver2/poly_encoder_covid19 ]
[ task solved! stopping. ]
[ warning: overriding opt['init_model'] to zoo:pretrained_transformers/poly_model_huge_reddit/model (previously: /home/ubuntu/ParlAI/data/models/pretrained_transformers/poly_model_huge_reddit/model )]

***************************************************************************
[ WARNING ] : your model is being loaded with opts that do not exist in the model you are initializing the weights with: dynamic_batching: None,evaltask: None,eval_batchsize: 10,display_examples: False,num_epochs: 8.0,max_train_time: 200000.0,validation_every_n_secs: -1,save_every_n_secs: -1,save_after_valid: True,validation_every_n_epochs: 0.5,validation_max_exs: 8000,short_final_eval: False,validation_patience: 10,validation_metric: accuracy,validation_metric_mode: max,validation_cutoff: 1.0,load_from_checkpoint: False,validation_share_agent: False,metrics: default,aggregate_micro: False,tensorboard_log: False,dict_maxexs: -1,dict_include_valid: False,dict_include_test: False,log_every_n_secs: 20.0,fp16_impl: apex,force_fp16_tokens: True,adam_eps: 1e-08,adafactor_eps: 1e-30,0.001,history_add_global_end_token: None,max_lr_steps: -1,invsqrt_lr_decay_gamma: -1,encode_candidate_vecs_batchsize: 256,rank_top_k: -1,inference: max,topk: 5,return_cand_scores: False,n_encoder_layers: -1,n_decoder_layers: -1,interactive_mode: False

***************************************************************************
[ WARNING ] : your model is being loaded with opts that differ from the model you are initializing the weights with. Add the following args to your run command to change this: 

--task convai2 --download-path /private/home/edinan/ParlAI/downloads --batchsize 2 --datapath /private/home/edinan/ParlAI/data --single-turn False --encode-candidate-vecs False --polyencoder-type n-first --parlai-home /private/home/edinan/ParlAI
***************************************************************************
[ Using CUDA ]
Dictionary: loading dictionary from fine_tuning_model_ver2/poly_encoder_covid19.dict
[ num words =  932 ]
Total parameters: 173,174,784 (173,174,784 trainable)
Loading existing model parameters from fine_tuning_model_ver2/poly_encoder_covid19
Traceback (most recent call last):
  File "/home/ubuntu/ParlAI/parlai/core/torch_agent.py", line 3726, in load_state_dict
    self.model.load_state_dict(state_dict)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for PolyEncoderModule:
	size mismatch for encoder_ctxt.embeddings.weight: copying a param with shape torch.Size([54944, 768]) from checkpoint, the shape in current model is torch.Size([936, 768]).
	size mismatch for encoder_cand.embeddings.weight: copying a param with shape torch.Size([54944, 768]) from checkpoint, the shape in current model is torch.Size([936, 768]).

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ubuntu/ParlAI/examples/train_model.py", line 17, in <module>
    TrainLoop(opt).train()
  File "/home/ubuntu/ParlAI/parlai/scripts/train_model.py", line 1467, in train
    self.agent = create_agent(opt)
  File "/home/ubuntu/ParlAI/parlai/core/agents.py", line 864, in create_agent
    model = create_agent_from_opt_file(opt)
  File "/home/ubuntu/ParlAI/parlai/core/agents.py", line 819, in create_agent_from_opt_file
    return model_class(new_opt)
  File "/home/ubuntu/ParlAI/parlai/agents/transformer/polyencoder.py", line 119, in __init__
    super().__init__(opt, shared)
  File "/home/ubuntu/ParlAI/parlai/core/torch_ranker_agent.py", line 1175, in __init__
    states = self.load(init_model)
  File "/home/ubuntu/ParlAI/parlai/core/torch_agent.py", line 3753, in load
    self.load_state_dict(states['model'])
  File "/home/ubuntu/ParlAI/parlai/agents/transformer/polyencoder.py", line 237, in load_state_dict
    super().load_state_dict(state_dict)
  File "/home/ubuntu/ParlAI/parlai/core/torch_agent.py", line 3731, in load_state_dict
    f'{msg_}\n'
RuntimeError: Error(s) in loading state_dict for PolyEncoderModule:
	size mismatch for encoder_ctxt.embeddings.weight: copying a param with shape torch.Size([54944, 768]) from checkpoint, the shape in current model is torch.Size([936, 768]).
	size mismatch for encoder_cand.embeddings.weight: copying a param with shape torch.Size([54944, 768]) from checkpoint, the shape in current model is torch.Size([936, 768]).
-----------------
Could not load the model due to a size mismatch in the embeddings. A common reason for this is trying to load a model trained with fp16 but loaded without fp16. Try adding --fp16 true or --force-fp16-tokens true.

Process finished with exit code 1
```

I think it related to the previous issue #1641.

**Comment by stephenroller** [comment]
It looks like the dict isn't being loaded.

Maybe add `--dict-file zoo:pretrained_transformers/poly_model_huge_reddit/model.dict` to the initial training. It's unclear to me why this isn't being done automatically on the reload.

**Comment by stephenroller** [comment]
(Maybe something in our recent BPE refactor?)

**Comment by sseol11** [comment]
Your suggestion works for me! thanks! 

```
[ saving model checkpoint: fine_tuning_model_ver3/poly_encoder_covid19.checkpoint ]
[ new best accuracy: 1 (previous best was 0.9828) ]
[ saving best valid model: fine_tuning_model_ver3/poly_encoder_covid19 ]
[ task solved! stopping. ]
[ warning: overriding opt['init_model'] to zoo:pretrained_transformers/poly_model_huge_reddit/model (previously: /home/ubuntu/ParlAI/data/models/pretrained_transformers/poly_model_huge_reddit/model )]

***************************************************************************
[ WARNING ] : your model is being loaded with opts that do not exist in the model you are initializing the weights with: dynamic_batching: None,evaltask: None,eval_batchsize: 10,display_examples: False,num_epochs: 8.0,max_train_time: 200000.0,validation_every_n_secs: -1,save_every_n_secs: -1,save_after_valid: True,validation_every_n_epochs: 0.5,validation_max_exs: 8000,short_final_eval: False,validation_patience: 10,validation_metric: accuracy,validation_metric_mode: max,validation_cutoff: 1.0,load_from_checkpoint: False,validation_share_agent: False,metrics: default,aggregate_micro: False,tensorboard_log: False,dict_maxexs: -1,dict_include_valid: False,dict_include_test: False,log_every_n_secs: 20.0,fp16_impl: apex,force_fp16_tokens: True,adam_eps: 1e-08,adafactor_eps: 1e-30,0.001,history_add_global_end_token: None,max_lr_steps: -1,invsqrt_lr_decay_gamma: -1,encode_candidate_vecs_batchsize: 256,rank_top_k: -1,inference: max,topk: 5,return_cand_scores: False,n_encoder_layers: -1,n_decoder_layers: -1,interactive_mode: False

***************************************************************************
[ WARNING ] : your model is being loaded with opts that differ from the model you are initializing the weights with. Add the following args to your run command to change this: 

--task convai2 --download-path /private/home/edinan/ParlAI/downloads --batchsize 2 --datapath /private/home/edinan/ParlAI/data --single-turn False --encode-candidate-vecs False --polyencoder-type n-first --parlai-home /private/home/edinan/ParlAI
***************************************************************************
[ Using CUDA ]
Dictionary: loading dictionary from fine_tuning_model_ver3/poly_encoder_covid19.dict
[ num words =  54944 ]
Total parameters: 256,131,072 (256,131,072 trainable)
Loading existing model parameters from fine_tuning_model_ver3/poly_encoder_covid19
Warning:  FP16_Optimizer is deprecated and dangerous, and will be deleted soon.  If it still works, you're probably getting lucky.  For mixed precision, use the documented API https://nvidia.github.io/apex/amp.html, with opt_level=O1.
[creating task(s): covid19]
[loading fbdialog data:/home/ubuntu/ParlAI/data/Covid19QA/valid-filtered.txt]
[ running eval: valid ]
[ eval completed in 3.90s ]
valid:
{'exs': 58, 'accuracy': 1.0, 'f1': 1.0, 'bleu-4': 1.0, 'hits@1': 1.0, 'hits@5': 1.0, 'hits@10': 1.0, 'hits@100': 1.0, 'loss': 0.01072, 'rank': 1.0, 'mrr': 1.0, 'tpb': 479.5, 'lr': 5e-09, 'gpu_mem': 1.464, 'total_train_updates': 24}

[creating task(s): covid19]
[loading fbdialog data:/home/ubuntu/ParlAI/data/Covid19QA/test-filtered.txt]
[ running eval: test ]
[ eval completed in 3.70s ]
test:
{'exs': 56, 'accuracy': 1.0, 'f1': 1.0, 'bleu-4': 1.0, 'hits@1': 1.0, 'hits@5': 1.0, 'hits@10': 1.0, 'hits@100': 1.0, 'loss': 0.01938, 'rank': 1.0, 'mrr': 1.0, 'tpb': 455.5, 'lr': 5e-09, 'gpu_mem': 1.464, 'total_train_updates': 24}


Process finished with exit code 0
```
