### ISSUE TITLE
light pre-trained model not running

### ISSUE THREAD

**Issue by pijusch** [facebookresearch/ParlAI#2554]
**Bug description**
I am getting error while running the light pretrained model.

**Reproduction steps**
python examples/eval_model.py -t light_dialog -mf models:light/biranker_dialogue/model -ne 10

**Expected behavior**
This should run the evaluation on pre-trained model.

**Logs**
Please paste the command line output:

```
Traceback (most recent call last):
  File "examples/eval_model.py", line 17, in <module>
    opt = parser.parse_args(print_args=False)
  File "/users/ParlAI/parlai/core/params.py", line 990, in parse_args
    self.add_extra_args(args)
  File "/users/ParlAI/parlai/core/params.py", line 830, in add_extra_args
    self.add_model_subargs(model)
  File "/users/ParlAI/parlai/core/params.py", line 738, in add_model_subargs
    agent = load_agent_module(model)
  File "/users/ParlAI/parlai/core/loader.py", line 133, in load_agent_module
    my_module = importlib.import_module(module_name)
  File "/users/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/users/ParlAI/parlai/agents/bert_ranker/bi_encoder_ranker.py", line 6, in <module>
    from parlai.core.torch_ranker_agent import TorchRankerAgent
  File "/users/ParlAI/parlai/core/torch_ranker_agent.py", line 25, in <module>
    from parlai.core.torch_agent import TorchAgent, Output
  File "/users/ParlAI/parlai/core/torch_agent.py", line 35, in <module>
    from parlai.core.dict import DictionaryAgent
  File "/users/ParlAI/parlai/core/dict.py", line 12, in <module>
    from parlai.utils.bpe import bpe_factory, BPEHelper
  File "/users/ParlAI/parlai/utils/bpe.py", line 18, in <module>
    from typing_extensions import final
ModuleNotFoundError: No module named 'typing_extensions'
```

**Additional context**
It was working fine. I think a recent update has caused this error.

**Comment by pijusch** [comment]
commenting out final in file parlai/utils/bpe.py works

**Comment by stephenroller** [comment]
Please `pip install typing_extensions`
