### ISSUE TITLE
Chat service error [terminal chat]

### ISSUE THREAD

**Issue by sseol11** [facebookresearch/ParlAI#2582]
**Bug description**
I ran chat service like this command line. 
`python parlai/chat_service/services/terminal_chat/run.py --config-path parlai/chat_service/tasks/chatbot/config.yml --port 5002`

also on the other terminal. 
`python parlai/chat_service/services/terminal_chat/client.py --port 5002`

**Expected behavior**
interactive with bot.

**Logs**
Please paste the command line output:

```
[I 200423 00:51:07 agents:55] Received new message: {'text': 'begin', 'payload': None, 'sender': {'id': '548465f1-25c0-4594-9ef3-a20159fef0e6'}, 'recipient': {'id': 0}}
2020-04-23 00:51:07: Adding agent 548465f1-25c0-4594-9ef3-a20159fef0e6 to pool...
onboarding/overworld complete
starting pool
2020-04-23 00:51:07: Removing agent 548465f1-25c0-4594-9ef3-a20159fef0e6 from pool...
Starting task t_3...
[E 200423 00:51:07 logging:44] World default had error KeyError('models',)
World default had error KeyError('models',)
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/ParlAI/parlai/chat_service/core/world_runner.py", line 128, in _world_fn
    return self._run_world(task, world_name, agents)
  File "/home/ubuntu/ParlAI/parlai/chat_service/core/world_runner.py", line 95, in _run_world
    world = world_generator(self.opt, agents)
  File "/home/ubuntu/ParlAI/parlai/chat_service/tasks/chatbot/worlds.py", line 44, in generate_world
    if opt['models'] is None:
KeyError: 'models'
Next task: None

```

**Comment by sseol11** [comment]
It seems typo on chatbot/worlds.py line 44 if opt['model'] is None:
wrote on chatbot/config.yml as model like this.
```
opt:
  debug: True
  model: legacy:seq2seq:0
  model_file: models:convai2/seq2seq/convai2_self_seq2seq_model
  override:
    model: legacy:seq2seq:0
    no_cuda: True
```

But still have issue. 
```
[E 200423 01:15:24 logging:44] World default had error KeyError('shared_bot_params',)
World default had error KeyError('shared_bot_params',)
NoneType: None
Next task: None

```

**Comment by sseol11** [comment]
I solved this issue, it seems not callable the model function. 

ParlAI/parlai/chat_service/tasks/chatbot/worlds.py

```
     @staticmethod
     def generate_world(opt, agents):
-        if opt['model'] is None and opt['model_file'] is None:
+        if opt['model'] is None:
             raise RuntimeError("Model must be specified")
         return MessengerBotChatTaskWorld(
-            opt, agents[0], create_agent_from_shared(opt['shared_bot_params'])
+            opt,
+            agents[0],
+            create_agent_from_shared(
+                # opt['shared_bot_params'][MessengerBotChatTaskWorld.MODEL_KEY]
+                opt['shared_bot_params']
+            ),
         )
```
on ParlAI/parlai/chat_service/services/websocket/websocket_manager.py
```
@@ -70,12 +70,8 @@ class WebsocketManager(ChatServiceManager):
         """
         Load model if necessary.
         """
-        if 'models' in self.opt and self.should_load_model:
-            model_params = {}
-            for model in self.opt['models']:
-                model_opt = self.opt['models'][model]
-                model_params[model] = create_agent(model_opt).share()
-            self.runner_opt['shared_bot_params'] = model_params
+        if 'model' in self.opt:
+            self.runner_opt['shared_bot_params'] = create_agent(self.runner_opt).share()
 
```

**Comment by stephenroller** [comment]
cc @klshuster, @hadasah.

**Comment by klshuster** [comment]
These commands work on master, we switched the way that models are specified in the config - the fix that is suggested above is for the old config style
