### ISSUE TITLE
Getting error when attempting to run HuggingFace under standard agents in the docs

### ISSUE THREAD

**Issue by ahowe444** [facebookresearch/ParlAI#2606]
**Expected behavior**
Give a clear and concise description of what you expected to happen.
I am attempting to run the example at this link: https://parl.ai/docs/agent_refs/hugging_face.html
It is a simple run of HuggingFace GPT2 in interactive mode, but I get the following error after CTRL-C terminating after hanging on the userwarning.
**Logs**
Please paste the command line output:

```
[ BPEHelper Arguments: ]
[  bpe_add_prefix_space: None ]
[  bpe_merge: None ]
[  bpe_vocab: None ]
[ Learning Rate Scheduler: ]
[  invsqrt_lr_decay_gamma: -1 ]
[  lr_scheduler: reduceonplateau ]
[  lr_scheduler_decay: 0.5 ]
[  lr_scheduler_patience: 3 ]
[  max_lr_steps: -1 ]
[  update_freq: 1 ]
[  warmup_rate: 0.0001 ]
[  warmup_updates: -1 ]
Enter [DONE] if you want to end the episode, [EXIT] to quit.
[creating task(s): interactive]
Enter Your Message: Parrots are
/pytorch/aten/src/ATen/native/BinaryOps.cpp:81: UserWarning: Integer division of tensors using div or / is deprecated, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.
^CTraceback (most recent call last):
  File "examples/interactive.py", line 16, in <module>
    Interactive.main()
  File "/home/whowe1/ParlAI/parlai/scripts/script.py", line 79, in main
    return cls._run_args(None)
  File "/home/whowe1/ParlAI/parlai/scripts/script.py", line 66, in _run_args
    script.run()
  File "/home/whowe1/ParlAI/parlai/scripts/interactive.py", line 94, in run
    return interactive(self.opt, print_parser=self.parser)
  File "/home/whowe1/ParlAI/parlai/scripts/interactive.py", line 80, in interactive
    world.parley()
  File "/home/whowe1/ParlAI/parlai/tasks/interactive/worlds.py", line 72, in parley
    acts[1] = agents[1].act()
  File "/home/whowe1/ParlAI/parlai/core/torch_agent.py", line 1883, in act
    response = self.batch_act([self.observation])[0]
  File "/home/whowe1/ParlAI/parlai/core/torch_agent.py", line 1933, in batch_act
    output = self.eval_step(batch)
  File "/home/whowe1/ParlAI/parlai/core/torch_generator_agent.py", line 743, in eval_step
    beam_preds_scores, _ = self._generate(batch, self.beam_size, maxlen)
  File "/home/whowe1/ParlAI/parlai/core/torch_generator_agent.py", line 936, in _generate
    incr_state, incr_state_inds
  File "/home/whowe1/ParlAI/parlai/agents/hugging_face/gpt2.py", line 151, in reorder_decoder_incremental_state
    new_incr_state.append(torch.index_select(layer_past, 1, inds))
KeyboardInterrupt
^C
```

**Additional context**
Add any other context about the problem here. (like proxy settings, network setup, overall goals, etc.)

**Comment by emilydinan** [comment]
Hi, that is not an error, it's showing the lines that were last executed before you hit Ctrl-C. How long did you wait before hitting Ctrl-C?

**Comment by ahowe444** [comment]
I meant the warning from pytorch. Sidenote, I realized this warning from BinaryOps.cpp was not the issue since I am able to run the Blender model in parlai despite also getting this warning. Sorry to bother, I think my laptop may just not have been able to handle inference for this particular model...

**Comment by emilydinan** [comment]
No worries! Inference is quite slow on CPU, so some wait time is to be expected. I'm going to close for now but feel free to reopen if you have further questions.
