### ISSUE TITLE
Requires Torch and other modules

### ISSUE THREAD

**Issue by hughdbrown** [facebookresearch/ParlAI#2639]
```
% pip install -r requirements.txt
...
% PYTHONPATH=$(pwd) python parlai/scripts/safe_interactive.py -t blended_skill_talk -mf zoo:blender/blender_3B/model
Traceback (most recent call last):
  File "parlai/scripts/safe_interactive.py", line 13, in <module>
    from parlai.core.worlds import create_task
  File "/home/ubuntu/workspace/ParlAI/parlai/core/worlds.py", line 57, in <module>
    from parlai.core.metrics import aggregate_named_reports
  File "/home/ubuntu/workspace/ParlAI/parlai/core/metrics.py", line 20, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
% pip install torch
...
% PYTHONPATH=$(pwd) python parlai/scripts/safe_interactive.py -t blended_skill_talk -mf zoo:blender/blender_3B/model
...
raise RuntimeError(
RuntimeError: Please run "pip install 'git+https://github.com/rsennrich/subword-nmt.git#egg=subword-nmt'"
```

**Comment by stephenroller** [comment]
Not all modules are required for all parts of ParlAI. We try to raise specific errors in specific spots.

The torch one is tricky, as it can require special installation.
