### ISSUE TITLE
Runtime error in Seq2Seq agent caused by changes to .t() in PyTorch v0.2

### ISSUE THREAD

**Issue by kearnsw** [facebookresearch/ParlAI#270]
As of PyTorch v0.2, the .t() function is only applicable to 2D Variables: https://github.com/pytorch/pytorch/commit/8d33603901100dbdff43b1947867430a93432999. This causes a runtime error when calling the Seq2Seq agent as in the following documentation example:
```
user:~/projects/ParlAI λ python examples/train_model.py -m seq2seq -t babi:task1k:1 -bs 8 -e 1 -mf /tmp/model_s2s 
Traceback (most recent call last):
  File "examples/train_model.py", line 216, in <module>
    main()
  File "examples/train_model.py", line 130, in main
    world.parley()
  File "/home/user/projects/ParlAI/parlai/core/worlds.py", line 601, in parley
    batch_act = self.batch_act(index, batch_observations[index])
  File "/home/user/projects/ParlAI/parlai/core/worlds.py", line 574, in batch_act
    batch_actions = a.batch_act(batch_observation)
  File "/home/user/projects/ParlAI/parlai/agents/seq2seq/seq2seq.py", line 425, in batch_act
    predictions, text_cand_inds = self.predict(xs, ys, cands)
  File "/home/user/projects/ParlAI/parlai/agents/seq2seq/seq2seq.py", line 218, in predict
    xes = self.lt(xs).t()
  File "/home/user/packages/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 729, in t
    raise RuntimeError("t() expects a 2D Variable, but self is {}D".format(self.dim()))
RuntimeError: t() expects a 2D Variable, but self is 3D 
```

**Comment by alexholdenmiller** [comment]
thanks for flagging, I'll update
