### ISSUE TITLE
--multimodal true option error: cannot load model

### ISSUE THREAD

**Issue by yskimno1** [facebookresearch/ParlAI#2744]
**Bug description**
Please enter a clear and concise description of what the bug is.

I wanted to use image_chat/transresnet_multimodal/transresnet_multimodal.py, so I used these options:

python3 examples/eval_model.py -bs 128 --n-heads 5 -t image_chat --multimodal true -mf models:image_chat/transresnet_multimodal/model -dt test

However, it shows an error message that it cannot load pre-trained model, because it does not contain some state_dict keys. Are my options wrong? or, is my pre-trained model(which automatically downloaded from the code) wrong? Then, can I download appropriate pre-trained model?

**Reproduction steps**
Enter steps to reproduce the behavior.

**Expected behavior**
Give a clear and concise description of what you expected to happen.

**Logs**
Please paste the command line output:
Traceback (most recent call last):
  File "examples/eval_model.py", line 18, in <module>
    eval_model(opt, print_parser=parser)
  File "/home/yunseong/parlai/ParlAI/parlai/scripts/eval_model.py", line 177, in eval_model
    agent = create_agent(opt, requireModelExists=True)
  File "/home/yunseong/parlai/ParlAI/parlai/core/agents.py", line 401, in create_agent
    model = create_agent_from_opt_file(opt)
  File "/home/yunseong/parlai/ParlAI/parlai/core/agents.py", line 356, in create_agent_from_opt_file
    return model_class(new_opt)
  File "/home/yunseong/parlai/ParlAI/projects/image_chat/transresnet_multimodal/transresnet_multimodal.py", line 67, in __init__
    super().__init__(opt, shared)
  File "/home/yunseong/parlai/ParlAI/projects/personality_captions/transresnet/transresnet.py", line 100, in __init__
    self._build_model()
  File "/home/yunseong/parlai/ParlAI/projects/image_chat/transresnet_multimodal/transresnet_multimodal.py", line 96, in _build_model
    self.load(init_model_path)
  File "/home/yunseong/parlai/ParlAI/projects/personality_captions/transresnet/transresnet.py", line 515, in load
    self.model.load_state_dict(states['model'])
  File "/usr/local/lib/python3.6/dist-packages/torch-1.4.0-py3.6-linux-x86_64.egg/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for TransresnetMultimodalModel:
	Missing key(s) in state_dict: "multimodal_encoder.position_embeddings.weight", "multimodal_encoder.layers.0.attention.q_lin.weight", "multimodal_encoder.layers.0.attention.q_lin.bias", "multimodal_encoder.layers.0.attention.k_lin.weight", "multimodal_encoder.layers.0.attention.k_lin.bias", "multimodal_encoder.layers.0.attention.v_lin.weight", "multimodal_encoder.layers.0.attention.v_lin.bias", "multimodal_encoder.layers.0.attention.out_lin.weight", "multimodal_encoder.layers.0.attention.out_lin.bias", "multimodal_encoder.layers.0.norm1.weight", "multimodal_encoder.layers.0.norm1.bias", "multimodal_encoder.layers.0.ffn.lin1.weight", "multimodal_encoder.layers.0.ffn.lin1.bias", "multimodal_encoder.layers.0.ffn.lin2.weight", "multimodal_encoder.layers.0.ffn.lin2.bias", "multimodal_encoder.layers.0.norm2.weight", "multimodal_encoder.layers.0.norm2.bias", "multimodal_encoder.layers.1.attention.q_lin.weight", "multimodal_encoder.layers.1.attention.q_lin.bias", "multimodal_encoder.layers.1.attention.k_lin.weight", "multimodal_encoder.layers.1.attention.k_lin.bias", "multimodal_encoder.layers.1.attention.v_lin.weight", "multimodal_encoder.layers.1.attention.v_lin.bias", "multimodal_encoder.layers.1.attention.out_lin.weight", "multimodal_encoder.layers.1.attention.out_lin.bias", "multimodal_encoder.layers.1.norm1.weight", "multimodal_encoder.layers.1.norm1.bias", "multimodal_encoder.layers.1.ffn.lin1.weight", "multimodal_encoder.layers.1.ffn.lin1.bias", "multimodal_encoder.layers.1.ffn.lin2.weight", "multimodal_encoder.layers.1.ffn.lin2.bias", "multimodal_encoder.layers.1.norm2.weight", "multimodal_encoder.layers.1.norm2.bias".

```
Output goes here
```

**Additional context**
Add any other context about the problem here. (like proxy settings, network setup, overall goals, etc.)

**Comment by yskimno1** [comment]
I've changed the load function in projects/personality_capsions/transresnet/modules.py like below:

        if 'model' in states:
            self.model.load_state_dict(states['model'], strict=False)

, and now it works. However, I'm still worrying that the current pre-trained model does not provide multimodal weights as well...
