### ISSUE TITLE
Having a Central Agent that controls multiple other agents 

### ISSUE THREAD

**Issue by AbdullaRifai** [facebookresearch/ParlAI#2771]
I copy pasted the code for _TorchAgent_ and I am playing around with it to see if having a central act method that chooses a response based on a confidence level. Those responses with confidence levels are given by each multiple instances of agents (like the _second_agent_ in this example). (The random is just for testing)
```
    def act(self):
        """
        Call batch_act with the singleton batch.
        """
        number = random()
        # BatchWorld handles calling self_observe, but we're in a Hogwild or Interactive
        # world, so we need to handle this ourselves.
        second_agent = copy.deepcopy(self)
        response = second_agent.act()
        if number < 0.5:
            response = self.batch_act([self.observation])[0]

        self.self_observe(response)
        return response
```

I got the following Error: 
```
C:\Users\rifai\Desktop\Research\May 6\Blender\~\ParlAI>python examples/display_model.py -t babi:task10k:1 -m internal:Covid
[ optional arguments: ]
[  display_ignore_fields:  ]
[  num_examples: 10 ]
[  verbose: False ]
[ Main ParlAI Arguments: ]
[  batchsize: 1 ]
[  datapath: c:\users\rifai\desktop\research\may 6\blender\~\parlai\data ]
[  datatype: valid ]
[  download_path: c:\users\rifai\desktop\research\may 6\blender\~\parlai\downloads ]
[  dynamic_batching: None ]
[  hide_labels: False ]
[  image_mode: raw ]
[  init_opt: None ]
[  multitask_weights: [1] ]
[  numthreads: 1 ]
[  show_advanced_args: False ]
[  task: babi:task10k:1 ]
[ ParlAI Model Arguments: ]
[  dict_class: parlai.core.dict:DictionaryAgent ]
[  init_model: None ]
[  model: internal:Covid ]
[  model_file: None ]
[ ParlAI Image Preprocessing Arguments: ]
[  image_cropsize: 224 ]
[  image_size: 256 ]
[ TorchAgent Arguments: ]
[  add_p1_after_newln: False ]
[  delimiter:
 ]
[  embedding_projection: random ]
[  embedding_type: random ]
[  force_fp16_tokens: False ]
[  fp16: False ]
[  fp16_impl: apex ]
[  gpu: -1 ]
[  history_add_global_end_token: None ]
[  history_size: -1 ]
[  interactive_mode: False ]
[  label_truncate: None ]
[  no_cuda: False ]
[  person_tokens: False ]
[  rank_candidates: False ]
[  split_lines: False ]
[  text_truncate: None ]
[  truncate: -1 ]
[  use_reply: label ]
[ Optimizer Arguments: ]
[  adafactor_eps: (1e-30, 0.001) ]
[  adam_eps: 1e-08 ]
[  betas: (0.9, 0.999) ]
[  gradient_clip: 0.1 ]
[  learningrate: 1 ]
[  momentum: 0 ]
[  nesterov: True ]
[  nus: (0.7,) ]
[  optimizer: sgd ]
[  weight_decay: None ]
[ Dictionary Arguments: ]
[  bpe_debug: False ]
[  dict_endtoken: __end__ ]
[  dict_file: None ]
[  dict_initpath: None ]
[  dict_language: english ]
[  dict_lower: False ]
[  dict_max_ngram_size: -1 ]
[  dict_maxtokens: -1 ]
[  dict_minfreq: 0 ]
[  dict_nulltoken: __null__ ]
[  dict_starttoken: __start__ ]
[  dict_textfields: text,labels ]
[  dict_tokenizer: re ]
[  dict_unktoken: __unk__ ]
[ BPEHelper Arguments: ]
[  bpe_add_prefix_space: None ]
[  bpe_merge: None ]
[  bpe_vocab: None ]
[ Learning Rate Scheduler: ]
[  invsqrt_lr_decay_gamma: -1 ]
[  lr_scheduler: reduceonplateau ]
[  lr_scheduler_decay: 0.5 ]
[  lr_scheduler_patience: 3 ]
[  max_lr_steps: -1 ]
[  update_freq: 1 ]
[  warmup_rate: 0.0001 ]
[  warmup_updates: -1 ]
[ Current ParlAI commit: 3a141ce09fa62fd56cbef198d35ccf1aacd47063 ]
[ Current internal commit: 3a141ce09fa62fd56cbef198d35ccf1aacd47063 ]
[ Using CUDA ]
2020-06-17 20:29:18,039 | INFO | Using CUDA
[creating task(s): babi:task10k:1]
[loading fbdialog data:c:\users\rifai\desktop\research\may 6\blender\~\parlai\data\bAbI\tasks_1-20_v1-2\en-valid-10k-nosf\qa1_valid.txt]
Traceback (most recent call last):
  File "c:\users\rifai\desktop\research\may 6\blender\~\parlai\parlai_internal\agents\Covid\Covid.py", line 348, in act
    response = second_agent.act()
  File "c:\users\rifai\desktop\research\may 6\blender\~\parlai\parlai_internal\agents\Covid\Covid.py", line 348, in act
    response = second_agent.act()
  File "c:\users\rifai\desktop\research\may 6\blender\~\parlai\parlai_internal\agents\Covid\Covid.py", line 348, in act
    response = second_agent.act()
  [Previous line repeated 980 more times]
  File "c:\users\rifai\desktop\research\may 6\blender\~\parlai\parlai_internal\agents\Covid\Covid.py", line 347, in act
    second_agent = copy.deepcopy(self)
  File "C:\Users\rifai\anaconda3\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\rifai\anaconda3\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\rifai\anaconda3\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Users\rifai\anaconda3\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\rifai\anaconda3\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\rifai\anaconda3\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\rifai\anaconda3\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Users\rifai\anaconda3\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\rifai\anaconda3\lib\copy.py", line 161, in deepcopy
    y = copier(memo)
  File "c:\users\rifai\desktop\research\may 6\blender\~\parlai\parlai\core\opt.py", line 50, in __deepcopy__
    loc = traceback.format_stack()[-3]
  File "C:\Users\rifai\anaconda3\lib\traceback.py", line 197, in format_stack
    return format_list(extract_stack(f, limit=limit))
  File "C:\Users\rifai\anaconda3\lib\traceback.py", line 211, in extract_stack
    stack = StackSummary.extract(walk_stack(f), limit=limit)
  File "C:\Users\rifai\anaconda3\lib\traceback.py", line 363, in extract
    f.line
  File "C:\Users\rifai\anaconda3\lib\traceback.py", line 285, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "C:\Users\rifai\anaconda3\lib\linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "C:\Users\rifai\anaconda3\lib\linecache.py", line 43, in getlines
    if len(entry) != 1:
RecursionError: maximum recursion depth exceeded while calling a Python object
```
I am using Python 3.7.6, Windows 10, Pycharm as my editor. Thanks in advance for the help.

**Comment by stephenroller** [comment]
I think the problem is orobably the deepcopy(self). You almost certainly want second_agent.clone()

**Comment by AbdullaRifai** [comment]
@stephenroller Yeah it was the deep copy, thanks!
