### ISSUE TITLE
Integer division of tensors using div or / is no longer supported

### ISSUE THREAD

**Issue by aslu98** [facebookresearch/ParlAI#2925]
**Bug description**
When I try to use my fine-tuned model I get the error.

**Reproduction steps**
I used the interactive script with
`!parlai interactive -mf covidmodels/covid1/covid_model1 `
     ` --single_turn True `
     ` --beam-min-length 20 --beam-block-ngram 3 --beam-context-block-ngram 3 --beam-size 10 --inference beam`

If do not use the last line I don't get the error but the bot is not good at all at answering question about the fine-tuning topic.

**Expected behavior**
I would expect the bot to answer.

**Logs**
Error Log:

```
Enter Your Message: What is covid?
Traceback (most recent call last):
  File "/usr/local/bin/parlai", line 33, in <module>
    sys.exit(load_entry_point('parlai', 'console_scripts', 'parlai')())
  File "/content/drive2/My Drive/ParlAI/parlai/core/script.py", line 272, in superscript_main
    SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "/content/drive2/My Drive/ParlAI/parlai/core/script.py", line 88, in _run_from_parser_and_opt
    return script.run()
  File "/content/drive2/My Drive/ParlAI/parlai/scripts/interactive.py", line 126, in run
    return interactive(self.opt, print_parser=self.parser)
  File "/content/drive2/My Drive/ParlAI/parlai/scripts/interactive.py", line 101, in interactive
    world.parley()
  File "/content/drive2/My Drive/ParlAI/parlai/tasks/interactive/worlds.py", line 78, in parley
    acts[1] = agents[1].act()
  File "/content/drive2/My Drive/ParlAI/parlai/core/torch_agent.py", line 1929, in act
    response = self.batch_act([self.observation])[0]
  File "/content/drive2/My Drive/ParlAI/parlai/core/torch_agent.py", line 1990, in batch_act
    output = self.eval_step(batch)
  File "/content/drive2/My Drive/ParlAI/parlai/core/torch_generator_agent.py", line 860, in eval_step
    beam_preds_scores, _ = self._generate(batch, self.beam_size, maxlen)
  File "/content/drive2/My Drive/ParlAI/parlai/core/torch_generator_agent.py", line 1085, in _generate
    b.advance(score[i])
  File "/content/drive2/My Drive/ParlAI/parlai/core/torch_generator_agent.py", line 1351, in advance
    logprobs, self.scores, current_length
  File "/content/drive2/My Drive/ParlAI/parlai/core/torch_generator_agent.py", line 1536, in select_paths
    hyp_ids = best_idxs / voc_size
RuntimeError: Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.
```

I suppose I should just change `hyp_ids = best_idxs / voc_size` to `hyp_ids = best_idxs // voc_size` in the ParlAI/parlai/core/torch_generator_agent.py file

**Comment by stephenroller** [comment]
This was fixed in #2902.

I’ll pop out a release in a little bit.
