### ISSUE TITLE
Error in training: module 'parlai.tasks.fromfile.agents' has no attribute 'create_agents'

### ISSUE THREAD

**Issue by aslu98** [facebookresearch/ParlAI#2945]
**Bug description**
Error while trying to train model.

**Reproduction steps**
Tried to train model with these args: `parlai train_model -t fromfile:parlaiformat --fromfile_datapath ./parlai_utilities/covid_qa+FAQ_parlaiformat.txt -m transformer/generator --multitask-weights 1 --num-epochs 10.0 --beam-block-ngram 3 --beam-context-block-ngram 3 --init-model zoo:blender/blender_90M/model --dict-file zoo:blender/blender_90M/model.dict --embedding-size 512 --n-layers 8 --ffn-size 2048 --dropout 0.1 --n-heads 16 --learn-positional-embeddings True  --n-positions 512 --variant xlm --activation gelu --skip-generation True --fp16 True --text-truncate 256 --label-truncate 256 --dict-tokenizer bpe --dict-lower True -lr 1e-06 --optimizer adamax --lr-scheduler reduceonplateau --gradient-clip 0.1 -veps 0.25 --betas 0.9,0.999 --update-freq 1 --attention-dropout 0.0 --relu-dropout 0.0 --skip-generation True -vp 15 -stim 60 -vme 20000 -bs 32 -vmt ppl -vmm min --save-after-valid True --model-file  covidmodel1`

**Logs**

```
  File "/ParlAI/parlai/core/worlds.py", line 1581, in _create_task_agents
    task_agents = my_module.create_agents(opt)  # type: ignore
AttributeError: module 'parlai.tasks.fromfile.agents' has no attribute 'create_agents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/parlai", line 33, in <module>
    sys.exit(load_entry_point('parlai', 'console_scripts', 'parlai')())
  File "/ParlAI/parlai/core/script.py", line 272, in superscript_main
    SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "/ParlAI/parlai/core/script.py", line 88, in _run_from_parser_and_opt
    return script.run()
  File "/ParlAI/parlai/scripts/train_model.py", line 768, in run
    self.train_loop = TrainLoop(self.opt)
  File "/ParlAI/parlai/scripts/train_model.py", line 279, in __init__
    self.world = create_task(opt, self.agent)
  File "/ParlAI/parlai/core/worlds.py", line 1633, in create_task
    world = create_task_world(opt, user_agents, default_world=default_world)
  File "/ParlAI/parlai/core/worlds.py", line 1596, in create_task_world
    task_agents = _create_task_agents(opt)
  File "/ParlAI/parlai/core/worlds.py", line 1584, in _create_task_agents
    return create_task_agent_from_taskname(opt)
  File "/ParlAI/parlai/core/teachers.py", line 2402, in create_task_agent_from_taskname
    task_agents = teacher_class(opt)
  File "/ParlAI/parlai/tasks/fromfile/agents.py", line 87, in __init__
    self._setup_data(datafile)
  File "/ParlAI/parlai/core/teachers.py", line 1394, in _setup_data
    for line_no, line in enumerate(read, 1):
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2204: ordinal not in range(128)
```

**Comment by stephenroller** [comment]
I think your environment is set to non-utf8 encodings.

Short term fix: add these variables (or similar ones) to your bash environment
```
LANG=en_US.UTF-8
PYTHONIOENCODING=utf-8
```

The real fix: this line needs to explicitly say opening with utf-8.
https://github.com/facebookresearch/ParlAI/blob/0fe83071f796c73930c79761d14d7b27070baced/parlai/core/teachers.py#L1393

Would you be willing to make a PR to add `encoding='utf-8'` to that call to `open`?

**Comment by aslu98** [comment]
Thanks for the quick answer.
I tried to do a PR but I'm very new to all this and I got stuck because pre-commit 'failed to find interpreter for Builtin discover of python_spec='python3.6' while committing and now I'm not able to go deeper into the problem, I'm sorry.

**Comment by stephenroller** [comment]
Thanks for your attempt.

**Comment by aslu98** [comment]
I'm having the same problem when I run `parlai safe_interactive -t blended_skill_talk -mf zoo:blender/blender_3B/model`.

Log:
```
Traceback (most recent call last):
  File "/usr/local/bin/parlai", line 33, in <module>
    sys.exit(load_entry_point('parlai', 'console_scripts', 'parlai')())
  File "/parlai/core/script.py", line 272, in superscript_main
    SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "/parlai/core/script.py", line 88, in _run_from_parser_and_opt
    return script.run()
  File "/parlai/scripts/safe_interactive.py", line 82, in run
    return safe_interactive(self.opt)
  File "/parlai/scripts/safe_interactive.py", line 58, in safe_interactive
    world = create_task(opt, [human_agent, agent])
  File "/parlai/core/worlds.py", line 1633, in create_task
    world = create_task_world(opt, user_agents, default_world=default_world)
  File "/parlai/core/worlds.py", line 1605, in create_task_world
    return world_class(opt, task_agents + user_agents)
  File "/parlai/tasks/blended_skill_talk/worlds.py", line 131, in __init__
    super().__init__(opt, agents, shared)
  File "/parlai/tasks/interactive/worlds.py", line 24, in __init__
    self.init_contexts(shared=shared)
  File "/parlai/tasks/blended_skill_talk/worlds.py", line 135, in init_contexts
    self.contexts_data = get_contexts_data(self.opt, shared=shared)
  File "/parlai/tasks/blended_skill_talk/worlds.py", line 18, in get_contexts_data
    return _load_personas(opt=opt)
  File "/parlai/tasks/blended_skill_talk/worlds.py", line 37, in _load_personas
    raw_safe_persona_groups = [line.strip() for line in f.readlines()]
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2235: ordinal not in range(128)
```
So i added `encoding='utf-8'` in `open` function on line 36 of /parlai/tasks/blended_skill_talk/worlds.py and now it works.
