### ISSUE TITLE
Broswer chat: __unk__ responses

### ISSUE THREAD

**Issue by aslu98** [facebookresearch/ParlAI#3017]
I would like to uso the broswer chat with my already trained model saved in my host. 
Actually, my config.yml file is:

```
tasks:
  default:
    onboard_world: MessengerBotChatCovidWorld
    task_world: MessengerBotChatTaskWorld
    timeout: 1800
    agents_required: 1
task_name: chatbot
world_module: parlai.chat_service.tasks.chatbot.worlds
overworld: MessengerOverworld
max_workers: 30
opt:
  debug: True
  models:
    covid90M:
      model: transformer/generator
      model_file: zoo:covid/covid90M
      interactive_mode: True
      no_cuda: False
additional_args:
  page_id: 1
```

I put my model and all the other files (.valid, .dict, .chekpoint, etc.) in a 'covid' repository inside the zoo directory.
When I try to run the server with `python3 parlai/chat_service/services/browser_chat/run.py --config-path parlai/chat_service/tasks/covid_task_browser/config.yml --port 10001` get the following error (as i kinda expected):

```
Traceback (most recent call last):
  File "parlai/chat_service/services/browser_chat/run.py", line 54, in <module>
    run(opt)
  File "parlai/chat_service/services/browser_chat/run.py", line 41, in run
    manager = BrowserManager(opt)
  File "/Users/asialucchi/Desktop/ParlAI/parlai/chat_service/services/websocket/websocket_manager.py", line 54, in __init__
    self._complete_setup()
  File "/Users/asialucchi/Desktop/ParlAI/parlai/chat_service/services/websocket/websocket_manager.py", line 67, in _complete_setup
    self._load_model()
  File "/Users/asialucchi/Desktop/ParlAI/parlai/chat_service/services/websocket/websocket_manager.py", line 81, in _load_model
    model_params[model] = create_agent(model_opt).share()
  File "/Users/asialucchi/Desktop/ParlAI/parlai/core/agents.py", line 386, in create_agent
    opt['model_file'] = modelzoo_path(opt.get('datapath'), opt['model_file'])
  File "/Users/asialucchi/Desktop/ParlAI/parlai/core/build_data.py", line 435, in modelzoo_path
    f'Could not find pretrained model in {module_name} or {module_name_}.'
ImportError: Could not find pretrained model in parlai.zoo.covid.build or parlai.zoo.covid.build.
```

From my understanding, I need to have a build file that will download the model somewhere to get it work... is there a way to just make the config use the model file I have locally? Without downloading it?

**Comment by aslu98** [comment]
I figured out the problem was I put my files in the "zoo" repository, If I leave them out I don't need to use build or any other script. Now I am able to start the server anche client processes, but when I chat with the model in browser chat I get responses like:

`__null__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__ __unk__`

or 

`__null__ __null__`

When I chat with the same model with intercative.py it works. (answers with proper words)

**Comment by stephenroller** [comment]
I don't think you want `zoo:covid/covid_90M`. I think you want `covid/covid_90M`

**Comment by aslu98** [comment]
Thanks, I had figured out that what I wanted was my model to be outside the zoo.
The __unk__ issue was solved using path `parlai/covid/covid90M` instead of just `covid/covid90M`.
I initially thought that my was supposed to start my path on the same place the zoo was, it still makes no sense to me why it uploaded a 3M model  and from where when I used path `covid/covid90M`.

**Comment by stephenroller** [comment]
Yeah that looks like it initiated a new model from scratch. Our chat services should be preventing that

**Comment by stephenroller** [comment]
Leaving this task open because we need to double check that chat services has requireExists=True on the call to create_agent.
