### ISSUE TITLE
Suggested test "python tests/datatests/test_new_tasks.py" appears to be broken

### ISSUE THREAD

**Issue by skiingpacman** [facebookresearch/ParlAI#3074]
When making a pull request on updates to task_list the test `python tests/datatests/test_new_tasks.py` is automatically suggested. When executing this test it runs for a long time and eventually crashes.

The added task works fine if I test with `parlai display_data -t multiwoz_v20`

```
$ python tests/datatests/test_new_tasks.py

10:21:52 INFO | Opt:
10:21:52 INFO |     batchsize: 1
10:21:52 INFO |     datapath: /Users/pacrook/ParlAI/data
10:21:52 INFO |     datatype: train:ordered
10:21:52 INFO |     dict_class: None
10:21:52 INFO |     display_examples: False
10:21:52 INFO |     download_path: None
10:21:52 INFO |     dynamic_batching: None
10:21:52 INFO |     hide_labels: False
10:21:52 INFO |     image_cropsize: 224
10:21:52 INFO |     image_mode: raw
10:21:52 INFO |     image_size: 256
10:21:52 INFO |     init_model: None
10:21:52 INFO |     init_opt: None
10:21:52 INFO |     log_every_n_secs: 2
10:21:52 INFO |     loglevel: info
10:21:52 INFO |     model: None
10:21:52 INFO |     model_file: None
10:21:52 INFO |     multitask_weights: [1]
10:21:52 INFO |     override: "{'task': 'multiwoz_v20:DefaultTeacher'}"
10:21:52 INFO |     parlai_home: /Users/pacrook/ParlAI
10:21:52 INFO |     starttime: Sep11_10-21
10:21:52 INFO |     task: multiwoz_v20:DefaultTeacher
10:21:52 INFO | Current ParlAI commit: ff67111a976f2dbdfebb31bdfdd7648810597e79
10:21:52 INFO | creating task(s): multiwoz_v20:DefaultTeacher
10:25:51 INFO | Loaded 8438 episodes with a total of 56778 examples
Traceback (most recent call last):
  File "tests/datatests/test_new_tasks.py", line 64, in test_verify_data
    text, log = verify(opt)
ValueError: too many values to unpack (expected 2)
Got above exception in multiwoz_v20:DefaultTeacher
E
======================================================================
ERROR: test_verify_data (_main_.TestNewTasks)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/datatests/test_new_tasks.py", line 70, in test_verify_data
    if log[key] != 0:
UnboundLocalError: local variable 'log' referenced before assignment

----------------------------------------------------------------------
Ran 1 test in 239.416s

FAILED (errors=1)
```

**Comment by skiingpacman** [comment]
The issue is the return object from verify(opt) in verify_data.py is not that expected at line 64 in test_new_tasks.py

```
> /Users/pacrook/ParlAI/parlai/scripts/verify_data.py(135)verify()
-> return counts
p counts
{'missing_text': 0, 'missing_labels': 0, 'missing_label_candidates': 56778, 'empty_string_label_candidates': 0, 'label_candidates_with_missing_label': 0, 'did_not_return_message': 0, 'exs': 56778}
n
--Return--
> /Users/pacrook/ParlAI/parlai/scripts/verify_data.py(135)verify()->{'did_not_return_message': 0, 'empty_string...el_candidates': 0, 'exs': 56778, 'label_candid...missing_label': 0, ...}
-> return counts
n
ValueError: too many values to unpack (expected 2)
> /Users/pacrook/ParlAI/tests/datatests/test_new_tasks.py(64)test_verify_data()
-> text, log = verify(opt)
l
 59  	                parser = setup_args()
 60  	                opt = parser.parse_args(args=['--task', subt])
 61  	                opt['task'] = subt
 62  	                try:
 63  	                    with testing_utils.capture_output():
 64 B->	                        text, log = verify(opt)
 65  	                except Exception:
 66  	                    found_errors = True
 67  	                    traceback.print_exc()
 68  	                    print("Got above exception in {}".format(subt))
 69  	                for key in KEYS:
```

At a guess instead of return counts, it should be `return report(world, counts, log_time)` at line 135 of `/Users/pacrook/ParlAI/parlai/scripts/verify_data.py` ?

**Comment by skiingpacman** [comment]
As a side note it seems the `print(text)` output from ParlAI/parlai/scripts/verify_data.py (line 123) that should reports progress is somehow 'muted' such that progress is not reported. The line is hit but the print statement output doesn't appear on stdout.

```
121  	        if log_time.time() > log_every_n_secs:
122  	            text, log = report(world, counts, log_time)
123 B	            print(text)
```

**Comment by moyapchen** [comment]
Fixed in https://github.com/facebookresearch/ParlAI/pull/3167
