### ISSUE TITLE
error on running first example 

### ISSUE THREAD

**Issue by Scanf-Myname** [facebookresearch/ParlAI#3099]
Hello when i am running the first example I meet this problem!

My instructions are as follows：
git clone https://github.com/facebookresearch/ParlAI.git
cd ParlAI
python setup.py develop
parlai display_data -t babi:task1k:1

>`Traceback (most recent call last):
  File "d:\硕士\2020夏季\背景对话\parlai\parlai\parlai\core\worlds.py", line 1211, in _create_task_agents
    task_agents = my_module.create_agents(opt)  # type: ignore
AttributeError: module 'parlai.tasks.babi.agents' has no attribute 'create_agents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\11141\AppData\Local\Continuum\anaconda3\envs\pytorch\Scripts\parlai-script.py", line 11, in <module>
    load_entry_point('parlai', 'console_scripts', 'parlai')()
  File "d:\硕士\2020夏季\背景对话\parlai\parlai\parlai\core\script.py", line 272, in superscript_main
    SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "d:\硕士\2020夏季\背景对话\parlai\parlai\parlai\core\script.py", line 88, in _run_from_parser_and_opt
    return script.run()
  File "d:\硕士\2020夏季\背景对话\parlai\parlai\parlai\scripts\display_data.py", line 109, in run
    return display_data(self.opt)
  File "d:\硕士\2020夏季\背景对话\parlai\parlai\parlai\scripts\display_data.py", line 71, in display_data
    world = create_task(opt, agent)
  File "d:\硕士\2020夏季\背景对话\parlai\parlai\parlai\core\worlds.py", line 1262, in create_task
    world = create_task_world(opt, user_agents, default_world=default_world)
  File "d:\硕士\2020夏季\背景对话\parlai\parlai\parlai\core\worlds.py", line 1226, in create_task_world
    task_agents = _create_task_agents(opt)
  File "d:\硕士\2020夏季\背景对话\parlai\parlai\parlai\core\worlds.py", line 1214, in _create_task_agents
    return create_task_agent_from_taskname(opt)
  File "d:\硕士\2020夏季\背景对话\parlai\parlai\parlai\core\teachers.py", line 2364, in create_task_agent_from_taskname
    task_agents = teacher_class(opt)
  File "d:\硕士\2020夏季\背景对话\parlai\parlai\parlai\tasks\babi\agents.py", line 51, in __init__
    opt['datafile'] = _path('', self.task_num, opt)
  File "d:\硕士\2020夏季\背景对话\parlai\parlai\parlai\tasks\babi\agents.py", line 15, in _path
    build(opt)
  File "d:\硕士\2020夏季\背景对话\parlai\parlai\parlai\tasks\babi\build.py", line 35, in build
    downloadable_file.download_file(dpath)
  File "d:\硕士\2020夏季\背景对话\parlai\parlai\parlai\core\build_data.py", line 90, in download_file
    untar(dpath, self.file_name)
  File "d:\硕士\2020夏季\背景对话\parlai\parlai\parlai\core\build_data.py", line 253, in untar
    return _untar(path, fname, delete=delete)
  File "d:\硕士\2020夏季\背景对话\parlai\parlai\parlai\core\build_data.py", line 294, in _untar
    PathManager.rm(fullpath)
  File "C:\Users\11141\AppData\Local\Continuum\anaconda3\envs\pytorch\lib\site-packages\fvcore-0.1.2.post20200912-py3.6.egg\fvcore\common\file_io.py", line 793, in rm
  File "C:\Users\11141\AppData\Local\Continuum\anaconda3\envs\pytorch\lib\site-packages\fvcore-0.1.2.post20200912-py3.6.egg\fvcore\common\file_io.py", line 468, in _rm
PermissionError: [WinError 32]Another program is using this file and the process cannot access it。: 'd:\\硕士\\2020夏季\\背景对话\\parlai\\parlai\\data\\bAbI\\babi.tar.gz'`

I knowI know this is a file conflict problem, but I don’t know how to solve this problem, I hope to get help, thank you very much

**Comment by stephenroller** [comment]
Hm, we don't support windows officially. I would suggest trying to make sure all programs are closed, maybe reboot, or manually deleting that folder and trying again.

**Comment by Bharathi-A-7** [comment]
I face the same problem . Is there no solution ? I tried deleting the folder and trying again .

**Comment by Scanf-Myname** [comment]
> I face the same problem . Is there no solution ? I tried deleting the folder and trying again .

I think it's something wrong with windows, when I tried to use my virtual machine to run Linux, these problems were resolved. You can try to install it in the Linux environment

**Comment by stephenroller** [comment]
It's very odd. I am very unsure why this would be problematic for windows. All the file handles were properly closed before the call to rm.

https://github.com/facebookresearch/ParlAI/blob/d7361333f05d8ca108bfb5133b80b2f123e17d64/parlai/core/build_data.py#L257-L295

**Comment by yizhouzhao** [comment]
I met the same problem and solved it manually by editing the original data of parlai. Here are the possible problems:

1. **[Problem]** Mix use of double slash \\ and single slash \ on windows when using os.path.join.
**[Solution]** str.replace("\\","/")

2. **[Problem]** PathManager cannot remove files 
**[Solution]** ParlAI/parlai/core/build_data.py line 294-295
comment delete(if you really want to delete zip, tar files, do it manually)
    #if delete:
    #   PathManager.rm(fullpath)

3.  **[Problem]** windows cannot support long folder name 
**[Solution]** https://knowledge.autodesk.com/support/autocad/learn-explore/caas/sfdcarticles/sfdcarticles/The-Windows-10-default-path-length-limitation-MAX-PATH-is-256-characters.html

**Comment by stephenroller** [comment]
Thanks for documenting this.

**Comment by Bharathi-A-7** [comment]
> I met the same problem and solved it manually by editing the original data of parlai. Here are the possible problems:
> 
> 1. **[Problem]** Mix use of double slash \\ and single slash \ on windows when using os.path.join.
>    **[Solution]** str.replace("\\","/")
> 2. **[Problem]** PathManager cannot remove files
>    **[Solution]** ParlAI/parlai/core/build_data.py line 294-295
>    comment delete(if you really want to delete zip, tar files, do it manually)
>    #if delete:
>    #PathManager.rm(fullpath)
> 3. **[Problem]** windows cannot support long folder name
>    **[Solution]** https://knowledge.autodesk.com/support/autocad/learn-explore/caas/sfdcarticles/sfdcarticles/The-Windows-10-default-path-length-limitation-MAX-PATH-is-256-characters.html

Thank you very much for this . Could you please tell me the file/files where I have to  'str.replace('\\','/') ? Or Should I make the change wherever os.path.join is used ?

**Comment by Bharathi-A-7** [comment]
> I met the same problem and solved it manually by editing the original data of parlai. Here are the possible problems:
> 
> 1. **[Problem]** Mix use of double slash \\ and single slash \ on windows when using os.path.join.
>    **[Solution]** str.replace("\\","/")
> 2. **[Problem]** PathManager cannot remove files
>    **[Solution]** ParlAI/parlai/core/build_data.py line 294-295
>    comment delete(if you really want to delete zip, tar files, do it manually)
>    #if delete:
>    #PathManager.rm(fullpath)
> 3. **[Problem]** windows cannot support long folder name
>    **[Solution]** https://knowledge.autodesk.com/support/autocad/learn-explore/caas/sfdcarticles/sfdcarticles/The-Windows-10-default-path-length-limitation-MAX-PATH-is-256-characters.html

This worked like charm ! Thank you very much .
