### ISSUE TITLE
TypeError when training model on custom task

### ISSUE THREAD

**Issue by rubenjanss** [facebookresearch/ParlAI#3289]
**Bug description**
After I defined a custom task/dataset following the tutorial (https://parl.ai/docs/tutorial_task.html#creating-a-new-task-the-more-complete-way), a TypeError is raised when training a model on this task. More precisely, the error appears to happen while building a dictionary.

Apologies if I missed some fundamental concept, I'm new to using ParlAI.

**Reproduction steps**
Add a new custom task in ParlAI/parlai_internal/tasks/opener_text ("opener_text" is the task ID; task code visible at bottom).
Add the data files for this task in ParlAI/data/opener_text/.
Run `parlai train_model -m tfidf_retriever -t internal:opener_text -mf /tmp/opener_text_tfidf -dt train:ordered -eps 1`

**Expected behavior**
Model training on this task without error.

**Logs**
```
21:46:20 | building dictionary first...
21:46:20 | Opt:
21:46:20 |     aggregate_micro: False
21:46:20 |     allow_missing_init_opts: False
21:46:20 |     batchsize: 1
21:46:20 |     bpe_add_prefix_space: None
21:46:20 |     bpe_debug: False
21:46:20 |     bpe_dropout: None
21:46:20 |     bpe_merge: None
21:46:20 |     bpe_vocab: None
21:46:20 |     datapath: /root/ParlAI/data
21:46:20 |     datatype: train:ordered
21:46:20 |     dict_class: None
21:46:20 |     dict_endtoken: __end__
21:46:20 |     dict_file: /tmp/opener_text_tfidf.dict
21:46:20 |     dict_include_test: False
21:46:20 |     dict_include_valid: False
21:46:20 |     dict_initpath: None
21:46:20 |     dict_language: english
21:46:20 |     dict_loaded: False
21:46:20 |     dict_lower: False
21:46:20 |     dict_max_ngram_size: -1
21:46:20 |     dict_maxexs: -1
21:46:20 |     dict_maxtokens: -1
21:46:20 |     dict_minfreq: 0
21:46:20 |     dict_nulltoken: __null__
21:46:20 |     dict_starttoken: __start__
21:46:20 |     dict_textfields: text,labels
21:46:20 |     dict_tokenizer: re
21:46:20 |     dict_unktoken: __unk__
21:46:20 |     display_examples: False
21:46:20 |     download_path: None
21:46:20 |     dynamic_batching: None
21:46:20 |     eval_batchsize: None
21:46:20 |     evaltask: None
21:46:20 |     hide_labels: False
21:46:20 |     image_cropsize: 224
21:46:20 |     image_mode: no_image_model
21:46:20 |     image_size: 256
21:46:20 |     index_by_int_id: True
21:46:20 |     init_model: None
21:46:20 |     init_opt: None
21:46:20 |     load_from_checkpoint: True
21:46:20 |     log_every_n_secs: 10
21:46:20 |     loglevel: info
21:46:20 |     max_train_time: -1
21:46:20 |     metrics: default
21:46:20 |     model: tfidf_retriever
21:46:20 |     model_file: /tmp/opener_text_tfidf
21:46:20 |     multitask_weights: [1]
21:46:20 |     num_epochs: 1.0
21:46:20 |     override: "{'model': 'tfidf_retriever', 'task': 'internal:opener_text', 'model_file': '/tmp/opener_text_tfidf', 'datatype': 'train:ordered', 'num_epochs': 1.0}"
21:46:20 |     parlai_home: /root/ParlAI
21:46:20 |     remove_title: False
21:46:20 |     retriever_hashsize: 16777216
21:46:20 |     retriever_mode: values
21:46:20 |     retriever_ngram: 2
21:46:20 |     retriever_num_retrieved: 5
21:46:20 |     retriever_numworkers: None
21:46:20 |     retriever_tokenizer: simple
21:46:20 |     save_after_valid: False
21:46:20 |     save_every_n_secs: -1
21:46:20 |     short_final_eval: False
21:46:20 |     starttime: Dec06_21-46
21:46:20 |     task: internal:opener_text
21:46:20 |     tensorboard_log: False
21:46:20 |     tensorboard_logdir: None
21:46:20 |     tfidf_context_length: -1
21:46:20 |     tfidf_include_labels: True
21:46:20 |     validation_cutoff: 1.0
21:46:20 |     validation_every_n_epochs: -1
21:46:20 |     validation_every_n_secs: -1
21:46:20 |     validation_max_exs: -1
21:46:20 |     validation_metric: accuracy
21:46:20 |     validation_metric_mode: None
21:46:20 |     validation_patience: 10
21:46:20 |     validation_share_agent: False
21:46:20 |     verbose: False
21:46:20 | Current ParlAI commit: db7086c7b6fad98a2e4c5ef2423f805359661cd2
21:46:20 | Current internal commit: 596c65ab313ab9ed4799b976de64e947df4cac18
21:46:20 | creating task(s): internal:opener_text
Building dictionary:   0%|                                                              | 0.00/9.00k [00:00<?, ?ex/s]
loading: /root/ParlAI/data/opener_text/descr_questions_12k_train.json
Traceback (most recent call last):
  File "/usr/local/bin/parlai", line 11, in <module>
    load_entry_point('parlai', 'console_scripts', 'parlai')()
  File "/root/ParlAI/parlai/__main__.py", line 14, in main
    superscript_main()
  File "/root/ParlAI/parlai/core/script.py", line 307, in superscript_main
    return SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "/root/ParlAI/parlai/core/script.py", line 90, in _run_from_parser_and_opt
    return script.run()
  File "/root/ParlAI/parlai/scripts/train_model.py", line 768, in run
    self.train_loop = TrainLoop(self.opt)
  File "/root/ParlAI/parlai/scripts/train_model.py", line 279, in __init__
    build_dict(opt, skip_if_built=True)
  File "/root/ParlAI/parlai/scripts/build_dict.py", line 133, in build_dict
    world_dict.parley()
  File "/root/ParlAI/parlai/core/worlds.py", line 344, in parley
    acts[0] = agents[0].act()
  File "/root/ParlAI/parlai/core/teachers.py", line 482, in act
    orig_action = self.get_orig_action()
  File "/root/ParlAI/parlai/core/teachers.py", line 502, in get_orig_action
    action, self.epochDone = self.next_example()
  File "/root/ParlAI/parlai/core/teachers.py", line 670, in next_example
    action, epoch_done = self.data.get()
TypeError: get expected at least 1 arguments, got 0
Building dictionary:   0%|                                                       | 1.00/9.00k [00:00<13:44, 10.9ex/s]
```

**Additional context**
The same error occurs when executing `parlai build_dict -t internal:opener_text --dict-file /tmp/dict_file`.

This is the code of parlai_internal/tasks/opener_text/agents.py:

```
from parlai.core.teachers import DialogTeacher
from parlai.utils.io import PathManager
from .build import build

import json
import os


def _path(opt):
    #build(opt) commented because local
    dt = opt['datatype'].split(':')[0]

    data_path = os.path.join(opt['datapath'], 'opener_text', 'descr_questions_12k_' + dt + '.json')
    return data_path


class TextOpenerTeacher(DialogTeacher):
    """
    This version of MNIST inherits from the core Dialog Teacher, which just requires it
    to define an iterator over its data `setup_data` in order to inherit basic metrics,
    a `act` function, and enables Hogwild training with shared memory with no extra
    work.
    """

    def __init__(self, opt, shared=None):
        self.datatype = opt['datatype'].split(':')[0]
        data_path = _path(opt)
        opt['datafile'] = data_path
        self.id = 'opener_text'
	
        super().__init__(opt, shared)

    def setup_data(self, path):
        print('loading: ' + path)
        with PathManager.open(path) as data_file:
            self.data = json.load(data_file)

        episode_done = True

        for i in self.data["Answer.question1"].keys():
            yield (self.data["dot_string"][i], self.data["Answer.question1"][i], None, None, None), episode_done
            yield (self.data["dot_string"][i], self.data["Answer.question2"][i], None, None, None), episode_done
            yield (self.data["dot_string"][i], self.data["Answer.question3"][i], None, None, None), episode_done

class DefaultTeacher(TextOpenerTeacher):
    pass
```

**Comment by stephenroller** [comment]
That looks quite correct to me.

Is there a chance that iterator never yields anything? This might be what happens when you return empty data. If so, I should improve the error message.

Try "parlai display_data -t internal:opener_text"

**Comment by stephenroller** [comment]
Otherwise, what is the type of each item in the Tuple you are returning?

I find your code quite vexing. It looks like it should work, and the following replication seems fine:

**Comment by stephenroller** [comment]
OH I SEE, you set `self.data`, but that attribute is reserved by the parent class. I'm sorry about that. Please call your variable something like `self._data` or `raw_data` or similar.

**Comment by rubenjanss** [comment]
Oh yes, you're absolutely right! That was an oversight. Thank you so much for the help!
