### ISSUE TITLE
RuntimeError: CUDA out of memory. 

### ISSUE THREAD

**Issue by mavisakal** [facebookresearch/ParlAI#3296]
I'm trying to run the websocket example on a Tesla V100 GPU machine. I use the command below:
`python parlai/chat_service/services/websocket/run.py --config-path parlai/chat_service/tasks/chatbot/config_custom.yml --port 8000`

After running this command I check the GPU processes with `nvidia-msi` command. As seen in the image below the python process allocates all the memory of the gpu.
![image](https://user-images.githubusercontent.com/2776816/101481464-46ab2200-3966-11eb-9193-a667631d93e0.png)

After starting the chat I got the following error:
RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 15.78 GiB total capacity; 14.32 GiB already allocated; 1.50 MiB free; 14.58 GiB reserved in total by PyTorch)

**Reproduction steps**
- Run this command on a Nvidia gpu machine
`python parlai/chat_service/services/websocket/run.py --config-path parlai/chat_service/tasks/chatbot/config_custom.yml --port 8000`

-start chat with begin command

**Logs**

```
[E 201208 11:58:35 logging:44] World default had error RuntimeError('CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0;                                       15.78 GiB total capacity; 14.32 GiB already allocated; 1.50 MiB free; 14.58 GiB reserved in total by PyTorch)')
World default had error RuntimeError('CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 15.78 GiB total capacity; 14.32                                       GiB already allocated; 1.50 MiB free; 14.58 GiB reserved in total by PyTorch)')
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/ParlAI/parlai/chat_service/core/world_runner.py", line 128, in _world_fn
    return self._run_world(task, world_name, agents)
  File "/home/ubuntu/ParlAI/parlai/chat_service/core/world_runner.py", line 95, in _run_world
    world = world_generator(self.opt, agents)
  File "/home/ubuntu/ParlAI/parlai/tasks/blended_skill_talk/worlds.py", line 142, in generate_world
    agent = create_agent(opt, requireModelExists=True)
  File "/home/ubuntu/ParlAI/parlai/core/agents.py", line 402, in create_agent
    model = create_agent_from_opt_file(opt)
  File "/home/ubuntu/ParlAI/parlai/core/agents.py", line 355, in create_agent_from_opt_file
    return model_class(opt_from_file)
  File "/home/ubuntu/ParlAI/parlai/core/torch_generator_agent.py", line 475, in __init__
    super().__init__(opt, shared)
  File "/home/ubuntu/ParlAI/parlai/core/torch_agent.py", line 679, in __init__
    super().__init__(opt, shared)
  File "/home/ubuntu/ParlAI/parlai/core/agents.py", line 69, in __init__
    self.opt = copy.deepcopy(opt)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/home/ubuntu/ParlAI/parlai/core/opt.py", line 71, in __deepcopy__
    memo = Opt({k: copy.deepcopy(v) for k, v in self.items()})
  File "/home/ubuntu/ParlAI/parlai/core/opt.py", line 71, in <dictcomp>
    memo = Opt({k: copy.deepcopy(v) for k, v in self.items()})
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 296, in _reconstruct
    value = deepcopy(value, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 296, in _reconstruct
    value = deepcopy(value, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/torch-1.7.0-py3.8-linux-x86_64.egg/torch/nn/parameter.py", line 32                                      , in __deepcopy__
    result = type(self)(self.data.clone(memory_format=torch.preserve_format), self.requires_grad)
RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 15.78 GiB total capacity; 14.32 GiB already allocated;                                       1.50 MiB free; 14.58 GiB reserved in total by PyTorch)
Next task: None
2020-12-08 11:58:35: Adding agent 2046c487-f5c3-4ec6-b55c-bf5331163d04 to pool...
onboarding/overworld complete
starting pool
2020-12-08 11:58:35: Removing agent 2046c487-f5c3-4ec6-b55c-bf5331163d04 from pool...
Starting task t_11...

```

**Additional context**
Running hardware:
![image](https://user-images.githubusercontent.com/2776816/101482186-5e36da80-3967-11eb-8a6a-f5cff9eb3ab9.png)

**Comment by mavisakal** [comment]
**Update:** Above error is for 2.7B parameter model. I tested it with 90M model and it allocates 2GiB GPU memory.
![image](https://user-images.githubusercontent.com/2776816/101485812-c805b300-396c-11eb-8399-cbe137f6f959.png)

In the ParlAI Recipes documentation it says 16gb Tesla p100 can run the 2.7B paramater model. Even though I've a better GPU with 16Gib ram it didn't work. 
![image](https://user-images.githubusercontent.com/2776816/101486142-42363780-396d-11eb-8097-df4edc586ff4.png)

Any help would be appreciated.

**Comment by klshuster** [comment]
could you please share your `config_custom.yml`? it looks like the model is being instantiated in a part of the code where it shouldn't be

**Comment by mavisakal** [comment]
Hi,
Here is my custom.config.yml
```

tasks:
  default:
    onboard_world: MessengerBotChatOnboardWorld
    task_world: InteractiveWorld
    timeout: 1800
    agents_required: 1
task_name: chatbot
world_module: parlai.tasks.blended_skill_talk.worlds
overworld: MessengerOverworld
max_workers: 30
opt:
  debug: True
  models:
    blender_90M:
      model: transformer/generator
      model_file: zoo:blender/blender_3B/model
      interactive_mode: False
      no_cuda: False
      include_personas: False
      safety: None
additional_args:
  page_id: 1 # Configure Your Own Page

```

**Comment by klshuster** [comment]
yeah so the issue here is that the worlds used in chat services have a slightly different format from the ones used in interactive mode; an example world can be found in the [`chatbot` demo task](https://github.com/facebookresearch/ParlAI/blob/master/parlai/chat_service/tasks/chatbot/worlds.py#L28) (specifically the `MessengerBotChatTaskWorld`

**Comment by mavisakal** [comment]
But the same code works when I change the blender_3B model to blender_90M . 
```
model_file: zoo:blender/blender_90M/model
```

**Comment by klshuster** [comment]
there is special logic within chat services in order to avoid unnecessarily loading the model weights more than once; the `InteractiveWorld` does not have this logic. it works with `blender_90m` because the gpu can support several copies of the 90m model.

it looks like you wrote a `generate_world` function for the `InteractiveWorld`. In this function, you should not use `create_agent`, but rather use `create_agent_from_shared(opt['shared_bot_params']['blender_90m']`. The key into the `'shared_bot_params'` is the model key you defined in your config.yml under `models`. This would most likely fix the issue

**Comment by mavisakal** [comment]
thanks. I used `create_agent_from_shared(opt['shared_bot_params']['blender_90m']` instead of `create_agent` and I got this strange `optimizer` error.

```
AttributeError: 'MemoryEfficientFP16Optimizer' object has no attribute 'optimizer'
[E 201208 17:05:03 _base:330] exception calling callback for <Future at 0x7fb2c06c8c40 state=finished raised AttributeError>

```

**Comment by klshuster** [comment]
could you please include the stack trace for the new OOM?

**Comment by mavisakal** [comment]
Sure:
**out.log**
````
2020-12-08 16:49:49,962 WARNING  | Loading model with `--beam-block-full-context false`
2020-12-08 16:49:51,422 INFO     | Using CUDA
2020-12-08 16:49:51,423 INFO     | loading dictionary from /home/ubuntu/ParlAI/data/models/blender/blender_3B/model.dict
2020-12-08 16:49:51,439 INFO     | num words = 8008
2020-12-08 16:50:46,528 INFO     | Total parameters: 2,696,268,800 (2,695,613,440 trainable)
2020-12-08 16:50:46,576 INFO     | Loading existing model params from /home/ubuntu/ParlAI/data/models/blender/blender_3B/model
2020-12-08 18:49:44,408 WARNING  | Loading model with `--beam-block-full-context false`
2020-12-08 18:49:45,892 INFO     | Using CUDA
2020-12-08 18:49:45,894 INFO     | loading dictionary from /home/ubuntu/ParlAI/data/models/blender/blender_3B/model.dict
2020-12-08 18:49:45,910 INFO     | num words = 8008
2020-12-08 18:49:46,152 INFO     | TransformerGenerator: full interactive mode on.
2020-12-08 18:50:41,122 INFO     | Total parameters: 2,696,268,800 (2,695,613,440 trainable)
2020-12-08 18:50:41,154 INFO     | Loading existing model params from /home/ubuntu/ParlAI/data/models/blender/blender_3B/model
2020-12-08 19:22:40: Adding agent ecb5ad2a-7235-4af3-b7ad-89ec16a73725 to pool...
onboarding/overworld complete
starting pool
2020-12-08 19:22:40: Removing agent ecb5ad2a-7235-4af3-b7ad-89ec16a73725 from pool...
Starting task t_1...
[ loading personas.. ]
2020-12-08 19:27:47: Adding agent aebcf189-35b5-4020-bed4-18095cfbd4dc to pool...
onboarding/overworld complete
starting pool
2020-12-08 19:27:47: Removing agent aebcf189-35b5-4020-bed4-18095cfbd4dc from pool...
Starting task t_2...
World default had error RuntimeError('CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 15.78 GiB total capacity; 14.24 GiB already allocated; 47.50 MiB free; 14.53 GiB reserved in total by PyTorch)')
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/ParlAI/parlai/chat_service/core/world_runner.py", line 128, in _world_fn
    return self._run_world(task, world_name, agents)
  File "/home/ubuntu/ParlAI/parlai/chat_service/core/world_runner.py", line 95, in _run_world
    world = world_generator(self.opt, agents)
  File "/home/ubuntu/ParlAI/parlai/tasks/blended_skill_talk/worlds.py", line 147, in generate_world
    return InteractiveWorld(
  File "/home/ubuntu/ParlAI/parlai/tasks/blended_skill_talk/worlds.py", line 153, in __init__
    super().__init__(opt, agents, shared)
  File "/home/ubuntu/ParlAI/parlai/tasks/interactive/worlds.py", line 23, in __init__
    super().__init__(opt, agents, shared)
  File "/home/ubuntu/ParlAI/parlai/core/worlds.py", line 310, in __init__
    super().__init__(opt)
  File "/home/ubuntu/ParlAI/parlai/core/worlds.py", line 74, in __init__
    self.opt = copy.deepcopy(opt)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/home/ubuntu/ParlAI/parlai/core/opt.py", line 71, in __deepcopy__
    memo = Opt({k: copy.deepcopy(v) for k, v in self.items()})
  File "/home/ubuntu/ParlAI/parlai/core/opt.py", line 71, in <dictcomp>
    memo = Opt({k: copy.deepcopy(v) for k, v in self.items()})
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 296, in _reconstruct
    value = deepcopy(value, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 296, in _reconstruct
    value = deepcopy(value, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 296, in _reconstruct
    value = deepcopy(value, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 296, in _reconstruct
    value = deepcopy(value, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 296, in _reconstruct
    value = deepcopy(value, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 296, in _reconstruct
    value = deepcopy(value, memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/torch-1.7.0-py3.8-linux-x86_64.egg/torch/nn/parameter.py", line 32, in __deepcopy__
    result = type(self)(self.data.clone(memory_format=torch.preserve_format), self.requires_grad)
RuntimeError: CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 15.78 GiB total capacity; 14.24 GiB already allocated; 47.50 MiB free; 14.53 GiB reserved in total by PyTorch)
````

**error.log:**
```
[I 201208 19:22:39 web:2246] 101 GET /websocket (13.*.*.*) 0.75ms
[I 201208 19:22:39 sockets:40] Opened new socket from ip: 13.*.*.*
[I 201208 19:22:39 sockets:41] Current subscribers: {'ecb5ad2a-7235-4af3-b7ad-89ec16a73725': <parlai.chat_service.services.websocket.sockets.MessageSocketHandler object at 0x7f7c6df8b400>}
[I 201208 19:22:39 sockets:60] websocket message from client: {"text":"begin"}
[I 201208 19:22:41 agents:40] Sending new message: {'id': 'World', 'text': 'How may I help you?'}
[I 201208 19:26:33 sockets:60] websocket message from client: {"text":"what are you up to"}
[I 201208 19:26:33 agents:55] Received new message: {'text': 'what are you up to', 'payload': None, 'sender': {'id': 'ecb5ad2a-7235-4af3-b7ad-89ec16a73725'}, 'recipient': {'id': 0}}
[I 201208 19:26:35 agents:40] Sending new message: {'id': 'TransformerGenerator', 'episode_done': False, 'text': 'Just got home from work. I work at a grocery store as a cashier. How about you?', 'beam_texts': [('Just got home from work. I work at a grocery store as a cashier. How about you?', -8.525582313537598), ('Just got home from work. I work at a grocery store as a cashier. What about you?', -8.623700141906738), ('Just got home from work. I work at a grocery store as a stocker. How about you?', -8.754502296447754), ('Just got home from work. I work at a grocery store as a stocker. What about you?', -8.813066482543945), ('Just got home from work. I work at a grocery store as a cashier. You?', -9.11656379699707), ('Just got home from work. I work at a grocery store as a cashier. How about yourself?', -9.428906440734863), ('Just got home from work. I work at a grocery store as a cashier. What are you doing?', -9.643617630004883), ('Just got home from work. I work at a grocery store as a stocker. How about yourself?', -9.651576042175293), ('Just got home from work. I work at a grocery store as a stocker. What are you doing?', -9.765267372131348), ('Just got home from work. I work at a grocery store as a cashier. How about you? ', -10.259851455688477), ('Just got home from work. I work at a grocery store as a cashier. What about you? ', -10.32338809967041), ('Just got home from work. I work at a grocery store as a cashier. What about you', -10.817492485046387)]}
[I 201208 19:27:47 web:2246] 101 GET /websocket (13*.*.*) 0.48ms
[I 201208 19:27:47 sockets:40] Opened new socket from ip: 13.*.*.*
[I 201208 19:27:47 sockets:41] Current subscribers: {'ecb5ad2a-7235-4af3-b7ad-89ec16a73725': <parlai.chat_service.services.websocket.sockets.MessageSocketHandler object at 0x7f7c6df8b400>, 'aebcf189-35b5-4020-bed4-18095cfbd4dc': <parlai.chat_service.services.websocket.sockets.MessageSocketHandler object at 0x7f7c6df8b130>}
[I 201208 19:27:47 sockets:60] websocket message from client: {"text":"begin"}
[E 201208 19:27:48 logging:44] World default had error RuntimeError('CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 15.78 GiB total capacity; 14.24 GiB already allocated; 47.50 MiB free; 14.53 GiB reserved in total by PyTorch)')
[E 201208 19:27:48 _base:330] exception calling callback for <Future at 0x7f7c6df967f0 state=finished raised RuntimeError>
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/ubuntu/ParlAI/parlai/chat_service/core/world_runner.py", line 128, in _world_fn
        return self._run_world(task, world_name, agents)
      File "/home/ubuntu/ParlAI/parlai/chat_service/core/world_runner.py", line 95, in _run_world
        world = world_generator(self.opt, agents)
      File "/home/ubuntu/ParlAI/parlai/tasks/blended_skill_talk/worlds.py", line 147, in generate_world
        return InteractiveWorld(
      File "/home/ubuntu/ParlAI/parlai/tasks/blended_skill_talk/worlds.py", line 153, in __init__
        super().__init__(opt, agents, shared)
      File "/home/ubuntu/ParlAI/parlai/tasks/interactive/worlds.py", line 23, in __init__
        super().__init__(opt, agents, shared)
      File "/home/ubuntu/ParlAI/parlai/core/worlds.py", line 310, in __init__
        super().__init__(opt)
      File "/home/ubuntu/ParlAI/parlai/core/worlds.py", line 74, in __init__
        self.opt = copy.deepcopy(opt)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 153, in deepcopy
        y = copier(memo)
      File "/home/ubuntu/ParlAI/parlai/core/opt.py", line 71, in __deepcopy__
        memo = Opt({k: copy.deepcopy(v) for k, v in self.items()})
      File "/home/ubuntu/ParlAI/parlai/core/opt.py", line 71, in <dictcomp>
        memo = Opt({k: copy.deepcopy(v) for k, v in self.items()})
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 146, in deepcopy
        y = copier(x, memo)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 230, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 146, in deepcopy
        y = copier(x, memo)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 230, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 172, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 270, in _reconstruct
        state = deepcopy(state, memo)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 146, in deepcopy
        y = copier(x, memo)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 230, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 172, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 296, in _reconstruct
        value = deepcopy(value, memo)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 172, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 270, in _reconstruct
        state = deepcopy(state, memo)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 146, in deepcopy
        y = copier(x, memo)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 230, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 172, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 296, in _reconstruct
        value = deepcopy(value, memo)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 172, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 270, in _reconstruct
        state = deepcopy(state, memo)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 146, in deepcopy
        y = copier(x, memo)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 230, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 172, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 296, in _reconstruct
        value = deepcopy(value, memo)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 172, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 270, in _reconstruct
        state = deepcopy(state, memo)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 146, in deepcopy
        y = copier(x, memo)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 230, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 172, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 296, in _reconstruct
        value = deepcopy(value, memo)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 172, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 270, in _reconstruct
        state = deepcopy(state, memo)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 146, in deepcopy
        y = copier(x, memo)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 230, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 172, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 296, in _reconstruct
        value = deepcopy(value, memo)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 172, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 270, in _reconstruct
        state = deepcopy(state, memo)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 146, in deepcopy
        y = copier(x, memo)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 230, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 172, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 296, in _reconstruct
        value = deepcopy(value, memo)
      File "/home/ubuntu/anaconda3/lib/python3.8/copy.py", line 153, in deepcopy
        y = copier(memo)
      File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/torch-1.7.0-py3.8-linux-x86_64.egg/torch/nn/parameter.py", line 32, in __deepcopy__
        result = type(self)(self.data.clone(memory_format=torch.preserve_format), self.requires_grad)
    RuntimeError: CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 15.78 GiB total capacity; 14.24 GiB already allocated; 47.50 MiB free; 14.53 GiB reserved in total by PyTorch)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
        callback(self)
      File "/home/ubuntu/ParlAI/parlai/chat_service/core/chat_service_manager.py", line 658, in _done_callback
        self.observe_message(
      File "/home/ubuntu/ParlAI/parlai/chat_service/services/websocket/websocket_manager.py", line 242, in observe_message
        self.agent_id_to_overworld_future[socket_id].cancel()
    KeyError: 'TransformerGenerator'
```

**Comment by klshuster** [comment]
i would try popping out the `shared_bot_params` from the opt before calling `super().__init__(opt, agents, shared)` for the `InteractiveWorld`

**Comment by mavisakal** [comment]
I need to change the design of the bot according to the following comment of klshuster.

> yeah so the issue here is that the worlds used in chat services have a slightly different format from the ones used in interactive mode; an example world can be found in the [`chatbot` demo task](https://github.com/facebookresearch/ParlAI/blob/master/parlai/chat_service/tasks/chatbot/worlds.py#L28) (specifically the `MessengerBotChatTaskWorld`
