### ISSUE TITLE
Could not find pretrained model: blender_1Bdistill

### ISSUE THREAD

**Issue by marcoaleixo** [facebookresearch/ParlAI#3390]
**Bug description**
I'm trying to load the "blender_1Bdistill" model but I'm receiving the "could not find pretrained model".

**Reproduction steps**
I'm using this Colab - https://colab.research.google.com/drive/12a0gc1qQdvWIhMcUcZ1-UIk8uOHWpKuh?usp=sharing

I'm using the "parlai==0.9.4" version.

**Expected behavior**
Automatically download the "1bdistil model"

**Logs**

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/parlai/core/build_data.py", line 467, in modelzoo_path
    my_module = importlib.import_module(module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'parlai.zoo.blender.blender_1Bdistill'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/parlai/core/build_data.py", line 475, in modelzoo_path
    my_module.download(datapath)
AttributeError: module 'parlai.zoo.blender.build' has no attribute 'download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/ParlAI/parlai/scripts/safe_interactive.py", line 87, in <module>
    SafeInteractive.main()
  File "/usr/local/lib/python3.6/dist-packages/parlai/core/script.py", line 110, in main
    return cls._run_args(None)
  File "/usr/local/lib/python3.6/dist-packages/parlai/core/script.py", line 82, in _run_args
    opt = parser.parse_args(args=args)
  File "/usr/local/lib/python3.6/dist-packages/parlai/core/params.py", line 1074, in parse_args
    self.add_extra_args(args)
  File "/usr/local/lib/python3.6/dist-packages/parlai/core/params.py", line 885, in add_extra_args
    model = get_model_name(parsed)
  File "/usr/local/lib/python3.6/dist-packages/parlai/core/params.py", line 126, in get_model_name
    model_file = modelzoo_path(opt.get('datapath'), model_file)
  File "/usr/local/lib/python3.6/dist-packages/parlai/core/build_data.py", line 479, in modelzoo_path
    f'Could not find pretrained model in {module_name} or {module_name_}.'
ImportError: Could not find pretrained model in parlai.zoo.blender.blender_1Bdistill or parlai.zoo.blender.build.
```

**Comment by stephenroller** [comment]
Sorry, that was released after the latest version. I'll tie off a release later this week.

In the meantime, you can use `pip install -U git+https://github.com/facebookresearch/ParlAI.git@master` to use the latest development version.
