### ISSUE TITLE
Can't build the new Blender distilled models

### ISSUE THREAD

**Issue by hadasah** [facebookresearch/ParlAI#3406]
Struggling to build/download the new distilled model. Command below is for the 400M model, but also getting the same failure on the 1B distilled model. Ran the same command with the zoo path for the (not distilled) 3B model and verified that it downloaded and built correctly.

```
python parlai/scripts/safe_interactive.py -mf zoo:blender/blender_400Mdistill/model -t blended_skill_talk
Traceback (most recent call last):
  File "/gscratch/bdata/margsli/gitfiles/fork-ParlAI/parlai/core/build_data.py", line 478, in modelzoo_path
    my_module = importlib.import_module(module_name)
  File "/usr/lusers/margsli/miniconda3/envs/latest/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'parlai.zoo.blender.blender_400Mdistill'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gscratch/bdata/margsli/gitfiles/fork-ParlAI/parlai/core/build_data.py", line 486, in modelzoo_path
    my_module.download(datapath)
AttributeError: module 'parlai.zoo.blender.build' has no attribute 'download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "parlai/scripts/safe_interactive.py", line 87, in <module>
    SafeInteractive.main()
  File "/gscratch/bdata/margsli/gitfiles/fork-ParlAI/parlai/core/script.py", line 111, in main
    return cls._run_args(None)
  File "/gscratch/bdata/margsli/gitfiles/fork-ParlAI/parlai/core/script.py", line 83, in _run_args
    opt = parser.parse_args(args=args)
  File "/gscratch/bdata/margsli/gitfiles/fork-ParlAI/parlai/core/params.py", line 1084, in parse_args
    self.add_extra_args(args)
  File "/gscratch/bdata/margsli/gitfiles/fork-ParlAI/parlai/core/params.py", line 895, in add_extra_args
    model = get_model_name(parsed)
  File "/gscratch/bdata/margsli/gitfiles/fork-ParlAI/parlai/core/params.py", line 136, in get_model_name
    model_file = modelzoo_path(opt.get('datapath'), model_file)
  File "/gscratch/bdata/margsli/gitfiles/fork-ParlAI/parlai/core/build_data.py", line 489, in modelzoo_path
    raise ImportError(
ImportError: Could not find pretrained model in parlai.zoo.blender.blender_400Mdistill or parlai.zoo.blender.build.
```

**Comment by Hilal-Urun** [comment]
Hi, first you can check the scripts in [https://github.com/facebookresearch/ParlAI/tree/master/parlai/zoo/blender](url) . If you have already build and blender_400Mdistill python files then you can check if you are install the parlai module and  requirements in requirements.txt file

**Comment by stephenroller** [comment]
hey margaret, I think you're too far behind master?

**Comment by hadasah** [comment]
Loll I pulled but to the other copy of the repo, not my fork. Thanks!

**Comment by hadasah** [comment]
Making a clearer error message in #3414
