### ISSUE TITLE
ModuleNotFoundError: No module named 'projects.personachat'

### ISSUE THREAD

**Issue by jkkl** [facebookresearch/ParlAI#3511]
**Bug description**
I have : git checkout personachat and python setup.py develop successfully.
My torch version is 1.6.0
When trying to run
python projects/personachat/scripts/kvmemnn_interactive.py
the following error occurs:
Traceback (most recent call last):
  File "projects/personachat/scripts/kvmemnn_interactive.py", line 28, in <module>
    opt = parser.parse_args()
  File "/opt/conda/lib/python3.7/site-packages/parlai/core/params.py", line 1128, in parse_args
    self.add_extra_args(args)
  File "/opt/conda/lib/python3.7/site-packages/parlai/core/params.py", line 931, in add_extra_args
    self.add_model_subargs(model, partial)
  File "/opt/conda/lib/python3.7/site-packages/parlai/core/params.py", line 805, in add_model_subargs
    agent = load_agent_module(model)
  File "/opt/conda/lib/python3.7/site-packages/parlai/core/loader.py", line 188, in load_agent_module
    my_module = importlib.import_module(module_name)
  File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'projects.personachat'
![image](https://user-images.githubusercontent.com/3937341/110746672-1bdbad00-8278-11eb-853f-03d57a605932.png)

Did anyone have a similar issue?

**Comment by stephenroller** [comment]
You may need to set your PYTHONPATH to include the current directory
