### ISSUE TITLE
Error while trying to run model_evaluator MTurk task

### ISSUE THREAD

**Issue by deshraj** [facebookresearch/ParlAI#354]
While trying to run the model_evaluator, I got the following error:

```
Exception in thread task-t_1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/deshraj/Documents/ParlAI/parlai/mturk/core/mturk_manager.py", line 755, in _task_function
    task_function(mturk_manager=self, opt=opt, workers=workers)
TypeError: run_conversation() got an unexpected keyword argument 'mturk_manager'
```

Just to make sure that I am executing the right command: `python run.py --sandbox --debug` is the correct way, right? 

Please find the full error log here: https://pastebin.com/j09NKv1F

**Comment by JackUrb** [comment]
Investigating now

**Comment by JackUrb** [comment]
This is my bad - I hadn't updated this particular task during the overhaul of our MTurk functionality. Pushing a fix now

**Comment by deshraj** [comment]
Thanks @JackUrb for the quick fix. :)
