### ISSUE TITLE
TypeError: _renorm() missing 1 required positional argument: 'norm_type'

### ISSUE THREAD

**Issue by nabihach** [facebookresearch/ParlAI#363]
I am new to ParlAI. I ran the following command on Ubuntu 16.04 and got the following error:
`python3 examples/train_model.py -m seq2seq -t cornell_movie -bs 8 -e 1 -mf /tmp/model_s2s --no-cuda`

```[creating task(s): cornell_movie]
[loading fbdialog data:/home/nasghar/ParlAI/data/CornellMovie/train.txt]
[ training... ]
Traceback (most recent call last):
  File "examples/train_model.py", line 219, in <module>
    main(setup_args())
  File "examples/train_model.py", line 133, in main
    world.parley()
  File "/home/nasghar/ParlAI/parlai/core/worlds.py", line 604, in parley
    batch_act = self.batch_act(index, batch_observations[index])
  File "/home/nasghar/ParlAI/parlai/core/worlds.py", line 577, in batch_act
    batch_actions = a.batch_act(batch_observation)
  File "/home/nasghar/ParlAI/parlai/agents/seq2seq/seq2seq.py", line 882, in batch_act
    predictions, text_cand_inds = self.predict(xs, ys, cands, valid_cands)
  File "/home/nasghar/ParlAI/parlai/agents/seq2seq/seq2seq.py", line 732, in predict
    encoder_output, hidden = self._encode(xs, is_training)
  File "/home/nasghar/ParlAI/parlai/agents/seq2seq/seq2seq.py", line 465, in _encode
    xes = F.dropout(self.enc_lt(xs), p=self.dropout, training=is_training)
  File "/home/nasghar/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nasghar/.local/lib/python3.5/site-packages/torch/nn/modules/sparse.py", line 94, in forward
    self.scale_grad_by_freq, self.sparse
  File "/home/nasghar/.local/lib/python3.5/site-packages/torch/nn/_functions/thnn/sparse.py", line 48, in forward
    cls._renorm(indices, weight, max_norm, norm_type)
TypeError: _renorm() missing 1 required positional argument: 'norm_type'```

**Comment by nabihach** [comment]
I fixed this issue by updating Pytorch.
