### ISSUE TITLE
I cannot download the model provided

### ISSUE THREAD

**Issue by ahf876828330** [facebookresearch/ParlAI#3661]
**when I want to download the model provided,the server display these information.How can I solve this problem,thanks for your help!**

 Downloading http://parl.ai/downloads/_models/dialogue_unlikelihood/rep_wiki_ctxt_and_label_v1.tgz to /home/aihongfei/ParlAI/data/models/dialogue_unlikelihood/rep_wiki_ctxt_and_label/rep_wiki_ctxt_and_label_v1.tgz
Downloading rep_wiki_ctxt_and_label_v1.tgz: 0.00B [00:00, ?B/s]
20:40:30 | Retried too many times, stopped retrying.
Traceback (most recent call last):
  File "parlai/scripts/interactive.py", line 123, in <module>
    Interactive.main()
  File "/home/aihongfei/ParlAI/parlai/core/script.py", line 128, in main
    return cls._run_args(None)
  File "/home/aihongfei/ParlAI/parlai/core/script.py", line 100, in _run_args
    opt = parser.parse_args(args=args)
  File "/home/aihongfei/ParlAI/parlai/core/params.py", line 1156, in parse_args
    self._process_args_to_opts(args)
  File "/home/aihongfei/ParlAI/parlai/core/params.py", line 1117, in _process_args_to_opts
    self.opt.get('datapath'), self.opt[each_key]
  File "/home/aihongfei/ParlAI/parlai/core/build_data.py", line 491, in modelzoo_path
    my_module.download(datapath)
  File "/home/aihongfei/ParlAI/parlai/zoo/dialogue_unlikelihood/rep_wiki_ctxt_and_label.py", line 23, in download
    version=VERSION,
  File "/home/aihongfei/ParlAI/parlai/zoo/dialogue_unlikelihood/build.py", line 21, in build
    opt, [fname], 'dialogue_unlikelihood', version=version, use_model_type=False
  File "/home/aihongfei/ParlAI/parlai/core/build_data.py", line 454, in download_models
    download(url, dpath, fname)
  File "/home/aihongfei/ParlAI/parlai/core/build_data.py", line 210, in download
    raise RuntimeError('Connection broken too many times. Stopped retrying.')
RuntimeError: Connection broken too many times. Stopped retrying.

**Comment by stephenroller** [comment]
Hmm, I would expect that to be a transient error.

Can you download https://dl.fbaipublicfiles.com/parlai/_models/dialogue_unlikelihood/rep_wiki_ctxt_and_label_v1.tgz and put it in the folder you described?
