### ISSUE TITLE
renorm() misses required positional argument when training seq2seq model on babi (example command)

### ISSUE THREAD

**Issue by k0105** [facebookresearch/ParlAI#376]
I encounter a similar issue to https://github.com/facebookresearch/ParlAI/issues/363
When I install PyTorch, clone ParlAI and then try to run one of the example commands, i.e. `python examples/train_model.py -m seq2seq -t babi:task1k:1 -bs 8 -e 1 -mf /tmp/model_s2s` I get the error `TypeError: _renorm() missing 1 required positional argument: 'norm_type'`. However, I am on the most recent version and the problem still persists, so the solution from the aforementioned thread does not work for me. I've tried this both on Ubuntu 16.04 LTS and 17.10 (64bit), both on my workstation and notebook and also both in a bash shell directly as well as inside an Anaconda environment. My PyTorch seems to work - I can import and use it just fine.

Any ideas about how to solve this? Thanks in advance.

Best wishes,
k0105

PS:
Stacktrace:
```
user@X1:~/Documents/DialogSystemBaseline/ParlAI-master$ python3 examples/train_model.py -m seq2seq -t babi:task1k:1 -bs 8 -e 1 -mf /tmp/model_s2s
[ Main ParlAI Arguments: ] 
[  task: babi:task1k:1 ]
[  download_path: /home/user/Documents/DialogSystemBaseline/ParlAI-master/downloads ]
[  datatype: train ]
[  image_mode: raw ]
[  numthreads: 1 ]
[  batchsize: 8 ]
[  datapath: /home/user/Documents/DialogSystemBaseline/ParlAI-master/data ]
[ ParlAI Model Arguments: ] 
[  model: seq2seq ]
[  model_file: /tmp/model_s2s ]
[  dict_class: None ]
[ Dictionary Arguments: ] 
[  dict_file: None ]
[  dict_initpath: None ]
[  dict_language: english ]
[  dict_max_ngram_size: -1 ]
[  dict_minfreq: 0 ]
[  dict_nulltoken: __NULL__ ]
[  dict_starttoken: __START__ ]
[  dict_endtoken: __END__ ]
[  dict_unktoken: __UNK__ ]
[  dict_maxexs: 100000 ]
[ Seq2Seq Arguments: ] 
[  hiddensize: 128 ]
[  embeddingsize: 128 ]
[  numlayers: 2 ]
[  learningrate: 0.005 ]
[  dropout: 0.1 ]
[  bidirectional: False ]
[  attention: none ]
[  attention_length: 48 ]
[  no_cuda: False ]
[  gpu: -1 ]
[  rank_candidates: False ]
[  truncate: -1 ]
[  encoder: gru ]
[  decoder: same ]
[  lookuptable: all ]
[  optimizer: adam ]
[  embedding_type: random ]
[  language_model: none ]
[ Training Loop Arguments: ] 
[  evaltask: None ]
[  display_examples: False ]
[  num_epochs: 1.0 ]
[  max_train_time: -1 ]
[  log_every_n_secs: 2 ]
[  validation_every_n_secs: -1 ]
[  validation_max_exs: -1 ]
[  validation_patience: 10 ]
[  validation_metric: accuracy ]
[  dict_build_first: True ]
[ building dictionary first... ]
[ setting up dictionary. ]
[nltk_data] Downloading package punkt to /home/user/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[creating task(s): babi:task1k:1]
[building data: /home/user/Documents/DialogSystemBaseline/ParlAI-master/data/bAbI]
[||||||||||||||||||||||||||||||||||||||||] 19212062 / 19212062
unpacking babi.tar.gz
[loading fbdialog data:/home/user/Documents/DialogSystemBaseline/ParlAI-master/data/bAbI/tasks_1-20_v1-2/en-valid-nosf/qa1_train.txt]
[ dictionary built. ]
Dictionary: saving dictionary to /tmp/model_s2s.dict
Dictionary: loading dictionary from /tmp/model_s2s.dict
[ num words =  25 ]
[creating task(s): babi:task1k:1]
[loading fbdialog data:/home/user/Documents/DialogSystemBaseline/ParlAI-master/data/bAbI/tasks_1-20_v1-2/en-valid-nosf/qa1_train.txt]
[ training... ]
Traceback (most recent call last):
  File "examples/train_model.py", line 219, in <module>
    main(setup_args())
  File "examples/train_model.py", line 133, in main
    world.parley()
  File "/home/user/Documents/DialogSystemBaseline/ParlAI-master/parlai/core/worlds.py", line 604, in parley
    batch_act = self.batch_act(index, batch_observations[index])
  File "/home/user/Documents/DialogSystemBaseline/ParlAI-master/parlai/core/worlds.py", line 577, in batch_act
    batch_actions = a.batch_act(batch_observation)
  File "/home/user/Documents/DialogSystemBaseline/ParlAI-master/parlai/agents/seq2seq/seq2seq.py", line 927, in batch_act
    predictions, text_cand_inds, loss = self.predict(xs, ys, cands, valid_cands)
  File "/home/user/Documents/DialogSystemBaseline/ParlAI-master/parlai/agents/seq2seq/seq2seq.py", line 754, in predict
    encoder_output, hidden = self._encode(xs, is_training)
  File "/home/user/Documents/DialogSystemBaseline/ParlAI-master/parlai/agents/seq2seq/seq2seq.py", line 474, in _encode
    xes = F.dropout(self.enc_lt(xs), p=self.dropout, training=is_training)
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 94, in forward
    self.scale_grad_by_freq, self.sparse
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/_functions/thnn/sparse.py", line 48, in forward
    cls._renorm(indices, weight, max_norm, norm_type)
TypeError: _renorm() missing 1 required positional argument: 'norm_type'
```

**Comment by kearnsw** [comment]
There was an issue with max_norm and embedding layers that has been solved in the current source code of PyTorch: https://github.com/pytorch/pytorch/issues/2620

This is not the current release in the repository, however, so you can either build pytorch from the source code on the github repo (recommended) or update the "/home/user/.local/lib/python3.6/site-packages/torch/nn/_functions/thnn/sparse.py" like https://github.com/pytorch/pytorch/commit/e51fec3be04b51deda6ffcc2362ed270ebbd3311.

**Comment by k0105** [comment]
You, Sir, are amazing. With Pytorch compiled from source the command works perfectly. Highly appreciate it, thank you very much.

**Comment by alexholdenmiller** [comment]
by the way--I'm updating this model in the next couple days to use nn.Module subclasses so it's easier to work with! Thanks for the quick comment @kearnsw, I am removing maxnorm from the default params so out-of-date pytorch stops causing this error...
