### ISSUE TITLE
Run crowdsourcing/tasks/model_chat/run.py directly will report errors.

### ISSUE THREAD

**Issue by SYSU-lulc** [facebookresearch/ParlAI#3770]
Run crowdsourcing/tasks/model_chat/run.py directly will report errors. Both Parlai and Mephisto are up to date.

Command:
`python run.py`

Errors:
`run.py:46: UserWarning:
config_path is not specified in @hydra.main().
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_hydra_main_config_path for more information.
  @hydra.main(config_name="scriptconfig")
/data3/anaconda3/envs/BEN/lib/python3.7/site-packages/hydra/core/default_element.py:127: UserWarning: In 'mephisto/provider/mock': Usage of deprecated
keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  See {url} for more information"""
/data3/anaconda3/envs/BEN/lib/python3.7/site-packages/hydra/core/default_element.py:127: UserWarning: In 'mephisto/architect/local': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  See {url} for more information"""
/data3/anaconda3/envs/BEN/lib/python3.7/site-packages/hydra/core/default_element.py:127: UserWarning: In 'mephisto/blueprint/model_chat_blueprint': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  See {url} for more information"""
In 'scriptconfig': Validation error while composing config:
Merge error: BlueprintArgs is not a subclass of ModelChatBlueprintArgs. value: {'_blueprint_type': '???', 'onboarding_qualification': '???', 'block_qualification': '???'}
    full_key:
    object_type=dict

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.`

This file can be run directly as an example, right? Or need to set any parameters in advance? 
Thank you for your attention!

**Comment by SYSU-lulc** [comment]
When I directly run the code on another machine, different errors will be reported. Both Parlai and Mephisto are up to date, too.

Command:
`python run.py`

Errors:
`15:59:34 | Overriding opt["model_file"] to /data4/ben/util/ParlAI/data/models/blender/blender_90M/model (previously: /checkpoint/edinan/20200210/baseline_BST_retnref/lr=7.5e-06_attention-dropo
ut=0.0_relu-dropout=0.0/model)
15:59:34 | Loading model with `--beam-block-full-context false`
15:59:38 | Using CUDA
15:59:38 | loading dictionary from /data4/ben/util/ParlAI/data/models/blender/blender_90M/model.dict
15:59:38 | num words = 54944
15:59:39 | DEPRECATED: XLM should only be used for backwards compatibility, as it involves a less-stable layernorm operation.
15:59:59 | Total parameters: 87,508,992 (87,508,992 trainable)
15:59:59 | Loading existing model params from /data4/ben/util/ParlAI/data/models/blender/blender_90M/model
[2021-07-09 16:00:00,216][mephisto.operations.operator][ERROR] - Encountered error while launching run, shutting down
Traceback (most recent call last):
  File "/data4/util/Mephisto/mephisto/operations/operator.py", line 213, in validate_and_run_config_or_die
    built_dir = architect.prepare()
  File "/data4/ben/util/Mephisto/mephisto/abstractions/architects/local_architect.py", line 138, in prepare
    server_source_path=self.server_source_path,
  File "/data4/ben/util/Mephisto/mephisto/abstractions/architects/router/build_router.py", line 82, in build_router
    server_source_directory_path = build_node_router(build_dir, task_run)
  File "/data4/ben/util/Mephisto/mephisto/abstractions/architects/router/build_router.py", line 58, in build_node_router
    install_router_files()
  File "/data4/ben/util/Mephisto/mephisto/abstractions/architects/router/build_router.py", line 47, in install_router_files
    packages_installed = subprocess.call(["npm", "install"])
  File "/data4/anaconda3/envs/BEN/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/data4/anaconda3/envs/BEN/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data4/anaconda3/envs/BEN/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'npm': 'npm'
[2021-07-09 16:00:00,219][mephisto.operations.operator][ERROR] - Could not shut down architect: shutdown called before deploy
Traceback (most recent call last):
  File "/data4/ben/util/Mephisto/mephisto/operations/operator.py", line 213, in validate_and_run_config_or_die
    built_dir = architect.prepare()
  File "/data4/ben/util/Mephisto/mephisto/abstractions/architects/local_architect.py", line 138, in prepare
    server_source_path=self.server_source_path,
  File "/data4/ben/util/Mephisto/mephisto/abstractions/architects/router/build_router.py", line 82, in build_router
    server_source_directory_path = build_node_router(build_dir, task_run)
  File "/data4/ben/util/Mephisto/mephisto/abstractions/architects/router/build_router.py", line 58, in build_node_router
    install_router_files()
  File "/data4/ben/util/Mephisto/mephisto/abstractions/architects/router/build_router.py", line 47, in install_router_files
    packages_installed = subprocess.call(["npm", "install"])
  File "/data4/anaconda3/envs/BEN/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/data4/anaconda3/envs/BEN/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data4/anaconda3/envs/BEN/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'npm': 'npm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data4/ben/util/Mephisto/mephisto/operations/operator.py", line 265, in validate_and_run_config_or_die
    architect.shutdown()
  File "/data4/ben/util/Mephisto/mephisto/abstractions/architects/local_architect.py", line 189, in shutdown
    assert self.running_dir is not None, "shutdown called before deploy"
AssertionError: shutdown called before deploy
[2021-07-09 16:00:00,220][mephisto.operations.operator][ERROR] - Ran into error while launching run: 
Traceback (most recent call last):
  File "/data4/ben/util/Mephisto/mephisto/operations/operator.py", line 425, in validate_and_run_config
    run_config=run_config, shared_state=shared_state
  File "/data4/ben/util/Mephisto/mephisto/operations/operator.py", line 271, in validate_and_run_config_or_die
    raise e
  File "/data4/ben/util/Mephisto/mephisto/operations/operator.py", line 213, in validate_and_run_config_or_die
    built_dir = architect.prepare()
  File "/data4/ben/util/Mephisto/mephisto/abstractions/architects/local_architect.py", line 138, in prepare
    server_source_path=self.server_source_path,
  File "/data4/ben/util/Mephisto/mephisto/abstractions/architects/router/build_router.py", line 82, in build_router
    server_source_directory_path = build_node_router(build_dir, task_run)
  File "/data4/ben/util/Mephisto/mephisto/abstractions/architects/router/build_router.py", line 58, in build_node_router
    install_router_files()
  File "/data4/ben/util/Mephisto/mephisto/abstractions/architects/router/build_router.py", line 47, in install_router_files
    packages_installed = subprocess.call(["npm", "install"])
  File "/data4/anaconda3/envs/BEN/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/data4/anaconda3/envs/BEN/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data4/anaconda3/envs/BEN/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'npm': 'npm'
[2021-07-09 16:00:00,222][mephisto.operations.operator][INFO] - operator shutting down`

Thanks for your attention!

**Comment by mojtaba-komeili** [comment]
The fact that you have two different errors on two different environments may mean that there is something wrong with the setup. I am not sure what goes wrong in the first one. But for the second one seems like you need to have the right installation of Node.
Also, most of the errors seems to be coming from Mephisto modules. Maybe it is not a bad idea to check with them as well.

**Comment by SYSU-lulc** [comment]
Thanks a lot!!!!!!
