### ISSUE TITLE
Error while running interactive code in quickstart with Windows

### ISSUE THREAD

**Issue by lingfei1999** [facebookresearch/ParlAI#3828]
**Bug description**
Error while running interactive code in quickstart with Windows

**Reproduction steps**
```
parlai train_model --task babi:task10k:1 --model-file E:/tmp.d/babi_memnn --batchsize 1 --num-epochs 5 --model memnn

parlai.exe display_model --task babi:task10k:1 --model-file E://tmp.d/babi_memnn --eval-candidates vocab

parlai interactive --model-file E:/tmp.d/babi_memnn --eval-candidates vocab
```

**Expected behavior**
It should show an interactive form to work with 

**Logs**
Please paste the command line output:

```
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\parlai.exe\__main__.py", line 7, in <module>
  File "c:\python39\lib\site-packages\parlai\__main__.py", line 14, in main
    superscript_main()
  File "c:\python39\lib\site-packages\parlai\core\script.py", line 325, in superscript_main
    return SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "c:\python39\lib\site-packages\parlai\core\script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "c:\python39\lib\site-packages\parlai\scripts\interactive.py", line 118, in run
    return interactive(self.opt)
  File "c:\python39\lib\site-packages\parlai\scripts\interactive.py", line 84, in interactive
    agent = create_agent(opt, requireModelExists=True)
  File "c:\python39\lib\site-packages\parlai\core\agents.py", line 402, in create_agent
    model = create_agent_from_opt_file(opt)
  File "c:\python39\lib\site-packages\parlai\core\agents.py", line 355, in create_agent_from_opt_file
    return model_class(opt_from_file)
  File "c:\python39\lib\site-packages\parlai\agents\memnn\memnn.py", line 79, in __init__
    super().__init__(opt, shared)
  File "c:\python39\lib\site-packages\parlai\core\torch_ranker_agent.py", line 190, in __init__
    super().__init__(opt, shared)
  File "c:\python39\lib\site-packages\parlai\core\torch_agent.py", line 840, in __init__
    self.set_interactive_mode(opt.get('interactive_mode', False), shared)
  File "c:\python39\lib\site-packages\parlai\core\torch_ranker_agent.py", line 310, in set_interactive_mode
    path = self.get_task_candidates_path()
  File "c:\python39\lib\site-packages\parlai\core\torch_ranker_agent.py", line 334, in get_task_candidates_path
    build_cands(opt)
  File "c:\python39\lib\site-packages\parlai\scripts\build_candidates.py", line 90, in build_cands
    fw = open(outfile, 'w')
OSError: [Errno 22] Invalid argument: 'E:\\tmp.d\\babi_memnn.cands-babi:task10k:1.cands'
```

**Additional context**
```
python --version
Python 3.9.6
```

**Comment by csangrim** [comment]
I also have the same problem.

**Comment by klshuster** [comment]
Hi, we don't currently support Windows

**Comment by csangrim** [comment]
Thank you for the answer. Although I am using Windows on my laptop, I tried this in my Anaconda environment cmd prompt and got the error. Would you suggest any other way to try this quick start?

**Comment by klshuster** [comment]
Yeah, I think the issue is with the fixed candidates path.

Try the third command but set `--fixed-candidates-path` to a normal filename, e.g. `E:\\tmp.d\\babi_memnn_cands`

**Comment by csangrim** [comment]
In my case, I ran this:
`parlai interactive --model-file /tmp/babi_memnn --eval-candidates vocab`

Then, the error message is the following:
...
  File "c:\users\pione\anaconda3\lib\site-packages\parlai\core\torch_ranker_agent.py", line 334, in get_task_candidates_path
    build_cands(opt)
  File "c:\users\pione\anaconda3\lib\site-packages\parlai\scripts\build_candidates.py", line 90, in build_cands
    fw = open(outfile, 'w')
**OSError: [Errno 22] Invalid argument: '/tmp/babi_memnn.cands-babi:task10k:1.cands'**

Note: The following previous command in the QuickStart guide works well:
parlai display_model --task babi:task10k:1 --model-file /tmp/babi_memnn --eval-candidates vocab

**Comment by klshuster** [comment]
yes, it looks like Windows doesn't like the name of the file. can you please rename the file from `/tmp/babi_memnn.cands-babi:task10k:1.cands'` to `/tmp/babi_memnn_cands_babi_task10k_1_cands`, and then rerun the interactive command:

```
parlai interactive --model-file /tmp/babi_memnn --eval-candidates vocab --fixed-candidates-path /tmp/babi_memnn_cands_babi_task10k_1_cands
```

**Comment by csangrim** [comment]
Sorry, I don't know where the file that said to be renamed is located. Please see the attached image showing all the files in the tmp folder.
![2021-08-04 09_17_31-Window](https://user-images.githubusercontent.com/62888402/128102198-6eda05f3-daaf-4f70-b3d2-43e9b60f81fe.png)
Note: I have followed the exactly the same commands mentioned here: https://parl.ai/docs/tutorial_quick.html#view-a-task-train-a-model

**Comment by stephenroller** [comment]
Maybe we should just release a new version of the babi data.

**Comment by klshuster** [comment]
the issue is that windows doesn't like how we're naming the automatically generated cands file
