### ISSUE TITLE
Unable to Reproduce Blender Bot 2

### ISSUE THREAD

**Issue by ethanjperez** [facebookresearch/ParlAI#3829]
**Bug description**
Running BlenderBot2 results in errors, since users must provide a valid search server. What is the right search server to use, in order to reproduce Blender Bot 2? I'm interested in studying the version of Blender Bot 2 used in the official papers on Blender 2, so it would be great to be able to use the same search server used in the papers. If that's not possible, I'd be interested in knowing how to use some workaround search server that gives similar results.

Users in other issues (e.g., https://github.com/facebookresearch/ParlAI/issues/3816 or https://github.com/facebookresearch/ParlAI/issues/3808) have implemented workarounds, but I'm unsure if these workarounds are close enough to the original Blender Bot 2 implementation in order to be able to e.g. report on Blender Bot 2 results with this search engine in a paper.

P.S.: Thanks for open-sourcing Blender 2 - excited to play around with it soon!

**Reproduction steps**
Install ParlAI from master and run:
```bash
parlai interactive --model-file zoo:blenderbot2/blenderbot2_400M/model
```

**Expected behavior**
To be able to use Blender Bot 2 in interactive mode without errors.

**Logs**
The error from running `parlai interactive` as described earleir is below:
```
18:45:48 | Overriding opt["model_file"] to /home/ethanperez/ParlAI/data/models/blenderbot2/blenderbot2_400M/model (previously: /checkpoint/kshuster/projects/knowledge_bot/kbot_memfix_sweep25_Fri_Jul__9/338/model.oss)
18:45:48 | loading dictionary from /home/ethanperez/ParlAI/data/models/blenderbot2/blenderbot2_400M/model.dict
18:45:48 | num words = 50264
18:45:49 | BlenderBot2Fid: full interactive mode on.
18:46:10 | Creating the search engine retriever.
search_server None
Traceback (most recent call last):
  File "/home/ethanperez/miniconda3/envs/parlai/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ethanperez/miniconda3/envs/parlai/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ethanperez/ParlAI/parlai/__main__.py", line 18, in <module>
    main()
  File "/home/ethanperez/ParlAI/parlai/__main__.py", line 14, in main
    superscript_main()
  File "/home/ethanperez/ParlAI/parlai/core/script.py", line 325, in superscript_main
    return SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "/home/ethanperez/ParlAI/parlai/core/script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "/home/ethanperez/ParlAI/parlai/scripts/interactive.py", line 118, in run
    return interactive(self.opt)
  File "/home/ethanperez/ParlAI/parlai/scripts/interactive.py", line 84, in interactive
    agent = create_agent(opt, requireModelExists=True)
  File "/home/ethanperez/ParlAI/parlai/core/agents.py", line 468, in create_agent
    model = create_agent_from_opt_file(opt)
  File "/home/ethanperez/ParlAI/parlai/core/agents.py", line 421, in create_agent_from_opt_file
    return model_class(opt_from_file)
  File "/home/ethanperez/ParlAI/parlai/agents/rag/rag.py", line 174, in __init__
    self._generation_agent.__init__(self, opt, shared)  # type: ignore
  File "/home/ethanperez/ParlAI/parlai/agents/bart/bart.py", line 72, in __init__
    super().__init__(opt, shared)
  File "/home/ethanperez/ParlAI/parlai/core/torch_generator_agent.py", line 484, in __init__
    self.model = fsdp_utils.fsdp_wrap(self.build_model())
  File "/home/ethanperez/ParlAI/projects/blenderbot2/agents/blenderbot2.py", line 885, in build_model
    model = BlenderBot2FidModel(self.opt, self.dict)
  File "/home/ethanperez/ParlAI/projects/blenderbot2/agents/modules.py", line 85, in __init__
    self.retriever = retriever_factory(opt, dictionary, shared=retriever_shared)
  File "/home/ethanperez/ParlAI/projects/blenderbot2/agents/modules.py", line 64, in retriever_factory
    return BB2SearchQuerySearchEngineRetriever(opt, dictionary, shared=shared)
  File "/home/ethanperez/ParlAI/parlai/agents/rag/retrievers.py", line 1124, in __init__
    self.search_client = self.initiate_retriever_api(opt)
  File "/home/ethanperez/ParlAI/parlai/agents/rag/retrievers.py", line 1135, in initiate_retriever_api
    return SearchEngineRetriever(opt)
  File "/home/ethanperez/ParlAI/parlai/agents/rag/retrieve_api.py", line 84, in __init__
    self.server_address = self._validate_server(opt.get('search_server'))
  File "/home/ethanperez/ParlAI/parlai/agents/rag/retrieve_api.py", line 100, in _validate_server
    raise ValueError('Must provide a valid server for search')
ValueError: Must provide a valid server for search
```

**Comment by ethanjperez** [comment]
Not sure who the right people to tag are... maybe @jxmsML or @jaseweston?

**Comment by klshuster** [comment]
Hi @ethanjperez --> we utilize the search setup outlined in the [Internet-Augmented Generation Paper](https://arxiv.org/abs/2107.07566) (associated with the Wizard of Internet dataset). In section 3.2 we describe the search server (Bing mapped to CC pages), and later in section 5.3 we outline the setup for model human evaluation (live Bing results). 

Hope that helps

**Comment by ethanjperez** [comment]
Thanks for the info! Do you/others plan to open-source either of the two search server setups? That would be quite helpful for my research, but I also understand if there are challenges in doing so.

In particular, I'm concerned that using a different search server implementation at test time is a form of distribution shift that might cause Blender Bot 2 to perform worse.

**Comment by klshuster** [comment]
We have plans to eventually open source certain elements of the search server setups, though we may not be able to directly provide other elements (e.g. the CC data itself); indeed, however, if using live results, there necessarily **will** be a distribution shift. Note that we provide gold results with the dataset and thus setups evaluated with those results will be comparable.

**Comment by ethanjperez** [comment]
Ok, great to know. Do you have a very rough sense of when the live Bing results setup might be made available? (Just wondering if I can plan to use it in a current project)

**Comment by klshuster** [comment]
Probably within the next couple of months

**Comment by klshuster** [comment]
going to close this issue for now, but will reference back when the search engine code is available.
