### ISSUE TITLE
Need Help Getting Blenderbot2 running as a server

### ISSUE THREAD

**Issue by hitchingsh** [facebookresearch/ParlAI#3835]
**Bug description**
I have gotten the blenderbot2 interactive to work with a search server (github.com/JulesGM/ParlAI_SearchEngine).  However, I want to run blenderbot2 as a server like I was able to for the original blenderbot.  In my environment where I have installed the latest blenderbot2 master code from github, the original blenderbot runs fine as a server and I can connect to it with your web client but blenderbot2 does not work and I get an error.  

**Reproduction steps**
$ ./ParlAI/parlai/chat_service/services/browser_chat/run.py --config-path ../../gcloud-docker-images/blenderbot2/config-blenderbot2.yml --port 8000

16:15:23 | loading dictionary from /Users/hamilton/Documents/python/virtual-environments/blenderbot2/ParlAI/data/models/blenderbot2/blenderbot2_400M/model.dict
16:15:23 | num words = 50264
16:15:23 | BlenderBot2Fid: full interactive mode on.
Traceback (most recent call last):
  File "./ParlAI/parlai/chat_service/services/browser_chat/run.py", line 54, in <module>
    run(opt)
  File "./ParlAI/parlai/chat_service/services/browser_chat/run.py", line 41, in run
    manager = BrowserManager(opt)
  File "/Users/hamilton/Documents/python/virtual-environments/blenderbot2/ParlAI/parlai/chat_service/services/websocket/websocket_manager.py", line 54, in __init__
    self._complete_setup()
  File "/Users/hamilton/Documents/python/virtual-environments/blenderbot2/ParlAI/parlai/chat_service/services/websocket/websocket_manager.py", line 67, in _complete_setup
    self._load_model()
  File "/Users/hamilton/Documents/python/virtual-environments/blenderbot2/ParlAI/parlai/chat_service/services/websocket/websocket_manager.py", line 81, in _load_model
    model_params[model] = create_agent(model_opt).share()
  File "/Users/hamilton/Documents/python/virtual-environments/blenderbot2/ParlAI/parlai/core/agents.py", line 468, in create_agent
    model = create_agent_from_opt_file(opt)
  File "/Users/hamilton/Documents/python/virtual-environments/blenderbot2/ParlAI/parlai/core/agents.py", line 421, in create_agent_from_opt_file
    return model_class(opt_from_file)
  File "/Users/hamilton/Documents/python/virtual-environments/blenderbot2/ParlAI/parlai/agents/rag/rag.py", line 174, in __init__
    self._generation_agent.__init__(self, opt, shared)  # type: ignore
  File "/Users/hamilton/Documents/python/virtual-environments/blenderbot2/ParlAI/parlai/agents/bart/bart.py", line 72, in __init__
    super().__init__(opt, shared)
  File "/Users/hamilton/Documents/python/virtual-environments/blenderbot2/ParlAI/parlai/core/torch_generator_agent.py", line 484, in __init__
    self.model = fsdp_utils.fsdp_wrap(self.build_model())
  File "/Users/hamilton/Documents/python/virtual-environments/blenderbot2/ParlAI/projects/blenderbot2/agents/blenderbot2.py", line 885, in build_model
    model = BlenderBot2FidModel(self.opt, self.dict)
  File "/Users/hamilton/Documents/python/virtual-environments/blenderbot2/ParlAI/projects/blenderbot2/agents/modules.py", line 85, in __init__
    self.retriever = retriever_factory(opt, dictionary, shared=retriever_shared)
  File "/Users/hamilton/Documents/python/virtual-environments/blenderbot2/ParlAI/projects/blenderbot2/agents/modules.py", line 64, in retriever_factory
    return BB2SearchQuerySearchEngineRetriever(opt, dictionary, shared=shared)
  File "/Users/hamilton/Documents/python/virtual-environments/blenderbot2/ParlAI/parlai/agents/rag/retrievers.py", line 1115, in __init__
    super().__init__(opt, dictionary, shared)
  File "/Users/hamilton/Documents/python/virtual-environments/blenderbot2/ParlAI/parlai/agents/rag/retrievers.py", line 1016, in __init__
    self.doc_chunk_split_mode = opt['doc_chunk_split_mode']
KeyError: 'doc_chunk_split_mode'

**Additional context**

Here is my config-blenderbot2.yml
tasks:
  default:
    onboard_world: MessengerBotChatOnboardWorld
    task_world: MessengerBotChatTaskWorld
    timeout: 1800
    agents_required: 1
task_name: chatbot
world_module: parlai.chat_service.tasks.chatbot.worlds
overworld: MessengerOverworld
max_workers: 1
opt:  # Additional model opts go here
  debug: True
  models:
    blenderbot2_400M:
      model: transformer/generator
      model_file: zoo:blenderbot2/blenderbot2_400M/model
      interactive_mode: True
      no_cuda: True
      search_server: 0.0.0.0:8090
additional_args:
  page_id: 1 # configure your own page

Any help would be greatly appreciated

**Comment by klshuster** [comment]
hi there, it looks like you need to change `model: transformer/generator` to `model: projects.blenderbot2.agents.blenderbot2:BlenderBot2FidAgent`. You'll additionally want to add an `override` key specifying the search server (due to the way the websockets implementation creates agents...)

Your config should look like the following:
```
tasks:
  default:
    onboard_world: MessengerBotChatOnboardWorld
    task_world: MessengerBotChatTaskWorld
    timeout: 1800
    agents_required: 1
task_name: chatbot
world_module: parlai.chat_service.tasks.chatbot.worlds
overworld: MessengerOverworld
max_workers: 1
opt: # Additional model opts go here
  debug: True
  models:
    blenderbot2_400M:
      model: projects.blenderbot2.agents.blenderbot2:BlenderBot2FidAgent
      model_file: zoo:blenderbot2/blenderbot2_400M/model
      interactive_mode: True
      no_cuda: True
      search_server: 0.0.0.0:8090
      override:
        search_server: 0.0.0.0:8090
additional_args:
  page_id: 1 # configure your own page
```

let me know if that works!

**Comment by hitchingsh** [comment]
Kurt, thank you so much.  I got it up and running although I also had to modify a line 34 of chat_service/tasks/chatbot/worlds.py to be
    MODEL_KEY = 'blenderbot2_400M'

The search does not seem to be properly hooked up so I have to investigate that more tomorrow

**Comment by klshuster** [comment]
glad to hear it! I'll go ahead and close this issue then, please reopen (or file a new one and tag me) if you have any further questions.

**Comment by theainerd** [comment]
Heyy i am trying the same thing. although my server is running i am getting 404 error . 

```bash
{
  mid: # ID of this message
  recipient: {
    id: #id of message recipient
  }
  sender: {
    id: #id of message sender
  }
  text: # text of the message
  attachment: # attachment of the message
}
```

this is the message format. I am not sure why this is happening.
The config file is also similar.
