### ISSUE TITLE
BlenderBot2 causing errors after a few lines of chat

### ISSUE THREAD

**Issue by Jawad1347** [facebookresearch/ParlAI#3898]
**Bug description**
requests.exceptions.ConnectionError: HTTPConnectionPool(host='asd', port=80)

**Reproduction steps**
just run the blenderbot2 with the following code (in colab)

!parlai interactive \
--model-file zoo:blenderbot2/blenderbot2_400M/model \
--search-server http://asd

**Expected behavior**
It is expected to chat, like blenderbot as long as user does not write [EXIT] or [DONE] or stop execution of the cell

**Logs**
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f6e7ba32e50>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='asd', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6e7ba32e50>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/parlai", line 33, in <module>
    sys.exit(load_entry_point('parlai', 'console_scripts', 'parlai')())
  File "/content/ParlAI/parlai/__main__.py", line 14, in main
    superscript_main()
  File "/content/ParlAI/parlai/core/script.py", line 325, in superscript_main
    return SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "/content/ParlAI/parlai/core/script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "/content/ParlAI/parlai/scripts/interactive.py", line 118, in run
    return interactive(self.opt)
  File "/content/ParlAI/parlai/scripts/interactive.py", line 93, in interactive
    world.parley()
  File "/content/ParlAI/parlai/tasks/interactive/worlds.py", line 89, in parley
    acts[1] = agents[1].act()
  File "/content/ParlAI/parlai/core/torch_agent.py", line 2143, in act
    response = self.batch_act([self.observation])[0]
  File "/content/ParlAI/parlai/core/torch_agent.py", line 2239, in batch_act
    output = self.eval_step(batch)
  File "/content/ParlAI/projects/blenderbot2/agents/blenderbot2.py", line 782, in eval_step
    output = super().eval_step(batch)
  File "/content/ParlAI/parlai/core/torch_generator_agent.py", line 876, in eval_step
    batch, self.beam_size, maxlen, prefix_tokens=prefix_tokens
  File "/content/ParlAI/parlai/agents/rag/rag.py", line 608, in _generate
    gen_outs = self._rag_generate(batch, beam_size, max_ts, prefix_tokens)
  File "/content/ParlAI/parlai/agents/rag/rag.py", line 648, in _rag_generate
    self, batch, beam_size, max_ts, prefix_tokens
  File "/content/ParlAI/parlai/core/torch_generator_agent.py", line 1094, in _generate
    encoder_states = model.encoder(*self._encoder_input(batch))
  File "/content/ParlAI/projects/blenderbot2/agents/modules.py", line 816, in encoder
    segments,
  File "/content/ParlAI/projects/blenderbot2/agents/modules.py", line 223, in encoder
    num_memory_decoder_vecs,
  File "/content/ParlAI/projects/blenderbot2/agents/modules.py", line 354, in retrieve_and_concat
    search_queries, query_vec, search_indices
  File "/content/ParlAI/projects/blenderbot2/agents/modules.py", line 515, in perform_search
    query_vec[search_indices]  # type: ignore
  File "/content/ParlAI/parlai/agents/rag/retrievers.py", line 398, in retrieve
    docs, scores = self.retrieve_and_score(query)
  File "/content/ParlAI/parlai/agents/rag/retrievers.py", line 1169, in retrieve_and_score
    search_results_batach = self.search_client.retrieve(search_queries, self.n_docs)
  File "/content/ParlAI/parlai/agents/rag/retrieve_api.py", line 132, in retrieve
    return [self._retrieve_single(q, num_ret) for q in queries]
  File "/content/ParlAI/parlai/agents/rag/retrieve_api.py", line 132, in <listcomp>
    return [self._retrieve_single(q, num_ret) for q in queries]
  File "/content/ParlAI/parlai/agents/rag/retrieve_api.py", line 111, in _retrieve_single
    search_server_resp = self._query_search_server(search_query, num_ret)
  File "/content/ParlAI/parlai/agents/rag/retrieve_api.py", line 89, in _query_search_server
    server_response = requests.post(server, data=req)
  File "/usr/local/lib/python3.7/dist-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='asd', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6e7ba32e50>: Failed to establish a new connection: [Errno -2] Name or service not known'))

**Additional context**
Some times it runs only for one line of chat and this happens. Maximum length of chat was 8 lines. And I found that (in 3 chats) if you don't talk to bot for a while then it throws the error sooner.

**Comment by klshuster** [comment]
you have specified an invalid search server

**Comment by Jawad1347** [comment]
But it goes on for at least a few lines (at least two, one question and its response). But thank you, the server I am using now is JulesGM's search engine and it is working fine. Also, what is RAM and GPU requirements for 400M bot? Currently (on inference) it is taking about 11GB VRAM and about 3GB RAM. Will I be able to do inference (just run model for chatting) on local machine (without GPU?).

Thank you for response.

**Comment by klshuster** [comment]
I think it depends on how much RAM you have on your local machine - you seem to have the correct numbers for VRAM and RAM

**Comment by superchargez** [comment]
Thank you Kurt for replies. I (and few others, as I have seen in discussion and in issues, some other people are) am having a problem of incorrect responses. BlenderBot2 is supposed to fetch data from internet and give correct answers but it still thinks that Donald Trump is the current president and it is 2017 (I found that during a chat session, with server 0.0.0.0:8080). Can I correct this problem by using google as search server as in following?

!parlai interactive
--model-file zoo:blenderbot2/blenderbot2_400M/model
--search-server http://google.com

??

**Comment by mittalpatel** [comment]
> you have specified an invalid search server

Is there a list of search servers we can use? Tried bing, google, duckduckgo, but getting below error:
`06:33:44 | Failed to retrieve data from server! Search server returned status 405`

**Comment by superchargez** [comment]
> 
> 
> > you have specified an invalid search server
> 
> Is there a list of search servers we can use? Tried bing, google, duckduckgo, but getting below error:
> `06:33:44 | Failed to retrieve data from server! Search server returned status 405`

Same problem here. I used google.

**Comment by mittalpatel** [comment]
> > > you have specified an invalid search server
> > 
> > 
> > Is there a list of search servers we can use? Tried bing, google, duckduckgo, but getting below error:
> > `06:33:44 | Failed to retrieve data from server! Search server returned status 405`
> 
> Same problem here. I used google.

We made it work using https://github.com/JulesGM/ParlAI_SearchEngine . So, set it up, run it in local and then run blenderbot command like:
`parlai interactive -mf zoo:blenderbot2/blenderbot2_3B/model --search-server 0.0.0.0:8080`

**Comment by Jawad1347** [comment]
@mittalpatel thank you. it did work (for a while) but then it stopped saying "user input"/something so I could not continue chatting with it. someone suggested to change port because a newer program can ask to go online on the same port used earlier, however I was running it in colab, so I don't think that should be the problem or does it mean that even colab can open a port multiple times? even if google provides VM with CPU, GPU and RAM, there should not be any programs running in background that would disturb a port, would/should there be?

**Comment by superchargez** [comment]
I am closing this, the issue has been resolved.
Problem occurred because I did not use correct search server.

**Comment by alexvaca0** [comment]
I'm facing the same issue when using https://github.com/JulesGM/ParlAI_SearchEngine, after some turns

```
Traceback (most recent call last):
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\urllib3\connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [WinError 10049] La dirección solicitada no es válida en este contexto

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\urllib3\connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\http\client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\http\client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\http\client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\http\client.py", line 1036, in _send_output
    self.send(msg)
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\http\client.py", line 976, in send
    self.connect()
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\urllib3\connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001BBD2A08208>: Failed to establish a new connection: [WinError 10049] La dirección solicitada no es válida en este contexto

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\requests\adapters.py", line 450, in send
    timeout=timeout
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\urllib3\connectionpool.py", line 786, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='0.0.0.0', port=10565): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BBD2A08208>: Failed to establish a new connection: [WinError 10049] La dirección solicitada no es válida en este contexto'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\Scripts\parlai.exe\__main__.py", line 7, in <module>
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\parlai\__main__.py", line 14, in main
    superscript_main()
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\parlai\core\script.py", line 325, in superscript_main
    return SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\parlai\core\script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\parlai\scripts\interactive.py", line 118, in run
    return interactive(self.opt)
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\parlai\scripts\interactive.py", line 93, in interactive
    world.parley()
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\parlai\tasks\interactive\worlds.py", line 89, in parley
    acts[1] = agents[1].act()
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\parlai\core\torch_agent.py", line 2143, in act
    response = self.batch_act([self.observation])[0]
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\parlai\core\torch_agent.py", line 2239, in batch_act
    output = self.eval_step(batch)
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\projects\blenderbot2\agents\blenderbot2.py", line 790, in eval_step
    output = super().eval_step(batch)
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\parlai\agents\rag\rag.py", line 290, in eval_step
    output = super().eval_step(batch)
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\parlai\core\torch_generator_agent.py", line 876, in eval_step
    batch, self.beam_size, maxlen, prefix_tokens=prefix_tokens
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\parlai\agents\rag\rag.py", line 673, in _generate
    gen_outs = self._rag_generate(batch, beam_size, max_ts, prefix_tokens)
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\parlai\agents\rag\rag.py", line 713, in _rag_generate
    self, batch, beam_size, max_ts, prefix_tokens
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\parlai\core\torch_generator_agent.py", line 1094, in _generate
    encoder_states = model.encoder(*self._encoder_input(batch))
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\projects\blenderbot2\agents\modules.py", line 821, in encoder
    segments,
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\projects\blenderbot2\agents\modules.py", line 226, in encoder
    num_memory_decoder_vecs,
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\projects\blenderbot2\agents\modules.py", line 357, in retrieve_and_concat
    search_queries, query_vec, search_indices
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\projects\blenderbot2\agents\modules.py", line 519, in perform_search
    query_vec[search_indices]  # type: ignore
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\parlai\agents\rag\retrievers.py", line 411, in retrieve
    docs, scores = self.retrieve_and_score(query)
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\parlai\agents\rag\retrievers.py", line 1192, in retrieve_and_score
    search_results_batach = self.search_client.retrieve(search_queries, self.n_docs)
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\parlai\agents\rag\retrieve_api.py", line 132, in retrieve
    return [self._retrieve_single(q, num_ret) for q in queries]
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\parlai\agents\rag\retrieve_api.py", line 132, in <listcomp>
    return [self._retrieve_single(q, num_ret) for q in queries]
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\parlai\agents\rag\retrieve_api.py", line 111, in _retrieve_single
    search_server_resp = self._query_search_server(search_query, num_ret)
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\parlai\agents\rag\retrieve_api.py", line 89, in _query_search_server
    server_response = requests.post(server, data=req)
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Usuario\anaconda3\envs\parlaisearch\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=10565): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BBD2A08208>: Failed to establish a new connection: [WinError 10049] La dirección solicitada no es válida en este contexto'))
```

Any ideas?
