### ISSUE TITLE
Memory_vec problem when trying to train Blenderbot2 model on the msc task

### ISSUE THREAD

**Issue by yiranzhong** [facebookresearch/ParlAI#3908]
Hi all,

I was trying to train a blenderbot2 model on the msc task. As discussed in #3876 , I used the command below:

`parlai train_model --model projects.blenderbot2.agents.blenderbot2:BlenderBot2FidAgent --task msc \
--include-last-session True  --rag-model-type token --rag-retriever-type dpr 
--dpr-model-file zoo:hallucination/multiset_dpr/hf_bert_base.cp --generation-model bart --batchsize 6 \
--fp16 True --gradient-clip 0.1 --label-truncate 128 --log-every-n-secs 30 --lr-scheduler reduceonplateau \
--lr-scheduler-patience 1 --model-parallel True --optimizer adam --text-truncate 512 --truncate 512 \
--learningrate 1e-05 --validation-metric-mode min --validation-every-n-epochs 0.25 --validation-max-exs 1000 \
--validation-metric ppl --validation-patience 5 --model-file /tmp/bb2`

It seems there is something wrong with the memory_vec. The error report is:

```
21:40:04 | creating task(s): msc
21:40:04 | loading normalized fbdialog data: /home/yiran/ParlAI/data/ConvAI2/train_self_original.txt
21:40:04 | loading fbdialog data: /home/yiran/ParlAI/data/ConvAI2/train_self_original.txt
loading: /home/yiran/ParlAI/data/msc/msc/msc_dialogue/session_2
loading: /home/yiran/ParlAI/data/msc/msc/msc_dialogue/session_3
loading: /home/yiran/ParlAI/data/msc/msc/msc_dialogue/session_4
21:40:28 | training...
Traceback (most recent call last):
  File "/home/yiran/anaconda3/envs/chatbot_env/bin/parlai", line 33, in <module>
    sys.exit(load_entry_point('parlai', 'console_scripts', 'parlai')())
  File "/home/yiran/ParlAI/parlai/__main__.py", line 14, in main
    superscript_main()
  File "/home/yiran/ParlAI/parlai/core/script.py", line 325, in superscript_main
    return SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "/home/yiran/ParlAI/parlai/core/script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "/home/yiran/ParlAI/parlai/scripts/train_model.py", line 933, in run
    return self.train_loop.train()
  File "/home/yiran/ParlAI/parlai/scripts/train_model.py", line 897, in train
    for _train_log in self.train_steps():
  File "/home/yiran/ParlAI/parlai/scripts/train_model.py", line 804, in train_steps
    world.parley()
  File "/home/yiran/ParlAI/parlai/core/worlds.py", line 865, in parley
    batch_act = self.batch_act(agent_idx, batch_observations[agent_idx])
  File "/home/yiran/ParlAI/parlai/core/worlds.py", line 833, in batch_act
    batch_actions = a.batch_act(batch_observation)
  File "/home/yiran/ParlAI/parlai/core/torch_agent.py", line 2234, in batch_act
    output = self.train_step(batch)
  File "/home/yiran/ParlAI/parlai/core/torch_generator_agent.py", line 734, in train_step
    loss = self.compute_loss(batch)
  File "/home/yiran/ParlAI/projects/blenderbot2/agents/blenderbot2.py", line 834, in compute_loss
    loss, output = super().compute_loss(batch, return_output=True)
  File "/home/yiran/ParlAI/parlai/agents/rag/rag.py", line 885, in compute_loss
    model_output = self.get_model_output(batch)
  File "/home/yiran/ParlAI/parlai/agents/rag/rag.py", line 858, in get_model_output
    *self._model_input(batch), ys=batch.label_vec
  File "/home/yiran/anaconda3/envs/chatbot_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yiran/ParlAI/parlai/core/torch_generator_agent.py", line 309, in forward
    encoder_states = prev_enc if prev_enc is not None else self.encoder(*xs)
  File "/home/yiran/ParlAI/projects/blenderbot2/agents/modules.py", line 817, in encoder
    num_gold_docs,
  File "/home/yiran/ParlAI/projects/blenderbot2/agents/modules.py", line 223, in encoder
    num_memory_decoder_vecs,
  File "/home/yiran/ParlAI/projects/blenderbot2/agents/modules.py", line 382, in retrieve_and_concat
    generated_memories,
  File "/home/yiran/ParlAI/projects/blenderbot2/agents/modules.py", line 556, in access_long_term_memory
    batch_id: memory_vec[batch_id, : num_memories[mem_id]]
  File "/home/yiran/ParlAI/projects/blenderbot2/agents/modules.py", line 556, in <dictcomp>
    batch_id: memory_vec[batch_id, : num_memories[mem_id]]
IndexError: index 3 is out of bounds for dimension 0 with size 3
```

After checking the error by pdb, the memory_vec has a shape like [1, 5, 16], while the indices may be [0, 2], and hence out of index. I was trying to trace where the error starts but found it a bit hard. Any suggestion would be much appreciated!

**Comment by klshuster** [comment]
hi there - this happens when the model is unable to extract suitable "memories" from the context; you'll want to specify `--memory-key personas` so that the model is aware of what memories are associated with the context (since, during training, we don't utilize the memory decoder)
