### ISSUE TITLE
Config file for Blender Bot 2.0

### ISSUE THREAD

**Issue by theainerd** [facebookresearch/ParlAI#3925]
I want to run the blender bot 2.0 on browser channel. I am not sure how to define the config file.

```python

tasks:
  default:
    onboard_world: MessengerBotChatOnboardWorld
    task_world: MessengerBotChatTaskWorld
    timeout: 1800
    agents_required: 1
task_name: chatbot
world_module: parlai.chat_service.tasks.chatbot.worlds
overworld: MessengerOverworld
max_workers: 30
opt:
  debug: True
  models:
    blenderbot2_400M:
      model: transformer/generator
      model_file: zoo:blenderbot2/blenderbot2_400M/model
      interactive_mode: True
      no_cuda: True
additional_args:
  page_id: 1

```

But when I run this command:
```bash
python parlai/chat_service/services/browser_chat/run.py --config-path parlai/chat_service/tasks/chatbot/config.yml --port 10001
```

I am new to ParlAI so excuse me if I am missing something even minor. Can someone point me how to define the config file.

Error I get;

```bash
2021-08-10 16:55:15.537736: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
16:55:17 INFO | Using CUDA
16:55:17 INFO | loading dictionary from /content/ParlAI/data/models/blenderbot2/blenderbot2_400M/model.dict
16:55:17 INFO | num words = 50264
16:55:17 INFO | BlenderBot2Fid: full interactive mode on.
Traceback (most recent call last):
  File "parlai/chat_service/services/browser_chat/run.py", line 54, in <module>
    run(opt)
  File "parlai/chat_service/services/browser_chat/run.py", line 41, in run
    manager = BrowserManager(opt)
  File "/content/ParlAI/parlai/chat_service/services/websocket/websocket_manager.py", line 54, in __init__
    self._complete_setup()
  File "/content/ParlAI/parlai/chat_service/services/websocket/websocket_manager.py", line 67, in _complete_setup
    self._load_model()
  File "/content/ParlAI/parlai/chat_service/services/websocket/websocket_manager.py", line 81, in _load_model
    model_params[model] = create_agent(model_opt).share()
  File "/content/ParlAI/parlai/core/agents.py", line 468, in create_agent
    model = create_agent_from_opt_file(opt)
  File "/content/ParlAI/parlai/core/agents.py", line 421, in create_agent_from_opt_file
    return model_class(opt_from_file)
  File "/content/ParlAI/parlai/agents/rag/rag.py", line 176, in __init__
    self._generation_agent.__init__(self, opt, shared)  # type: ignore
  File "/content/ParlAI/parlai/agents/bart/bart.py", line 72, in __init__
    super().__init__(opt, shared)
  File "/content/ParlAI/parlai/core/torch_generator_agent.py", line 484, in __init__
    self.model = fsdp_utils.fsdp_wrap(self.build_model())
  File "/content/ParlAI/projects/blenderbot2/agents/blenderbot2.py", line 885, in build_model
    model = BlenderBot2FidModel(self.opt, self.dict)
  File "/content/ParlAI/projects/blenderbot2/agents/modules.py", line 85, in __init__
    self.retriever = retriever_factory(opt, dictionary, shared=retriever_shared)
  File "/content/ParlAI/projects/blenderbot2/agents/modules.py", line 64, in retriever_factory
    return BB2SearchQuerySearchEngineRetriever(opt, dictionary, shared=shared)
  File "/content/ParlAI/parlai/agents/rag/retrievers.py", line 1122, in __init__
    super().__init__(opt, dictionary, shared)
  File "/content/ParlAI/parlai/agents/rag/retrievers.py", line 1023, in __init__
    self.doc_chunk_split_mode = opt['doc_chunk_split_mode']
KeyError: 'doc_chunk_split_mode'
```

**Comment by klshuster** [comment]
you'll want to specify `model: projects.blenderbot2.agents.blenderbot2:BlenderBot2FidAgent`

additionally, if you have changed the key to `blenderbot2_400M`, you'll need to make sure this is changed in the chatbot world: https://github.com/facebookresearch/ParlAI/blob/master/parlai/chat_service/tasks/chatbot/worlds.py#L34

**Comment by theainerd** [comment]
Thanks @klshuster , but how do we provide the search server. ? It works well in interactive mode.
Do we provide the search_server on the config file or somewhere else.

**Comment by jaekookang** [comment]
Hi, I have a related question about setting up the config file.

I have my own search server activated on the server (e.g., 0.0.0.0:10002). I'm adding the keyword `search_server` with its parameter `0.0.0.0:10002` under `opt`, but it doesn't seem to recognize the search server.

For example, I tried to add three different locations under `opt` in config.yml file.

Try1:
<img width="743" alt="01" src="https://user-images.githubusercontent.com/18749927/128975947-28967362-e98b-4e91-85f4-7a5e5f2e37a4.png">


Try2:
<img width="745" alt="02" src="https://user-images.githubusercontent.com/18749927/128975961-e9457c50-0377-40a6-beb1-c65091a08b49.png">


Try3:
<img width="758" alt="03" src="https://user-images.githubusercontent.com/18749927/128975975-f3619d46-e1fe-44b5-97fd-a144b3efda2a.png">


Finally, I typed the command line as follows:
```bash
python parlai/chat_service/services/browser_chat/run.py --config-path parlai/chat_service/tasks/chatbot/config.yml --port 10001
```

It comes with the error whichever I tried.
```bash
Traceback (most recent call last):
  File "/home/jkang/anaconda3/envs/blenderbot/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jkang/anaconda3/envs/blenderbot/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jkang/.vscode-server/extensions/ms-python.python-2021.8.1105858891/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/jkang/.vscode-server/extensions/ms-python.python-2021.8.1105858891/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/jkang/.vscode-server/extensions/ms-python.python-2021.8.1105858891/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/home/jkang/anaconda3/envs/blenderbot/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/jkang/anaconda3/envs/blenderbot/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/jkang/anaconda3/envs/blenderbot/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jkang/project/ParlAI/parlai/chat_service/services/browser_chat/run.py", line 57, in <module>
    run(opt)
  File "/home/jkang/project/ParlAI/parlai/chat_service/services/browser_chat/run.py", line 41, in run
    manager = BrowserManager(opt)
  File "/home/jkang/project/ParlAI/parlai/chat_service/services/websocket/websocket_manager.py", line 54, in __init__
    self._complete_setup()
  File "/home/jkang/project/ParlAI/parlai/chat_service/services/websocket/websocket_manager.py", line 67, in _complete_setup
    self._load_model()
  File "/home/jkang/project/ParlAI/parlai/chat_service/services/websocket/websocket_manager.py", line 81, in _load_model
    model_params[model] = create_agent(model_opt).share()
  File "/home/jkang/project/ParlAI/parlai/core/agents.py", line 468, in create_agent
    model = create_agent_from_opt_file(opt)
  File "/home/jkang/project/ParlAI/parlai/core/agents.py", line 421, in create_agent_from_opt_file
    return model_class(opt_from_file)
  File "/home/jkang/project/ParlAI/parlai/agents/rag/rag.py", line 176, in __init__
    self._generation_agent.__init__(self, opt, shared)  # type: ignore
  File "/home/jkang/project/ParlAI/parlai/core/torch_generator_agent.py", line 484, in __init__
    self.model = fsdp_utils.fsdp_wrap(self.build_model())
  File "/home/jkang/project/ParlAI/projects/blenderbot2/agents/blenderbot2.py", line 885, in build_model
    model = BlenderBot2FidModel(self.opt, self.dict)
  File "/home/jkang/project/ParlAI/projects/blenderbot2/agents/modules.py", line 85, in __init__
    self.retriever = retriever_factory(opt, dictionary, shared=retriever_shared)
  File "/home/jkang/project/ParlAI/projects/blenderbot2/agents/modules.py", line 64, in retriever_factory
    return BB2SearchQuerySearchEngineRetriever(opt, dictionary, shared=shared)
  File "/home/jkang/project/ParlAI/parlai/agents/rag/retrievers.py", line 1124, in __init__
    self.search_client = self.initiate_retriever_api(opt)
  File "/home/jkang/project/ParlAI/parlai/agents/rag/retrievers.py", line 1135, in initiate_retriever_api
    return SearchEngineRetriever(opt)
  File "/home/jkang/project/ParlAI/parlai/agents/rag/retrieve_api.py", line 84, in __init__
    self.server_address = self._validate_server(opt.get('search_server'))
  File "/home/jkang/project/ParlAI/parlai/agents/rag/retrieve_api.py", line 100, in _validate_server
    raise ValueError('Must provide a valid server for search')
```

Could you tell me if I miss anything here?

Thanks

**Comment by klshuster** [comment]
you'll need an additional `override` field under the `blenderbot` key. your config would look like this:

```
opt:
  debug: True
  models:
    blenderbot2_400M:
      model: transformer/generator
      model_file: zoo:blenderbot2/blenderbot2_400M/model
      interactive_mode: True
      no_cuda: True
      override:
        search_server: 0.0.0.0:10002
````

let me know if that fixes things

**Comment by jaekookang** [comment]
@klshuster Your solution works perfectly. I don't see the search server issue anymore. Thank you!

**Comment by theainerd** [comment]
I have deployed the model on vm instance and now the server is up. I am trying to hit it using api calls. But i am geeting 404 error constantly. 

```python
[W 210814 09:18:40 web:2243] 404 POST / (54.86.50.139) 3.07ms
[W 210814 09:19:14 web:2243] 404 POST / (54.86.50.139) 0.60ms
[W 210814 09:19:30 web:2243] 404 GET / (54.86.50.139) 0.48ms
[W 210814 09:20:31 web:2243] 404 GET / (54.86.50.139) 0.53ms
[W 210814 09:20:41 web:2243] 404 POST / (54.86.50.139) 0.57ms
[W 210814 09:21:07 web:2243] 404 POST / (54.86.50.139) 0.48ms
[W 210814 09:22:24 web:2243] 404 GET / (54.86.50.139) 0.51ms
[W 210814 09:23:52 web:2243] 404 GET / (54.86.50.139) 0.51ms
[W 210814 09:24:02 web:2243] 404 POST / (54.86.50.139) 0.57ms

```

I am using this message format. 

```text
{
  mid: 105
  recipient: {
    id: 302
  }
  sender: {
    id: 555
  }
  text: "hi"
  attachment: 
}
```

I am using browser  chat services as a sample. Any suggestions would be helpful @jaekookang @klshuster

**Comment by jaekookang** [comment]
@theainerd I'm not sure why you get 404 error, but I found this repo useful if you haven't checked it out yet [https://github.com/JulesGM/ParlAI_SearchEngine](https://github.com/JulesGM/ParlAI_SearchEngine).

**Comment by gianlucabusatta** [comment]
This is my config.yml file:

```
tasks:
  default:
    onboard_world: MessengerBotChatOnboardWorld
    task_world: MessengerBotChatTaskWorld
    timeout: 1800
    agents_required: 1
task_name: chatbot
world_module: parlai.chat_service.tasks.chatbot.worlds
overworld: MessengerOverworld
max_workers: 30
opt:
  debug: True
  models:
    blenderbot2_400M:
      model: projects.blenderbot2.agents.blenderbot2:BlenderBot2RagAgent
      model_file: zoo:blenderbot2/blenderbot2_400M/model
      interactive_mode: True
      no_cuda: True
      search_server: 0.0.0.0:1111
      override:
        search_server: 0.0.0.0:1111
additional_args:
  page_id: 1 # Configure Your Own Page
```

I don't know why it starts as it was 'model: projects.blenderbot2.agents.blenderbot2:**BlenderBot2FidAgent**' rather than as specified 'model: projects.blenderbot2.agents.blenderbot2:**BlenderBot2RagAgent**'.

**Comment by AndrewMpapalika** [comment]
> Thanks @klshuster , but how do we provide the search server. ?
> Do we provide the search_server on the config file or somewhere else.
> 
> Also as i have read the documentation i can use google and bing api. How to use the Bing API ?
> In colab mostly i get 404 error for search, i am trying on an vm instance as well.



@theainerd:   Did you look more into the usage of google and bing api for the search server?

**Comment by louis030195** [comment]
@theainerd have you been able to reach the bot API in the end? I have the same issue running the bot in Kubernetes using https://github.com/langa-me/helm-charts/tree/main/charts/parlai I can reach the API when ssh'ing into the container but not outside, even on the node, strange... Otherwise, I'll dig how they set up the API, I guess...
