### ISSUE TITLE
 assert text.startswith(' ') error while training the blender using blended skill talk

### ISSUE THREAD

**Issue by kazeto111** [facebookresearch/ParlAI#3938]
I implement 
`python parlai/scripts/train_model.py -t blended_skill_talk --model transformer/generator --model_file outputs/models/model --init_model zoo:blender/blender_3B/model --dict_file zoo:blender/blender_3B/model.dict --datapath outputs/data --download_path outputs/data --n_heads 4 --n_encoder_layers 2 --n_decoder_layers 24 --n_positions 128 --delimiter --label_truncate 128 --ffn_size 10240 --embedding_size 2560 --activation gelu --variant prelayernorm --dropout 0.1 --special_tok_lst [U1],[U2] --dict_lower true --dict_tokenizer bytelevelbpe --optimizer adafactor --warmup_updates 100 --batchsize 4 --save_after_valid  true --text_truncate 128 --truncate 128 --max_train_time 600 --validation_metric ppl --validation_every_n_epochs 0.25 --fp16 true --fp16_impl mem_efficient --force-fp16-tokens true --update_freq 4 --gradient_clip 0.1 --skip_generation false --dynamic_batching full --model-parallel true   `

And got the error

> Traceback (most recent call last):
  File "main.py", line 143, in <module>
    train(parser.parse_args())
  File "main.py", line 75, in train
    model_parallel = args.model_parallel
  File "/mnt/batch/tasks/shared/LS_root/jobs/m8-brain-training/azureml/add_u1_to_input_1628935500_cae14635/wd/azureml/add_U1_to_input_1628935500_cae14635/parlai/core/script.py", line 108, in main
    return cls._run_kwargs(kwargs)
  File "/mnt/batch/tasks/shared/LS_root/jobs/m8-brain-training/azureml/add_u1_to_input_1628935500_cae14635/wd/azureml/add_U1_to_input_1628935500_cae14635/parlai/core/script.py", line 74, in _run_kwargs
    return cls._run_from_parser_and_opt(opt, parser)
  File "/mnt/batch/tasks/shared/LS_root/jobs/m8-brain-training/azureml/add_u1_to_input_1628935500_cae14635/wd/azureml/add_U1_to_input_1628935500_cae14635/parlai/core/script.py", line 89, in _run_from_parser_and_opt
    return script.run()
  File "/mnt/batch/tasks/shared/LS_root/jobs/m8-brain-training/azureml/add_u1_to_input_1628935500_cae14635/wd/azureml/add_U1_to_input_1628935500_cae14635/parlai/scripts/train_model.py", line 1054, in run
    return self.train_loop.train()
  File "/mnt/batch/tasks/shared/LS_root/jobs/m8-brain-training/azureml/add_u1_to_input_1628935500_cae14635/wd/azureml/add_U1_to_input_1628935500_cae14635/parlai/scripts/train_model.py", line 1016, in train
    for _train_log in self.train_steps():
  File "/mnt/batch/tasks/shared/LS_root/jobs/m8-brain-training/azureml/add_u1_to_input_1628935500_cae14635/wd/azureml/add_U1_to_input_1628935500_cae14635/parlai/scripts/train_model.py", line 954, in train_steps
    yield self.log()
  File "/mnt/batch/tasks/shared/LS_root/jobs/m8-brain-training/azureml/add_u1_to_input_1628935500_cae14635/wd/azureml/add_U1_to_input_1628935500_cae14635/parlai/scripts/train_model.py", line 799, in log
    self.valid_worlds, opt, 'valid', opt['validation_max_exs']
  File "/mnt/batch/tasks/shared/LS_root/jobs/m8-brain-training/azureml/add_u1_to_input_1628935500_cae14635/wd/azureml/add_U1_to_input_1628935500_cae14635/parlai/scripts/train_model.py", line 647, in _run_eval
    task_report = self._run_single_eval(opt, v_world, max_exs_per_worker)
  File "/mnt/batch/tasks/shared/LS_root/jobs/m8-brain-training/azureml/add_u1_to_input_1628935500_cae14635/wd/azureml/add_U1_to_input_1628935500_cae14635/parlai/scripts/train_model.py", line 613, in _run_single_eval
    valid_world.parley()
  File "/mnt/batch/tasks/shared/LS_root/jobs/m8-brain-training/azureml/add_u1_to_input_1628935500_cae14635/wd/azureml/add_U1_to_input_1628935500_cae14635/parlai/core/worlds.py", line 1192, in parley
    acts = self.handle_batch([self._obs[i] for i in batch])
  File "/mnt/batch/tasks/shared/LS_root/jobs/m8-brain-training/azureml/add_u1_to_input_1628935500_cae14635/wd/azureml/add_U1_to_input_1628935500_cae14635/parlai/core/worlds.py", line 1216, in handle_batch
    acts = self.world.get_model_agent().batch_act(batch)
  File "/mnt/batch/tasks/shared/LS_root/jobs/m8-brain-training/azureml/add_u1_to_input_1628935500_cae14635/wd/azureml/add_U1_to_input_1628935500_cae14635/parlai/core/torch_agent.py", line 2208, in batch_act
    output = self.eval_step(batch)
  File "/mnt/batch/tasks/shared/LS_root/jobs/m8-brain-training/azureml/add_u1_to_input_1628935500_cae14635/wd/azureml/add_U1_to_input_1628935500_cae14635/parlai/core/torch_generator_agent.py", line 900, in eval_step
    beam_texts[-1].append((self._v2t(tokens), score.item()))
  File "/mnt/batch/tasks/shared/LS_root/jobs/m8-brain-training/azureml/add_u1_to_input_1628935500_cae14635/wd/azureml/add_U1_to_input_1628935500_cae14635/parlai/core/torch_generator_agent.py", line 567, in _v2t
    return self.dict.vec2txt(new_vec)
  File "/mnt/batch/tasks/shared/LS_root/jobs/m8-brain-training/azureml/add_u1_to_input_1628935500_cae14635/wd/azureml/add_U1_to_input_1628935500_cae14635/parlai/core/dict.py", line 781, in vec2txt
    text = self.bpe.decode(tokens, vector, delimiter)
  File "/mnt/batch/tasks/shared/LS_root/jobs/m8-brain-training/azureml/add_u1_to_input_1628935500_cae14635/wd/azureml/add_U1_to_input_1628935500_cae14635/parlai/utils/bpe.py", line 236, in decode
    assert text.startswith(' ')
AssertionError

This error happens randomly, once during 1.50-1.75 epoch and next 0.50-0.75 epoch.
I wonder why I got the error like this 
           1. even though the training went through '1 epoch' and should have browsed all the data successfully at least one time
           2. even though my --dict_tokenizer is bytelevelbpe, not bpe

note:
Internally I modified  parlai/core/teachers.py class ParlAIDialogTeacher get() function
from
```
def get(self, episode_idx, entry_idx=None):
        return self.episodes[episode_idx][entry_idx]
```
to
```
def get(self, episode_idx, entry_idx=None):
        print('ParlAIDialogTeacher get()')
        print('this time the get of blended skill talk')
        print(self.episodes[episode_idx][entry_idx])
        d = self.episodes[episode_idx][entry_idx]
        d_text_list = d['text'].split('\n')
        if len(d_text_list) >= 3:
            d_text_list[-1] += ' [U1]'
            d_text_list[-2] += ' [U2]'
            d_text_list[-3] += ' [U1]'
            d.force_set('text', '\n'.join(d_text_list))
            d.force_set('labels', [d['labels'][0] + ' [U2]'])
        return d
```

What is the  cause of the error and how can it be solved?

Thank you so much

**Comment by stephenroller** [comment]
You _can_ just comment out the line throwing the exception but it usually indicates something is going wrong in the setup or the training -- bad dictionary or corrupted file somewhere or something. I know it's not helpful, but this thing is just a "sanity check"

If you add `--skip-generation True` you'll train faster and avoid this issue during training. You *could* still have it after training though.

**Comment by kazeto111** [comment]
Thank you so much!
Is there possibility that --dict_lower true --dict_tokenizer bytelevelbpe is not good for blended skill talk?

**Comment by stephenroller** [comment]
No, that's the right dictionary/tokenizer. I am not exactly sure what's happening. Perhaps train longer and see.

**Comment by kazeto111** [comment]
OK I will do so.
Thank you so much!
