### ISSUE TITLE
No module named 'parlai.zoo.bart.bart_large' with BlenderBot 2 interactive

### ISSUE THREAD

**Issue by pablogranolabar** [facebookresearch/ParlAI#3970]
Attempting to run BlenderBot 2 in interactive mode with:

```
python3 -m parlai interactive --model-file zoo:blenderbot2/blenderbot2_400M/model --search_server 127.0.0.1:9000
```

The following error occurs when downloading the BART weights:

```
[downloading BART models: /home/devel/ParlAI/data/models/bart]
Downloading bart.large.tar.gz: 0.00B [00:00, ?B/s]
Traceback (most recent call last):
  File "/home/devel/ParlAI/parlai/core/build_data.py", line 490, in modelzoo_path
    my_module = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'parlai.zoo.bart.bart_large'
```
All of the other model weights appear to download properly, and the 3B model appears to properly download the BART weights although I am getting OOM with BlenderBot2 3B even with a 16GB RTX 3080 so I haven't been able to run either yet.

**Comment by pablogranolabar** [comment]
Fixed by manually downloading the model checkpoints.

**Comment by dimitriosp** [comment]
> 

How did you loaded the checkpoints manually? I am having the same issue on my system. Fairseq v. 0.10.0 is installed
