### ISSUE TITLE
Could not find pretrained model in parlai.zoo.bart.bart_large or parlai.zoo.bart.build

### ISSUE THREAD

**Issue by Deepayan137** [facebookresearch/ParlAI#3975]
**Bug description**
Getting Import Error (Could not find pretrained model in parlai.zoo.bart.bart_large or parlai.zoo.bart.build. Please check your spelling and make sure you've pulled from master.) when trying to run the example invocation for BlenderBot2 400M mentioned in the ParlAI docs.

**Reproduction steps**
Copied the command mentioned in the docs
`parlai interactive -mf zoo:blenderbot2/blenderbot2_400M/model --search-server relevant_search_server
`

**Expected behavior**
Expected to launch the interactive chat.

**Logs**
Please paste the command line output:

```
Traceback (most recent call last):
  File "/Users/deep/opt/miniconda3/envs/parlai/bin/parlai", line 33, in <module>
    sys.exit(load_entry_point('parlai', 'console_scripts', 'parlai')())
  File "/Users/deep/Projects/ParlAI/parlai/__main__.py", line 14, in main
    superscript_main()
  File "/Users/deep/Projects/ParlAI/parlai/core/script.py", line 325, in superscript_main
    return SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "/Users/deep/Projects/ParlAI/parlai/core/script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "/Users/deep/Projects/ParlAI/parlai/scripts/interactive.py", line 118, in run
    return interactive(self.opt)
  File "/Users/deep/Projects/ParlAI/parlai/scripts/interactive.py", line 84, in interactive
    agent = create_agent(opt, requireModelExists=True)
  File "/Users/deep/Projects/ParlAI/parlai/core/agents.py", line 468, in create_agent
    model = create_agent_from_opt_file(opt)
  File "/Users/deep/Projects/ParlAI/parlai/core/agents.py", line 421, in create_agent_from_opt_file
    return model_class(opt_from_file)
  File "/Users/deep/Projects/ParlAI/parlai/agents/rag/rag.py", line 176, in __init__
    self._generation_agent.__init__(self, opt, shared)  # type: ignore
  File "/Users/deep/Projects/ParlAI/parlai/agents/bart/bart.py", line 72, in __init__
    super().__init__(opt, shared)
  File "/Users/deep/Projects/ParlAI/parlai/core/torch_generator_agent.py", line 484, in __init__
    self.model = fsdp_utils.fsdp_wrap(self.build_model())
  File "/Users/deep/Projects/ParlAI/projects/blenderbot2/agents/blenderbot2.py", line 885, in build_model
    model = BlenderBot2FidModel(self.opt, self.dict)
  File "/Users/deep/Projects/ParlAI/projects/blenderbot2/agents/modules.py", line 97, in __init__
    self.memory_decoder = MemoryDecoder(opt)
  File "/Users/deep/Projects/ParlAI/projects/blenderbot2/agents/sub_modules.py", line 281, in __init__
    base_agent = create_agent_from_model_file(
  File "/Users/deep/Projects/ParlAI/parlai/core/agents.py", line 347, in create_agent_from_model_file
    return create_agent_from_opt_file(opt)
  File "/Users/deep/Projects/ParlAI/parlai/core/agents.py", line 421, in create_agent_from_opt_file
    return model_class(opt_from_file)
  File "/Users/deep/Projects/ParlAI/parlai/agents/bart/bart.py", line 71, in __init__
    opt = self._initialize_bart(opt)
  File "/Users/deep/Projects/ParlAI/parlai/agents/bart/bart.py", line 97, in _initialize_bart
    compare_init_model_opts(opt, opt)
  File "/Users/deep/Projects/ParlAI/parlai/core/agents.py", line 273, in compare_init_model_opts
    opt['init_model'] = modelzoo_path(opt['datapath'], opt['init_model'])
  File "/Users/deep/Projects/ParlAI/parlai/core/build_data.py", line 501, in modelzoo_path
    raise ImportError(
ImportError: Could not find pretrained model in parlai.zoo.bart.bart_large or parlai.zoo.bart.build. Please check your spelling and make sure you've pulled from master.
```

**Additional context**
Add any other context about the problem here. (like proxy settings, network setup, overall goals, etc.)

**Comment by klshuster** [comment]
which pip version of parlai are you using? you may need to upgrade to the latest version

**Comment by adityaarun1** [comment]
@klshuster I am currently on `1.5.0`. I have also tried with the source build, but the error is there as well.

**Comment by klshuster** [comment]
if you've built from source, try running `python parlai/scripts/interactive.py`; there could be something wrong with your installation

**Comment by fabon** [comment]
interested in a fix for this one :)

**Comment by Deepayan137** [comment]
> if you've built from source, try running `python parlai/scripts/interactive.py`; there could be something wrong with your installation

Hi @klshuster, I uninstalled parlAI and built it from the source. However, I am still getting the same error. I am not sure whether it has something to do with the `--search-server` argument because currently, I am leaving it blank.

**Comment by stephenroller** [comment]
Can you try just `parlai interactive -m bart`? The bot should just echo after you?

**Comment by Deepayan137** [comment]
@stephenroller Thanks a lot. It seems to be working now. I had to install fairseq and that basically did the trick.
