### ISSUE TITLE
CUDA illegal memory access after encountering OOM error

### ISSUE THREAD

**Issue by renziver** [facebookresearch/ParlAI#4013]
I'm running a BB2 demo  using the interactive feature of ParlAI with the following command:

`parlai interactive -mf zoo:blenderbot2/blenderbot2_400M/model --search-server 0.0.0.0:8080 --loglevel debug`

and I encountered an OOM issue after several conversation lines with BB2, particularly on the processing of the search engine results. I'm using a VM w/ Tesla K80.

However, when I reran the command for the interactive demo, I'm encountering a new error with the following logs:

`
[BlenderBot2Fid]: I am doing well, thank you for asking. How about yourself? _POTENTIALLY_UNSAFE__
Enter Your Message: I'm good.
Traceback (most recent call last):
  File "/home/renz/venv/bin/parlai", line 11, in <module>
    load_entry_point('parlai', 'console_scripts', 'parlai')()
  File "/home/renz/ParlAI/parlai/__main__.py", line 14, in main
    superscript_main()
  File "/home/renz/ParlAI/parlai/core/script.py", line 325, in superscript_main
    return SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "/home/renz/ParlAI/parlai/core/script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "/home/renz/ParlAI/parlai/scripts/interactive.py", line 118, in run
    return interactive(self.opt)
  File "/home/renz/ParlAI/parlai/scripts/interactive.py", line 93, in interactive
    world.parley()
  File "/home/renz/ParlAI/parlai/tasks/interactive/worlds.py", line 89, in parley
    acts[1] = agents[1].act()
  File "/home/renz/ParlAI/parlai/core/torch_agent.py", line 2143, in act
    response = self.batch_act([self.observation])[0]
  File "/home/renz/ParlAI/parlai/core/torch_agent.py", line 2229, in batch_act
    batch = batch.to(0 if self.opt['gpu'] == -1 else self.opt['gpu'])
  File "/home/renz/ParlAI/parlai/core/torch_agent.py", line 185, in to
    output[key] = value.to(dev)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
`

It continues to occur even if I reset the cuda and nvidia drivers 

`
sudo rmmod nvidia_uvm
sudo modprobe nvidia_uvm
`

and the only way to make it work again is to restart the machine itself.

**Comment by renziver** [comment]
Issue address by upgrading torch into the nightly build.
`torch 1.9.0` -> `torch 1.10.0` 

See [discussion](https://github.com/pytorch/pytorch/issues/21819)
