### ISSUE TITLE
Error orrcured during interactivce_web mode on blended_skill_talk task

### ISSUE THREAD

**Issue by Arrivederci** [facebookresearch/ParlAI#4020]
When running
```python -m parlai.scripts.interactive_web -t blended_skill_talk --model-file "zoo:blender/blender_3B/model" --host 0.0.0.0 --port 4888```
I got this error
```
Traceback (most recent call last):
  File "/ssd5/exec/muyt/anaconda3/envs/dialog/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/ssd5/exec/muyt/anaconda3/envs/dialog/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/ssd5/exec/muyt/tools/ParlAI/parlai/scripts/interactive_web.py", line 306, in <module>
    InteractiveWeb.main()
  File "/ssd5/exec/muyt/tools/ParlAI/parlai/core/script.py", line 129, in main
    return cls._run_args(None)
  File "/ssd5/exec/muyt/tools/ParlAI/parlai/core/script.py", line 101, in _run_args
    return cls._run_from_parser_and_opt(opt, parser)
  File "/ssd5/exec/muyt/tools/ParlAI/parlai/core/script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "/ssd5/exec/muyt/tools/ParlAI/parlai/scripts/interactive_web.py", line 302, in run
    return interactive_web(self.opt)
  File "/ssd5/exec/muyt/tools/ParlAI/parlai/scripts/interactive_web.py", line 280, in interactive_web
    SHARED['world'] = create_task(SHARED.get('opt'), SHARED['agent'])
  File "/ssd5/exec/muyt/tools/ParlAI/parlai/core/worlds.py", line 1445, in create_task
    world = MultiWorld(opt, user_agents, default_world=default_world)
  File "/ssd5/exec/muyt/tools/ParlAI/parlai/core/worlds.py", line 556, in __init__
    create_task_world(
  File "/ssd5/exec/muyt/tools/ParlAI/parlai/core/worlds.py", line 1414, in create_task_world
    return world_class(opt, task_agents + user_agents)
  File "/ssd5/exec/muyt/tools/ParlAI/parlai/tasks/wizard_of_wikipedia/worlds.py", line 59, in __init__
    super().__init__(opt, agents, shared)
  File "/ssd5/exec/muyt/tools/ParlAI/parlai/core/worlds.py", line 340, in __init__
    raise RuntimeError('There must be exactly two agents for this world.')
RuntimeError: There must be exactly two agents for this world.
```
Does interactivce_web not support blended_skill_talk task yet ?

**Comment by stephenroller** [comment]
ah sorry, I believe last i checked, `interactive_web` didn't support the `-t` flag
