### ISSUE TITLE
BB2

### ISSUE THREAD

**Issue by SamsTheGreatest** [facebookresearch/ParlAI#4039]
**Bug description**
`RuntimeError: Received less data than specified in Content-Length header for http://dl.fbaipublicfiles.com/fairseq/models/bart.large.tar.gz. There may be a download problem.
Downloading bart.large.tar.gz:
`
get stuck at 4% and throws that error

**Reproduction steps**
`python -m parlai interactive --model-file zoo:blenderbot2/blenderbot2_400M/model --search_server http://0.0.0.0:8080`

**Logs**
```
14:23:53 | Using CUDA
14:23:53 | loading dictionary from /home/jovyan/anaconda3/envs/bb2/lib/python3.9/site-packages/data/models/blenderbot2/blenderbot2_400M/model.dict
14:23:53 | num words = 50264
14:23:54 | BlenderBot2Fid: full interactive mode on.14:24:10 | Creating the search engine retriever.
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.dense.weight', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
14:24:24 | Building Query Generator from file: /home/jovyan/anaconda3/envs/bb2/lib/python3.9/site-packages/data/models/blenderbot2/query_generator/model14:24:37 | Building Memory Decoder from file: /home/jovyan/anaconda3/envs/bb2/lib/python3.9/site-packages/data/models/blenderbot2/memory_decoder/model
[downloading BART models: /home/jovyan/anaconda3/envs/bb2/lib/python3.9/site-packages/data/models/bart]Downloading bart.large.tar.gz:   4%|██                                                 | 152M/3.70G [00:15<05:10, 11.4MB/s]Traceback (most recent call last):
  File "/home/jovyan/anaconda3/envs/bb2/lib/python3.9/site-packages/parlai/core/build_data.py", line 506, in modelzoo_path
    my_module = importlib.import_module(module_name)
  File "/home/jovyan/anaconda3/envs/bb2/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'parlai.zoo.bart.bart_large'

During handling of the above exception, another exception occurred:
...........
```

**Comment by mojtaba-komeili** [comment]
I have seen that error when one of the required modules was not installed. Could you `pip install fairseq transformer` and try again?

**Comment by SamsTheGreatest** [comment]
@mojtaba-komeili tried creating new conda env with `python3.7` and did `pip install fairseq transformers` as a first step, and then installed parlai from source (before I installed using `pip install parlai`), and same error occurs `bart.large.tar.gz`

**Comment by Guest400123064** [comment]
Same error! Any update is appreciated!

**Comment by mojtaba-komeili** [comment]
Another suggestion I have is deleting the temporary files where the models are downloaded (maybe there was a corrupted file during the download). You should be able to find the downloaded models under `data/models` directory of where your ParlAI source code is (assuming you installed from the Github repository).
