### ISSUE TITLE
BlenderBot2 - Self chat - no search -  KeyError: 'full_text'

### ISSUE THREAD

**Issue by louis030195** [facebookresearch/ParlAI#4202]
**Bug description**

I'm trying to run self-chat of BlenderBot2 on Google Colab, it fails.

**Reproduction steps**

```bash
echo "Hi, my name is Bob" >> foo.txt
echo "Hi, my name is Alice" >> foo.txt
```

```bash
!pip install parlai fairseq transformers
```

```bash
!parlai self_chat --model projects.blenderbot2.agents.blenderbot2:BlenderBot2FidAgent --model-file zoo:blenderbot2/blenderbot2_400M/model --task empathetic_dialogues --num-self-chats 1000 --display-examples True --knowledge_access_method "memory_only" --search_server None --seed_messages_from_file="./foo.txt" --outfile="./out"
```

**Expected behavior**

Run self chat using my messages as seed

**Logs**
Please paste the command line output:

```
/usr/local/lib/python3.7/dist-packages/nltk/twitter/__init__.py:20: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  warnings.warn("The twython library has not been installed. "
17:32:44 | Overriding opt["model_file"] to /root/ParlAI/data/models/blenderbot2/blenderbot2_400M/model (previously: /checkpoint/kshuster/projects/knowledge_bot/kbot_memfix_sweep25_Fri_Jul__9/338/model.oss)
17:32:44 | Overriding opt["task"] to empathetic_dialogues (previously: None)
17:32:44 | Overriding opt["knowledge_access_method"] to memory_only (previously: classify)
17:32:44 | Using CUDA
17:32:44 | loading dictionary from /root/ParlAI/data/models/blenderbot2/blenderbot2_400M/model.dict
17:32:44 | num words = 50264
17:32:44 | BlenderBot2Fid: full interactive mode on.
17:33:31 | Creating the search engine retriever.
17:33:31 | No protocol provided, using "http://"
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
17:34:23 | Building Query Generator from file: /root/ParlAI/data/models/blenderbot2/query_generator/model
17:34:56 | Building Memory Decoder from file: /root/ParlAI/data/models/blenderbot2/memory_decoder/model
17:35:26 | Total parameters: 732,961,280 (731,781,632 trainable)
17:35:26 | Loading existing model params from /root/ParlAI/data/models/blenderbot2/blenderbot2_400M/model
17:36:39 | Agent 1 Opt:
17:36:39 |     activation: gelu
17:36:39 |     adafactor_eps: '[1e-30, 0.001]'
17:36:39 |     adam_eps: 1e-08
17:36:39 |     add_p1_after_newln: False
17:36:39 |     allow_missing_init_opts: False
17:36:39 |     attention_dropout: 0.1
17:36:39 |     batchsize: 12
17:36:39 |     beam_block_full_context: False
17:36:39 |     beam_block_list_filename: None
17:36:39 |     beam_block_ngram: 3
17:36:39 |     beam_context_block_ngram: 3
17:36:39 |     beam_delay: 30
17:36:39 |     beam_length_penalty: 0.65
17:36:39 |     beam_min_length: 20
17:36:39 |     beam_size: 10
17:36:39 |     betas: '[0.9, 0.999]'
17:36:39 |     bpe_add_prefix_space: None
17:36:39 |     bpe_debug: False
17:36:39 |     bpe_dropout: None
17:36:39 |     bpe_merge: None
17:36:39 |     bpe_vocab: None
17:36:39 |     candidates: inline
17:36:39 |     cap_num_predictions: 100
17:36:39 |     checkpoint_activations: False
17:36:39 |     codes_attention_num_heads: 4
17:36:39 |     codes_attention_type: basic
17:36:39 |     compressed_indexer_factory: IVF4096_HNSW128,PQ128
17:36:39 |     compressed_indexer_gpu_train: False
17:36:39 |     compressed_indexer_nprobe: 64
17:36:39 |     compute_tokenized_bleu: False
17:36:39 |     converting: False
17:36:39 |     data_parallel: False
17:36:39 |     datapath: /root/ParlAI/data
17:36:39 |     datatype: train:stream
17:36:39 |     delimiter: '\n'
17:36:39 |     dict_class: parlai.core.dict:DictionaryAgent
17:36:39 |     dict_endtoken: __end__
17:36:39 |     dict_file: /root/ParlAI/data/models/blenderbot2/blenderbot2_400M/model.dict
17:36:39 |     dict_initpath: None
17:36:39 |     dict_language: english
17:36:39 |     dict_loaded: True
17:36:39 |     dict_lower: False
17:36:39 |     dict_max_ngram_size: -1
17:36:39 |     dict_maxtokens: -1
17:36:39 |     dict_minfreq: 0
17:36:39 |     dict_nulltoken: __null__
17:36:39 |     dict_starttoken: __start__
17:36:39 |     dict_textfields: text,labels
17:36:39 |     dict_tokenizer: gpt2
17:36:39 |     dict_unktoken: __unk__
17:36:39 |     display_add_fields: 
17:36:39 |     display_examples: True
17:36:39 |     doc_chunk_split_mode: word
17:36:39 |     doc_chunks_ranker: head
17:36:39 |     download_path: None
17:36:39 |     dpr_model_file: zoo:hallucination/bart_rag_token/model
17:36:39 |     dpr_num_docs: 25
17:36:39 |     dropout: 0.1
17:36:39 |     dynamic_batching: None
17:36:39 |     embedding_projection: random
17:36:39 |     embedding_size: 1024
17:36:39 |     embedding_type: random
17:36:39 |     embeddings_scale: True
17:36:39 |     encode_candidate_vecs: True
17:36:39 |     encode_candidate_vecs_batchsize: 256
17:36:39 |     eval_candidates: inline
17:36:39 |     ffn_size: 4096
17:36:39 |     fixed_candidate_vecs: reuse
17:36:39 |     fixed_candidates_path: None
17:36:39 |     force_fp16_tokens: True
17:36:39 |     fp16: False
17:36:39 |     fp16_impl: safe
17:36:39 |     generation_model: bart
17:36:39 |     gold_document_key: __selected-docs__
17:36:39 |     gold_document_titles_key: select-docs-titles
17:36:39 |     gold_knowledge_passage_key: checked_sentence
17:36:39 |     gold_knowledge_title_key: title
17:36:39 |     gold_sentence_key: __selected-sentences__
17:36:39 |     gpu: -1
17:36:39 |     gradient_clip: 0.1
17:36:39 |     hide_labels: False
17:36:39 |     history_add_global_end_token: None
17:36:39 |     history_reversed: False
17:36:39 |     history_size: -1
17:36:39 |     hnsw_ef_construction: 200
17:36:39 |     hnsw_ef_search: 128
17:36:39 |     hnsw_indexer_store_n: 128
17:36:39 |     ignore_bad_candidates: False
17:36:39 |     image_cropsize: 224
17:36:39 |     image_mode: raw
17:36:39 |     image_size: 256
17:36:39 |     indexer_buffer_size: 65536
17:36:39 |     indexer_type: compressed
17:36:39 |     inference: beam
17:36:39 |     init_fairseq_model: None
17:36:39 |     init_model: None
17:36:39 |     init_opt: None
17:36:39 |     insert_gold_docs: True
17:36:39 |     interactive_candidates: fixed
17:36:39 |     interactive_mode: True
17:36:39 |     invsqrt_lr_decay_gamma: -1
17:36:39 |     is_debug: False
17:36:39 |     knowledge_access_method: memory_only
17:36:39 |     label_truncate: 128
17:36:39 |     learn_embeddings: True
17:36:39 |     learn_positional_embeddings: True
17:36:39 |     learningrate: 1e-05
17:36:39 |     log_keep_fields: all
17:36:39 |     loglevel: info
17:36:39 |     lr_scheduler: reduceonplateau
17:36:39 |     lr_scheduler_decay: 0.5
17:36:39 |     lr_scheduler_patience: 1
17:36:39 |     max_doc_token_length: 256
17:36:39 |     memory_attention: sqrt
17:36:39 |     memory_decoder_beam_min_length: 10
17:36:39 |     memory_decoder_beam_size: 3
17:36:39 |     memory_decoder_delimiter: '\n'
17:36:39 |     memory_decoder_ignore_phrase: persona:
17:36:39 |     memory_decoder_key: full_text
17:36:39 |     memory_decoder_model_file: zoo:blenderbot2/memory_decoder/model
17:36:39 |     memory_decoder_one_line_memories: False
17:36:39 |     memory_decoder_truncate: -1
17:36:39 |     memory_doc_delimiter: :
17:36:39 |     memory_doc_title_delimiter: ' / '
17:36:39 |     memory_extractor_phrase: persona:
17:36:39 |     memory_key: personas
17:36:39 |     memory_reader_model: None
17:36:39 |     memory_retriever_truncate: -1
17:36:39 |     memory_writer_model: bert
17:36:39 |     memory_writer_model_file: zoo:hallucination/multiset_dpr/hf_bert_base.cp
17:36:39 |     min_doc_token_length: 64
17:36:39 |     model: projects.blenderbot2.agents.blenderbot2:BlenderBot2FidAgent
17:36:39 |     model_file: /root/ParlAI/data/models/blenderbot2/blenderbot2_400M/model
17:36:39 |     model_parallel: True
17:36:39 |     momentum: 0
17:36:39 |     multitask_weights: '[3.0, 1.0, 1.0, 1.0, 3.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]'
17:36:39 |     mutators: None
17:36:39 |     n_decoder_layers: 12
17:36:39 |     n_docs: 5
17:36:39 |     n_encoder_layers: 12
17:36:39 |     n_extra_positions: 0
17:36:39 |     n_heads: 16
17:36:39 |     n_layers: 12
17:36:39 |     n_positions: 1024
17:36:39 |     n_ranked_doc_chunks: 1
17:36:39 |     n_segments: 0
17:36:39 |     nesterov: True
17:36:39 |     no_cuda: False
17:36:39 |     normalize_sent_emb: False
17:36:39 |     num_self_chats: 1000
17:36:39 |     nus: [0.7]
17:36:39 |     optimizer: adamax
17:36:39 |     outfile: ./out
17:36:39 |     output_conversion_path: None
17:36:39 |     output_scaling: 1.0
17:36:39 |     override: "{'model': 'projects.blenderbot2.agents.blenderbot2:BlenderBot2FidAgent', 'model_file': '/root/ParlAI/data/models/blenderbot2/blenderbot2_400M/model', 'task': 'empathetic_dialogues', 'num_self_chats': 1000, 'display_examples': True, 'knowledge_access_method': 'memory_only', 'search_server': 'None'}"
17:36:39 |     parlai_home: /private/home/kshuster/ParlAI
17:36:39 |     partner_model_file: None
17:36:39 |     partner_opt_file: None
17:36:39 |     path_to_dense_embeddings: None
17:36:39 |     path_to_dpr_passages: zoo:hallucination/wiki_passages/psgs_w100.tsv
17:36:39 |     path_to_index: zoo:hallucination/wiki_index_compressed/compressed_pq
17:36:39 |     person_tokens: False
17:36:39 |     poly_attention_num_heads: 4
17:36:39 |     poly_attention_type: basic
17:36:39 |     poly_faiss_model_file: None
17:36:39 |     poly_n_codes: 64
17:36:39 |     poly_score_initial_lambda: 0.5
17:36:39 |     polyencoder_init_model: wikito
17:36:39 |     polyencoder_type: codes
17:36:39 |     print_docs: False
17:36:39 |     query_generator_beam_min_length: 2
17:36:39 |     query_generator_beam_size: 1
17:36:39 |     query_generator_delimiter: '\n'
17:36:39 |     query_generator_ignore_phrase: persona:
17:36:39 |     query_generator_inference: beam
17:36:39 |     query_generator_key: full_text
17:36:39 |     query_generator_model_file: zoo:blenderbot2/query_generator/model
17:36:39 |     query_generator_truncate: -1
17:36:39 |     query_model: bert_from_parlai_rag
17:36:39 |     rag_model_type: token
17:36:39 |     rag_query_truncate: 512
17:36:39 |     rag_retriever_query: full_history
17:36:39 |     rag_retriever_type: search_engine
17:36:39 |     rag_turn_discount_factor: 1.0
17:36:39 |     rag_turn_marginalize: doc_then_turn
17:36:39 |     rag_turn_n_turns: 2
17:36:39 |     rank_candidates: False
17:36:39 |     rank_top_k: -1
17:36:39 |     reduction_type: mean
17:36:39 |     regret: False
17:36:39 |     regret_dict_file: None
17:36:39 |     regret_intermediate_maxlen: 32
17:36:39 |     regret_model_file: None
17:36:39 |     regret_override_index: False
17:36:39 |     relu_dropout: 0.0
17:36:39 |     remove_political_convos: False
17:36:39 |     repeat_blocking_heuristic: True
17:36:39 |     retriever_debug_index: None
17:36:39 |     retriever_delimiter: '\n'
17:36:39 |     retriever_embedding_size: 768
17:36:39 |     retriever_ignore_phrase: persona:
17:36:39 |     return_cand_scores: False
17:36:39 |     save_format: conversations
17:36:39 |     search_query_generator_beam_min_length: 2
17:36:39 |     search_query_generator_beam_size: 1
17:36:39 |     search_query_generator_inference: greedy
17:36:39 |     search_query_generator_model_file: zoo:blenderbot2/query_generator/model
17:36:39 |     search_query_generator_text_truncate: 512
17:36:39 |     search_server: None
17:36:39 |     seed: 42
17:36:39 |     seed_messages_from_file: ./all3.txt
17:36:39 |     seed_messages_from_task: False
17:36:39 |     selfchat_max_turns: 6
17:36:39 |     selfchat_task: True
17:36:39 |     share_encoders: True
17:36:39 |     share_search_and_memory_query_encoder: False
17:36:39 |     share_word_embeddings: True
17:36:39 |     skip_generation: False
17:36:39 |     skip_retrieval_token: no_passages_used
17:36:39 |     special_tok_lst: None
17:36:39 |     split_lines: True
17:36:39 |     splitted_chunk_length: 256
17:36:39 |     starttime: Jul09_14-09
17:36:39 |     t5_dropout: 0.0
17:36:39 |     t5_generation_config: None
17:36:39 |     t5_model_arch: t5-base
17:36:39 |     t5_model_parallel: False
17:36:39 |     task: empathetic_dialogues
17:36:39 |     temperature: 1.0
17:36:39 |     text_truncate: 512
17:36:39 |     tfidf_max_doc_paragraphs: -1
17:36:39 |     tfidf_model_path: zoo:wikipedia_full/tfidf_retriever/model
17:36:39 |     thorough: False
17:36:39 |     topk: 10
17:36:39 |     topp: 0.9
17:36:39 |     train_experiencer_only: False
17:36:39 |     train_predict: False
17:36:39 |     truncate: 512
17:36:39 |     update_freq: 1
17:36:39 |     use_memories: False
17:36:39 |     use_reply: label
17:36:39 |     variant: prelayernorm
17:36:39 |     verbose: False
17:36:39 |     warmup_rate: 0.0001
17:36:39 |     warmup_updates: -1
17:36:39 |     weight_decay: None
17:36:39 |     wrap_memory_encoder: False
17:36:40 | Current ParlAI commit: 4b1d07d0eeb14f849ad930eeb001327f9bfc2db1
17:36:40 | creating task(s): empathetic_dialogues
Traceback (most recent call last):
  File "/usr/local/bin/parlai", line 33, in <module>
    sys.exit(load_entry_point('parlai', 'console_scripts', 'parlai')())
  File "/root/ParlAI/parlai/__main__.py", line 14, in main
    superscript_main()
  File "/root/ParlAI/parlai/core/script.py", line 325, in superscript_main
    return SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "/root/ParlAI/parlai/core/script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "/root/ParlAI/parlai/scripts/self_chat.py", line 176, in run
    return self_chat(self.opt)
  File "/root/ParlAI/parlai/scripts/self_chat.py", line 146, in self_chat
    _run_self_chat_episode(opt, world, logger)
  File "/root/ParlAI/parlai/scripts/self_chat.py", line 93, in _run_self_chat_episode
    world.parley()
  File "/root/ParlAI/parlai/tasks/self_chat/worlds.py", line 174, in parley
    self.agents[i].observe({'episode_done': False})
  File "/root/ParlAI/projects/blenderbot2/agents/blenderbot2.py", line 442, in observe
    observation = super().observe(observation)
  File "/root/ParlAI/parlai/agents/rag/rag.py", line 292, in observe
    self._set_query_vec(observation)
  File "/root/ParlAI/projects/blenderbot2/agents/blenderbot2.py", line 502, in _set_query_vec
    query_str = observation[self._query_key]
KeyError: 'full_text'
```

**Additional context**

Running in Google Colab with GPU on.

```bash
!parlai --version
# ParlAI version 1.5.1
```

**Comment by klshuster** [comment]
Thanks for flagging, fix is up in #4207
