### ISSUE TITLE
Size mismatch error on training a simple sequence to sequence model

### ISSUE THREAD

**Issue by ymihay** [facebookresearch/ParlAI#424]
Hi there,

I've receive an error when running code described in examples:
`python train_model.py -m seq2seq -t babi:task1k:1 -bs 8 -e 1 -mf /tmp/model_s2s`:

Error log:
`/Users/yanamikhaylenko/miniconda3/lib/python3.6/site-packages/torch/autograd/_functions/basic_ops.py:48: UserWarning: self and other not broadcastable, but have the same number of elements.  Falling back to deprecated pointwise behavior.
  return a.mul(b)
Traceback (most recent call last):
  File "train_model.py", line 255, in <module>
    TrainLoop(setup_args()).train()
  File "train_model.py", line 220, in train
    world.parley()
  File "/Users/yanamikhaylenko/PycharmProjects/ParlAI/parlai/core/worlds.py", line 605, in parley
    batch_act = self.batch_act(agent_idx, batch_observations[agent_idx])
  File "/Users/yanamikhaylenko/PycharmProjects/ParlAI/parlai/core/worlds.py", line 578, in batch_act
    batch_actions = a.batch_act(batch_observation)
  File "/Users/yanamikhaylenko/PycharmProjects/ParlAI/parlai/agents/seq2seq/seq2seq.py", line 506, in batch_act
    predictions, text_cand_inds, loss = self.predict(xs, ys, cands, valid_cands)
  File "/Users/yanamikhaylenko/PycharmProjects/ParlAI/parlai/agents/seq2seq/seq2seq.py", line 351, in predict
    predictions, scores, _ = self.model(xs, ys)
  File "/Users/yanamikhaylenko/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/yanamikhaylenko/PycharmProjects/ParlAI/parlai/agents/seq2seq/modules.py", line 74, in forward
    preds, score = self.decoder(xs, hidden, enc_out, attn_mask)
  File "/Users/yanamikhaylenko/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/yanamikhaylenko/PycharmProjects/ParlAI/parlai/agents/seq2seq/modules.py", line 218, in forward
    output, hidden = self.rnn(xes, hidden)
  File "/Users/yanamikhaylenko/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/yanamikhaylenko/miniconda3/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 162, in forward
    output, hidden = func(input, self.all_weights, hx)
  File "/Users/yanamikhaylenko/miniconda3/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 351, in forward
    return func(input, *fargs, **fkwargs)
  File "/Users/yanamikhaylenko/miniconda3/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 244, in forward
    nexth, output = func(input, hidden, weight)
  File "/Users/yanamikhaylenko/miniconda3/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 84, in forward
    hy, output = inner(input, hidden[l], weight[l])
  File "/Users/yanamikhaylenko/miniconda3/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 113, in forward
    hidden = inner(input[i], hidden, *weight)
  File "/Users/yanamikhaylenko/miniconda3/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 31, in LSTMCell
    gates = F.linear(input, w_ih, b_ih) + F.linear(hx, w_hh, b_hh)
  File "/Users/yanamikhaylenko/miniconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 555, in linear
    output = input.matmul(weight.t())
  File "/Users/yanamikhaylenko/miniconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 560, in matmul
    return torch.matmul(self, other)
  File "/Users/yanamikhaylenko/miniconda3/lib/python3.6/site-packages/torch/functional.py", line 191, in matmul
    output = torch.mm(tensor1, tensor2)
  File "/Users/yanamikhaylenko/miniconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 579, in mm
    return Addmm.apply(output, self, matrix, 0, 1, True)
  File "/Users/yanamikhaylenko/miniconda3/lib/python3.6/site-packages/torch/autograd/_functions/blas.py", line 26, in forward
    matrix1, matrix2, out=output)
RuntimeError: size mismatch, m1: [2 x 512], m2: [128 x 512] at /Users/soumith/code/builder/wheel/pytorch-src/torch/lib/TH/generic/THTensorMath.c:1293
`

**Comment by alexholdenmiller** [comment]
Hi @ymihay, I don't get any errors running that. Which version of pytorch are you using? (`import torch; torch.__version__`)

**Comment by ymihay** [comment]
Nice catch, @alexholdenmiller! I reproduced this issue with pytorch version 0.2.0_3. But I switched to version 0.3.0.post4, which was released yesterday. And this error disappeared.
Thank you!

**Comment by alexholdenmiller** [comment]
Okay great--thanks for flagging!
