### ISSUE TITLE
Error when training T5 RAG model

### ISSUE THREAD

**Issue by thies1006** [facebookresearch/ParlAI#4280]
When running the command (from 'hallucination' project page):
`parlai train_model --model rag --task wizard_of_wikipedia --rag-model-type turn --rag-turn-marginalize doc_then_turn --rag-retriever-type dpr --generation-model t5 --t5-model-arch t5-large --batchsize 8 --fp16 True --gradient-clip 0.1 --label-truncate 128 --log-every-n-secs 30 --lr-scheduler reduceonplateau --lr-scheduler-patience 1 --model-parallel True --optimizer adam --text-truncate 512 --truncate 512 --learningrate 1e-05 --validation-metric-mode min --validation-every-n-epochs 0.25 --validation-max-exs 1000 --validation-metric ppl --validation-patience 5 --model-file /tmp/model`

I get this error
`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!`

I tried on different machines with different number of GPUs and different version of HF, but I always get this error.
pytorch version is 1.8.1.

[log.txt](https://github.com/facebookresearch/ParlAI/files/7795879/log.txt)

**Comment by stephenroller** [comment]
Can you give the full traceback?

**Comment by thies1006** [comment]
Sure!

2021-12-31 11:03:15,940 INFO     | Current fb commit: 339a29eaff8da90d9e87ff8c72a21475cf768b89
2021-12-31 11:03:15,941 INFO     | creating task(s): wizard_of_wikipedia
loading: /tertiary/thies/ParlAI/data/wizard_of_wikipedia/train.json
2021-12-31 11:03:30,945 WARNING  | Some data not being used. If you are not trying to reproduce the previous results, it is recommended that you run with the flag --add-missing-turns train or --add-missing-turns all.
2021-12-31 11:03:47,508 INFO     | training...
Traceback (most recent call last):
  File "/secondary/thies/.virtualenvs/parlai/bin/parlai", line 8, in <module>
    sys.exit(main())
  File "/tertiary/thies/ParlAI/parlai/__main__.py", line 14, in main
    superscript_main()
  File "/tertiary/thies/ParlAI/parlai/core/script.py", line 325, in superscript_main
    return SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "/tertiary/thies/ParlAI/parlai/core/script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "/tertiary/thies/ParlAI/parlai/scripts/train_model.py", line 998, in run
    return self.train_loop.train()
  File "/tertiary/thies/ParlAI/parlai/scripts/train_model.py", line 950, in train
    for _train_log in self.train_steps():
  File "/tertiary/thies/ParlAI/parlai/scripts/train_model.py", line 857, in train_steps
    world.parley()
  File "/tertiary/thies/ParlAI/parlai/core/worlds.py", line 873, in parley
    batch_act = self.batch_act(agent_idx, batch_observations[agent_idx])
  File "/tertiary/thies/ParlAI/parlai/core/worlds.py", line 841, in batch_act
    batch_actions = a.batch_act(batch_observation)
  File "/tertiary/thies/ParlAI/parlai/core/torch_agent.py", line 2235, in batch_act
    output = self.train_step(batch)
  File "/tertiary/thies/ParlAI/parlai/core/torch_generator_agent.py", line 749, in train_step
    raise e
  File "/tertiary/thies/ParlAI/parlai/core/torch_generator_agent.py", line 734, in train_step
    loss = self.compute_loss(batch)
  File "/tertiary/thies/ParlAI/parlai/agents/rag/rag.py", line 909, in compute_loss
    model_output = self.get_model_output(batch)
  File "/tertiary/thies/ParlAI/parlai/agents/rag/rag.py", line 881, in get_model_output
    model_output = self.model(
  File "/secondary/thies/.virtualenvs/parlai/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/tertiary/thies/ParlAI/parlai/core/torch_generator_agent.py", line 309, in forward
    encoder_states = prev_enc if prev_enc is not None else self.encoder(*xs)
  File "/tertiary/thies/ParlAI/parlai/agents/rag/modules.py", line 185, in encoder
    tensor, mask = self.seq2seq_encoder(
  File "/secondary/thies/.virtualenvs/parlai/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/tertiary/thies/ParlAI/parlai/agents/hugging_face/t5.py", line 59, in wrap
    ret = func(*args, **kwargs)
  File "/tertiary/thies/ParlAI/parlai/agents/hugging_face/t5.py", line 236, in forward
    outputs = self.stack(input, attention_mask=mask, output_hidden_states=False)
  File "/secondary/thies/.virtualenvs/parlai/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/secondary/thies/.virtualenvs/parlai/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 1008, in forward
    layer_outputs = layer_module(
  File "/secondary/thies/.virtualenvs/parlai/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/secondary/thies/.virtualenvs/parlai/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 643, in forward
    self_attention_outputs = self.layer[0](
  File "/secondary/thies/.virtualenvs/parlai/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/secondary/thies/.virtualenvs/parlai/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 549, in forward
    normed_hidden_states = self.layer_norm(hidden_states)
  File "/secondary/thies/.virtualenvs/parlai/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/secondary/thies/.virtualenvs/parlai/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 252, in forward
    return self.weight * hidden_states
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!

**Comment by stephenroller** [comment]
Which version of transformers are you using?

**Comment by thies1006** [comment]
I tried 4.15 and 4.9.

**Comment by klshuster** [comment]
Can you try specifying `--t5-model-parallel True`?

**Comment by thies1006** [comment]
Thank you @klshuster! I added this option and now it works.
