### ISSUE TITLE
ModuleNotFoundError: No module named 'parlai_internal' on Interactive mode

### ISSUE THREAD

**Issue by evelynkyl** [facebookresearch/ParlAI#4373]
**Bug description**
When using 'zoo:blended_skill_talk/multi_task_bst_tuned/model', it returns ModuleNotFoundError: No module named 'parlai_internal'

**Reproduction steps**
```parlai interactive -mf zoo:blended_skill_talk/multi_task_bst_tuned/model -t blended_skill_talk```

**Expected behavior**
be able to use the interactive mode

**Logs**
Please paste the command line output:

```
13:30:19 | Using CUDA
13:30:19 | loading dictionary from /home/evelyn/ParlAI/data/models/blended_skill_talk/multi_task_bst_tuned/model.dict
13:30:19 | num words = 54944
13:30:19 | Polyencoder: full interactive mode on.
13:30:19 | Building candidates file as they do not exist: /home/evelyn/ParlAI/data/models/blended_skill_talk/multi_task_bst_tuned/model.cands-parlai_internal.tasks.all_in_one.agents:AllInOneDialogueTeacher.cands
13:30:19 | Opt:
13:30:19 |     activation: gelu
13:30:19 |     adafactor_eps: '(1e-30, 0.001)'
13:30:19 |     adam_eps: 1e-08
13:30:19 |     add_p1_after_newln: False
13:30:19 |     aggregate_micro: False
13:30:19 |     allow_missing_init_opts: False
13:30:19 |     attention_dropout: 0.1
13:30:19 |     batch_length_range: 5
13:30:19 |     batch_sort_cache_type: pop
13:30:19 |     batch_sort_field: text
13:30:19 |     batchsize: 1
13:30:19 |     betas: '[0.9, 0.999]'
13:30:19 |     bpe_add_prefix_space: None
13:30:19 |     bpe_debug: False
13:30:19 |     bpe_dropout: None
13:30:19 |     bpe_merge: None
13:30:19 |     bpe_vocab: None
13:30:19 |     candidates: batch
13:30:19 |     cap_num_predictions: 100
13:30:19 |     checkpoint_activations: False
13:30:19 |     codes_attention_num_heads: 4
13:30:19 |     codes_attention_type: basic
13:30:19 |     data_parallel: True
13:30:19 |     datapath: /home/evelyn/ParlAI/data
13:30:19 |     datatype: train:evalmode
13:30:19 |     delimiter: '\n'
13:30:19 |     dict_class: parlai.core.dict:DictionaryAgent
13:30:19 |     dict_endtoken: __start__
13:30:19 |     dict_file: /home/evelyn/ParlAI/data/models/blended_skill_talk/multi_task_bst_tuned/model.dict
13:30:19 |     dict_include_test: False
13:30:19 |     dict_include_valid: False
13:30:19 |     dict_initpath: None
13:30:19 |     dict_language: english
13:30:19 |     dict_loaded: True
13:30:19 |     dict_lower: True
13:30:19 |     dict_max_ngram_size: -1
13:30:19 |     dict_maxexs: -1
13:30:19 |     dict_maxtokens: -1
13:30:19 |     dict_minfreq: 0
13:30:19 |     dict_nulltoken: __null__
13:30:19 |     dict_starttoken: __start__
13:30:19 |     dict_textfields: text,labels
13:30:19 |     dict_tokenizer: bpe
13:30:19 |     dict_unktoken: __unk__
13:30:19 |     display_add_fields: 
13:30:19 |     display_examples: False
13:30:19 |     display_partner_persona: True
13:30:19 |     display_prettify: False
13:30:19 |     download_path: None
13:30:19 |     dropout: 0.15
13:30:19 |     dynamic_batching: None
13:30:19 |     embedding_projection: random
13:30:19 |     embedding_size: 768
13:30:19 |     embedding_type: random
13:30:19 |     embeddings_scale: False
13:30:19 |     encode_candidate_vecs: True
13:30:19 |     encode_candidate_vecs_batchsize: 256
13:30:19 |     eval_batchsize: 16
13:30:19 |     eval_candidates: inline
13:30:19 |     evaltask: None
13:30:19 |     ffn_size: 3072
13:30:19 |     fixed_candidate_vecs: reuse
13:30:19 |     fixed_candidates_path: None
13:30:19 |     force_fp16_tokens: True
13:30:19 |     fp16: True
13:30:19 |     fp16_impl: safe
13:30:19 |     gpu: -1
13:30:19 |     gradient_clip: 0.1
13:30:19 |     hide_labels: False
13:30:19 |     history_add_global_end_token: None
13:30:19 |     history_reversed: False
13:30:19 |     history_size: 20
13:30:19 |     ignore_bad_candidates: False
13:30:19 |     image_cropsize: 224
13:30:19 |     image_mode: raw
13:30:19 |     image_size: 256
13:30:19 |     include_initial_utterances: False
13:30:19 |     include_personas: True
13:30:19 |     inference: max
13:30:19 |     init_model: /checkpoint/marywilliamson/all_in_one_dialogue/scripts/multitask_sweep_20191203/003/fb1_jobid=1/model
13:30:19 |     init_opt: None
13:30:19 |     interactive_candidates: fixed
13:30:19 |     interactive_mode: True
13:30:19 |     interactive_task: False
13:30:19 |     invsqrt_lr_decay_gamma: -1
13:30:19 |     is_debug: False
13:30:19 |     label_truncate: 72
13:30:19 |     learn_embeddings: True
13:30:19 |     learn_positional_embeddings: True
13:30:19 |     learningrate: 3e-06
13:30:19 |     local_human_candidates_file: None
13:30:19 |     log_every_n_secs: 20.0
13:30:19 |     log_keep_fields: all
13:30:19 |     loglevel: info
13:30:19 |     lr_scheduler: reduceonplateau
13:30:19 |     lr_scheduler_decay: 0.65
13:30:19 |     lr_scheduler_patience: 1
13:30:19 |     max_train_time: 200000.0
13:30:19 |     memory_attention: sqrt
13:30:19 |     metrics: default
13:30:19 |     model: transformer/polyencoder
13:30:19 |     model_file: /home/evelyn/ParlAI/data/models/blended_skill_talk/multi_task_bst_tuned/model
13:30:19 |     model_parallel: False
13:30:19 |     momentum: 0
13:30:19 |     multitask_weights: [1]
13:30:19 |     mutators: None
13:30:19 |     n_decoder_layers: -1
13:30:19 |     n_encoder_layers: -1
13:30:19 |     n_heads: 12
13:30:19 |     n_layers: 12
13:30:19 |     n_positions: 1024
13:30:19 |     n_segments: 2
13:30:19 |     nesterov: True
13:30:19 |     no_cuda: False
13:30:19 |     normalize_sent_emb: False
13:30:19 |     num_epochs: 50.0
13:30:19 |     numthreads: 1
13:30:19 |     numworkers: 4
13:30:19 |     nus: [0.7]
13:30:19 |     optimizer: adamax
13:30:19 |     outfile: /home/evelyn/ParlAI/data/models/blended_skill_talk/multi_task_bst_tuned/model.cands-parlai_internal.tasks.all_in_one.agents:AllInOneDialogueTeacher.cands
13:30:19 |     output_scaling: 0.04
13:30:19 |     override: {}
13:30:19 |     parlai_home: /checkpoint/marywilliamson/all_in_one_dialogue/scripts/multitask_ft_aio_20191205/001/ParlAI
13:30:19 |     person_tokens: False
13:30:19 |     poly_attention_num_heads: 4
13:30:19 |     poly_attention_type: basic
13:30:19 |     poly_n_codes: 300
13:30:19 |     polyencoder_type: n_first
13:30:19 |     pytorch_context_length: -1
13:30:19 |     pytorch_datapath: None
13:30:19 |     pytorch_include_labels: True
13:30:19 |     pytorch_preprocess: False
13:30:19 |     pytorch_teacher_batch_sort: False
13:30:19 |     pytorch_teacher_dataset: None
13:30:19 |     pytorch_teacher_task: None
13:30:19 |     rank_candidates: True
13:30:19 |     rank_top_k: -1
13:30:19 |     reduction_type: first
13:30:19 |     relu_dropout: 0.1
13:30:19 |     repeat_blocking_heuristic: True
13:30:19 |     return_cand_scores: False
13:30:19 |     safe_personas_only: True
13:30:19 |     save_after_valid: True
13:30:19 |     save_every_n_secs: -1
13:30:19 |     save_format: conversations
13:30:19 |     share_encoders: False
13:30:19 |     share_word_embeddings: True
13:30:19 |     short_final_eval: False
13:30:19 |     show_advanced_args: False
13:30:19 |     shuffle: True
13:30:19 |     single_turn: False
13:30:19 |     special_tok_lst: None
13:30:19 |     split_lines: False
13:30:19 |     starttime: Dec05_08-40
13:30:19 |     task: parlai_internal.tasks.all_in_one.agents:AllInOneDialogueTeacher
13:30:19 |     tensorboard_log: False
13:30:19 |     text_truncate: 360
13:30:19 |     topk: 5
13:30:19 |     train_predict: False
13:30:19 |     truncate: 1024
13:30:19 |     update_freq: 1
13:30:19 |     use_memories: False
13:30:19 |     use_reply: label
13:30:19 |     validation_cutoff: 1.0
13:30:19 |     validation_every_n_epochs: 0.5
13:30:19 |     validation_every_n_secs: -1
13:30:19 |     validation_max_exs: 8000
13:30:19 |     validation_metric: accuracy
13:30:19 |     validation_metric_mode: max
13:30:19 |     validation_patience: 10
13:30:19 |     validation_share_agent: False
13:30:19 |     variant: xlm
13:30:19 |     verbose: False
13:30:19 |     warmup_rate: 0.0001
13:30:19 |     warmup_updates: 100
13:30:19 |     weight_decay: None
13:30:19 |     wrap_memory_encoder: False
13:30:19 | Current ParlAI commit: 3cdf65add3242d91ff90ef55649e6fceec89d6cf
13:30:19 | Current internal commit: 3cdf65add3242d91ff90ef55649e6fceec89d6cf
13:30:19 | Current fb commit: 3cdf65add3242d91ff90ef55649e6fceec89d6cf
13:30:19 | creating task(s): parlai_internal.tasks.all_in_one.agents:AllInOneDialogueTeacher
Traceback (most recent call last):
  File "/home/evelyn/ParlAI/parlai/core/worlds.py", line 1389, in _create_task_agents
    my_module = load_task_module(opt['task'])
  File "/home/evelyn/ParlAI/parlai/core/loader.py", line 247, in load_task_module
    task_module = importlib.import_module(module_name)
  File "/home/evelyn/miniconda3/envs/baseline/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'parlai_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/evelyn/miniconda3/envs/baseline/bin/parlai", line 33, in <module>
    sys.exit(load_entry_point('parlai', 'console_scripts', 'parlai')())
  File "/home/evelyn/ParlAI/parlai/__main__.py", line 14, in main
    superscript_main()
  File "/home/evelyn/ParlAI/parlai/core/script.py", line 325, in superscript_main
    return SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "/home/evelyn/ParlAI/parlai/core/script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "/home/evelyn/ParlAI/parlai/scripts/interactive.py", line 118, in run
    return interactive(self.opt)
  File "/home/evelyn/ParlAI/parlai/scripts/interactive.py", line 84, in interactive
    agent = create_agent(opt, requireModelExists=True)
  File "/home/evelyn/ParlAI/parlai/core/agents.py", line 468, in create_agent
    model = create_agent_from_opt_file(opt)
  File "/home/evelyn/ParlAI/parlai/core/agents.py", line 421, in create_agent_from_opt_file
    return model_class(opt_from_file)
  File "/home/evelyn/ParlAI/parlai/agents/transformer/polyencoder.py", line 121, in __init__
    super().__init__(opt, shared)
  File "/home/evelyn/ParlAI/parlai/core/torch_ranker_agent.py", line 190, in __init__
    super().__init__(opt, shared)
  File "/home/evelyn/ParlAI/parlai/core/torch_agent.py", line 840, in __init__
    self.set_interactive_mode(opt.get('interactive_mode', False), shared)
  File "/home/evelyn/ParlAI/parlai/core/torch_ranker_agent.py", line 310, in set_interactive_mode
    path = self.get_task_candidates_path()
  File "/home/evelyn/ParlAI/parlai/core/torch_ranker_agent.py", line 334, in get_task_candidates_path
    build_cands(opt)
  File "/home/evelyn/ParlAI/parlai/scripts/build_candidates.py", line 55, in build_cands
    world = create_task(opt, agent)
  File "/home/evelyn/ParlAI/parlai/core/worlds.py", line 1441, in create_task
    world = create_task_world(opt, user_agents, default_world=default_world)
  File "/home/evelyn/ParlAI/parlai/core/worlds.py", line 1405, in create_task_world
    task_agents = _create_task_agents(opt)
  File "/home/evelyn/ParlAI/parlai/core/worlds.py", line 1393, in _create_task_agents
    return create_task_agent_from_taskname(opt)
  File "/home/evelyn/ParlAI/parlai/core/teachers.py", line 2657, in create_task_agent_from_taskname
    teacher_class = load_teacher_module(opt['task'])
  File "/home/evelyn/ParlAI/parlai/core/loader.py", line 281, in load_teacher_module
    task_module = load_task_module(taskname)
  File "/home/evelyn/ParlAI/parlai/core/loader.py", line 247, in load_task_module
    task_module = importlib.import_module(module_name)
  File "/home/evelyn/miniconda3/envs/baseline/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'parlai_internal'
```

Thank you for the help!

**Comment by stephenroller** [comment]
Can you try adding "-t blended_skill_talk"?

**Comment by evelynkyl** [comment]
Hi! I've already added "-t blended_skill_talk" at the end of the line, but it still doesn't work. I tried "bst_single_task/model" and "multi_task_bst_tuned/model" but both of them returned the same erorrs.

>

**Comment by tariqrahiman** [comment]
I also got the same error ModuleNotFoundError: No module named 'parlai_internal' for the below 3 commands

parlai interactive -mf zoo:blended_skill_talk/multi_task_bst_tuned/model -t blended_skill_talk
parlai interactive -mf zoo:blended_skill_talk/bst_single_task/model -t blended_skill_talk
parlai interactive -mf zoo:blended_skill_talk/multi_task_bst_tuned/model

**Comment by stephenroller** [comment]
Todo: add a manual override to rewrite internal:blended_skill_talk to blended_skill_talk in create_task
