### ISSUE TITLE
AttributeError when trying to add a new dataset

### ISSUE THREAD

**Issue by evelynkyl** [facebookresearch/ParlAI#4376]
**Bug description**
When trying to add a new dataset (plain text), it returns AttributeError: module 'parlai.tasks.fromfile.agents' has no attribute 'create_agents'.

Also, ParlaiDialogTeacher can't seem to identify the "labels" in the entries and returns this error "ValueError: ParlaiDialogTeacher requires a "labels" field in every entry, but one is missing in Line 1 in /home/evelyn/ParlAI/parlai/tasks/xorqa/xorqa.txt."

**Reproduction steps**
```python3 display_data.py --task fromfile:parlaiformat --fromfile_datapath /home/evelyn/ParlAI/parlai/tasks/xorqa/xorqa.txt```

**Expected behavior**
Should be able to return some samples of the dialog, as shown in https://www.parl.ai/docs/tutorial_task.html#parlaidialogteacher
In addition, ParlaiDialogTeacher should identify the labels field in each entry
**Logs**
```
01:05:25 | Opt:
01:05:25 |     allow_missing_init_opts: False
01:05:25 |     batchsize: 1
01:05:25 |     datapath: /home/evelyn/ParlAI/data
01:05:25 |     datatype: train:ordered
01:05:25 |     dict_class: None
01:05:25 |     display_add_fields: 
01:05:25 |     download_path: None
01:05:25 |     dynamic_batching: None
01:05:25 |     fromfile_datapath: /home/evelyn/ParlAI/parlai/tasks/xorqa/xorqa.txt
01:05:25 |     fromfile_datatype_extension: False
01:05:25 |     hide_labels: False
01:05:25 |     ignore_agent_reply: True
01:05:25 |     image_cropsize: 224
01:05:25 |     image_mode: raw
01:05:25 |     image_size: 256
01:05:25 |     init_model: None
01:05:25 |     init_opt: None
01:05:25 |     is_debug: False
01:05:25 |     loglevel: info
01:05:25 |     max_display_len: 1000
01:05:25 |     model: None
01:05:25 |     model_file: None
01:05:25 |     multitask_weights: [1]
01:05:25 |     mutators: None
01:05:25 |     num_examples: 10
01:05:25 |     override: "{'task': 'fromfile:parlaiformat', 'fromfile_datapath': '/home/evelyn/ParlAI/parlai/tasks/xorqa/xorqa.txt'}"
01:05:25 |     parlai_home: /home/evelyn/ParlAI
01:05:25 |     starttime: Feb23_01-05
01:05:25 |     task: fromfile:parlaiformat
01:05:25 |     verbose: False
01:05:25 | Current ParlAI commit: 3cdf65add3242d91ff90ef55649e6fceec89d6cf
01:05:25 | Current internal commit: 3cdf65add3242d91ff90ef55649e6fceec89d6cf
01:05:25 | Current fb commit: 3cdf65add3242d91ff90ef55649e6fceec89d6cf
01:05:25 | creating task(s): fromfile:parlaiformat
01:05:25 | Loading ParlAI text data: /home/evelyn/ParlAI/parlai/tasks/xorqa/xorqa.txt
Traceback (most recent call last):
  File "/home/evelyn/ParlAI/parlai/core/worlds.py", line 1390, in _create_task_agents
    task_agents = my_module.create_agents(opt)  # type: ignore
AttributeError: module 'parlai.tasks.fromfile.agents' has no attribute 'create_agents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "display_data.py", line 114, in <module>
    DisplayData.main()
  File "/home/evelyn/ParlAI/parlai/core/script.py", line 129, in main
    return cls._run_args(None)
  File "/home/evelyn/ParlAI/parlai/core/script.py", line 101, in _run_args
    return cls._run_from_parser_and_opt(opt, parser)
  File "/home/evelyn/ParlAI/parlai/core/script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "display_data.py", line 109, in run
    return display_data(self.opt)
  File "display_data.py", line 71, in display_data
    world = create_task(opt, agent)
  File "/home/evelyn/ParlAI/parlai/core/worlds.py", line 1441, in create_task
    world = create_task_world(opt, user_agents, default_world=default_world)
  File "/home/evelyn/ParlAI/parlai/core/worlds.py", line 1405, in create_task_world
    task_agents = _create_task_agents(opt)
  File "/home/evelyn/ParlAI/parlai/core/worlds.py", line 1393, in _create_task_agents
    return create_task_agent_from_taskname(opt)
  File "/home/evelyn/ParlAI/parlai/core/teachers.py", line 2659, in create_task_agent_from_taskname
    task_agents = teacher_class(opt)
  File "/home/evelyn/ParlAI/parlai/tasks/fromfile/agents.py", line 108, in __init__
    self._setup_data(datafile)
  File "/home/evelyn/ParlAI/parlai/core/teachers.py", line 1568, in _setup_data
    raise ValueError(
ValueError: ParlaiDialogTeacher requires a "labels" field in every entry, but one is missing in Line 1 in /home/evelyn/ParlAI/parlai/tasks/xorqa/xorqa.txt. The line is:
	text:জে. কে. রাউলিং রচিত হ্যারি পটার সিরিজ কোন প্রকাশনা সংস্থা থেকে প্রকাশিত হয় ?  labels:['ব্লুমসবারি', 'যুক্তরাজ্যের ব্লুমসবারি এবং যুক্তরাষ্ট্রে স্কলাস্টিক প্রেস']   new_episode = True

```

**Additional context**
Examples of the text file:
```
text:জে. কে. রাউলিং রচিত হ্যারি পটার সিরিজ কোন প্রকাশনা সংস্থা থেকে প্রকাশিত হয় ?  labels:['ব্লুমসবারি', 'যুক্তরাজ্যের ব্লুমসবারি এবং যুক্তরাষ্ট্রে স্কলাস্টিক প্রেস']   new_episode = True
text:আরএমএস টাইটানিক জাহাজটির মালিক কে ছিলেন ?  labels:['হোয়াইট স্টার লাইন']   new_episode = True
text:গলদা-চিংড়ি কোন শ্রেণীর জীব ?  labels:['সিটেসিয়ানস', 'নেফ্রোপিডি']   new_episode = True
text:ঈশ্বরের অস্তিত্বের পক্ষে দর্শনের কোন শাখায় আলোচনা করা হয়েছে ?  labels:['ধর্মের দর্শন']   new_episode = True
text:খুলনা বিভাগের অন্তর্গত মোট কতগুলি জেলা আছে ?  labels:['দশ']   new_episode = True
```

Thank you very much!

**Comment by evelynkyl** [comment]
The issues were fixed after updating the spacing between the text and the labels. I used tab as instructed in the website but it didn't work in the beginning. Later I downloaded a sample task and copy the spacing from the txt file and it's working now.

**Comment by stephenroller** [comment]
Thanks for posting the solution!!
