### ISSUE TITLE
Cannot run Zero2 training

### ISSUE THREAD

**Issue by zhangmozhi** [facebookresearch/ParlAI#4402]
**Bug description**
On the latest commit, training with --ddp-backend=zero2 causes an error.

**Reproduction steps**
`parlai multiprocessing_train -t convai2 -veps 0.25 --attention-dropout 0.0 --batchsize 32 --model transformer/generator --embedding-size 2560 --ffn-size 10240 --variant prelayernorm --n-heads 32 --n-positions 128 --n-encoder-layers 2 --n-decoder-layers 24 --history-add-global-end-token end --delimiter '  ' --dict-tokenizer bytelevelbpe  --dropout 0.1 --fp16 True --init-model zoo:blender/reddit_3B/model --dict-file zoo:blender/reddit_3B/model.dict --label-truncate 128 --log_every_n_secs 30 -lr 7e-06 --lr-scheduler reduceonplateau --lr-scheduler-patience 3 --optimizer adam --relu-dropout 0.0 --activation gelu --save-after-valid True --ddp-backend zero2 --learn-positional-embeddings true --text-truncate 128 --truncate 128 --warmup_updates 100 --fp16-impl mem_efficient --update-freq 1 --gradient-clip 0.1 --skip-generation True -vp 10 -vmt ppl  --model-file /data/kai/modelfiles/test/testmt`

**Expected behavior**
There should be no error.

**Logs**
Please paste the command line output:

```
00:09:39 | Distributed group initialized
00:09:45 | building dictionary first...
00:09:45 | No model with opt yet at: /data/kai/modelfiles/test/testmt(.opt)
00:09:45 | your model is being loaded with opts that do not exist in the model you are initializing the weights with: allow_missing_init_opts: False,download_path: None,loglevel: info,verbose: False,is_debug: False,datapath: /data/kai/test/ParlAI/data,evaltask: None,final_extra_opt: ,eval_batchsize: None,eval_dynamic_batching: None,num_workers: 0,display_examples: False,num_epochs: -1,max_train_time: -1,max_train_steps: -1,log_every_n_steps: 50,validation_every_n_secs: -1,validation_every_n_steps: -1,save_every_n_secs: -1,save_after_valid: True,validation_every_n_epochs: 0.25,validation_max_exs: -1,short_final_eval: False,validation_patience: 10,validation_metric: ppl,validation_metric_mode: None,validation_cutoff: 1.0,load_from_checkpoint: True,validation_share_agent: False,metrics: default,aggregate_micro: False,world_logs: ,save_format: conversations,log_keep_fields: all,tensorboard_log: False,tensorboard_logdir: None,wandb_log: False,wandb_name: None,wandb_project: None,wandb_entity: None,dict_maxexs: -1,dict_include_valid: False,dict_include_test: False,log_every_n_secs: 30.0,distributed_world_size: 8,ddp_backend: zero2,port: None,mutators: None,checkpoint_activations: False,beam_block_full_context: True,beam_block_list_filename: None,interactive_mode: False,history_reversed: False,special_tok_lst: None,bpe_dropout: None,rank: 0,multiprocessing: True
00:09:45 | your model is being loaded with opts that differ from the model you are initializing the weights with. Add the following args to your run command to change this: 
--show-advanced-args False --task None --numthreads 1 --batchsize 1 --dropout 0.05 --learn-positional-embeddings False --inference beam --beam-size 10 --beam-min-length 20 --beam-context-block-ngram 3 --beam-block-ngram 3 --skip-generation False --fp16 False --fp16-impl apex --force-fp16-tokens True --optimizer sgd --learningrate 1 --gpu -1 --bpe-vocab /tmp/meena_converter/bpe-vocab.json --bpe-merge /tmp/meena_converter/bpe-merges.txt --bpe-add-prefix-space True --max-lr-steps -1 --warmup-updates -1 --parlai-home /private/home/roller/working/parlai
00:09:45 | Using CUDA
00:09:45 | loading dictionary from /data/kai/test/ParlAI/data/models/blender/reddit_3B/model.dict
00:09:45 | num words = 8008
00:10:57 | Total parameters: 337,033,600 (337,033,600 trainable)
00:10:57 | Loading existing model params from /data/kai/test/ParlAI/data/models/blender/reddit_3B/model
00:11:26 | Detected a fine-tune run. Resetting the optimizer.
00:11:26 | Optimizer was reset. Also resetting LR scheduler.
00:11:26 | Opt:
00:11:26 |     activation: gelu
00:11:26 |     adafactor_eps: '(1e-30, 0.001)'
00:11:26 |     adam_eps: 1e-08
00:11:26 |     add_p1_after_newln: False
00:11:26 |     aggregate_micro: False
00:11:26 |     allow_missing_init_opts: False
00:11:26 |     attention_dropout: 0.0
00:11:26 |     batchsize: 32
00:11:26 |     beam_block_full_context: True
00:11:26 |     beam_block_list_filename: None
00:11:26 |     beam_block_ngram: -1
00:11:26 |     beam_context_block_ngram: -1
00:11:26 |     beam_delay: 30
00:11:26 |     beam_length_penalty: 0.65
00:11:26 |     beam_min_length: 1
00:11:26 |     beam_size: 1
00:11:26 |     betas: '(0.9, 0.999)'
00:11:26 |     bpe_add_prefix_space: None
00:11:26 |     bpe_debug: False
00:11:26 |     bpe_dropout: None
00:11:26 |     bpe_merge: /data/kai/test/ParlAI/data/models/blender/reddit_3B/model.dict-merges.txt
00:11:26 |     bpe_vocab: /data/kai/test/ParlAI/data/models/blender/reddit_3B/model.dict-vocab.json
00:11:26 |     checkpoint_activations: False
00:11:26 |     compute_tokenized_bleu: False
00:11:26 |     datapath: /data/kai/test/ParlAI/data
00:11:26 |     datatype: train
00:11:26 |     ddp_backend: zero2
00:11:26 |     delimiter: '  '
00:11:26 |     dict_class: parlai.core.dict:DictionaryAgent
00:11:26 |     dict_endtoken: __end__
00:11:26 |     dict_file: /data/kai/test/ParlAI/data/models/blender/reddit_3B/model.dict
00:11:26 |     dict_include_test: False
00:11:26 |     dict_include_valid: False
00:11:26 |     dict_initpath: None
00:11:26 |     dict_language: english
00:11:26 |     dict_loaded: True
00:11:26 |     dict_lower: False
00:11:26 |     dict_max_ngram_size: -1
00:11:26 |     dict_maxexs: -1
00:11:26 |     dict_maxtokens: -1
00:11:26 |     dict_minfreq: 0
00:11:26 |     dict_nulltoken: __null__
00:11:26 |     dict_starttoken: __start__
00:11:26 |     dict_textfields: text,labels
00:11:26 |     dict_tokenizer: bytelevelbpe
00:11:26 |     dict_unktoken: __unk__
00:11:26 |     display_examples: False
00:11:26 |     distributed_world_size: 8
00:11:26 |     download_path: None
00:11:26 |     dropout: 0.1
00:11:26 |     dynamic_batching: None
00:11:26 |     embedding_projection: random
00:11:26 |     embedding_size: 2560
00:11:26 |     embedding_type: random
00:11:26 |     embeddings_scale: True
00:11:26 |     eval_batchsize: None
00:11:26 |     eval_dynamic_batching: None
00:11:26 |     evaltask: None
00:11:26 |     ffn_size: 10240
00:11:26 |     final_extra_opt: 
00:11:26 |     force_fp16_tokens: False
00:11:26 |     fp16: True
00:11:26 |     fp16_impl: mem_efficient
00:11:26 |     gpu: 0
00:11:26 |     gradient_clip: 0.1
00:11:26 |     hide_labels: False
00:11:26 |     history_add_global_end_token: end
00:11:26 |     history_reversed: False
00:11:26 |     history_size: -1
00:11:26 |     image_cropsize: 224
00:11:26 |     image_mode: raw
00:11:26 |     image_size: 256
00:11:26 |     inference: greedy
00:11:26 |     init_model: /data/kai/test/ParlAI/data/models/blender/reddit_3B/model
00:11:26 |     init_opt: None
00:11:26 |     interactive_mode: False
00:11:26 |     invsqrt_lr_decay_gamma: -1
00:11:26 |     is_debug: False
00:11:26 |     label_truncate: 128
00:11:26 |     learn_positional_embeddings: True
00:11:26 |     learningrate: 7e-06
00:11:26 |     load_from_checkpoint: True
00:11:26 |     log_every_n_secs: 30.0
00:11:26 |     log_every_n_steps: 50
00:11:26 |     log_keep_fields: all
00:11:26 |     loglevel: info
00:11:26 |     lr_scheduler: reduceonplateau
00:11:26 |     lr_scheduler_decay: 0.5
00:11:26 |     lr_scheduler_patience: 3
00:11:26 |     max_train_steps: -1
00:11:26 |     max_train_time: -1
00:11:26 |     metrics: default
00:11:26 |     model: transformer/generator
00:11:26 |     model_file: /data/kai/modelfiles/test/testmt
00:11:26 |     model_parallel: False
00:11:26 |     momentum: 0
00:11:26 |     multiprocessing: True
00:11:26 |     multitask_weights: [1]
00:11:26 |     mutators: None
00:11:26 |     n_decoder_layers: 24
00:11:26 |     n_encoder_layers: 2
00:11:26 |     n_heads: 32
00:11:26 |     n_layers: 2
00:11:26 |     n_positions: 128
00:11:26 |     n_segments: 0
00:11:26 |     nesterov: True
00:11:26 |     no_cuda: False
00:11:26 |     num_epochs: -1
00:11:26 |     num_workers: 0
00:11:26 |     nus: (0.7,)
00:11:26 |     optimizer: mem_eff_adam
00:11:26 |     output_scaling: 1.0
00:11:26 |     override: "{'attention_dropout': 0.0, 'batchsize': 32, 'model': 'transformer/generator', 'embedding_size': 2560, 'ffn_size': 10240, 'variant': 'prelayernorm', 'n_heads': 32, 'n_positions': 128, 'n_encoder_layers': 2, 'n_decoder_layers': 24, 'history_add_global_end_token': 'end', 'delimiter': '  ', 'dict_tokenizer': 'bytelevelbpe', 'dropout': 0.1, 'fp16': True, 'init_model': 'zoo:blender/reddit_3B/model', 'dict_file': '/data/kai/test/ParlAI/data/models/blender/reddit_3B/model.dict', 'label_truncate': 128, 'log_every_n_secs': 30.0, 'lr_scheduler': 'reduceonplateau', 'lr_scheduler_patience': 3, 'optimizer': 'adam', 'relu_dropout': 0.0, 'activation': 'gelu', 'save_after_valid': True, 'ddp_backend': 'zero2', 'learn_positional_embeddings': True, 'text_truncate': 128, 'truncate': 128, 'warmup_updates': 100, 'fp16_impl': 'mem_efficient', 'update_freq': 1, 'gradient_clip': 0.1, 'skip_generation': True, 'model_file': '/data/kai/modelfiles/test/testmt', 'gpu': 0}"
00:11:26 |     parlai_home: /data/kai/test/ParlAI
00:11:26 |     person_tokens: False
00:11:26 |     port: None
00:11:26 |     rank: 0
00:11:26 |     rank_candidates: False
00:11:26 |     relu_dropout: 0.0
00:11:26 |     save_after_valid: True
00:11:26 |     save_every_n_secs: -1
00:11:26 |     save_format: conversations
00:11:26 |     share_word_embeddings: True
00:11:26 |     short_final_eval: False
00:11:26 |     skip_generation: True
00:11:26 |     special_tok_lst: None
00:11:26 |     split_lines: False
00:11:26 |     starttime: Mar08_00-09
00:11:26 |     task: convai2
00:11:26 |     temperature: 1.0
00:11:26 |     tensorboard_log: False
00:11:26 |     tensorboard_logdir: None
00:11:26 |     text_truncate: 128
00:11:26 |     topk: 10
00:11:26 |     topp: 0.9
00:11:26 |     truncate: 128
00:11:26 |     update_freq: 1
00:11:26 |     use_reply: label
00:11:26 |     validation_cutoff: 1.0
00:11:26 |     validation_every_n_epochs: 0.25
00:11:26 |     validation_every_n_secs: -1
00:11:26 |     validation_every_n_steps: -1
00:11:26 |     validation_max_exs: -1
00:11:26 |     validation_metric: ppl
00:11:26 |     validation_metric_mode: None
00:11:26 |     validation_patience: 10
00:11:26 |     validation_share_agent: False
00:11:26 |     variant: prelayernorm
00:11:26 |     verbose: False
00:11:26 |     wandb_entity: None
00:11:26 |     wandb_log: False
00:11:26 |     wandb_name: None
00:11:26 |     wandb_project: None
00:11:26 |     warmup_rate: 0.0001
00:11:26 |     warmup_updates: 100
00:11:26 |     weight_decay: None
00:11:26 |     world_logs: 
00:11:27 | Current ParlAI commit: 289942b11d97f162ac208128ec7d32abb72ef4d0
00:11:27 | creating task(s): convai2
00:11:27 | loading fbdialog data: /data/kai/test/ParlAI/data/ConvAI2/train_self_original.txt
00:11:29 | Using --log-every-n-secs in distributed mode can lead to slowdowns. See https://github.com/facebookresearch/ParlAI/pull/3379 for more info.
00:11:29 | Using --validation-every-n-epochs in distributed mode can lead to slowdowns. See https://github.com/facebookresearch/ParlAI/pull/3379 for more info.
00:11:29 | training...
rank:  2 | 00:11:34 | Traceback (most recent call last):
  File "/data/kai/test/ParlAI/parlai/scripts/multiprocessing_train.py", line 45, in multiprocess_train
    return single_train.TrainLoop(opt).train()
  File "/data/kai/test/ParlAI/parlai/scripts/train_model.py", line 996, in train
    for _train_log in self.train_steps():
  File "/data/kai/test/ParlAI/parlai/scripts/train_model.py", line 903, in train_steps
    world.parley()
  File "/data/kai/test/ParlAI/parlai/core/worlds.py", line 873, in parley
    batch_act = self.batch_act(agent_idx, batch_observations[agent_idx])
  File "/data/kai/test/ParlAI/parlai/core/worlds.py", line 841, in batch_act
    batch_actions = a.batch_act(batch_observation)
  File "/data/kai/test/ParlAI/parlai/core/torch_agent.py", line 2234, in batch_act
    output = self.train_step(batch)
  File "/data/kai/test/ParlAI/parlai/core/torch_generator_agent.py", line 735, in train_step
    self.backward(loss)
  File "/data/kai/test/ParlAI/parlai/core/torch_agent.py", line 2320, in backward
    self.optimizer.backward(loss, update_main_grads=False)
  File "/data/kai/test/ParlAI/parlai/utils/fp16.py", line 522, in backward
    loss.backward()
  File "/data/kai/miniconda3/envs/testparlai/lib/python3.8/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/data/kai/miniconda3/envs/testparlai/lib/python3.8/site-packages/torch/autograd/__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
  File "/data/kai/miniconda3/envs/testparlai/lib/python3.8/site-packages/fairscale-0.4.5-py3.8.egg/fairscale/nn/data_parallel/fully_sharded_data_parallel.py", line 1446, in _pre_backward_hook
    self._use_full_params()
  File "/data/kai/miniconda3/envs/testparlai/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/data/kai/miniconda3/envs/testparlai/lib/python3.8/site-packages/fairscale-0.4.5-py3.8.egg/fairscale/nn/data_parallel/fully_sharded_data_parallel.py", line 1944, in _use_full_params
    assert self.has_full_params
AssertionError
```

**Additional context**
Changing `flatten_parameters=False` to `flatten_parameters=True` in `parlai/utils/fsdp.py` seems to fix the problem. I'm not sure why though.

**Comment by stephenroller** [comment]
Thanks. We're submitting a patch to change the value of that.

**Comment by zhangmozhi** [comment]
> Thanks. We're submitting a patch to change the value of that.

Thanks for the quick response! Out of curiosity, why does this parameter break training? I thought this is only used to accelerate training, and I couldn't really understand the error message.

**Comment by stephenroller** [comment]
I believe it's a bug in fairscale. There was a patch last week that is related

**Comment by stephenroller** [comment]
This was fixed recently.
