### ISSUE TITLE
AttributeError: module 'parlai.tasks.holl_e.agents' has no attribute 'create_agents'

### ISSUE THREAD

**Issue by wujiayue18** [facebookresearch/ParlAI#4411]
I am experiencing some errors while using ParlAI in colab.

!pip install -q parlai
!pip install -q subword_nmt

after this, I want to display holl_e dataset.but something went wrong.

!parlai display_data --task holl_e

[building data: /usr/local/lib/python3.7/dist-packages/data/holl_e]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/parlai/core/worlds.py", line 1390, in _create_task_agents
    task_agents = my_module.create_agents(opt)  # type: ignore
AttributeError: module 'parlai.tasks.holl_e.agents' has no attribute 'create_agents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/parlai", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/parlai/__main__.py", line 14, in main
    superscript_main()
  File "/usr/local/lib/python3.7/dist-packages/parlai/core/script.py", line 325, in superscript_main
    return SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "/usr/local/lib/python3.7/dist-packages/parlai/core/script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "/usr/local/lib/python3.7/dist-packages/parlai/scripts/display_data.py", line 109, in run
    return display_data(self.opt)
  File "/usr/local/lib/python3.7/dist-packages/parlai/scripts/display_data.py", line 71, in display_data
    world = create_task(opt, agent)
  File "/usr/local/lib/python3.7/dist-packages/parlai/core/worlds.py", line 1441, in create_task
    world = create_task_world(opt, user_agents, default_world=default_world)
  File "/usr/local/lib/python3.7/dist-packages/parlai/core/worlds.py", line 1405, in create_task_world
    task_agents = _create_task_agents(opt)
  File "/usr/local/lib/python3.7/dist-packages/parlai/core/worlds.py", line 1393, in _create_task_agents
    return create_task_agent_from_taskname(opt)
  File "/usr/local/lib/python3.7/dist-packages/parlai/core/teachers.py", line 2668, in create_task_agent_from_taskname
    task_agents = teacher_class(opt)
  File "/usr/local/lib/python3.7/dist-packages/parlai/tasks/holl_e/agents.py", line 61, in __init__
    holle_path = _path(opt)
  File "/usr/local/lib/python3.7/dist-packages/parlai/tasks/holl_e/agents.py", line 21, in _path
    build(opt)
  File "/usr/local/lib/python3.7/dist-packages/parlai/tasks/holl_e/build.py", line 44, in build
    downloadable_file.download_file(dpath)
  File "/usr/local/lib/python3.7/dist-packages/parlai/core/build_data.py", line 102, in download_file
    self.checksum(dpath)
  File "/usr/local/lib/python3.7/dist-packages/parlai/core/build_data.py", line 88, in checksum
    f"Checksum for {self.file_name} from \n{self.url}\n"
AttributeError: 'DownloadableFile' object has no attribute 'filename'

**Comment by klshuster** [comment]
Is that the full, un-altered stack trace? nowhere in the codebase can I find a `.filename` attribute access for a `DownloadableFile` object

**Comment by stephenroller** [comment]
This seems weird. It should be file_name by that stacktrace.
