### ISSUE TITLE
AttributeError: module 'parlai.tasks.light_dialog.agents' has no attribute 'create_agents'

### ISSUE THREAD

**Issue by Hao0501** [facebookresearch/ParlAI#4494]
Hi there, I was trying to evaluate the 'all_task_mt' model on all of the provided dodecaDialogue tasks by running the command:

**parlai eval_model -mf zoo:dodecadialogue/all_tasks_mt/model -t "#Dodeca" --prepend-personality True --prepend-gold-knowledge True**

Then it comes up with the following error:

Traceback (most recent call last):
  File "c:\users\hao li\~\parlai\parlai\core\worlds.py", line 1397, in _create_task_agents
    task_agents = my_module.create_agents(opt)  # type: ignore
AttributeError: module 'parlai.tasks.light_dialog.agents' has no attribute 'create_agents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hao Li\AppData\Local\Programs\Python\Python38\Scripts\parlai-script.py", line 33, in <module>
    sys.exit(load_entry_point('parlai', 'console_scripts', 'parlai')())
  File "c:\users\hao li\~\parlai\parlai\__main__.py", line 14, in main
    superscript_main()
  File "c:\users\hao li\~\parlai\parlai\core\script.py", line 325, in superscript_main
    return SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "c:\users\hao li\~\parlai\parlai\core\script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "c:\users\hao li\~\parlai\parlai\scripts\eval_model.py", line 265, in run
    return eval_model(self.opt)
  File "c:\users\hao li\~\parlai\parlai\scripts\eval_model.py", line 239, in eval_model
    task_report = _eval_single_world(opt, agent, task)
  File "c:\users\hao li\~\parlai\parlai\scripts\eval_model.py", line 160, in _eval_single_world
    world = create_task(task_opt, agent)  # create worlds for tasks
  File "c:\users\hao li\~\parlai\parlai\core\worlds.py", line 1452, in create_task
    world = MultiWorld(opt, user_agents, default_world=default_world)
  File "c:\users\hao li\~\parlai\parlai\core\worlds.py", line 556, in __init__
    create_task_world(
  File "c:\users\hao li\~\parlai\parlai\core\worlds.py", line 1412, in create_task_world
    task_agents = _create_task_agents(opt)
  File "c:\users\hao li\~\parlai\parlai\core\worlds.py", line 1400, in _create_task_agents
    return create_task_agent_from_taskname(opt)
  File "c:\users\hao li\~\parlai\parlai\core\teachers.py", line 2666, in create_task_agent_from_taskname
    task_agents = teacher_class(opt)
  File "c:\users\hao li\~\parlai\parlai\tasks\light_dialog\agents.py", line 129, in __init__
    opt['parlaidialogteacher_datafile'] = _path(opt)
  File "c:\users\hao li\~\parlai\parlai\tasks\light_dialog\agents.py", line 20, in _path
    build(opt)
  File "c:\users\hao li\~\parlai\parlai\tasks\light_dialog\build.py", line 87, in build
    build_from_db(opt, dpath, dpath2, fname, fname2)
  File "c:\users\hao li\~\parlai\parlai\tasks\light_dialog\builder.py", line 367, in build_from_db
    write_out_candidates(db, data_path, split)
  File "c:\users\hao li\~\parlai\parlai\tasks\light_dialog\builder.py", line 335, in write_out_candidates
    fw.write(k + "\n")
  File "C:\Users\Hao Li\AppData\Local\Programs\Python\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f4b5' in position 24: character maps to <undefined>

Any idea why this error will come up or I just did something wrong. 

Thanks in advance,
Hao

**Comment by klshuster** [comment]
Note that ParlAI is unsupported on Windows, and this looks like that is partially the cause. Perhaps @JackUrb could comment on the specific error here iwthin the `builder.py` script

**Comment by stephenroller** [comment]
I might suggest:

https://dev.to/methane/python-use-utf-8-mode-on-windows-212i

**Comment by Hao0501** [comment]
> I might suggest:
> 
> https://dev.to/methane/python-use-utf-8-mode-on-windows-212i

Thanks for the reply, this perfectly solve the problem.
