### ISSUE TITLE
Seeker training crashes at validation step

### ISSUE THREAD

**Issue by zhangmozhi** [facebookresearch/ParlAI#4517]
**Bug description**
When using the Seeker-3B training command, I run into a FileNotFoundError.

**Reproduction steps**
```
$ python -m parlai.scripts.multiprocessing_train \
--task projects.seeker.tasks.knowledge,projects.seeker.tasks.dialogue,projects.seeker.tasks.search_query \
--multitask-weights 2,2,1 -bs 1 -vstep 1000 -vmt ppl -vp 5 -vmm min -vme 100000 -lstep 50 \
--init-opt arch/r2c2_base_3B --init-model zoo:seeker/r2c2_blenderbot_3B/model \
--model projects.seeker.agents.seeker:ComboFidGoldDocumentAgent --n-docs 5 \
--text-truncate 1000 --label-truncate 128 --truncate 1000 \
--fp16 True -lr 1e-06 --lr-scheduler reduceonplateau --optimizer adamw --save-after-valid True \
--warmup-updates 100 --update-freq 1 --gradient-clip 1.0 --skip-generation True --dropout 0.1 \
--attention-dropout 0.0 --load-from-checkpoint true --ddp-backend zero2 \
--checkpoint-activations true--model-file /tmp/my_seeker_dialogue_model
```

**Expected behavior**
There should be no error.

**Logs**
Please paste the command line output:

```
Exception in thread Thread-39:
Traceback (most recent call last):
  File "/data/kai/miniconda3/envs/parlai/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/data/kai/ParlAI/parlai/core/teachers.py", line 127, in run
    receive_fn(future)
  File "/data/kai/ParlAI/parlai/core/teachers.py", line 2442, in receive_data
    return self._process_data(future.result())
  File "/data/kai/miniconda3/envs/parlai/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/data/kai/miniconda3/envs/parlai/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/data/kai/miniconda3/envs/parlai/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data/kai/ParlAI/parlai/core/teachers.py", line 2540, in get_chunk
    output = self.load_from_chunk(next_chunk)
  File "/data/kai/ParlAI/parlai/tasks/natural_questions/agents.py", line 231, in load_from_chunk
    with jsonlines.open(fpath, 'r') as fi:
  File "/data/kai/miniconda3/envs/parlai/lib/python3.8/site-packages/jsonlines/jsonlines.py", line 328, in open
    fp = io.open(name, mode=mode + 't', encoding='utf-8')
FileNotFoundError: [Errno 2] No such file or directory: '/data/kai/ParlAI/data/NaturalQuestions/valid/nq-valid-00.jsonl'
```

**Additional context**
Renaming the file fixes this error, but I still can't get past validation after running the command for a few hours. Based on the log, it seems that validation stuck at Wizards of Internet.

**Comment by stephenroller** [comment]
Did the dataset drift on us?

**Comment by klshuster** [comment]
Could you please send the validation log where you say it is stuck?

For the NQ error, it seems that your build might have failed mid-way, as we have code that renames the files appropriately. I'm checking locally to see if that's still an issue

**Comment by klshuster** [comment]
Confirmed locally on my end that the dataset *has not* drifted on us

**Comment by zhangmozhi** [comment]
Thanks for looking into this! It's probably a build failure from our side then; I'll double check later.

We also realized that validation didn't stuck. It's just quite slow (a few hours with the command above). Sorry for the false alarm.
