### ISSUE TITLE
FileNotFoundError when Verifying the Downloaded Data

### ISSUE THREAD

**Issue by ChawDoe** [facebookresearch/ParlAI#4525]
Hi,

I have downloaded the data of image chat.
But when i ran verify_data.py, it told me:
`32.6% complete (9,785 / 29,991), 0:01:36 elapsed, 0:03:19 eta
    did_not_return_message  empty_string_label_candidates   exs  label_candidates_with_missing_label  missing_label_candidates  missing_labels  missing_text
                         0                              0  9785                                    0                         0               0             0
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/mnt/user/xx/ParlAI-main/parlai/core/teachers.py", line 127, in run
    receive_fn(future)
  File "/mnt/user/xxParlAI-main/parlai/core/teachers.py", line 389, in receive_data
    data = future.result()
  File "/opt/conda/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/opt/conda/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/mnt/user/xx/ParlAI-main/parlai/core/image_featurizers.py", line 241, in load
    return self._load_image(path)
  File "/mnt/user/xx/ParlAI-main/parlai/core/image_featurizers.py", line 229, in _load_image
    with PathManager.open(path, 'rb') as f:
  File "/home/xx/.local/lib/python3.8/site-packages/iopath/common/file_io.py", line 1012, in open
    bret = handler._open(path, mode, buffering=buffering, **kwargs)  # type: ignore
  File "/home/xx/.local/lib/python3.8/site-packages/iopath/common/file_io.py", line 604, in _open
    return open(  # type: ignore
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/user/xx/ParlAI-main/data/yfcc_images/ac8ee3225ea20433642b347f8fa8d81.jpg'`

**Comment by klshuster** [comment]
hi there, some of the images are no longer available via YFCC-100m. as a temporary fix, you can try just inserting a blank image at that location
