### ISSUE TITLE
How to change WizIntGoldDocRetrieverFiDAgent model to T5FidModel ?

### ISSUE THREAD

**Issue by entaroee** [facebookresearch/ParlAI#4563]
Hello, I'm trying to switch WizIntGoldDocRetrieverFiDAgent model to T5FidModel.

Because I want to change BART based model to T5 based model.

I tried
parlai train -t wizard_of_internet --model projects.blenderbot2.agents.blenderbot2:WizIntGoldDocRetrieverFiDAgent \
--batchsize 8 --dict-file zoo:sea/bart_fid_sqse/model.dict --truncate 512 \
--fp16 True --fp16-impl mem_efficient --optimizer mem_eff_adam \ --model-file my_bart_Fid_model_001
and succeeded.

then I tried 
parlai train -t wizard_of_internet --model projects.blenderbot2.agents.modules:T5FidModel --batchsize 8 --dict-file parlai.t5fid:T5_FiD_made.dict  --truncate 512 --fp16 True --fp16-impl mem_efficient --optimizer mem_eff_adam --model-file my_T5_Fid_model_001
(I made my own dictionary at /parlai/t5fid/ and named it T5_FiD_made.dict)

and it made
Parse Error: unrecognized arguments: --truncate 512 --fp16 True --fp16-impl mem_efficient --optimizer mem_eff_adam

so I erased that arguments and tried
parlai train -t wizard_of_internet --model projects.blenderbot2.agents.modules:T5FidModel --batchsize 8 --dict-file parlai.t5fid:T5_FiD_made.dict  --model-file my_T5_Fid_model_001

and it made
TypeError: __init__() missing 1 required positional argument: 'dictionary'

here are my questions
1. Is it possible to change BART based FiD model to T5 based FiD model? If it is possible, How can I make it with some changes on commands?
2. How can I use my own dictionary to model training? I think that 'dict-file' part I typed is wrong.

Thank you for reading this long comment.

**Comment by klshuster** [comment]
1. To use the T5 fid model, you'll need to specify `--model fid --generation-model t5`
2. You cannot specify your own dictionary for t5; it has a prebuilt dictionary

**Comment by entaroee** [comment]
Wow, such an easy way to train.. Thanks!

I tried
parlai train -t wizard_of_internet --model fid --generation-model t5 --batchsize 4 --truncate 512 --fp16 True --fp16-impl mem_efficient --optimizer mem_eff_adam --model-file my_T5_Fid_model_001


and it made

Downloading https://dl.fbaipublicfiles.com/dpr/checkpoint/retriver/multiset/hf_bert_base.cp to /home/ds_user1/ParlAI/data/models/hallucination/multiset_dpr/hf_bert_base.cp
Downloading hf_bert_base.cp: 100%|████████████████████████████████████████| 876M/876M [01:44<00:00, 8.36MB/s]
Downloading: 100%|████████████████████████████████████████████████████████| 420M/420M [00:05<00:00, 80.5MB/s]
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Killed

could you please help me a bit more about this bert-initializing concerened problem?

**Comment by klshuster** [comment]
what version of `transformers` do you have installed?

**Comment by entaroee** [comment]
With python 3.8.0 and transformers version 4.3.3, I tried 
parlai train -t wizard_of_internet --model fid --generation-model t5 --batchsize 4 --truncate 512 --fp16 True --fp16-impl mem_efficient --optimizer mem_eff_adam --model-file my_T5_Fid_model_001

and it failed :cry: .

After some attempts, with python 3.9.12 and transformers version 4.19.2, finally it worked! :smiley: 


but there still is one thing that makes me feel uncomfortable.
Right after I enter that command above, It made this error.

 | Downloading http://parl.ai/downloads/wizard_of_internet/wizard_of_internet.tgz to /home/ds_user1/ParlAI/data/wizard_of_interent/wizard_of_internet.tgz
Downloading wizard_of_internet.tgz: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.32G/1.32G [03:35<00:00, 6.11MB/s]
 | Finished downloading dataset files successfully.
 | Loading data from /home/ds_user1/ParlAI/data/wizard_of_interent/train.jsonl ...
8614it [00:23, 368.88it/s]
Building dictionary:   0%|                                                                                                                                            | 0.00/41.5k [00:00<?, ?ex/s]13:25:02 | Loading data from /home/ds_user1/ParlAI/data/wizard_of_interent/train.jsonl ...
                  Traceback (most recent call last):
  File "/home/ds_user1/anaconda3/envs/parl38/bin/parlai", line 33, in <module>
    sys.exit(load_entry_point('parlai', 'console_scripts', 'parlai')())
  File "/home/ds_user1/ParlAI/parlai/__main__.py", line 14, in main
    superscript_main()
  File "/home/ds_user1/ParlAI/parlai/core/script.py", line 325, in superscript_main
    return SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "/home/ds_user1/ParlAI/parlai/core/script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "/home/ds_user1/ParlAI/parlai/scripts/train_model.py", line 1047, in run
    self.train_loop = TrainLoop(self.opt)
  File "/home/ds_user1/ParlAI/parlai/scripts/train_model.py", line 368, in __init__
    build_dict(opt, skip_if_built=True)
  File "/home/ds_user1/ParlAI/parlai/scripts/build_dict.py", line 133, in build_dict
    world_dict.parley()
  File "/home/ds_user1/ParlAI/parlai/core/worlds.py", line 371, in parley
    agents[0].observe(validate(acts[1]))
  File "/home/ds_user1/ParlAI/parlai/core/teachers.py", line 540, in observe
    self.custom_evaluation(self.last_act, self.lastY, observation)
  File "/home/ds_user1/ParlAI/parlai/tasks/wizard_of_internet/agents.py", line 386, in custom_evaluation
    or (model_response.is_padding())
AttributeError: 'dict' object has no attribute 'is_padding'


so I just erased /home/ds_user1/ParlAI/parlai/tasks/wizard_of_internet/agents.py", line 386, and It runs.


Is it okay with ignoring that line?
Is there any other way to successfully train my model without making that error?

**Comment by klshuster** [comment]
That is an error on our end; I've just put up a fix that should solve that issue. For now, ignoring the line is OK.

**Comment by entaroee** [comment]
Thank you so much! after I ignore that line, I was able to train my own model.
I have one more question but I think that seems to be different from this subject, so I made another issue #4584 . Please check.

**Comment by klshuster** [comment]
Great, i'll go ahead and close this one then. feel free to reopen if you have additional concerns
