### ISSUE TITLE
KeyError: 'doc_chunk_split_mode' for blenderbot2_3B model

### ISSUE THREAD

**Issue by Eichhof** [facebookresearch/ParlAI#4586]
Hello

I'm using BlenderBot 2.0 on a Python Flask Server using the following code snippets:

```
from parlai.core.agents import create_agent_from_model_file
opt = {'skip_generation': False, 'include_personas': True, "knowledge_access_method": "memory_only"}
blender_agent = create_agent_from_model_file("zoo:blenderbot2/blenderbot2_3B/model", opt)
```

When I try to start the server, I'm getting the following error:

```
00:48:08 | Overriding opt["knowledge_access_method"] to memory_only (previously: classify)
00:48:11 | Using CUDA
00:48:11 | loading dictionary from C:\Users\myUser\ParlAI\data\models\blenderbot2/blenderbot2_3B/model.dict
00:48:11 | num words = 8008
Traceback (most recent call last):
  File "C:\Users\myUser\ParlAI\server\server.py", line 101, in <module>
    blender_agent = Model_init()
  File "C:\Users\myUser\ParlAI\server\server.py", line 25, in Model_init
    blender_agent = create_agent_from_model_file("zoo:blenderbot2/blenderbot2_3B/model", opt)
  File "c:\users\myUser\parlai\parlai\core\agents.py", line 347, in create_agent_from_model_file
    return create_agent_from_opt_file(opt)
  File "c:\users\myUser\parlai\parlai\core\agents.py", line 421, in create_agent_from_opt_file
    return model_class(opt_from_file)
  File "c:\users\myUser\parlai\parlai\agents\rag\rag.py", line 186, in __init__
    self._generation_agent.__init__(self, opt, shared)  # type: ignore
  File "c:\users\myUser\parlai\parlai\core\torch_generator_agent.py", line 485, in __init__
    self.model = fsdp_utils.fsdp_wrap(self.build_model())
  File "c:\users\myUser\parlai\projects\blenderbot2\agents\blenderbot2.py", line 969, in build_model
    model = BlenderBot2FidModel(self.opt, self.dict)
  File "c:\users\myUser\parlai\projects\blenderbot2\agents\modules.py", line 835, in __init__
    super().__init__(
  File "c:\users\myUser\parlai\projects\blenderbot2\agents\modules.py", line 90, in __init__
    self.retriever = retriever_factory(opt, dictionary, shared=retriever_shared)
  File "c:\users\myUser\parlai\projects\blenderbot2\agents\modules.py", line 65, in retriever_factory
    return BB2SearchQuerySearchEngineRetriever(opt, dictionary, shared=shared)
  File "c:\users\myUser\parlai\parlai\agents\rag\retrievers.py", line 1158, in __init__
    super().__init__(opt, dictionary, shared)
  File "c:\users\myUser\parlai\parlai\agents\rag\retrievers.py", line 1052, in __init__
    self.doc_chunk_split_mode = opt['doc_chunk_split_mode']
KeyError: 'doc_chunk_split_mode'
```

When I'm using BlenderBot 1.0 (zoo:blender/blender_3B/model) everything works.

How can I resolve this issue?

**Comment by mojtaba-komeili** [comment]
You may add ` 'doc_chunk_split_mode': ' word '` to your opt.

**Comment by Eichhof** [comment]
Thank you very much, that worked.
I'm now getting the warning:
```

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.decoder.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
```

Is this fine?
