### ISSUE TITLE
Unable to Find gen/seeker_dialogue option file

### ISSUE THREAD

**Issue by stanleyshly** [facebookresearch/ParlAI#4616]
I was attempting to interact with the Seeker model with this command: `parlai i -mf zoo:seeker/seeker_dialogue_3B/model -o gen/seeker_dialogue --search-server <search_server>`. However, the -o flag raises an error, and instead, I need to go into the opt_presets folder and manually find seeker_dialogue.opt instead and move it to my current working directory.

**Comment by klshuster** [comment]
can you please paste the full stack trace?

**Comment by stanleyshly** [comment]
Here is the full stack trace: 
```
Traceback (most recent call last):
  File "/usr/local/bin/parlai", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/parlai/__main__.py", line 14, in main
    superscript_main()
  File "/usr/local/lib/python3.7/dist-packages/parlai/core/script.py", line 316, in superscript_main
    opt = parser.parse_args(args)
  File "/usr/local/lib/python3.7/dist-packages/parlai/core/params.py", line 1163, in parse_args
    self.add_extra_args(args)
  File "/usr/local/lib/python3.7/dist-packages/parlai/core/script.py", line 175, in add_extra_args
    sa.choices[args[0]].add_extra_args(args)
  File "/usr/local/lib/python3.7/dist-packages/parlai/core/params.py", line 966, in add_extra_args
    self._load_known_opts(parsed.get('init_opt'), parsed)
  File "/usr/local/lib/python3.7/dist-packages/parlai/core/params.py", line 1016, in _load_known_opts
    new_opt = Opt.load_init(optfile)
  File "/usr/local/lib/python3.7/dist-packages/parlai/core/opt.py", line 177, in load_init
    f"Could not find filename '{optfile} or opt preset '{optfile}.opt'. "
FileNotFoundError: Could not find filename 'gen/seeker_dialogue or opt preset 'gen/seeker_dialogue.opt'. Please check https://parl.ai/docs/opt_presets.html for a list of available opt presets.
```
A related error, when running:
```
 parlai train_model \
--task convai2 \
--multitask-weights 2,2,1 -bs 1 -vstep 1000 -vmt ppl -vp 5 -vmm min -vme 100000 -lstep 50 \
--init-opt arch/r2c2_base_400M --init-model zoo:seeker/r2c2_blenderbot_400M/model \
--model projects.seeker.agents.seeker:ComboFidGoldDocumentAgent --n-docs 5 \
--text-truncate 1000 --label-truncate 128 --truncate 1000 \
--fp16 True -lr 1e-06 --lr-scheduler reduceonplateau --optimizer adamw --save-after-valid True \
--warmup-updates 100 --update-freq 1 --gradient-clip 1.0 --skip-generation True --dropout 0.1 \
--attention-dropout 0.0 --load-from-checkpoint true \
--checkpoint-activations True --model-file /tmp/my_seeker_dialogue_model --save_every_n_secs 600 
``` 
to train seeker, the init-opts config file also cannot be found, here is another stack trace: 
```
Traceback (most recent call last):
  File "/usr/local/bin/parlai", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/parlai/__main__.py", line 14, in main
    superscript_main()
  File "/usr/local/lib/python3.7/dist-packages/parlai/core/script.py", line 316, in superscript_main
    opt = parser.parse_args(args)
  File "/usr/local/lib/python3.7/dist-packages/parlai/core/params.py", line 1163, in parse_args
    self.add_extra_args(args)
  File "/usr/local/lib/python3.7/dist-packages/parlai/core/script.py", line 175, in add_extra_args
    sa.choices[args[0]].add_extra_args(args)
  File "/usr/local/lib/python3.7/dist-packages/parlai/core/params.py", line 966, in add_extra_args
    self._load_known_opts(parsed.get('init_opt'), parsed)
  File "/usr/local/lib/python3.7/dist-packages/parlai/core/params.py", line 1016, in _load_known_opts
    new_opt = Opt.load_init(optfile)
  File "/usr/local/lib/python3.7/dist-packages/parlai/core/opt.py", line 177, in load_init
    f"Could not find filename '{optfile} or opt preset '{optfile}.opt'. "
FileNotFoundError: Could not find filename 'arch/r2c2_base_400M or opt preset 'arch/r2c2_base_400M.opt'. Please check https://parl.ai/docs/opt_presets.html for a list of available opt presets.```

**Comment by klshuster** [comment]
Have you installed ParlAI from source or from pip?

If from source, you may need to re-run `python setup.py develop` at the repo root.

If from pip, you may need to upgrade your `parlai` version

**Comment by jh-skaion** [comment]
Hello @klshuster i am having the same issue and i have update the parlai version

![image](https://user-images.githubusercontent.com/82824999/176234789-60f8f264-a07d-4f88-b5ec-666723c49082.png)

please advice... thanks

**Comment by fraziermatthew** [comment]
Having the same issue. I am also using parlai v1.6.0.

```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/blenderbot2.0/bin/parlai", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/envs/blenderbot2.0/lib/python3.7/site-packages/parlai/__main__.py", line 14, in main
    superscript_main()
  File "/home/ubuntu/anaconda3/envs/blenderbot2.0/lib/python3.7/site-packages/parlai/core/script.py", line 316, in superscript_main
    opt = parser.parse_args(args)
  File "/home/ubuntu/anaconda3/envs/blenderbot2.0/lib/python3.7/site-packages/parlai/core/params.py", line 1163, in parse_args
    self.add_extra_args(args)
  File "/home/ubuntu/anaconda3/envs/blenderbot2.0/lib/python3.7/site-packages/parlai/core/script.py", line 175, in add_extra_args
    sa.choices[args[0]].add_extra_args(args)
  File "/home/ubuntu/anaconda3/envs/blenderbot2.0/lib/python3.7/site-packages/parlai/core/params.py", line 966, in add_extra_args
    self._load_known_opts(parsed.get('init_opt'), parsed)
  File "/home/ubuntu/anaconda3/envs/blenderbot2.0/lib/python3.7/site-packages/parlai/core/params.py", line 1016, in _load_known_opts
    new_opt = Opt.load_init(optfile)
  File "/home/ubuntu/anaconda3/envs/blenderbot2.0/lib/python3.7/site-packages/parlai/core/opt.py", line 177, in load_init
    f"Could not find filename '{optfile} or opt preset '{optfile}.opt'. "
FileNotFoundError: Could not find filename 'gen/seeker_dialogue or opt preset 'gen/seeker_dialogue.opt'. Please check https://parl.ai/docs/opt_presets.html for a list of available opt presets.
```

**Comment by fraziermatthew** [comment]
I was able to figure out a way around this based on [this post](https://github.com/facebookresearch/ParlAI/issues/4465#issuecomment-1086015902).

When I checked my `opt` folder locally, `gen/gen/seeker_dialogue.opt` file did not exist so I manually added it [see here](https://github.com/facebookresearch/ParlAI/blob/main/parlai/opt_presets/gen/seeker_dialogue.opt).
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/28677682/177043738-6fce2615-ab16-4ff2-87b7-a16a5433a50e.png">

Then, I gave the full path to the opt file as a parameter and it worked.
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/28677682/177043881-0e3cb4b7-1514-4a14-a91e-b5dbd536e963.png">

Hope this helps.
