### ISSUE TITLE
Error running safety benchmark on custom agent.

### ISSUE THREAD

**Issue by Jsiewierski11** [facebookresearch/ParlAI#4619]
I have a custom agent that is a mix of the BlenderBot2 model and a set of scripted dialogues which the agent switches between based on a set of arbitrary rules. I want to run the agent through the safety benchmark to see how the custom safe guards I put in place affect the score but have been running into the following error: 
RuntimeError: Last observe() was episode_done, but we never saw a corresponding self_observe to clear the history, probably because you missed an act(). This was changed in #2043. 
My repo is up to date with that change but I am a little stuck on why this issue would be appearing. I am wondering if it's because the agent isn't always calling batch_act() since it sometimes gets responses from the scripted dialogues?

Here is the wrapper code for reference:
`@register_model_wrapper("mybot")
class MybotWrapper:
    def __init__(self):
        overrides = {
                        "skip_generation": False, 
                        "interactive_mode": True, 
                        "custom_config": "/path/to/config.yaml",
                        "logging_file": "/path/to/logging-bot.yaml",
                        "config_format": "yaml"
                    }
        self.model = create_agent_from_model_file("/path/to/blenderbot2_3B/model", overrides)

    def get_response(self, input_text: str) -> str:
        # In ParlAI, we use observe/act syntax to get a response from the model
        # Please see the ParlAI docs for more info
        self.model.observe({"text": input_text, "episode_done": True})
        response = self.model.act()

        return response.get("text")`

**Comment by klshuster** [comment]
As the error states, you'll want to call `self.model.self_observe(response)` after calling `self.model.act()`

You can also get around this entirely by simply calling `self.model.respond(input_text)`

**Comment by klshuster** [comment]
Ahh, I may have jumped the gun on your initial message. When you return a scripted dialogue, are you calling `self_observe`? Perhaps you can update `get_response` to call `self_observe` only if your model returns a scripted response.

I would *not* comment out the validation as it is there for cases like this, as you may end up with incorrect history management

**Comment by Jsiewierski11** [comment]
Yes `self_observe` is getting called whether a response is coming from the BlenderBot2 model or the scripted dialogue. Should `self_observe` not be called if I get a response from the BB2 model?

I figured commenting out that line might have repercussions. I only needed to comment it out for the unit tests, when I run the agent locally or in a docker container I can leave the line in which is a bit confusing to me as why that allowed the tests to run.

**Comment by klshuster** [comment]
You're saying that, during a live run, and with the lines not commented out, your model runs fine?

**Comment by Jsiewierski11** [comment]
Correct. But that line seemed to cause issues when running the safety benchmark. In all other cases that line of code doesn't cause an issue.

**Comment by klshuster** [comment]
Could you share maybe a skeleton or pseudocode of what your custom agent act/observe/self-observe looks like? It seems somewhere in the act/observe pipeline you are indeed missing a self-observe

You may not see the issue live since you're most likely always observing with `'episode_done': False`

**Comment by Jsiewierski11** [comment]
So the ```observe()``` and the ```self_observe()``` functions are unmodified. Here is a basic outline of the pseudocode for the ```act()``` function:

```def act(self):```
     
      scripted_resp = get_scripted_resp(reply)
     
      if mode == 'scripted':
          reply['text'] = scripted_resp
      else: // blenderbot mode
          if scripted_resp has command:
             reply['text'] = scripted_resp
           else:
             reply['text'] = self.batch_act([self.observation])[0]
      
      self.self_observe(reply)
      return reply

**Comment by klshuster** [comment]
It's not super clear to me what's going on / why you're having issues with the invariants. If it continue to causes you trouble, let me know - if there's any way you can code up a minimal repro (without your custom agent code) that would be greatly appreciated as well

**Comment by klshuster** [comment]
based on discussions in other issues, there may be something going on here with the query generator or memory decoder. would it be possible to paste a full stack trace of your error?

**Comment by Jsiewierski11** [comment]
Here is the full stack trace.

`Traceback (most recent call last):
  File "projects/safety_bench/run_unit_tests.py", line 197, in <module>
    SafetyUnitTests.main()
  File "/home/dft/parlai/parlai/core/script.py", line 129, in main
    return cls._run_args(None)
  File "/home/dft/parlai/parlai/core/script.py", line 101, in _run_args
    return cls._run_from_parser_and_opt(opt, parser)
  File "/home/dft/parlai/parlai/core/script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "projects/safety_bench/run_unit_tests.py", line 193, in run
    return run_safety_unit_tests(self.opt)
  File "projects/safety_bench/run_unit_tests.py", line 148, in run_safety_unit_tests
    gen_report = generate_offensive_language_test.main(wrapper, opt)
  File "/home/dft/parlai/projects/safety_bench/unit_tests/generate_offensive_language_test.py", line 178, in main
    report = test_generation_safe(model_wrapper, opt)
  File "/home/dft/parlai/projects/safety_bench/unit_tests/generate_offensive_language_test.py", line 40, in test_generation_safe
    model_input, model_responses = collect_task_data_and_model_response(
  File "/home/dft/parlai/projects/safety_bench/utils/safety_testing.py", line 95, in collect_task_data_and_model_response
    model_responses = collect_model_responses(model_wrapper, model_inputs)
  File "/home/dft/parlai/projects/safety_bench/utils/safety_testing.py", line 38, in collect_model_responses
    model_responses.append(model_wrapper.get_response(text))
  File "/home/dft/parlai/projects/safety_bench/model_wrappers/example_wrapper.py", line 51, in get_response
    self.model.observe({"text": input_text, "episode_done": True})
  File "/home/dft/parlai/projects/blenderbot2/agents/blenderbot2.py", line 1315, in observe
    observation = super().observe(observation)
  File "/home/dft/parlai/parlai/agents/rag/rag.py", line 290, in observe
    observation = self._generation_agent.observe(self, observation)
  File "/home/dft/parlai/parlai/core/torch_agent.py", line 1833, in observe
    self._validate_observe_invariants()
  File "/home/dft/parlai/parlai/core/torch_agent.py", line 1946, in _validate_observe_invariants
    raise RuntimeError(
RuntimeError: Last observe() was episode_done, but we never saw a corresponding self_observe to clear the history, probably because you missed an act(). This was changed in #2043. File a GitHub issue if you require assistance.`

**Comment by klshuster** [comment]
Hmm ok, perhaps in `get_response` you can just call `self.model.reset()` at the end? As it seems you're just observing with `episode_done: True` anyway

**Comment by Jsiewierski11** [comment]
That seemed to do the trick!

**Comment by klshuster** [comment]
Great! Will close the issue then, feel free to reopen if there are future concerns.
