### ISSUE TITLE
Error running TOD simulator model

### ISSUE THREAD

**Issue by ssdavidson** [facebookresearch/ParlAI#4627]
When running: `parlai dd -t google_sgd_simulation_splits:OutDomainSystemTeacher -mf zoo:tod/tod_base_no_api/model  --skip-generation false --api-schemas true` as described on the TOD simulator page (https://parl.ai/projects/tod_simulator/), I receive the following error:

```python-traceback
Traceback (most recent call last):
  File "/home/ec2-user/.conda/envs/parlai/bin/parlai", line 33, in <module>
    sys.exit(load_entry_point('parlai', 'console_scripts', 'parlai')())
  File "/home/ec2-user/user_simulation/ParlAI/parlai/__main__.py", line 14, in main
    superscript_main()
  File "/home/ec2-user/user_simulation/ParlAI/parlai/core/script.py", line 316, in superscript_main
    opt = parser.parse_args(args)
  File "/home/ec2-user/user_simulation/ParlAI/parlai/core/params.py", line 1169, in parse_args
    self.add_extra_args(args)
  File "/home/ec2-user/user_simulation/ParlAI/parlai/core/script.py", line 175, in add_extra_args
    sa.choices[args[0]].add_extra_args(args)
  File "/home/ec2-user/user_simulation/ParlAI/parlai/core/params.py", line 948, in add_extra_args
    self.add_model_subargs(model, partial)
  File "/home/ec2-user/user_simulation/ParlAI/parlai/core/params.py", line 822, in add_model_subargs
    agent = load_agent_module(model)
  File "/home/ec2-user/user_simulation/ParlAI/parlai/core/loader.py", line 188, in load_agent_module
    my_module = importlib.import_module(module_name)
  File "/home/ec2-user/.conda/envs/parlai/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'parlai_fb'
```

I cannot seem to find any reference to parlai_fb module when searching through the repo.

**Comment by ssdavidson** [comment]
Ah I see, it appears that this is a reference to FB internal repositories. However, the project site indicates that these pretrained models are being released publicly.

**Comment by moyapchen** [comment]
Looking at this now
