### ISSUE TITLE
[Seeker self chat] RuntimeError: Message already contains key `knowledge_response`. If this was intentional, please use the function `force_set(key, value)`.

### ISSUE THREAD

**Issue by louis030195** [facebookresearch/ParlAI#4629]
Hi, I'm still trying to figure out how to run Seeker in self chat with a search engine, I'm facing the following issue.

```bash
parlai self_chat --model-file zoo:seeker/seeker_dialogue_400M/model  --num-self-chats 200 --display-examples True --seed_messages_from_file="./seeds.txt" --outfile="./out"  --init-opt gen/seeker_dialogue --search-server 0.0.0.0:8083
```

```
Current ParlAI commit: a84d28c4f9e9a56ddf9f8c3b124b61ac5ae991f5
Current internal commit: a84d28c4f9e9a56ddf9f8c3b124b61ac5ae991f5
Current fb commit: a84d28c4f9e9a56ddf9f8c3b124b61ac5ae991f5
```

>...
>20:40:13 | creating task(s): self_chat
[context]: Hi!
/home/gpu/ParlAI/parlai/core/torch_generator_agent.py:1728: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  hyp_ids = best_idxs // voc_size
20:40:13 | Search Queries: ['conscious experiences']
20:40:13 | sending search request to http://0.0.0.0:8083
20:40:23 | URLS:
https://www.sciencedirect.com/topics/computer-science/conscious-experience
https://nobaproject.com/modules/consciousness
https://www.open.edu/openlearn/mod/resource/view.php?id=25779
https://www.verywellmind.com/what-is-consciousness-2795922
https://www.jstor.org/stable/2253868
20:40:23 | Generated knowledge: ['1. Browse Content\n2. ScienceDirect help']
Traceback (most recent call last):
  File "/home/gpu/env/bin/parlai", line 33, in <module>
    sys.exit(load_entry_point('parlai', 'console_scripts', 'parlai')())
  File "/home/gpu/ParlAI/parlai/__main__.py", line 14, in main
    superscript_main()
  File "/home/gpu/ParlAI/parlai/core/script.py", line 325, in superscript_main
    return SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "/home/gpu/ParlAI/parlai/core/script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "/home/gpu/ParlAI/parlai/scripts/self_chat.py", line 176, in run
    return self_chat(self.opt)
  File "/home/gpu/ParlAI/parlai/scripts/self_chat.py", line 146, in self_chat
    _run_self_chat_episode(opt, world, logger)
  File "/home/gpu/ParlAI/parlai/scripts/self_chat.py", line 93, in _run_self_chat_episode
    world.parley()
  File "/home/gpu/ParlAI/parlai/tasks/self_chat/worlds.py", line 178, in parley
    self.agents[1 - i].observe(validate(self.acts[i]))
  File "/home/gpu/ParlAI/projects/seeker/agents/seeker.py", line 566, in observe
    observation['knowledge_response'] = observation.get('checked_sentence', '')
  File "/home/gpu/ParlAI/parlai/core/message.py", line 30, in __setitem__
    raise RuntimeError(
RuntimeError: Message already contains key `knowledge_response`. If this was intentional, please use the function `force_set(key, value)`.

Should I tweak the knowledge params? Or could you give me the CLI to run Seeker in self chat with a search engine please?

Thanks a lot 😇

**Comment by klshuster** [comment]
Hi there, I've put up a fix in #4634

**Comment by louis030195** [comment]
> #4634

Awesome, works perfect 👏
