### ISSUE TITLE
IndexError for memory_ve while training blenderbot2

### ISSUE THREAD

**Issue by robinsongh381** [facebookresearch/ParlAI#4674]
Hello !
After reading #4340 i tried to train blenderbot2_400M with following script

```
parlai train_model \
-lr 7e-6 \
-bs 16 \
--task msc \
--model-file ./bb2 \
--model projects.blenderbot2.agents.blenderbot2:BlenderBot2FidAgent \
--dict-file zoo:blenderbot2/blenderbot2_400M/model.dict \
--init-model zoo:blenderbot2/blenderbot2_400M/model \
--skip-generation True \
--knowledge-access-method memory_only \
--search-server None \
--metrics ppl \
--validation-metric ppl \
--model-parallel True \
--memory-decoder-model-file '' \
--datatype train:stream \
--generation-model transformer/generator \
--query-model bert_from_parlai_rag \
--rag-model-type token \
--rag-retriever-type dpr \
--max-doc-token-length 64 \
--dpr-model-file zoo:hallucination/bart_rag_token/model \
--beam-size 10 \
--beam-min-length 20 \
--beam-context-block-ngram 3 \
--beam-block-ngram 3 \
--beam-block-full-context False \
--inference beam \
--fp16-impl mem_efficient \
--optimizer mem_eff_adam \
--truncate 128 \
--text-truncate 128 \
--label-truncate 128 \
--history-add-global-end-token end \
--warmup-updates 100 \
--gold-document-titles-key select-docs-titles \
--insert-gold-docs True \
--activation gelu \
--attention-dropout 0.0 \
--dict-tokenizer gpt2 \
--dropout 0.1 \
--embedding-size 1024 \
--embeddings-scale false \
--ffn_size 4096 \
--force-fp16-tokens true \
--fp16 true \
--learn-positional-embeddings true \
--n-decoder-layers 12 \
--n-encoder-layers 12 \
--n-heads 16 \
--n-positions 1024 \
--variant bart \
--memory-key full_text \
```

as can ben seen from the last row, i ensured `--memory-key full_text` but i met the following errors.

Any help ?

**Logs**

```
02:41:51 | building dictionary first...
02:41:51 | No model with opt yet at: user/documents/your_directory_to_save_model(.opt)
02:41:51 | your model is being loaded with opts that do not exist in the model you are initializing the weights with: download_path: None,verbose: False,datapath: /data/private/langu
age_model/git/ParlAI/data,evaltask: None,eval_batchsize: None,eval_dynamic_batching: None,num_workers: 0,display_examples: False,num_epochs: -1,max_train_time: -1,max_train_steps: -1
,log_every_n_steps: 50,validation_every_n_secs: -1,validation_every_n_steps: -1,save_every_n_secs: -1,save_after_valid: False,validation_every_n_epochs: -1,validation_max_exs: -1,sho
rt_final_eval: False,validation_patience: 10,validation_metric: ppl,validation_metric_mode: None,validation_cutoff: 1.0,load_from_checkpoint: True,validation_share_agent: False,metri
cs: ppl,aggregate_micro: False,tensorboard_log: False,tensorboard_logdir: None,wandb_log: False,wandb_name: None,wandb_project: None,wandb_entity: None,dict_maxexs: -1,dict_include_v
alid: False,dict_include_test: False,log_every_n_secs: -1,include_session1: True,include_last_session: False,session_id: 2,previous_persona_type: raw_history,session_openning: False,
label_speaker_id: both,include_time_gap: False,history_time_gaps_token: None,history_person_tokens: None,previous_session_delimiter: None,mutators: None,your_persona_first: True,max_
num_turns: -1,is_convai2_session_level: False,interactive_mode: False,doc_chunk_split_mode: word
02:41:51 | your model is being loaded with opts that differ from the model you are initializing the weights with. Add the following args to your run command to change this:
--task None --multitask-weights 3.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0 --batchsize 12 --n-layers 12 --attention-dropout 0.1 --embeddings-scale True --variant prelayernorm --gene
ration-model bart --rag-retriever-type search_engine --max-doc-token-length 256 --skip-generation False --fp16 False --fp16-impl safe --optimizer adamax --learningrate 1e-05 --trunca
te 512 --text-truncate 512 --split-lines True --history-add-global-end-token None --lr-scheduler-patience 1 --warmup-updates -1 --search-query-generator-model-file zoo:blenderbot2/qu
ery_generator/model --search-query-generator-beam-min-length 2 --search-server None --knowledge-access-method classify --memory-key personas --memory-decoder-model-file zoo:blenderbo
t2/memory_decoder/model --parlai-home /private/home/kshuster/ParlAI
02:41:51 | Using CUDA
02:41:51 | loading dictionary from /data/private/language_model/git/ParlAI/data/models/blenderbot2/blenderbot2_400M/model.dict
02:41:51 | num words = 50264
02:42:08 | Creating Index from Index Factory: IVF4096_HNSW128,PQ128
02:42:08 | Loading index from /data/private/language_model/git/ParlAI/data/models/hallucination/wiki_index_compressed/compressed_pq
02:42:11 | Loaded index of type <faiss.swigfaiss_avx2.IndexIVFPQ; proxy of <Swig Object of type 'faiss::IndexIVFPQ *' at 0x7f2525ae6ea0> > and size 21015300
02:42:23 | Reading data from: /data/private/language_model/git/ParlAI/data/models/hallucination/wiki_passages/psgs_w100.tsv
1000it [00:00, 2426.52it/s]
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.weight',
'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.bias', 'cls.predictions
.transform.LayerNorm.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassific
ation model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model fr
om a BertForSequenceClassification model).
02:42:48 | Building Query Generator from file: /data/private/language_model/git/ParlAI/data/models/blenderbot2/query_generator/model
02:43:05 | Total parameters: 732,961,280 (731,781,632 trainable)
02:43:05 | Loading existing model params from /data/private/language_model/git/ParlAI/data/models/blenderbot2/blenderbot2_400M/model
02:43:10 | Detected a fine-tune run. Resetting the optimizer.
02:43:10 | Optimizer was reset. Also resetting LR scheduler.
02:43:10 | Opt:
02:43:10 |     activation: gelu
02:43:10 |     adafactor_eps: '(1e-30, 0.001)'
02:43:10 |     adam_eps: 1e-08
02:43:10 |     add_p1_after_newln: False
02:43:10 |     aggregate_micro: False
02:43:10 |     allow_missing_init_opts: False
02:43:10 |     attention_dropout: 0.0
02:43:10 |     batchsize: 16
02:43:10 |     beam_block_full_context: False
02:43:10 |     beam_block_list_filename: None
02:43:10 |     beam_block_ngram: 3
02:43:10 |     beam_context_block_ngram: 3
02:43:10 |     beam_delay: 30
02:43:10 |     beam_length_penalty: 0.65
02:43:10 |     beam_min_length: 20
02:43:10 |     beam_size: 10
02:43:10 |     betas: '(0.9, 0.999)'
02:43:10 |     bpe_add_prefix_space: None
02:43:10 |     bpe_debug: False
02:43:10 |     bpe_dropout: None
02:43:10 |     bpe_merge: None
02:43:10 |     bpe_vocab: None
02:43:10 |     candidates: inline
02:43:10 |     cap_num_predictions: 100
02:43:10 |     codes_attention_num_heads: 4
02:43:10 |     codes_attention_type: basic
02:43:10 |     compressed_indexer_factory: IVF4096_HNSW128,PQ128
02:43:10 |     compressed_indexer_gpu_train: False
02:43:10 |     compressed_indexer_nprobe: 64
02:43:10 |     compute_tokenized_bleu: False
02:43:10 |     converting: False
02:43:10 |     data_parallel: False
02:43:10 |     datapath: /data/private/language_model/git/ParlAI/data
02:43:10 |     datatype: train:stream
02:43:10 |     delimiter: '\n'
02:43:10 |     dict_class: parlai.core.dict:DictionaryAgent
02:43:10 |     dict_endtoken: __end__
02:43:10 |     dict_file: /data/private/language_model/git/ParlAI/data/models/blenderbot2/blenderbot2_400M/model.dict
02:43:10 |     dict_include_test: False
02:43:10 |     dict_include_valid: False
02:43:10 |     dict_initpath: None
02:43:10 |     dict_language: english
02:43:10 |     dict_loaded: True
02:43:10 |     dict_lower: False
02:43:10 |     dict_max_ngram_size: -1
02:43:10 |     dict_maxexs: -1
02:43:10 |     dict_maxtokens: -1
02:43:10 |     dict_minfreq: 0
02:43:10 |     dict_nulltoken: __null__
02:43:10 |     dict_starttoken: __start__
02:43:10 |     dict_textfields: text,labels
02:43:10 |     dict_tokenizer: gpt2
02:43:10 |     dict_unktoken: __unk__
02:43:10 |     display_examples: False
02:43:10 |     doc_chunk_split_mode: word
02:43:10 |     doc_chunks_ranker: head
02:43:10 |     download_path: None
02:43:10 |     dpr_model_file: zoo:hallucination/bart_rag_token/model
02:43:10 |     dpr_num_docs: 25
02:43:10 |     dropout: 0.1
02:43:10 |     dynamic_batching: None
02:43:10 |     embedding_projection: random
02:43:10 |     embedding_size: 1024
02:43:10 |     embedding_type: random
02:43:10 |     embeddings_scale: False
02:43:10 |     encode_candidate_vecs: True
02:43:10 |     encode_candidate_vecs_batchsize: 256
02:43:10 |     eval_batchsize: None
02:43:10 |     eval_candidates: inline
02:43:10 |     eval_dynamic_batching: None
02:43:10 |     evaltask: None
02:43:10 |     ffn_size: 4096
02:43:10 |     fixed_candidate_vecs: reuse
02:43:10 |     fixed_candidates_path: None
02:43:10 |     force_fp16_tokens: True
02:43:10 |     fp16: True
02:43:10 |     fp16_impl: mem_efficient
02:43:10 |     generation_model: transformer/generator
02:43:10 |     gold_document_key: __selected-docs__
02:43:10 |     gold_document_titles_key: select-docs-titles
02:43:10 |     gold_knowledge_passage_key: checked_sentence
02:43:10 |     gold_knowledge_title_key: title
02:43:10 |     gold_sentence_key: __selected-sentences__
02:43:10 |     gpu: -1
02:43:10 |     gradient_clip: 0.1
02:43:10 |     hide_labels: False
02:43:10 |     history_add_global_end_token: end
02:43:10 |     history_person_tokens: None
02:43:10 |     history_reversed: False
02:43:10 |     history_size: -1
02:43:10 |     history_time_gaps_token: None
02:43:10 |     hnsw_ef_construction: 200
02:43:10 |     hnsw_ef_search: 128
02:43:10 |     hnsw_indexer_store_n: 128
02:43:10 |     ignore_bad_candidates: False
02:43:10 |     image_cropsize: 224
02:43:10 |     image_mode: raw
02:43:10 |     image_size: 256
02:43:10 |     include_last_session: False
02:43:10 |     include_session1: True
02:43:10 |     include_time_gap: False
02:43:10 |     indexer_buffer_size: 65536
02:43:10 |     indexer_type: compressed
02:43:10 |     inference: beam
02:43:10 |     init_model: /data/private/language_model/git/ParlAI/data/models/blenderbot2/blenderbot2_400M/model
02:43:10 |     init_opt: None
02:43:10 |     insert_gold_docs: True
02:43:10 |     interactive_candidates: fixed
02:43:10 |     interactive_mode: False
02:43:10 |     invsqrt_lr_decay_gamma: -1
02:43:10 |     is_convai2_session_level: False
02:43:10 |     is_debug: False
02:43:10 |     knowledge_access_method: memory_only
02:43:10 |     label_speaker_id: both
02:43:10 |     label_truncate: 128
02:43:10 |     learn_embeddings: True
02:43:10 |     learn_positional_embeddings: True
02:43:10 |     learningrate: 7e-06
02:43:10 |     load_from_checkpoint: True
02:43:10 |     log_every_n_secs: -1
02:43:10 |     log_every_n_steps: 50
02:43:10 |     loglevel: info
02:43:10 |     lr_scheduler: reduceonplateau
02:43:10 |     lr_scheduler_decay: 0.5
02:43:10 |     lr_scheduler_patience: 3
02:43:10 |     max_doc_token_length: 64
02:43:10 |     max_num_turns: -1
02:43:10 |     max_train_steps: -1
02:43:10 |     max_train_time: -1
02:43:10 |     memory_attention: sqrt
02:43:10 |     memory_decoder_beam_min_length: 10
02:43:10 |     memory_decoder_beam_size: 3
02:43:10 |     memory_decoder_delimiter: '\n'
02:43:10 |     memory_decoder_ignore_phrase: persona:
02:43:10 |     memory_decoder_key: full_text
02:43:10 |     memory_decoder_model_file:
02:43:10 |     memory_decoder_one_line_memories: False
02:43:10 |     memory_decoder_truncate: -1
02:43:10 |     memory_doc_title_delimiter: ' / '
02:43:10 |     memory_extractor_phrase: persona:
02:43:10 |     memory_key: full_text
02:43:10 |     memory_reader_model: None
02:43:10 |     memory_retriever_truncate: -1
02:43:10 |     memory_writer_model: bert
02:43:10 |     memory_writer_model_file: zoo:hallucination/multiset_dpr/hf_bert_base.cp
02:43:10 |     metrics: ppl
02:43:10 |     min_doc_token_length: 64
02:43:10 |     model: projects.blenderbot2.agents.blenderbot2:BlenderBot2FidAgent
02:43:10 |     model_file: user/documents/your_directory_to_save_model
02:43:10 |     model_parallel: True
02:43:10 |     momentum: 0
02:43:10 |     multitask_weights: [1]
02:43:10 |     mutators: None
02:43:10 |     n_decoder_layers: 12
02:43:10 |     n_docs: 5
02:43:10 |     n_encoder_layers: 12
02:43:10 |     n_extra_positions: 0
02:43:10 |     n_heads: 16
02:43:10 |     n_layers: 2
02:43:10 |     n_positions: 1024
02:43:10 |     n_ranked_doc_chunks: 1
02:43:10 |     n_segments: 0
02:43:10 |     nesterov: True
02:43:10 |     no_cuda: False
02:43:10 |     normalize_sent_emb: False
02:43:10 |     num_epochs: -1
02:43:10 |     num_workers: 0
02:43:10 |     nus: (0.7,)
02:43:10 |     optimizer: mem_eff_adam
02:43:10 |     output_scaling: 1.0
02:43:10 |     override: "{'task': 'msc', 'model_file': 'user/documents/your_directory_to_save_model', 'model': 'projects.blenderbot2.agents.blenderbot2:BlenderBot2FidAgent', 'dict_f
ile': '/data/private/language_model/git/ParlAI/data/models/blenderbot2/blenderbot2_400M/model.dict', 'init_model': 'zoo:blenderbot2/blenderbot2_400M/model', 'skip_generation': True,
'knowledge_access_method': 'memory_only', 'search_server': 'None', 'metrics': 'ppl', 'validation_metric': 'ppl', 'model_parallel': True, 'memory_decoder_model_file': '', 'datatype':
'train:stream', 'generation_model': 'transformer/generator', 'query_model': 'bert_from_parlai_rag', 'rag_model_type': 'token', 'rag_retriever_type': 'dpr', 'max_doc_token_length': 64
, 'dpr_model_file': 'zoo:hallucination/bart_rag_token/model', 'beam_size': 10, 'beam_min_length': 20, 'beam_context_block_ngram': 3, 'beam_block_ngram': 3, 'beam_block_full_context':
 False, 'inference': 'beam', 'fp16_impl': 'mem_efficient', 'optimizer': 'mem_eff_adam', 'truncate': 128, 'text_truncate': 128, 'label_truncate': 128, 'history_add_global_end_token':
'end', 'warmup_updates': 100, 'gold_document_titles_key': 'select-docs-titles', 'insert_gold_docs': True, 'activation': 'gelu', 'attention_dropout': 0.0, 'dict_tokenizer': 'gpt2', 'd
ropout': 0.1, 'embedding_size': 1024, 'embeddings_scale': False, 'ffn_size': 4096, 'force_fp16_tokens': True, 'fp16': True, 'learn_positional_embeddings': True, 'n_decoder_layers': 1
2, 'n_encoder_layers': 12, 'n_heads': 16, 'n_positions': 1024, 'variant': 'bart', 'memory_key': 'full_text'}"
02:43:10 |     parlai_home: /data/private/language_model/git/ParlAI
02:43:10 |     path_to_dense_embeddings: None
02:43:10 |     path_to_dpr_passages: zoo:hallucination/wiki_passages/psgs_w100.tsv
02:43:10 |     path_to_index: zoo:hallucination/wiki_index_compressed/compressed_pq
02:43:10 |     person_tokens: False
02:43:10 |     poly_attention_num_heads: 4
02:43:10 |     poly_attention_type: basic
02:43:10 |     poly_faiss_model_file: None
02:43:10 |     poly_n_codes: 64
02:43:10 |     poly_score_initial_lambda: 0.5
02:43:10 |     polyencoder_init_model: wikito
02:43:10 |     polyencoder_type: codes
02:43:10 |     previous_persona_type: raw_history
02:43:10 |     previous_session_delimiter: None
02:43:10 |     print_docs: False
02:43:10 |     query_generator_beam_min_length: 2
02:43:10 |     query_generator_beam_size: 1
02:43:10 |     query_generator_delimiter: '\n'
02:43:10 |     query_generator_ignore_phrase: persona:
02:43:10 |     query_generator_inference: beam
02:43:10 |     query_generator_key: full_text
02:43:10 |     query_generator_model_file: zoo:blenderbot2/query_generator/model
02:43:10 |     query_generator_truncate: -1
02:43:10 |     query_model: bert_from_parlai_rag
02:43:10 |     rag_model_type: token
02:43:10 |     rag_query_truncate: 512
02:43:10 |     rag_retriever_query: full_history
02:43:10 |     rag_retriever_type: dpr
02:43:10 |     rag_turn_discount_factor: 1.0
02:43:10 |     rag_turn_marginalize: doc_then_turn
02:43:10 |     rag_turn_n_turns: 2
02:43:10 |     rank_candidates: False
02:43:10 |     rank_top_k: -1
02:43:10 |     reduction_type: mean
02:43:10 |     regret: False
02:43:10 |     regret_intermediate_maxlen: 32
02:43:10 |     regret_model_file: None
02:43:10 |     relu_dropout: 0.0
02:43:10 |     repeat_blocking_heuristic: True
02:43:10 |     retriever_debug_index: None
02:43:10 |     retriever_delimiter: '\n'
02:43:10 |     retriever_embedding_size: 768
02:43:10 |     retriever_ignore_phrase: persona:
02:43:10 |     return_cand_scores: False
02:43:10 |     save_after_valid: False
02:43:10 |     save_every_n_secs: -1
02:43:10 |     search_query_generator_beam_min_length: 1
02:43:10 |     search_query_generator_beam_size: 1
02:43:10 |     search_query_generator_inference: greedy
02:43:10 |     search_query_generator_model_file: None
02:43:10 |     search_query_generator_text_truncate: 512
02:43:10 |     search_server: None
02:43:10 |     session_id: 2
02:43:10 |     session_openning: False
02:43:10 |     share_encoders: True
02:43:10 |     share_search_and_memory_query_encoder: False
02:43:10 |     share_word_embeddings: True
02:43:10 |     short_final_eval: False
02:43:10 |     skip_generation: True
02:43:10 |     special_tok_lst: None
02:43:10 |     split_lines: False
02:43:10 |     splitted_chunk_length: 256
02:43:10 |     starttime: Jul22_02-41
02:43:10 |     t5_dropout: 0.0
02:43:10 |     t5_generation_config: None
02:43:10 |     t5_model_arch: t5-base
02:43:10 |     t5_model_parallel: False
02:43:10 |     task: msc
02:43:10 |     temperature: 1.0
02:43:10 |     tensorboard_log: False
02:43:10 |     tensorboard_logdir: None
02:43:10 |     text_truncate: 128
02:43:10 |     tfidf_max_doc_paragraphs: -1
02:43:10 |     tfidf_model_path: zoo:wikipedia_full/tfidf_retriever/model
02:43:10 |     thorough: False
02:43:10 |     topk: 10
02:43:10 |     topp: 0.9
02:43:10 |     train_predict: False
02:43:10 |     truncate: 128
02:43:10 |     update_freq: 1
02:43:10 |     use_memories: False
02:43:10 |     use_reply: label
02:43:10 |     validation_cutoff: 1.0
02:43:10 |     validation_every_n_epochs: -1
02:43:10 |     validation_every_n_secs: -1
02:43:10 |     validation_every_n_steps: -1
02:43:10 |     validation_max_exs: -1
02:43:10 |     validation_metric: ppl
02:43:10 |     validation_metric_mode: None
02:43:10 |     validation_patience: 10
02:43:10 |     validation_share_agent: False
02:43:10 |     variant: bart
02:43:10 |     verbose: False
02:43:10 |     wandb_entity: None
02:43:10 |     wandb_log: False
02:43:10 |     wandb_name: None
02:43:10 |     wandb_project: None
02:43:10 |     warmup_rate: 0.0001
02:43:10 |     warmup_updates: 100
02:43:10 |     weight_decay: None
02:43:10 |     wrap_memory_encoder: False
02:43:10 |     your_persona_first: True
02:43:10 | Current ParlAI commit: ad57e5281de76ed42a378bdd2bcdef2fafc54ab8
02:43:11 | creating task(s): msc
02:43:11 | training...
02:43:11 | loading normalized fbdialog data: /data/private/language_model/git/ParlAI/data/ConvAI2/train_self_original.txt
02:43:11 | loading fbdialog data: /data/private/language_model/git/ParlAI/data/ConvAI2/train_self_original.txt
02:43:12 | Overflow: setting loss scale to 65536.0
02:43:13 | Overflow: setting loss scale to 32768.0
02:43:13 | Overflow: setting loss scale to 16384.0
loading: /data/private/language_model/git/ParlAI/data/msc/msc/msc_dialogue/session_2
cTraceback (most recent call last):
  File "/opt/conda/bin/parlai", line 33, in <module>
    sys.exit(load_entry_point('parlai', 'console_scripts', 'parlai')())
  File "/data/private/language_model/git/ParlAI/parlai/__main__.py", line 14, in main
    superscript_main()
  File "/data/private/language_model/git/ParlAI/parlai/core/script.py", line 325, in superscript_main
    return SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "/data/private/language_model/git/ParlAI/parlai/core/script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "/data/private/language_model/git/ParlAI/parlai/scripts/train_model.py", line 933, in run
    return self.train_loop.train()
  File "/data/private/language_model/git/ParlAI/parlai/scripts/train_model.py", line 897, in train
    for _train_log in self.train_steps():
  File "/data/private/language_model/git/ParlAI/parlai/scripts/train_model.py", line 804, in train_steps
    world.parley()
  File "/data/private/language_model/git/ParlAI/parlai/core/worlds.py", line 865, in parley
    batch_act = self.batch_act(agent_idx, batch_observations[agent_idx])
  File "/data/private/language_model/git/ParlAI/parlai/core/worlds.py", line 833, in batch_act
    batch_actions = a.batch_act(batch_observation)
  File "/data/private/language_model/git/ParlAI/parlai/core/torch_agent.py", line 2234, in batch_act
    output = self.train_step(batch)
  File "/data/private/language_model/git/ParlAI/parlai/core/torch_generator_agent.py", line 734, in train_step
    loss = self.compute_loss(batch)
  File "/data/private/language_model/git/ParlAI/projects/blenderbot2/agents/blenderbot2.py", line 833, in compute_loss
    loss, output = super().compute_loss(batch, return_output=True)
  File "/data/private/language_model/git/ParlAI/parlai/agents/rag/rag.py", line 836, in compute_loss
    model_output = self.get_model_output(batch)
  File "/data/private/language_model/git/ParlAI/parlai/agents/rag/rag.py", line 808, in get_model_output
    model_output = self.model(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/private/language_model/git/ParlAI/parlai/core/torch_generator_agent.py", line 309, in forward
    encoder_states = prev_enc if prev_enc is not None else self.encoder(*xs)
  File "/data/private/language_model/git/ParlAI/projects/blenderbot2/agents/modules.py", line 802, in encoder
    enc_out, mask, input_turns_cnt, top_docs, top_doc_scores = super().encoder(  # type: ignore
  File "/data/private/language_model/git/ParlAI/projects/blenderbot2/agents/modules.py", line 211, in encoder
    expanded_input, top_docs, top_doc_scores = self.retrieve_and_concat(
  File "/data/private/language_model/git/ParlAI/projects/blenderbot2/agents/modules.py", line 376, in retrieve_and_concat
    memories, memory_scores = self.access_long_term_memory(
  File "/data/private/language_model/git/ParlAI/projects/blenderbot2/agents/modules.py", line 554, in access_long_term_memory
    memory_dict = {
  File "/data/private/language_model/git/ParlAI/projects/blenderbot2/agents/modules.py", line 555, in <dictcomp>
    batch_id: memory_vec[batch_id, : num_memories[mem_id]]
IndexError: index 11 is out of bounds for dimension 0 with size 11
```

### environment
- ParlAI version 1.3.0
- torch 1.12.0

**Comment by klshuster** [comment]
Please consult the [agent FAQ](https://github.com/facebookresearch/ParlAI/tree/main/projects/blenderbot2/agents), as I believe your error may be resolved there

**Comment by robinsongh381** [comment]
@klshuster Thank you for reply.

I have already read the agent [FAQ page](https://github.com/facebookresearch/ParlAI/tree/main/projects/blenderbot2/agents), and it suggests to add `--memory-key full_text` arguemt - which i included in my script - but still the `IndexError` occurs.

```
  File "/data/private/language_model/git/ParlAI/projects/blenderbot2/agents/modules.py", line 555, in <dictcomp>
    batch_id: memory_vec[batch_id, : num_memories[mem_id]]
```

**Comment by robinsongh381** [comment]
or can you give me an example of script that allows fine-tuning blenderbot 1.0 on msc benchmark ?
I want to train the model `BST+MSC w/LT-Mem` explained [here](https://parl.ai/projects/blenderbot2/)

**Comment by klshuster** [comment]
are you on the latest parlai version? I ran your exact command and cannot reproduce your error

**Comment by robinsongh381** [comment]
I will have a look. Thank you !

**Comment by robinsongh381** [comment]
yes it works with `parlai==1.6.0`, thank you !
