### ISSUE TITLE
SeeKer running, but not searching [Windows]

### ISSUE THREAD

**Issue by Darth-Carrotpie** [facebookresearch/ParlAI#4697]
**Bug description**
I've been trying to run SeeKer for a while now, but with no success. First I'd like to mention a weird behavior, when initially loading any SeeKer model (this happened in both 3B and 400M versions), ParlAI first correctly downloads the model, but then proceeds to try deleting it, fails, then downloads a larger R2C2 blenderbot model for no apparent reason (no explanation messages).
Probably useful to mention, that I am attempting this on Windows and on a standalone/embedded Python version (no global paths), because I'm trying to make SeeKer cooperate with Unity :)

<details>
  <summary>Download Log</summary>
  
  
  ```javascript
16:16:52 | building data: C:\Users\carro\Documents\Unity Projects\Tests\SeekerTest\Assets\StreamingAssets\python-3.8.10\Lib\site-packages\parlai-1.6.0-py3.8.egg\data\models\seeker\seeker_dialogue_3B/model.tgz
16:16:52 | Downloading http://parl.ai/downloads/_models/seeker/seeker_dialogue_3B/model.tgz to C:\Users\carro\Documents\Unity Projects\Tests\SeekerTest\Assets\StreamingAssets\python-3.8.10\Lib\site-packages\parlai-1.6.0-py3.8.egg\data\models\seeker\seeker_dialogue_3B\model.tgz
Downloading model.tgz: 100%| 5.36G/5.36G [07:48<00:00, 11.4MB/s]

16:25:50 | Tried to delete C:\Users\carro\Documents\Unity Projects\Tests\SeekerTest\Assets\StreamingAssets\python-3.8.10\Lib\site-packages\parlai-1.6.0-py3.8.egg\data\models\seeker\seeker_dialogue_3B\model.tgz but got a permission error. This is known to happen in Windows and is probably not fatal.
16:25:50 | Overriding opt["init_opt"] to gen/seeker_dialogue (previously: None)
16:25:50 | Overriding opt["search_server"] to 127.0.0.1:8888 (previously: None)
16:25:50 | building data: C:\Users\carro\Documents\Unity Projects\Tests\SeekerTest\Assets\StreamingAssets\python-3.8.10\Lib\site-packages\parlai-1.6.0-py3.8.egg\data\models\seeker\r2c2_blenderbot_3B/model.tgz
16:25:50 | Downloading http://parl.ai/downloads/_models/seeker/r2c2_blenderbot_3B/model.tgz to C:\Users\carro\Documents\Unity Projects\Tests\SeekerTest\Assets\StreamingAssets\python-3.8.10\Lib\site-packages\parlai-1.6.0-py3.8.egg\data\models\seeker\r2c2_blenderbot_3B\model.tgz
Downloading model.tgz:
...
  ```
</details>

The real issues are:
- When run, SeeKer will not perform a search, no matter if the search API is available or not. This can be seen in search API console - no  POST requests are received;
- Replies with a single keyword within 'text' field, as opposed to an expected proper sentence. Seems like the keyword should have been what was supposed to be sent to search API instead of being replied to the Agent.
- 3B and 400M act the same, but one replies with 'camping' another - 'travel'

<details>
  <summary>Reply Example</summary>

  ```javascript
[I 220801 16:15:25 agents:55] Received new message: {'text': 'How would you spend your summer vacation?', 'payload': None, 'sender': {'id': 'cdc29cda-16e9-4946-8a9f-e02ef861d5dd'}, 'recipient': {'id': 0}}
===act====
How would you spend your summer vacation?
~~~~~~~~~~~
{'episode_done': False, 'text': 'How would you spend your summer vacation?', 'payload': None, 'full_text': 'How would you spend your summer vacation?', 'text_vec': tensor([    1,  2441,   565,   349,  4345,   538,  3935, 14604,    34,     2]), 'full_text_vec': [2441, 565, 349, 4345, 538, 3935, 14604, 34], 'context_original_length': 8, 'context_truncate_rate': False, 'context_truncated_length': 0, 'added_start_end_tokens': True, 'query_vec': [0]}
===response====
{'id': 'ComboFidGoldDocument', 'episode_done': False, 'text': 'camping', 'beam_texts': [('camping', -3.8510303497314453)], 'top_docs': [ID:
Title:
Text: , ID:
Title:
Text: , ID:
Title:
Text: , ID:
Title:
Text: , ID:
Title:
Text: ], 'metrics': {'clen': AverageMetric(8), 'ctrunc': AverageMetric(0), 'ctrunclen': AverageMetric(0), 'gen_n_toks': AverageMetric(4)}}
~~~~~~~~~~~
[I 220801 16:15:34 agents:40] Sending new message: {'id': 'ComboFidGoldDocument', 'episode_done': False, 'text': 'camping', 'beam_texts': [('camping', -3.8510303497314453)], 'top_docs': [ID:
    Title:
    Text: , ID:
    Title:
    Text: , ID:
    Title:
    Text: , ID:
    Title:
    Text: , ID:
    Title:
    Text: ], 'metrics': {'clen': AverageMetric(8), 'ctrunc': AverageMetric(0), 'ctrunclen': AverageMetric(0), 'gen_n_toks': AverageMetric(4)}}
  ```
  
</details>

Could this be silently falling back to some default behavior because of missing global paths/files?

**Reproduction steps**
I used task code bases and configs from [This Issue](https://github.com/facebookresearch/ParlAI/issues/4451) without any luck. Saw there [were issues](https://github.com/facebookresearch/ParlAI/blob/main/parlai/opt_presets/gen/seeker_dialogue.opt) for others with "gen" folder not being present and since it was missing in my case also (both pip and git pull versions) tried to manually copy them in for no effect.

**Expected behavior**
Run a search and reply with a sentence... :)
Also, not download additional 10 GB files if not needed/asked for.

**Additional context**
Probably also worth to mention, I've made some changes to ParlAI code to be able to run in windows, i.e. replaced `sh` with `shutil` like [suggested in other threads](https://github.com/facebookresearch/ParlAI/issues/4305).

<details>
  <summary>Run File</summary>

  `UnityAPIManager` class here is just an empty inheritance from `parlai.chat_service.services.websocket.websocket_manager`
  
  ```python
from parlai.core.params import ParlaiParser
from interface_manager import UnityAPIManager
import parlai.chat_service.utils.config as config_utils
from os import path


class ChatServiceRunner:

    def setup_args(self):
        """
        Set up args.
        :return: A parser that takes in command line arguments for chat services (debug, config-path, password), and a port.
        """
        parser = ParlaiParser(False, False)
        parser.add_parlai_data_path()
        #parser.add_model_args() #this is in config file, like --model, --model-file, -im, --dict-class
        #parser.add_websockets_args() #same code is bellow, which adds port
        #parser.add_chatservice_args() #adds require passwords, --debug, --config-path
        parser_grp = parser.add_argument_group('Websockets')
        parser_grp.add_argument('--port', default=34500, type=int, help='Port to run the browser chat server')
        parser_grp.add_argument('--debug', dest='is_debug', action='store_true', help='print and log all server interactions and messages',)
        parser_grp.add_argument(
            '--password',
            dest='password',
            type=str,
            default=None,
            help='Require a password for entry to the bot',
        )

        return parser.parse_args()

    def run(self):
        """
        Run UnityAPIManager.
        """
        self.opt['service'] = 'terminal'
        manager = UnityAPIManager(self.opt)
        try:
            manager.start_task()
        except BaseException:
            raise
        finally:
            manager.shutdown()

    def __init__(self):
        self.opt = self.setup_args()
        #config_path = opt.get('config_path')

    def setup(self, corePath):
        relPath = path.join(corePath, "src", "config.yml")
        print(relPath)
        config = config_utils.parse_configuration_file(relPath)
        self.opt.update(config['world_opt'])
        self.opt['config'] = config
  ```
  
</details>

<details>
  <summary>Main python file</summary>
  
- 'sys.path.append()' has to be called due to an embedded python version, otherwise local modules are not imported. 
- Some issue said nltk has to be installed and nltk.download called before running a model.
  

```python

import os
import sys
mydir = os.path.dirname(__file__)
sys.path.append(mydir)

from src.run import ChatServiceRunner
import nltk

class Seeker():
    response = ""
    custom_model_file = 'zoo:seeker/seeker_dialogue_400M/model',
    nltk.download('stopwords') #path is changeable, second argument is path override

    def run(self):
        self.chatServiceRunner = ChatServiceRunner()
        self.chatServiceRunner.setup(mydir)
        self.chatServiceRunner.run()

    def infer(self, UTTERANCE=""):
        pass

    def getOutput(self):
        return self.response


instance = Seeker()
instance.run()

```
</details>

**Configs tested**

Here are some configs which I've tried, some behaving differently than others...

<details>
  <summary>Minimal one, custom task/world</summary>
This config results in the outcome above.
  
  ```javascript
tasks:
  default:
    onboard_world: MyOnboardWorld
    task_world: MyTaskWorld
    timeout: 180
    agents_required: 1
task_name: mytask
world_module: src.worlds
overworld: SeekerMessengerOverworld
max_workers: 5
opt:
  debug: True
  models:
    seeker:
      interactive_mode: True
      model: projects.seeker.agents.seeker:SeekerAgent
      #model_file: zoo:seeker/seeker_dialogue_400M/model
      model_file: zoo:seeker/seeker_dialogue_3B/model
      init_opt: gen/seeker_dialogue
      search_server: 127.0.0.1:8888
      no_cuda: False
      override:
        no_cuda: False
        init_opt: gen/seeker_dialogue
        search_server: 127.0.0.1:8888

  ```
  
</details>

<details>
  <summary>Config2, custom task, detailed override</summary>

Acts exactly the same as the first one. Probably because first one loads init-opts which are identical to this, as to be expected I guess. 

  ```javascript
tasks:
  default:
    onboard_world: MyOnboardWorld
    task_world: MyTaskWorld
    timeout: 180
    agents_required: 1
task_name: mytask
world_module: src.worlds
overworld: SeekerMessengerOverworld
max_workers: 5
opt:
  debug: True
  models:
    seeker:
      interactive_mode: True
      model: projects.seeker.agents.seeker:SeekerAgent
      model_file: zoo:seeker/seeker_dialogue_400M/model # or zoo:seeker/seeker_dialogue_3B/model
      search_server: http://127.0.0.1:8888
      init_opt: gen/seeker_dialogue
      override:
        beam_disregard_knowledge_for_context_blocking: false
        datatype: valid
        drm_beam_block_full_context: true
        drm_beam_block_ngram: 3
        drm_beam_context_block_ngram: 3
        drm_beam_min_length: 20
        drm_beam_size: 10
        drm_inference: beam
        drm_message_mutators:
        drm_model: projects.seeker.agents.seeker:ComboFidSearchQueryAgent
        exclude_context_in_krm_context_blocking: false
        include_knowledge_in_krm_context_blocking: true
        inject_query_string:
        knowledge_response_control_token:
        krm_beam_block_ngram: 3
        krm_beam_context_block_ngram: 3
        krm_beam_min_length: 1
        krm_beam_size: 3
        krm_doc_chunks_ranker: woi_chunk_retrieved_docs
        krm_inference: beam
        krm_message_mutators:
        krm_model: projects.seeker.agents.seeker:ComboFidSearchQueryAgent
        krm_n_ranked_doc_chunks: 1
        krm_rag_retriever_type: search_engine
        krm_search_query_generator_model_file: "''"
        krm_search_server: http://127.0.0.1:8888
        loglevel: debug
        min_knowledge_length_when_search: 10
        sdm_beam_block_ngram: -1
        sdm_beam_min_length: 1
        sdm_beam_size: 1
        sdm_history_size: 4
        sdm_inference: greedy
        sdm_model: projects.seeker.agents.seeker:ComboFidSearchQueryAgent
        search_decision: always
        search_decision_control_token: __is-search-required__
        search_decision_do_search_reply: __do-search__
        search_decision_dont_search_reply: __do-not-search__
        search_query_control_token: __generate-query__
        sqm_beam_block_ngram: -1
        sqm_beam_min_length: 2
        sqm_beam_size: 1
        sqm_inference: beam
        sqm_model: projects.seeker.agents.seeker:ComboFidSearchQueryAgent
        no_cuda: False
        init_opt: gen/seeker_dialogue
        search_server: http://127.0.0.1:8888
        skip_generation: False

  ```
  
</details>

<details>
  <summary>Config 3, Demo Worlds</summary>
  
Now this errors out when trying to send something to the agent, gives a KeyError pasted bellow. The error then proceeds to infinitely loop. Really weird. I'd expect Demo to work, but I guess it's a windows thing?

  ```javascript
tasks:
  default:
    onboard_world: MessengerChatOnboardWorld
    task_world: MessengerChatTaskWorld
    timeout: 180
    agents_required: 1
task_name: overworld_demo
world_module: parlai.chat_service.tasks.overworld_demo.worlds
overworld: MessengerOverworld
max_workers: 30
opt:
  debug: True
  models:
    seeker:
      interactive_mode: True
      model: projects.seeker.agents.seeker:SeekerAgent
      model_file: zoo:seeker/seeker_dialogue_400M/model # or zoo:seeker/seeker_dialogue_3B/model
      override:
        beam_disregard_knowledge_for_context_blocking: false
        datatype: valid
        drm_beam_block_full_context: true
        drm_beam_block_ngram: 3
        drm_beam_context_block_ngram: 3
        drm_beam_min_length: 20
        drm_beam_size: 10
        drm_inference: beam
        drm_message_mutators:
        drm_model: projects.seeker.agents.seeker:ComboFidSearchQueryAgent
        exclude_context_in_krm_context_blocking: false
        include_knowledge_in_krm_context_blocking: true
        inject_query_string:
        knowledge_response_control_token:
        krm_beam_block_ngram: 3
        krm_beam_context_block_ngram: 3
        krm_beam_min_length: 1
        krm_beam_size: 3
        krm_doc_chunks_ranker: woi_chunk_retrieved_docs
        krm_inference: beam
        krm_message_mutators:
        krm_model: projects.seeker.agents.seeker:ComboFidSearchQueryAgent
        krm_n_ranked_doc_chunks: 1
        krm_rag_retriever_type: search_engine
        krm_search_query_generator_model_file: "''"
        krm_search_server: ''
        loglevel: debug
        min_knowledge_length_when_search: 10
        sdm_beam_block_ngram: -1
        sdm_beam_min_length: 1
        sdm_beam_size: 1
        sdm_history_size: 4
        sdm_inference: greedy
        sdm_model: projects.seeker.agents.seeker:ComboFidSearchQueryAgent
        search_decision: always
        search_decision_control_token: __is-search-required__
        search_decision_do_search_reply: __do-search__
        search_decision_dont_search_reply: __do-not-search__
        search_query_control_token: __generate-query__
        sqm_beam_block_ngram: -1
        sqm_beam_min_length: 2
        sqm_beam_size: 1
        sqm_inference: beam
        sqm_model: projects.seeker.agents.seeker:ComboFidSearchQueryAgent
        no_cuda: True
        init_opt: gen/seeker_dialogue
        search_server: 127.0.0.1:8888
        skip_generation: False

  ```
  
</details>

<details>
  <summary>KeyError:'chat'</summary>
  
  ```javascript
[I 220801 17:24:49 sockets:60] websocket message from client: {"id":"999111","text":"chat"}
[I 220801 17:24:49 agents:55] Received new message: {'text': 'chat', 'payload': None, 'sender': {'id': 'ca545a2e-b42d-4394-9ce7-2f31b0994078'}, 'recipient': {'id': 0}}
[I 220801 17:24:49 agents:40] Sending new message: {'id': 'Overworld', 'text': 'Transferring to chat'}
2022-08-01 17:24:49: Adding agent ca545a2e-b42d-4394-9ce7-2f31b0994078 to pool...
onboarding/overworld complete
[E 220801 17:24:50 ioloop:907] Exception in callback <bound method WebsocketManager._manager_loop_fn of <interface_manager.UnityAPIManager object at 0x0000018BE43CB700>>
    Traceback (most recent call last):
      File "C:\Users\carro\Documents\Unity Projects\Tests\SeekerTest\Assets\StreamingAssets\python-3.8.10\lib\site-packages\tornado\ioloop.py", line 905, in _run
        return self.callback()
      File "C:\Users\carro\Documents\Unity Projects\Tests\SeekerTest\Assets\StreamingAssets\python-3.8.10\lib\site-packages\parlai-1.6.0-py3.8.egg\parlai\chat_service\services\websocket\websocket_manager.py", line 101, in _manager_loop_fn
        world_config = self.task_configs[world_type]
    KeyError: 'chat'
[E 220801 17:24:50 ioloop:907] Exception in callback <bound method WebsocketManager._manager_loop_fn of <interface_manager.UnityAPIManager object at 0x0000018BE43CB700>>
    Traceback (most recent call last):
      File "C:\Users\carro\Documents\Unity Projects\Tests\SeekerTest\Assets\StreamingAssets\python-3.8.10\lib\site-packages\tornado\ioloop.py", line 905, in _run
        return self.callback()
      File "C:\Users\carro\Documents\Unity Projects\Tests\SeekerTest\Assets\StreamingAssets\python-3.8.10\lib\site-packages\parlai-1.6.0-py3.8.egg\parlai\chat_service\services\websocket\websocket_manager.py", line 101, in _manager_loop_fn
        world_config = self.task_configs[world_type]
    KeyError: 'chat'
  ```
  
</details>

**Comment by Darth-Carrotpie** [comment]
**Solved**
After adding this line to config under "override":
```
      override:
        model: projects.seeker.agents.seeker:SeekerAgent
```
It downloaded a few more files and magically started working! Still downloading lots of gigs of data though...
