### ISSUE TITLE
No module named 'fcntl' error during ParlAI installation

### ISSUE THREAD

**Issue by Eichhof** [facebookresearch/ParlAI#4722]
Hello

I would like to install the development version of ParlAI on Windows 10 on Python 3.9. I have cloned the repository and then I'm running `python setup.py develop`. Unfortunately, I'm getting the error shown below. fcntl is only supported on Unix, thus it does not work. Surprisingly, I was running ParlAI on Windows and Python 3.9 successfully some months ago, but I don't remember how I did it.

Does somebody know how to circumvent this error?

```
running develop
C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running egg_info
writing parlai.egg-info\PKG-INFO
writing dependency_links to parlai.egg-info\dependency_links.txt
writing entry points to parlai.egg-info\entry_points.txt
writing requirements to parlai.egg-info\requires.txt
writing top-level names to parlai.egg-info\top_level.txt
reading manifest file 'parlai.egg-info\SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'parlai.egg-info\SOURCES.txt'
running build_ext
Creating c:\users\myName\anaconda3\envs\parlai\lib\site-packages\parlai.egg-link (link to .)
parlai 1.6.0 is already the active version in easy-install.pth
Installing parlai-script.py script to C:\Users\myName\Anaconda3\envs\parlai\Scripts
Installing parlai.exe script to C:\Users\myName\Anaconda3\envs\parlai\Scripts

Installed c:\users\myName\parlai
Processing dependencies for parlai==1.6.0
Searching for sh
Reading https://pypi.org/simple/sh/
C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\pkg_resources\__init__.py:122: PkgResourcesDeprecationWarning: 0.106.linux-i686 is an invalid version and will not be supported in a future release
  warnings.warn(
C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\pkg_resources\__init__.py:122: PkgResourcesDeprecationWarning: i686 is an invalid version and will not be supported in a future release
  warnings.warn(
C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\pkg_resources\__init__.py:122: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
Downloading https://files.pythonhosted.org/packages/b7/09/89c28aaf2a49f226fef8587c90c6386bd2cc03a0295bc4ff7fc6ee43c01d/sh-1.14.3.tar.gz#sha256=e4045b6c732d9ce75d571c79f5ac2234edd9ae4f5fa9d59b09705082bdca18c7
Best match: sh 1.14.3
Processing sh-1.14.3.tar.gz
Writing C:\Users\myName\AppData\Local\Temp\easy_install-jllh0cyw\sh-1.14.3\setup.cfg
Running sh-1.14.3\setup.py -q bdist_egg --dist-dir C:\Users\myName\AppData\Local\Temp\easy_install-jllh0cyw\sh-1.14.3\egg-dist-tmp-_xinrkug
Traceback (most recent call last):
  File "C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\setuptools\sandbox.py", line 156, in save_modules
    yield saved
  File "C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
    yield
  File "C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\setuptools\sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\setuptools\sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "C:\Users\myName\AppData\Local\Temp\easy_install-jllh0cyw\sh-1.14.3\setup.py", line 5, in <module>
    # LICENSE file in the root directory of this source tree.
  File "C:\Users\myName\AppData\Local\Temp\easy_install-jllh0cyw\sh-1.14.3\sh.py", line 37, in <module>
ModuleNotFoundError: No module named 'fcntl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\myName\ParlAI\setup.py", line 29, in <module>
    setup(
  File "C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
    return run_commands(dist)
  File "C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
    dist.run_commands()
  File "C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\setuptools\dist.py", line 1214, in run_command
    super().run_command(command)
  File "C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
    cmd_obj.run()
  File "C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\setuptools\command\develop.py", line 34, in run
    self.install_for_development()
  File "C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\setuptools\command\develop.py", line 129, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\setuptools\command\easy_install.py", line 760, in process_distribution
    distros = WorkingSet([]).resolve(
  File "C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\pkg_resources\__init__.py", line 777, in resolve
    dist = best[req.key] = env.best_match(
  File "C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\pkg_resources\__init__.py", line 1062, in best_match
    return self.obtain(req, installer)
  File "C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\pkg_resources\__init__.py", line 1074, in obtain
    return installer(requirement)
  File "C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\setuptools\command\easy_install.py", line 687, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\setuptools\command\easy_install.py", line 713, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\setuptools\command\easy_install.py", line 906, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\setuptools\command\easy_install.py", line 1180, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\setuptools\command\easy_install.py", line 1164, in run_setup
    run_setup(setup_script, args)
  File "C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\setuptools\sandbox.py", line 262, in run_setup
    raise
  File "C:\Users\myName\Anaconda3\envs\parlai\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
    yield
  File "C:\Users\myName\Anaconda3\envs\parlai\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\setuptools\sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\setuptools\sandbox.py", line 143, in resume
    raise exc.with_traceback(self._tb)
  File "C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\setuptools\sandbox.py", line 156, in save_modules
    yield saved
  File "C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
    yield
  File "C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\setuptools\sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "C:\Users\myName\Anaconda3\envs\parlai\lib\site-packages\setuptools\sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "C:\Users\myName\AppData\Local\Temp\easy_install-jllh0cyw\sh-1.14.3\setup.py", line 5, in <module>
    # LICENSE file in the root directory of this source tree.
  File "C:\Users\myName\AppData\Local\Temp\easy_install-jllh0cyw\sh-1.14.3\sh.py", line 37, in <module>
ModuleNotFoundError: No module named 'fcntl'
```

**Comment by harrywillss** [comment]
How were you able to fix this? I cannot find a way around this issue.

**Comment by Eichhof** [comment]
You need to delete in requirements.txt sh==1.12.14.
