### ISSUE TITLE
BB3 30B Error

### ISSUE THREAD

**Issue by ildoonet** [facebookresearch/ParlAI#4741]
**Bug description**
Please enter a clear and concise description of what the bug is.

I see this : https://parl.ai/projects/bb3/

When I run this

```parlai interactive --init-opt gen/opt_bb3 --opt-server API_SERVER --loglevel debug --raw-search-server RELEVANT_SEARCH_SERVER````

I got below error.

```
Traceback (most recent call last):
  File "/root/anaconda3/bin/parlai", line 33, in <module>
    sys.exit(load_entry_point('parlai', 'console_scripts', 'parlai')())
  File "/data/private/dev/ParlAI/parlai/__main__.py", line 14, in main
    superscript_main()
  File "/data/private/dev/ParlAI/parlai/core/script.py", line 325, in superscript_main
    return SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "/data/private/dev/ParlAI/parlai/core/script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "/data/private/dev/ParlAI/parlai/scripts/interactive.py", line 118, in run
    return interactive(self.opt)
  File "/data/private/dev/ParlAI/parlai/scripts/interactive.py", line 84, in interactive
    agent = create_agent(opt, requireModelExists=True)
  File "/data/private/dev/ParlAI/parlai/core/agents.py", line 479, in create_agent
    model = model_class(opt)
  File "/data/private/dev/ParlAI/projects/bb3/agents/opt_bb3_agent.py", line 160, in __init__
    super().__init__(opt, shared)
  File "/data/private/dev/ParlAI/projects/bb3/agents/r2c2_bb3_agent.py", line 411, in __init__
    agent = self._init_top_agent(agent_opts)
  File "/data/private/dev/ParlAI/projects/bb3/agents/opt_bb3_agent.py", line 208, in _init_top_agent
    return create_agent(opt)
  File "/data/private/dev/ParlAI/parlai/core/agents.py", line 479, in create_agent
    model = model_class(opt)
  File "/data/private/dev/ParlAI/projects/bb3/agents/opt_api_agent.py", line 598, in __init__
    self.history = BB3PromptHistory(opt=opt, dictionary=self.dictionary)
  File "/data/private/dev/ParlAI/projects/bb3/agents/opt_api_agent.py", line 114, in __init__
    self.final_prefix = f"{self.module.opt_final_prefix()}:"
  File "/data/private/dev/ParlAI/projects/bb3/agents/module.py", line 186, in opt_final_prefix
    import parlai_internal.projects.blenderbot3.agents.prompts as PROMPT
ModuleNotFoundError: No module named 'parlai_internal'
```

**Reproduction steps**
Enter steps to reproduce the behavior.

**Expected behavior**
Give a clear and concise description of what you expected to happen.

**Logs**
Please paste the command line output:

```
Output goes here
```

**Additional context**
Add any other context about the problem here. (like proxy settings, network setup, overall goals, etc.)

I guess that the code for 30B model is not released yet. Right?

**Comment by ildoonet** [comment]
@klshuster I hosted 30B model using metaseq API and then run below command

`parlai interactive --init-opt gen/opt_bb3 --opt-server API_SERVER --loglevel debug --raw-search-server RELEVANT_SEARCH_SERVER`

I guess that 'parlai_internal' package is not included in the public repository.

**Comment by ildoonet** [comment]
@klshuster This is resolved after I pulled the recent code. Thanks.

**Comment by guialfaro053** [comment]
I am trying to run BB3 30B as well, but when I run `metaseq-api-local` I find many errors even after changing the values in the `constants.py`. Would you mind sharing how you did that setting? Thanks!

**Comment by klshuster** [comment]
Could you paste your stack trace? I can try to help but it may be more fruitful to file an issue in that repo

**Comment by guialfaro053** [comment]
I tried reinstalling all the packages but now I get the following error:

`
Traceback (most recent call last):
  File "/home/Guillermo/anaconda3/envs/chatbots/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/Guillermo/anaconda3/envs/chatbots/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/Guillermo/metaseq/metaseq/__init__.py", line 20, in <module>
    from metaseq.distributed import utils as distributed_utils
  File "/home/Guillermo/metaseq/metaseq/distributed/__init__.py", line 6, in <module>
    from .distributed_timeout_wrapper import DistributedTimeoutWrapper
  File "/home/Guillermo/metaseq/metaseq/distributed/distributed_timeout_wrapper.py", line 11, in <module>
    from torch import nn
  File "/home/Guillermo/anaconda3/envs/chatbots/lib/python3.9/site-packages/torch/__init__.py", line 811, in <module>
    from .functional import *  # noqa: F403
  File "/home/Guillermo/anaconda3/envs/chatbots/lib/python3.9/site-packages/torch/functional.py", line 7, in <module>
    import torch.nn.functional as F
  File "/home/Guillermo/anaconda3/envs/chatbots/lib/python3.9/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/home/Guillermo/anaconda3/envs/chatbots/lib/python3.9/site-packages/torch/nn/modules/__init__.py", line 2, in <module>
    from .linear import Identity, Linear, Bilinear, LazyLinear
  File "/home/Guillermo/anaconda3/envs/chatbots/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 7, in <module>
    from .. import functional as F
  File "/home/Guillermo/anaconda3/envs/chatbots/lib/python3.9/site-packages/torch/nn/functional.py", line 18, in <module>
    from .._jit_internal import boolean_dispatch, _overload, BroadcastingList1, BroadcastingList2, BroadcastingList3
  File "/home/Guillermo/anaconda3/envs/chatbots/lib/python3.9/site-packages/torch/_jit_internal.py", line 25, in <module>
    import torch.distributed.rpc
  File "/home/Guillermo/anaconda3/envs/chatbots/lib/python3.9/site-packages/torch/distributed/__init__.py", line 55, in <module>
    from .distributed_c10d import *  # noqa: F403
  File "/home/Guillermo/anaconda3/envs/chatbots/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 63, in <module>
    logger = logging.getLogger(__name__)
AttributeError: module 'logging' has no attribute 'getLogger'
`

I don't understand why that problem arises now
