### ISSUE TITLE
Heroku Buildpack error

### ISSUE THREAD

**Issue by omi-akif** [facebookresearch/ParlAI#4795]
Hello. I wanted to try out the Chat Services of ParlAI by typing the command: 

python parlai/chat_service/services/messenger/run.py --config-path parlai/chat_service/tasks/chatbot/config.yml

I encounter an error. 

The error message:

You are going to allow people on Facebook to be agents in ParlAI.
During this process, Internet connection is required, and you should turn off your computer's auto-sleep feature.

Please press Enter to continue... 

Setting up Messenger webhook...
Heroku: Collecting files...
Heroku: Starting server...
Enabling http-session-affinity for hummer-parlai-messenger-chatbo... done
Traceback (most recent call last):
  File "/mnt/f/ParlAI/ParlAI/parlai/chat_service/services/messenger/run.py", line 47, in <module>
    run(opt)
  File "/mnt/f/ParlAI/ParlAI/parlai/chat_service/services/messenger/run.py", line 32, in run
    manager = MessengerManager(opt)
  File "/mnt/f/R_D_ENV/nlp/lib/python3.10/site-packages/parlai/chat_service/services/messenger/messenger_manager.py", line 43, in __init__
    self._complete_setup()
  File "/mnt/f/R_D_ENV/nlp/lib/python3.10/site-packages/parlai/chat_service/services/messenger/messenger_manager.py", line 63, in _complete_setup
    self.setup_server()
  File "/mnt/f/R_D_ENV/nlp/lib/python3.10/site-packages/parlai/chat_service/services/messenger/messenger_manager.py", line 210, in setup_server
    self.server_url = server_utils.setup_server(
  File "/mnt/f/R_D_ENV/nlp/lib/python3.10/site-packages/parlai/chat_service/utils/server.py", line 284, in setup_server
    return setup_heroku_server(task_name)
  File "/mnt/f/R_D_ENV/nlp/lib/python3.10/site-packages/parlai/chat_service/utils/server.py", line 191, in setup_heroku_server
    sh.git(shlex.split('push -f heroku master'))
  File "/mnt/f/R_D_ENV/nlp/lib/python3.10/site-packages/sh.py", line 1524, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/mnt/f/R_D_ENV/nlp/lib/python3.10/site-packages/sh.py", line 788, in __init__
    self.wait()
  File "/mnt/f/R_D_ENV/nlp/lib/python3.10/site-packages/sh.py", line 845, in wait
    self.handle_command_exit_code(exit_code)
  File "/mnt/f/R_D_ENV/nlp/lib/python3.10/site-packages/sh.py", line 869, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/git push -f heroku master

  STDOUT:

  STDERR:
remote: Compressing source files... done.        
remote: Building source:        
remote: 
remote: -----> Building on the Heroku-22 stack        
remote: -----> Determining which buildpack to use for this app        
remote:  !     No default language could be detected for this app.        
remote: 			HINT: This occurs when Heroku cannot detect the buildpack to use for this application automatically.        
remote: 			See https://devcenter.heroku.com/articles/buildpacks        
remote: 
remote:  !     Push failed        
remote: Verifying deploy....        
remote: 
remote: !	Push rejected to hummer-parlai-messenger-chatbo.        
remote: 
To https://git.heroku.com/hummer-parlai-messenger-chatbo.git
 ! [remote rejected] master -> master ... (123 more, please see e.stderr)

Could it be that the ParlAI is creating a heroku app without mentioning the build packs? Is there any way around for this problem?

**Comment by klshuster** [comment]
have you set up your heroku credentials?

**Comment by omi-akif** [comment]
Yes @klshuster, I have done that. I tried to follow this [guide](https://parl.ai/docs/tutorial_chat_service.html) of ParlAI chat service. I tried to follow the steps mentioned. No Webhook URL was posted. I am also logged in heroku-cli.

**Comment by klshuster** [comment]
Maybe CC @JackUrb who might know why heroku is not working here. Have you searched elsewhere for this issue? It may not be related to ParlAI specifically?

**Comment by omi-akif** [comment]
Hey @klshuster . I believe this could be something related to the [server setup](https://github.com/facebookresearch/ParlAI/blob/main/parlai/chat_service/utils/server.py) code. I am currently trying to debug this.

Hey @JackUrb . I am trying to look a way on how to rewrite the script of [server.py](https://github.com/facebookresearch/ParlAI/blob/main/parlai/chat_service/utils/server.py) to see if I can find some good results. Could you please keep the issue open for one or two weeks so that I can manage to find a solution for this?

**Comment by klshuster** [comment]
Yes, feel free to come back and update us when you find something!
