### ISSUE TITLE
The interactive script finishes its operation when you press ENTER in the first question.

### ISSUE THREAD

**Issue by jacek-michalak** [facebookresearch/ParlAI#4799]
parlai i -mf zoo:seeker/r2c2_blenderbot_3B/model

**Logs**:

Enter Your Message: 
Traceback (most recent call last):
  File "/usr/local/bin/parlai", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/parlai/__main__.py", line 14, in main
    superscript_main()
  File "/usr/local/lib/python3.8/dist-packages/parlai/core/script.py", line 325, in superscript_main
    return SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "/usr/local/lib/python3.8/dist-packages/parlai/core/script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "/usr/local/lib/python3.8/dist-packages/parlai/scripts/interactive.py", line 118, in run
    return interactive(self.opt)
  File "/usr/local/lib/python3.8/dist-packages/parlai/scripts/interactive.py", line 93, in interactive
    world.parley()
  File "/usr/local/lib/python3.8/dist-packages/parlai/tasks/interactive/worlds.py", line 89, in parley
    acts[1] = agents[1].act()
  File "/usr/local/lib/python3.8/dist-packages/parlai/core/torch_agent.py", line 2149, in act
    self.self_observe(response)
  File "/usr/local/lib/python3.8/dist-packages/parlai/core/torch_agent.py", line 1926, in self_observe
    last_reply = self_message['text']
KeyError: 'text'

**Comment by klshuster** [comment]
I ran your exact command and cannot repro. Is there something else you're doing? Have you installed the latest parlai?

**Comment by jacek-michalak** [comment]
Yes I installed the latest parlai.

sudo pip install parlai
sudo parlai i -mf zoo:seeker/r2c2_blenderbot_3B/model

I install as root because r2c2_blenderbot_3B is the ONLY chatbot on my Linux PC
