### ISSUE TITLE
BB3Retriever object has no attribute search_queries

### ISSUE THREAD

**Issue by YufeiT** [facebookresearch/ParlAI#4830]
**Bug description**
Running ` parlai interactive --model projects.bb3.agents.r2c2_bb3_agent:BB3SubSearchAgent --model-file zoo:bb3/bb3_3B/model --rag-retriever-type search_engine --search-server MRM` or with any module crash right after first message.

**Reproduction steps**
` parlai interactive --model projects.bb3.agents.r2c2_bb3_agent:BB3SubSearchAgent --model-file zoo:bb3/bb3_3B/model --rag-retriever-type search_engine --search-server MRM`
I have tried to replace MRM with other modules or set up a search engine from [ParlAI_SearchEngine](https://github.com/JulesGM/ParlAI_SearchEngine)

**Expected behavior**
Expect to get response from chatbot

**Logs**

```
(venv) (base) yufeitao@MacBook-Pro ParlAI-1.7.1 % parlai interactive --model projects.bb3.agents.r2c2_bb3_agent:BB3SubSearchAgent --model-file zoo:bb3/bb3_3B/model --rag-retriever-type search_engine --search-server MRM
14:34:19 | Please install spacy: pip install spacy
14:34:19 | Please install spacy: pip install spacy
14:34:19 | Overriding opt["model"] to projects.bb3.agents.r2c2_bb3_agent:BB3SubSearchAgent (previously: projects.seeker.agents.seeker:ComboFidGoldDocumentAgent)
14:34:19 | Overriding opt["model_file"] to /Users/yufeitao/Desktop/ParlAI-1.7.1/data/models/bb3/bb3_3B/model (previously: zoo:bb3/bb3_3B/model)
14:34:19 | Overriding opt["rag_retriever_type"] to search_engine (previously: observation_echo_retriever)
14:34:19 | your model is being loaded with opts that do not exist in the model you are initializing the weights with: evaltask: projects.bb3.tasks.module_level_tasks:AlwaysSearchTeacher,projects.bb3.tasks.module_level_tasks:MaybeSearchTeacher,projects.bb3.tasks.module_level_tasks:MemoryDecisionTeacher,projects.bb3.tasks.module_level_tasks:SearchQueryGenerationTeacher,projects.bb3.tasks.module_level_tasks:MemoryGenerationTeacher,projects.bb3.tasks.module_level_tasks:MemoryKnowledgeGenerationTeacher,projects.bb3.tasks.module_level_tasks:SearchKnowledgeGenerationTeacher,projects.bb3.tasks.module_level_tasks:EntityKnowledgeGenerationTeacher,projects.bb3.tasks.module_level_tasks:SearchDialogueGenerationTeacher,projects.bb3.tasks.module_level_tasks:EntityDialogueGenerationTeacher,projects.bb3.tasks.module_level_tasks:MemoryDialogueGenerationTeacher,projects.bb3.tasks.module_level_tasks:VanillaDialogueGenerationTeacher,final_extra_opt: ,eval_batchsize: None,eval_dynamic_batching: None,num_workers: 0,display_examples: False,num_epochs: -1,max_train_time: -1,max_train_steps: -1,log_every_n_steps: 50,validation_every_n_secs: -1,validation_every_n_steps: 1000,save_every_n_secs: -1,save_after_valid: True,validation_every_n_epochs: -1,validation_max_exs: 100000,short_final_eval: False,validation_patience: 10,validation_metric: ppl,validation_metric_mode: min,validation_cutoff: 1.0,validation_share_agent: False,metrics: default,aggregate_micro: False,world_logs: ,save_format: conversations,log_keep_fields: all,tensorboard_log: False,tensorboard_logdir: None,dict_maxexs: -1,dict_include_valid: False,dict_include_test: False,log_every_n_secs: -1,distributed_world_size: 64,ddp_backend: zero2,port: 36973,mutators: None,jsonfile_datapath: None,jsonfile_datatype_extension: False,label_turns: secondspeaker,filter_for_label: None,num_shards: 1,shard_id: 0,candidates: inline,eval_candidates: inline,interactive_candidates: fixed,repeat_blocking_heuristic: True,fixed_candidates_path: None,fixed_candidate_vecs: reuse,encode_candidate_vecs: True,encode_candidate_vecs_batchsize: 256,train_predict: False,cap_num_predictions: 100,ignore_bad_candidates: False,rank_top_k: -1,return_cand_scores: False,use_memories: False,wrap_memory_encoder: False,memory_attention: sqrt,normalize_sent_emb: False,share_encoders: True,learn_embeddings: True,data_parallel: False,reduction_type: mean,polyencoder_type: codes,poly_n_codes: 64,poly_attention_type: basic,poly_attention_num_heads: 4,codes_attention_type: basic,codes_attention_num_heads: 4,generation_model: bart,query_model: bert,rag_model_type: token,thorough: False,n_extra_positions: 0,gold_knowledge_passage_key: checked_sentence,gold_knowledge_title_key: title,rag_retriever_query: full_history,rag_retriever_type: search_engine,retriever_debug_index: None,n_docs: 5,min_doc_token_length: 64,max_doc_token_length: 256,rag_query_truncate: 512,print_docs: False,path_to_index: zoo:hallucination/wiki_index_compressed/compressed_pq,path_to_dense_embeddings: None,dpr_model_file: zoo:hallucination/multiset_dpr/hf_bert_base.cp,path_to_dpr_passages: zoo:hallucination/wiki_passages/psgs_w100.tsv,retriever_embedding_size: 768,tfidf_max_doc_paragraphs: -1,tfidf_model_path: zoo:wikipedia_full/tfidf_retriever/model,dpr_num_docs: 25,poly_score_initial_lambda: 0.5,polyencoder_init_model: wikito,poly_faiss_model_file: None,regret: False,regret_intermediate_maxlen: 32,regret_model_file: None,regret_dict_file: None,regret_override_index: False,indexer_type: compressed,indexer_buffer_size: 65536,compressed_indexer_factory: IVF4096_HNSW128,PQ128,compressed_indexer_gpu_train: False,compressed_indexer_nprobe: 64,hnsw_indexer_store_n: 128,hnsw_ef_search: 128,hnsw_ef_construction: 200,rag_turn_n_turns: 2,rag_turn_marginalize: doc_then_turn,rag_turn_discount_factor: 1.0,t5_model_arch: t5-base,t5_model_parallel: False,t5_dropout: 0.0,t5_generation_config: None,search_query_generator_model_file: None,search_query_generator_inference: greedy,search_query_generator_beam_min_length: 1,search_query_generator_beam_size: 1,search_query_generator_text_truncate: 512,splitted_chunk_length: 256,doc_chunk_split_mode: word,n_ranked_doc_chunks: 1,doc_chunks_ranker: head,woi_doc_chunk_size: 500,skip_retrieval_key: skip_retrieval,serializable: False,rank: 0,dict_loaded: True,search_server: MRM,download_path: None,verbose: False,datapath: /Users/yufeitao/Desktop/ParlAI-1.7.1/data,display_prettify: False,display_add_fields: ,interactive_task: True,outfile: ,local_human_candidates_file: None,single_turn: False,gpu_beam_blocking: False,interactive_mode: True,force_skip_retrieval: False
14:34:19 | your model is being loaded with opts that differ from the model you are initializing the weights with. Add the following args to your run command to change this: 
--init-opt None --task blended_skill_talk,wizard_of_wikipedia:Generator,convai2:normalized,empathetic_dialogues --multitask-weights 1.0,3.0,3.0,3.0 --batchsize 2 --dynamic-batching full --model bart --beam-size 10 --beam-min-length 20 --beam-context-block-ngram 3 --beam-block-ngram 3 --skip-generation False --inference beam --truncate 1022 --text-truncate 1000 --label-truncate 1000
14:34:19 | loading dictionary from /Users/yufeitao/Desktop/ParlAI-1.7.1/data/models/bb3/bb3_3B/model.dict
14:34:19 | num words = 50264
14:34:19 | BB3SubSearch: full interactive mode on.
14:34:22 | Not initializing SQ Generator *within* retriever
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
14:34:25 | Creating the search engine retriever.
14:34:25 | No protocol provided, using "http://"
14:34:53 | Total parameters: 2,801,167,872 (2,800,774,656 trainable)
14:34:53 | Loading existing model params from /Users/yufeitao/Desktop/ParlAI-1.7.1/data/models/bb3/bb3_3B/model
14:35:16 | Opt:
14:35:16 |     activation: gelu
14:35:16 |     adafactor_eps: '[1e-30, 0.001]'
14:35:16 |     adam_eps: 1e-08
14:35:16 |     add_p1_after_newln: False
14:35:16 |     aggregate_micro: False
14:35:16 |     allow_missing_init_opts: False
14:35:16 |     attention_dropout: 0.0
14:35:16 |     batchsize: 1
14:35:16 |     beam_block_full_context: True
14:35:16 |     beam_block_list_filename: None
14:35:16 |     beam_block_ngram: -1
14:35:16 |     beam_context_block_ngram: -1
14:35:16 |     beam_delay: 30
14:35:16 |     beam_length_penalty: 0.65
14:35:16 |     beam_min_length: 1
14:35:16 |     beam_size: 1
14:35:16 |     betas: '[0.9, 0.999]'
14:35:16 |     bpe_add_prefix_space: None
14:35:16 |     bpe_debug: False
14:35:16 |     bpe_dropout: None
14:35:16 |     bpe_merge: None
14:35:16 |     bpe_vocab: None
14:35:16 |     candidates: inline
14:35:16 |     cap_num_predictions: 100
14:35:16 |     checkpoint_activations: True
14:35:16 |     codes_attention_num_heads: 4
14:35:16 |     codes_attention_type: basic
14:35:16 |     compressed_indexer_factory: IVF4096_HNSW128,PQ128
14:35:16 |     compressed_indexer_gpu_train: False
14:35:16 |     compressed_indexer_nprobe: 64
14:35:16 |     compute_tokenized_bleu: False
14:35:16 |     data_parallel: False
14:35:16 |     datapath: /Users/yufeitao/Desktop/ParlAI-1.7.1/data
14:35:16 |     datatype: train
14:35:16 |     ddp_backend: zero2
14:35:16 |     delimiter: '\n'
14:35:16 |     dict_class: parlai.core.dict:DictionaryAgent
14:35:16 |     dict_endtoken: __end__
14:35:16 |     dict_file: /Users/yufeitao/Desktop/ParlAI-1.7.1/data/models/bb3/bb3_3B/model.dict
14:35:16 |     dict_include_test: False
14:35:16 |     dict_include_valid: False
14:35:16 |     dict_initpath: None
14:35:16 |     dict_language: english
14:35:16 |     dict_loaded: True
14:35:16 |     dict_lower: False
14:35:16 |     dict_max_ngram_size: -1
14:35:16 |     dict_maxexs: -1
14:35:16 |     dict_maxtokens: -1
14:35:16 |     dict_minfreq: 0
14:35:16 |     dict_nulltoken: __null__
14:35:16 |     dict_starttoken: __start__
14:35:16 |     dict_textfields: text,labels
14:35:16 |     dict_tokenizer: gpt2
14:35:16 |     dict_unktoken: __unk__
14:35:16 |     display_add_fields: 
14:35:16 |     display_examples: False
14:35:16 |     display_prettify: False
14:35:16 |     distributed_world_size: 64
14:35:16 |     doc_chunk_split_mode: word
14:35:16 |     doc_chunks_ranker: head
14:35:16 |     download_path: None
14:35:16 |     dpr_model_file: zoo:hallucination/multiset_dpr/hf_bert_base.cp
14:35:16 |     dpr_num_docs: 25
14:35:16 |     dropout: 0.1
14:35:16 |     dynamic_batching: None
14:35:16 |     embedding_projection: random
14:35:16 |     embedding_size: 2048
14:35:16 |     embedding_type: random
14:35:16 |     embeddings_scale: True
14:35:16 |     encode_candidate_vecs: True
14:35:16 |     encode_candidate_vecs_batchsize: 256
14:35:16 |     eval_batchsize: None
14:35:16 |     eval_candidates: inline
14:35:16 |     eval_dynamic_batching: None
14:35:16 |     evaltask: projects.bb3.tasks.module_level_tasks:AlwaysSearchTeacher,projects.bb3.tasks.module_level_tasks:MaybeSearchTeacher,projects.bb3.tasks.module_level_tasks:MemoryDecisionTeacher,projects.bb3.tasks.module_level_tasks:SearchQueryGenerationTeacher,projects.bb3.tasks.module_level_tasks:MemoryGenerationTeacher,projects.bb3.tasks.module_level_tasks:MemoryKnowledgeGenerationTeacher,projects.bb3.tasks.module_level_tasks:SearchKnowledgeGenerationTeacher,projects.bb3.tasks.module_level_tasks:EntityKnowledgeGenerationTeacher,projects.bb3.tasks.module_level_tasks:SearchDialogueGenerationTeacher,projects.bb3.tasks.module_level_tasks:EntityDialogueGenerationTeacher,projects.bb3.tasks.module_level_tasks:MemoryDialogueGenerationTeacher,projects.bb3.tasks.module_level_tasks:VanillaDialogueGenerationTeacher
14:35:16 |     ffn_size: 8192
14:35:16 |     filter_for_label: None
14:35:16 |     final_extra_opt: 
14:35:16 |     fixed_candidate_vecs: reuse
14:35:16 |     fixed_candidates_path: None
14:35:16 |     force_fp16_tokens: True
14:35:16 |     force_skip_retrieval: False
14:35:16 |     fp16: True
14:35:16 |     fp16_impl: safe
14:35:16 |     generation_model: bart
14:35:16 |     gold_knowledge_passage_key: checked_sentence
14:35:16 |     gold_knowledge_title_key: title
14:35:16 |     gpu: 0
14:35:16 |     gpu_beam_blocking: False
14:35:16 |     gradient_clip: 1.0
14:35:16 |     hide_labels: False
14:35:16 |     history_add_global_end_token: end
14:35:16 |     history_reversed: False
14:35:16 |     history_size: -1
14:35:16 |     hnsw_ef_construction: 200
14:35:16 |     hnsw_ef_search: 128
14:35:16 |     hnsw_indexer_store_n: 128
14:35:16 |     ignore_bad_candidates: False
14:35:16 |     image_cropsize: 224
14:35:16 |     image_mode: raw
14:35:16 |     image_size: 256
14:35:16 |     indexer_buffer_size: 65536
14:35:16 |     indexer_type: compressed
14:35:16 |     inference: greedy
14:35:16 |     init_fairseq_model: None
14:35:16 |     init_model: /Users/yufeitao/Desktop/ParlAI-1.7.1/data/models/seeker/r2c2_blenderbot_3B/model
14:35:16 |     init_opt: arch/r2c2_base_3B
14:35:16 |     interactive_candidates: fixed
14:35:16 |     interactive_mode: True
14:35:16 |     interactive_task: True
14:35:16 |     invsqrt_lr_decay_gamma: -1
14:35:16 |     is_debug: False
14:35:16 |     jsonfile_datapath: None
14:35:16 |     jsonfile_datatype_extension: False
14:35:16 |     label_truncate: 128
14:35:16 |     label_turns: secondspeaker
14:35:16 |     learn_embeddings: True
14:35:16 |     learn_positional_embeddings: True
14:35:16 |     learningrate: 1e-06
14:35:16 |     local_human_candidates_file: None
14:35:16 |     log_every_n_secs: -1
14:35:16 |     log_every_n_steps: 50
14:35:16 |     log_keep_fields: all
14:35:16 |     loglevel: info
14:35:16 |     lr_scheduler: reduceonplateau
14:35:16 |     lr_scheduler_decay: 0.5
14:35:16 |     lr_scheduler_patience: 3
14:35:16 |     max_doc_token_length: 256
14:35:16 |     max_train_steps: -1
14:35:16 |     max_train_time: -1
14:35:16 |     memory_attention: sqrt
14:35:16 |     metrics: default
14:35:16 |     min_doc_token_length: 64
14:35:16 |     model: projects.bb3.agents.r2c2_bb3_agent:BB3SubSearchAgent
14:35:16 |     model_file: /Users/yufeitao/Desktop/ParlAI-1.7.1/data/models/bb3/bb3_3B/model
14:35:16 |     model_parallel: False
14:35:16 |     momentum: 0
14:35:16 |     multitask_weights: [1]
14:35:16 |     mutators: None
14:35:16 |     n_decoder_layers: 22
14:35:16 |     n_docs: 5
14:35:16 |     n_encoder_layers: 22
14:35:16 |     n_extra_positions: 0
14:35:16 |     n_heads: 32
14:35:16 |     n_layers: 22
14:35:16 |     n_positions: 1024
14:35:16 |     n_ranked_doc_chunks: 1
14:35:16 |     n_segments: 0
14:35:16 |     nesterov: True
14:35:16 |     no_cuda: False
14:35:16 |     normalize_sent_emb: False
14:35:16 |     num_epochs: -1
14:35:16 |     num_shards: 1
14:35:16 |     num_workers: 0
14:35:16 |     nus: [0.7]
14:35:16 |     optimizer: adamw
14:35:16 |     outfile: 
14:35:16 |     output_conversion_path: None
14:35:16 |     output_scaling: 1
14:35:16 |     override: "{'model': 'projects.bb3.agents.r2c2_bb3_agent:BB3SubSearchAgent', 'model_file': '/Users/yufeitao/Desktop/ParlAI-1.7.1/data/models/bb3/bb3_3B/model', 'rag_retriever_type': 'search_engine', 'search_server': 'MRM'}"
14:35:16 |     parlai_home: /private/home/kshuster/ParlAI
14:35:16 |     path_to_dense_embeddings: None
14:35:16 |     path_to_dpr_passages: zoo:hallucination/wiki_passages/psgs_w100.tsv
14:35:16 |     path_to_index: zoo:hallucination/wiki_index_compressed/compressed_pq
14:35:16 |     person_tokens: False
14:35:16 |     poly_attention_num_heads: 4
14:35:16 |     poly_attention_type: basic
14:35:16 |     poly_faiss_model_file: None
14:35:16 |     poly_n_codes: 64
14:35:16 |     poly_score_initial_lambda: 0.5
14:35:16 |     polyencoder_init_model: wikito
14:35:16 |     polyencoder_type: codes
14:35:16 |     port: 36973
14:35:16 |     print_docs: False
14:35:16 |     query_model: bert
14:35:16 |     rag_model_type: token
14:35:16 |     rag_query_truncate: 512
14:35:16 |     rag_retriever_query: full_history
14:35:16 |     rag_retriever_type: search_engine
14:35:16 |     rag_turn_discount_factor: 1.0
14:35:16 |     rag_turn_marginalize: doc_then_turn
14:35:16 |     rag_turn_n_turns: 2
14:35:16 |     rank: 0
14:35:16 |     rank_candidates: False
14:35:16 |     rank_top_k: -1
14:35:16 |     reduction_type: mean
14:35:16 |     regret: False
14:35:16 |     regret_dict_file: None
14:35:16 |     regret_intermediate_maxlen: 32
14:35:16 |     regret_model_file: None
14:35:16 |     regret_override_index: False
14:35:16 |     relu_dropout: 0.0
14:35:16 |     repeat_blocking_heuristic: True
14:35:16 |     retriever_debug_index: None
14:35:16 |     retriever_embedding_size: 768
14:35:16 |     return_cand_scores: False
14:35:16 |     save_after_valid: True
14:35:16 |     save_every_n_secs: -1
14:35:16 |     save_format: conversations
14:35:16 |     search_query_generator_beam_min_length: 1
14:35:16 |     search_query_generator_beam_size: 1
14:35:16 |     search_query_generator_inference: greedy
14:35:16 |     search_query_generator_model_file: None
14:35:16 |     search_query_generator_text_truncate: 512
14:35:16 |     search_server: MRM
14:35:16 |     serializable: False
14:35:16 |     shard_id: 0
14:35:16 |     share_encoders: True
14:35:16 |     share_word_embeddings: True
14:35:16 |     short_final_eval: False
14:35:16 |     single_turn: False
14:35:16 |     skip_generation: True
14:35:16 |     skip_retrieval_key: skip_retrieval
14:35:16 |     skip_retrieval_token: no_passages_used
14:35:16 |     special_tok_lst: None
14:35:16 |     split_lines: True
14:35:16 |     splitted_chunk_length: 256
14:35:16 |     starttime: May11_16-58
14:35:16 |     t5_dropout: 0.0
14:35:16 |     t5_generation_config: None
14:35:16 |     t5_model_arch: t5-base
14:35:16 |     t5_model_parallel: False
14:35:16 |     task: projects.bb3.tasks.module_level_tasks:AlwaysSearchTeacher,projects.bb3.tasks.module_level_tasks:MaybeSearchTeacher,projects.bb3.tasks.module_level_tasks:MemoryDecisionTeacher,projects.bb3.tasks.module_level_tasks:SearchQueryGenerationTeacher,projects.bb3.tasks.module_level_tasks:MemoryGenerationTeacher,projects.bb3.tasks.module_level_tasks:MemoryKnowledgeGenerationTeacher,projects.bb3.tasks.module_level_tasks:SearchKnowledgeGenerationTeacher,projects.bb3.tasks.module_level_tasks:EntityKnowledgeGenerationTeacher,projects.bb3.tasks.module_level_tasks:SearchDialogueGenerationTeacher,projects.bb3.tasks.module_level_tasks:EntityDialogueGenerationTeacher,projects.bb3.tasks.module_level_tasks:MemoryDialogueGenerationTeacher,projects.bb3.tasks.module_level_tasks:VanillaDialogueGenerationTeacher
14:35:16 |     temperature: 1.0
14:35:16 |     tensorboard_log: False
14:35:16 |     tensorboard_logdir: None
14:35:16 |     text_truncate: 1024
14:35:16 |     tfidf_max_doc_paragraphs: -1
14:35:16 |     tfidf_model_path: zoo:wikipedia_full/tfidf_retriever/model
14:35:16 |     thorough: False
14:35:16 |     topk: 10
14:35:16 |     topp: 0.9
14:35:16 |     train_predict: False
14:35:16 |     truncate: 1024
14:35:16 |     update_freq: 1
14:35:16 |     use_memories: False
14:35:16 |     use_reply: label
14:35:16 |     validation_cutoff: 1.0
14:35:16 |     validation_every_n_epochs: -1
14:35:16 |     validation_every_n_secs: -1
14:35:16 |     validation_every_n_steps: 1000
14:35:16 |     validation_max_exs: 100000
14:35:16 |     validation_metric: ppl
14:35:16 |     validation_metric_mode: min
14:35:16 |     validation_patience: 10
14:35:16 |     validation_share_agent: False
14:35:16 |     variant: prelayernorm
14:35:16 |     verbose: False
14:35:16 |     warmup_rate: 0.0001
14:35:16 |     warmup_updates: 100
14:35:16 |     weight_decay: None
14:35:16 |     woi_doc_chunk_size: 500
14:35:16 |     world_logs: 
14:35:16 |     wrap_memory_encoder: False
Enter [DONE] if you want to end the episode, [EXIT] to quit.
14:35:16 | creating task(s): interactive
Enter Your Message: Hi
Traceback (most recent call last):
  File "/Users/yufeitao/Desktop/ParlAI-1.7.1/venv/bin/parlai", line 33, in <module>
    sys.exit(load_entry_point('parlai', 'console_scripts', 'parlai')())
  File "/Users/yufeitao/Desktop/ParlAI-1.7.1/parlai/__main__.py", line 14, in main
    superscript_main()
  File "/Users/yufeitao/Desktop/ParlAI-1.7.1/parlai/core/script.py", line 325, in superscript_main
    return SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "/Users/yufeitao/Desktop/ParlAI-1.7.1/parlai/core/script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "/Users/yufeitao/Desktop/ParlAI-1.7.1/parlai/scripts/interactive.py", line 118, in run
    return interactive(self.opt)
  File "/Users/yufeitao/Desktop/ParlAI-1.7.1/parlai/scripts/interactive.py", line 93, in interactive
    world.parley()
  File "/Users/yufeitao/Desktop/ParlAI-1.7.1/parlai/tasks/interactive/worlds.py", line 89, in parley
    acts[1] = agents[1].act()
  File "/Users/yufeitao/Desktop/ParlAI-1.7.1/parlai/core/torch_agent.py", line 2148, in act
    response = self.batch_act([self.observation])[0]
  File "/Users/yufeitao/Desktop/ParlAI-1.7.1/parlai/core/torch_agent.py", line 2244, in batch_act
    output = self.eval_step(batch)
  File "/Users/yufeitao/Desktop/ParlAI-1.7.1/projects/seeker/agents/seeker.py", line 160, in eval_step
    output = TorchGeneratorAgent.eval_step(self, batch)
  File "/Users/yufeitao/Desktop/ParlAI-1.7.1/parlai/core/torch_generator_agent.py", line 901, in eval_step
    beam_preds_scores, beams = self._generate(
  File "/Users/yufeitao/Desktop/ParlAI-1.7.1/parlai/agents/rag/rag.py", line 684, in _generate
    gen_outs = self._rag_generate(batch, beam_size, max_ts, prefix_tokens)
  File "/Users/yufeitao/Desktop/ParlAI-1.7.1/parlai/agents/rag/rag.py", line 727, in _rag_generate
    return self._generation_agent._generate(
  File "/Users/yufeitao/Desktop/ParlAI-1.7.1/parlai/core/torch_generator_agent.py", line 1163, in _generate
    encoder_states = model.encoder(*self._encoder_input(batch))
  File "/Users/yufeitao/Desktop/ParlAI-1.7.1/projects/seeker/agents/seeker_modules.py", line 244, in encoder
    output = super().encoder(
  File "/Users/yufeitao/Desktop/ParlAI-1.7.1/parlai/agents/fid/fid.py", line 149, in encoder
    enc_out, mask, input_turns_cnt, top_docs, top_doc_scores = super().encoder(
  File "/Users/yufeitao/Desktop/ParlAI-1.7.1/parlai/agents/rag/modules.py", line 192, in encoder
    expanded_input, top_docs, top_doc_scores = self.retrieve_and_concat(
  File "/Users/yufeitao/Desktop/ParlAI-1.7.1/parlai/agents/rag/modules.py", line 327, in retrieve_and_concat
    top_docs, top_doc_scores = self.retriever.retrieve(query_vec)
  File "/Users/yufeitao/Desktop/ParlAI-1.7.1/parlai/agents/rag/retrievers.py", line 419, in retrieve
    docs, scores = self.retrieve_and_score(query)
  File "/Users/yufeitao/Desktop/ParlAI-1.7.1/projects/bb3/agents/r2c2_bb3_agent.py", line 166, in retrieve_and_score
    return super().retrieve_and_score(query)
  File "/Users/yufeitao/Desktop/ParlAI-1.7.1/parlai/agents/rag/retrievers.py", line 1212, in retrieve_and_score
    search_queries = self.generate_search_query(query)
  File "/Users/yufeitao/Desktop/ParlAI-1.7.1/projects/seeker/agents/seeker_modules.py", line 130, in generate_search_query
    if self.search_queries:
  File "/Users/yufeitao/Desktop/ParlAI-1.7.1/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'BB3Retriever' object has no attribute 'search_queries'
```

**Additional context**
Add any other context about the problem here. (like proxy settings, network setup, overall goals, etc.)

**Comment by klshuster** [comment]
What is your goal? Why not use the standard interactive command provided on the project page:

```bash
parlai safe_interactive --model-file zoo:bb3/bb3_3B/model --init-opt gen/r2c2_bb3
```

**Comment by robinsongh381** [comment]
@klshuster The command used by @YufeiT is also the "official" command prodived on [this page](https://github.com/facebookresearch/ParlAI/tree/main/projects/bb3/agents#blenderbot-3-agent-information).

I encountered the same error (i.e., `AttributeError: 'BB3Retriever' object has no attribute 'search_queries'
`) upon running with `parlai interactive`. This error should be fixed.

**Comment by klshuster** [comment]
As suggested on the linked page, if you do not want to use a search server, you should set `--force-skip-retrieval True`

Additionally, if you want to use a search server, you need to directly call the `set_search_queries` function; [see instructions here](https://github.com/facebookresearch/ParlAI/tree/main/projects/bb3/agents#skm-search-knowledge-module)
