### ISSUE TITLE
Running display_data script on sample json provided is throwing JSONDecodeError 

### ISSUE THREAD

**Issue by Sidx-sys** [facebookresearch/ParlAI#4855]
**Bug description**
On a freshly installed parlai on conda environment, I run the `display_data` script, to find a JSONDecodeError, even though I have provided it with a valid JSON file (verified using json.load() on the same file)

**Reproduction steps**
`parlai display_data --task jsonfile --jsonfile-datapath ../chatbot/data/sample_data.json` where I my data is in the provided path. The data in the path is essentially the sample data given in the ParlAI getting started on Tasks and Dataset docs.

**Expected behavior**
I would expect the Episode information to be neatly displayed as shown in the documentation.

**Logs**

```
Traceback (most recent call last):
  File "/home2/sidharth.giri/ParlAI/parlai/core/worlds.py", line 1397, in _create_task_agents
    task_agents = my_module.create_agents(opt)  # type: ignore
AttributeError: module 'parlai.tasks.jsonfile.agents' has no attribute 'create_agents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home2/sidharth.giri/miniconda3/envs/parlai/bin/parlai", line 33, in <module>
    sys.exit(load_entry_point('parlai', 'console_scripts', 'parlai')())
  File "/home2/sidharth.giri/ParlAI/parlai/__main__.py", line 14, in main
    superscript_main()
  File "/home2/sidharth.giri/ParlAI/parlai/core/script.py", line 325, in superscript_main
    return SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "/home2/sidharth.giri/ParlAI/parlai/core/script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "/home2/sidharth.giri/ParlAI/parlai/scripts/display_data.py", line 113, in run
    return display_data(self.opt)
  File "/home2/sidharth.giri/ParlAI/parlai/scripts/display_data.py", line 75, in display_data
    world = create_task(opt, agent)
  File "/home2/sidharth.giri/ParlAI/parlai/core/worlds.py", line 1448, in create_task
    world = create_task_world(opt, user_agents, default_world=default_world)
  File "/home2/sidharth.giri/ParlAI/parlai/core/worlds.py", line 1412, in create_task_world
    task_agents = _create_task_agents(opt)
  File "/home2/sidharth.giri/ParlAI/parlai/core/worlds.py", line 1400, in _create_task_agents
    return create_task_agent_from_taskname(opt)
  File "/home2/sidharth.giri/ParlAI/parlai/core/teachers.py", line 2669, in create_task_agent_from_taskname
    task_agents = teacher_class(opt)
  File "/home2/sidharth.giri/ParlAI/parlai/tasks/jsonfile/agents.py", line 66, in __init__
    super().__init__(opt, shared)
  File "/home2/sidharth.giri/ParlAI/parlai/tasks/jsonfile/agents.py", line 57, in __init__
    super().__init__(opt, shared)
  File "/home2/sidharth.giri/ParlAI/parlai/core/teachers.py", line 1691, in __init__
    super().__init__(opt, shared)
  File "/home2/sidharth.giri/ParlAI/parlai/core/teachers.py", line 675, in __init__
    self.data = data_class(
  File "/home2/sidharth.giri/ParlAI/parlai/core/teachers.py", line 862, in __init__
    self._load(data_loader, opt['datafile'])
  File "/home2/sidharth.giri/ParlAI/parlai/core/teachers.py", line 907, in _load
    for i, episode in enumerate(self._read_episode(data_loader(datafile))):
  File "/home2/sidharth.giri/ParlAI/parlai/core/teachers.py", line 888, in _read_episode
    for entry, new in data_loader:
  File "/home2/sidharth.giri/ParlAI/parlai/core/teachers.py", line 1704, in setup_data
    for conv in conversations:
  File "/home2/sidharth.giri/ParlAI/parlai/utils/conversations.py", line 226, in <genexpr>
    return (self._parse(line) for line in self._load_raw(datapath))
  File "/home2/sidharth.giri/ParlAI/parlai/utils/conversations.py", line 223, in _parse
    return Conversation(json.loads(line))
  File "/home2/sidharth.giri/miniconda3/envs/parlai/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home2/sidharth.giri/miniconda3/envs/parlai/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home2/sidharth.giri/miniconda3/envs/parlai/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
```

**Additional context**
I was attempting to do this since I wanted to try what an episode would look like 3 unique speakers rather than the standard 2 example provided in the documentation, but the provided one was not working to begin with.

**Comment by klshuster** [comment]
the `jsonfile` agent expects a `.jsonl` file; specifically, a file where each line is an example dialogue. You may want to dump your dialogues to the file using `f.write(f"{json.dumps(dialogue)}\n")` for each `dialogue`
