### ISSUE TITLE
ImportError: Could not find pretrained model in parlai.zoo.controllable_dialogue.build or parlai.zoo.controllable_dialogue.build.

### ISSUE THREAD

**Issue by wliang0** [facebookresearch/ParlAI#4863]
**Description:** I'm trying to access the pre-trained models from the [What makes a good conversation? How controllable attributes affect human judgments](https://arxiv.org/abs/1902.08654). I understand that this project has been archived, so I'm checking out the  `controllable_dialogue_archive` tag and following the instructions on the readme to chat with the pre-trained models.

Running this
```
python projects/controllable_dialogue/interactive.py \
-mf models:controllable_dialogue/convai2_finetuned_baseline \
--beam-size 1
```
returns the following error
```
Traceback (most recent call last):
  File "/Users/wliang/opt/miniconda3/envs/myenv/lib/python3.10/site-packages/parlai/core/build_data.py", line 511, in modelzoo_path
    my_module = importlib.import_module(module_name)
  File "/Users/wliang/opt/miniconda3/envs/myenv/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'parlai.zoo.controllable_dialogue'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wliang/opt/miniconda3/envs/myenv/lib/python3.10/site-packages/parlai/core/build_data.py", line 518, in modelzoo_path
    my_module = importlib.import_module(module_name_)
  File "/Users/wliang/opt/miniconda3/envs/myenv/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'parlai.zoo.controllable_dialogue'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/wliang/ParlAI/projects/controllable_dialogue/interactive.py", line 24, in <module>
    interactive(parser.parse_args())
  File "/Users/wliang/opt/miniconda3/envs/myenv/lib/python3.10/site-packages/parlai/core/params.py", line 1169, in parse_args
    self.add_extra_args(args)
  File "/Users/wliang/opt/miniconda3/envs/myenv/lib/python3.10/site-packages/parlai/core/params.py", line 946, in add_extra_args
    model = get_model_name(parsed)
  File "/Users/wliang/opt/miniconda3/envs/myenv/lib/python3.10/site-packages/parlai/core/params.py", line 136, in get_model_name
    model_file = modelzoo_path(opt.get('datapath'), model_file)
  File "/Users/wliang/opt/miniconda3/envs/myenv/lib/python3.10/site-packages/parlai/core/build_data.py", line 522, in modelzoo_path
    raise ImportError(
ImportError: Could not find pretrained model in parlai.zoo.controllable_dialogue.build or parlai.zoo.controllable_dialogue.build. Please check your spelling and make sure you've pulled from master.
```

Thanks!

**Comment by klshuster** [comment]
Hmm, @stephenroller any insight here? 

Are you sure you've properly checked out the tag? I.e., can you locate the `parlai/zoo/controllable_dialogue/build` file in your ParlAI checkout?

**Comment by wliang0** [comment]
Yes, I can confirm I checked out the tag. There is a build.py file in `parlai/zoo/controllable_dialogue/`. Perhaps the module is disabled?

**Comment by klshuster** [comment]
there might be some missing `__init__.py` files. i wonder if you tried with an earlier version of python (3.8?) if that would resolve things?

**Comment by wliang0** [comment]
I reverted to python=3.8 and did a fresh install of the dev environment. It worked, thanks!
