### ISSUE TITLE
Run time error

### ISSUE THREAD

**Issue by jinfagang** [facebookresearch/ParlAI#49]
When I run this command, 
```
 python3 examples/display_data.py -t babi:task1k:1
```
just got this error. System is Ubuntu16.04, and I have installed pytorch already.

```
[task:babi:task1k:1]
[numthreads:1]
[num_examples:10]
[datatype:train]
[download_path:/usr/local/lib/python3.5/dist-packages/parlai-0.1.0-py3.5.egg/downloads/]
[datapath:/usr/local/lib/python3.5/dist-packages/parlai-0.1.0-py3.5.egg/data/]
[batchsize:1]
[Agent initializing.]
[creating task(s): babi:task1k:1]
[building data: /usr/local/lib/python3.5/dist-packages/parlai-0.1.0-py3.5.egg/data//bAbI/]
mkdir: cannot create directory ‘/usr/local/lib/python3.5/dist-packages/parlai-0.1.0-py3.5.egg/data’: Permission denied
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/parlai-0.1.0-py3.5.egg/parlai/core/agents.py", line 218, in _create_task_agents
    create_agent = getattr(my_module, 'create_agents')
AttributeError: module 'parlai.tasks.babi.agents' has no attribute 'create_agents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/display_data.py", line 42, in <module>
    main()
  File "examples/display_data.py", line 30, in main
    world = create_task(opt, agent)
  File "/usr/local/lib/python3.5/dist-packages/parlai-0.1.0-py3.5.egg/parlai/core/worlds.py", line 673, in create_task
    world = create_task_world(opt, user_agents)
  File "/usr/local/lib/python3.5/dist-packages/parlai-0.1.0-py3.5.egg/parlai/core/worlds.py", line 648, in create_task_world
    world_class, task_agents = _get_task_world(opt)
  File "/usr/local/lib/python3.5/dist-packages/parlai-0.1.0-py3.5.egg/parlai/core/worlds.py", line 643, in _get_task_world
    task_agents = _create_task_agents(opt)
  File "/usr/local/lib/python3.5/dist-packages/parlai-0.1.0-py3.5.egg/parlai/core/agents.py", line 222, in _create_task_agents
    return create_task_agent_from_taskname(opt)
  File "/usr/local/lib/python3.5/dist-packages/parlai-0.1.0-py3.5.egg/parlai/core/agents.py", line 186, in create_task_agent_from_taskname
    task_agents = teacher_class(opt)
  File "/usr/local/lib/python3.5/dist-packages/parlai-0.1.0-py3.5.egg/parlai/tasks/babi/agents.py", line 28, in __init__
    opt['datafile'] = _path('', task.split(':')[2], opt)
  File "/usr/local/lib/python3.5/dist-packages/parlai-0.1.0-py3.5.egg/parlai/tasks/babi/agents.py", line 15, in _path
    build(opt)
  File "/usr/local/lib/python3.5/dist-packages/parlai-0.1.0-py3.5.egg/parlai/tasks/babi/build.py", line 18, in build
    build_data.make_dir(dpath)
  File "/usr/local/lib/python3.5/dist-packages/parlai-0.1.0-py3.5.egg/parlai/core/build_data.py", line 24, in make_dir
    raise RuntimeError('failed: ' + s)
RuntimeError: failed: mkdir -p "/usr/local/lib/python3.5/dist-packages/parlai-0.1.0-py3.5.egg/data//bAbI/"

```
So, what is this indicates?

**Comment by alexholdenmiller** [comment]
@jinfagang were you able to resolve this, then?

**Comment by jinfagang** [comment]
Well, sorry for the disturb, just permission issue, already handle that.

**Comment by alexholdenmiller** [comment]
No problem just wanted to make sure! :)

**Comment by dcshenyufei** [comment]
> Well, sorry for the disturb, just permission issue, already handle that.

I have the same question , could you tell how to handle the problem? What dose the permission issue mean?

**Comment by alexholdenmiller** [comment]
@dcshenyufei did you install parlai via `python setup.py develop`? This error may be caused by mistakenly installing with `python setup.py install` (not our recommended setup process).
