### ISSUE TITLE
can't find filename or opt preset for Seeker model

### ISSUE THREAD

**Issue by amrohendawi** [facebookresearch/ParlAI#4936]
I am unable of running any of the seeker models available [in the zoo](https://www.parl.ai/docs/zoo.html)

When I run:

```bash
parlai i -mf zoo:seeker/seeker_dialogue_3B/model -o gen/seeker_dialogue --search-server http://0.0.0.0:8081
```

I should be able to interact with the model and ask questions. Instead, I get the following error:

```bash
Traceback (most recent call last):
  File "/home/lazerdance/miniconda3/envs/ParlAI/bin/parlai", line 8, in <module>
    sys.exit(main())
  File "/home/lazerdance/miniconda3/envs/ParlAI/lib/python3.9/site-packages/parlai/__main__.py", line 14, in main
    superscript_main()
  File "/home/lazerdance/miniconda3/envs/ParlAI/lib/python3.9/site-packages/parlai/core/script.py", line 316, in superscript_main
    opt = parser.parse_args(args)
  File "/home/lazerdance/miniconda3/envs/ParlAI/lib/python3.9/site-packages/parlai/core/params.py", line 1169, in parse_args
    self.add_extra_args(args)
  File "/home/lazerdance/miniconda3/envs/ParlAI/lib/python3.9/site-packages/parlai/core/script.py", line 175, in add_extra_args
    sa.choices[args[0]].add_extra_args(args)
  File "/home/lazerdance/miniconda3/envs/ParlAI/lib/python3.9/site-packages/parlai/core/params.py", line 966, in add_extra_args
    self._load_known_opts(parsed.get('init_opt'), parsed)
  File "/home/lazerdance/miniconda3/envs/ParlAI/lib/python3.9/site-packages/parlai/core/params.py", line 1020, in _load_known_opts
    new_opt = Opt.load_init(optfile)
  File "/home/lazerdance/miniconda3/envs/ParlAI/lib/python3.9/site-packages/parlai/core/opt.py", line 176, in load_init
    raise FileNotFoundError(
FileNotFoundError: Could not find filename 'gen/seeker_dialogue or opt preset 'gen/seeker_dialogue.opt'. Please check https://parl.ai/docs/opt_presets.html for a list of available opt presets.
```

How can I get this model to run? What am I doing wrong?

**Comment by sourcenix** [comment]
I came across this issue as well. I solved it by creating this file manually in the opt_presets directory:
https://github.com/facebookresearch/ParlAI/blob/main/parlai/opt_presets/gen/seeker_dialogue.opt

From memory the file was missing from ~/.local/lib/python3.10/site-packages/parlai/opt_presets/, create the "gen" folder manually then create the seeker_dialogue.opt manually in the gen folder.

**Comment by amrohendawi** [comment]
solved it by pointing the to the .opt file in the correct directory where it is downloaded the first time as follows:

```bash
parlai i -mf zoo:seeker/seeker_dialogue_3B/model -o parlai/opt_presets/gen/seeker_dialogue.opt --search-server http://0.0.0.0:8081
```

If you haven't cloned parlai github repo, then you need to create the `.opt` file manually.
Another important point is that you need to explicitly add the file format `.opt`  at the end.
