### ISSUE TITLE
no module named ...

### ISSUE THREAD

**Issue by calebre2000** [facebookresearch/ParlAI#4938]
Hi, I installed ParlAI in a Windows Subsystem for Linux. Everything works perfectly fine, I can train, display data, interact with models, ... BUT as soon as I want to add a new module I get a ModuleNotFoundError.

Example:
I tried following the add a simple model tutorial (https://parl.ai/docs/tutorial_quick.html#add-a-simple-model). I added the model and when I enter the command parlai display_model --task babi:task10k:1 --model parrot I get this:

/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
16:35:07 | Unable to load ngram blocking on GPU: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
Traceback (most recent call last):
  File "/home/x/.local/bin/parlai", line 8, in <module>
    sys.exit(main())
  File "/home/x/.local/lib/python3.8/site-packages/parlai/__main__.py", line 14, in main
    superscript_main()
  File "/home/x/.local/lib/python3.8/site-packages/parlai/core/script.py", line 316, in superscript_main
    opt = parser.parse_args(args)
  File "/home/x/.local/lib/python3.8/site-packages/parlai/core/params.py", line 1169, in parse_args
    self.add_extra_args(args)
  File "/home/x/.local/lib/python3.8/site-packages/parlai/core/script.py", line 175, in add_extra_args
    sa.choices[args[0]].add_extra_args(args)
  File "/home/x/.local/lib/python3.8/site-packages/parlai/core/params.py", line 948, in add_extra_args
    self.add_model_subargs(model, partial)
  File "/home/x/.local/lib/python3.8/site-packages/parlai/core/params.py", line 822, in add_model_subargs
    agent = load_agent_module(model)
  File "/home/x/.local/lib/python3.8/site-packages/parlai/core/loader.py", line 188, in load_agent_module
    my_module = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'parlai.agents.parrot'

Same thing when I tried adding a new task. Pls help :(

**Comment by mojtaba-komeili** [comment]
It looks to me that for some reason ParlAI can not find the new model you added.
Could you provide details on these two please?
* How did you install ParlAI? `pip` or from the GitHub clone?
* Where did you add your model file?

**Comment by calebre2000** [comment]
@mojtaba-komeili thanks for your reply!
I installed ParlAI from the GitHub clone and I added the model to the agents folder
looks like this on vs code
![image](https://user-images.githubusercontent.com/83135976/215588805-1e305670-703f-40cc-831c-7443b5cc0a67.png)

**Comment by klshuster** [comment]
could you try `python -m parlai.scripts.display_model` instead of `parlai display_model`?
