### ISSUE TITLE
ModuleNotFoundError: No module named 'projects.msc'

### ISSUE THREAD

**Issue by unknowed-ER** [facebookresearch/ParlAI#4942]
**Bug description**
I install parlai by command ‘pip install parlai’ on Ubuntu 20.04, python3.9.0, pytorch1.13.
I run following command to download model MSC2.7B and evaluate it on MSC dataset. 
```
parlai eval_model -mf zoo:msc/msc3B_1024/model -t msc -dt valid -bs 16 --previous-persona-type raw_history
```
I miss the error 'ModuleNotFoundError: No module named 'projects.msc''

**Reproduction steps**
parlai eval_model -mf zoo:msc/msc3B_1024/model -t msc -dt valid -bs 16 --previous-persona-type raw_history

**Expected behavior**
How to fix this error？

**Logs**
Please paste the command line output:

```
(torch1.13) fsx@fsx:~$ parlai eval_model -mf zoo:msc/summsc_fidrag3B/model -t msc -dt valid -bs 16 --previous-persona-type predsum_both
Traceback (most recent call last):
  File "/home/fsx/anaconda3/envs/torch1.13/bin/parlai", line 8, in <module>
    sys.exit(main())
  File "/home/fsx/anaconda3/envs/torch1.13/lib/python3.9/site-packages/parlai/__main__.py", line 14, in main
    superscript_main()
  File "/home/fsx/anaconda3/envs/torch1.13/lib/python3.9/site-packages/parlai/core/script.py", line 316, in superscript_main
    opt = parser.parse_args(args)
  File "/home/fsx/anaconda3/envs/torch1.13/lib/python3.9/site-packages/parlai/core/params.py", line 1169, in parse_args
    self.add_extra_args(args)
  File "/home/fsx/anaconda3/envs/torch1.13/lib/python3.9/site-packages/parlai/core/script.py", line 175, in add_extra_args
    sa.choices[args[0]].add_extra_args(args)
  File "/home/fsx/anaconda3/envs/torch1.13/lib/python3.9/site-packages/parlai/core/params.py", line 948, in add_extra_args
    self.add_model_subargs(model, partial)
  File "/home/fsx/anaconda3/envs/torch1.13/lib/python3.9/site-packages/parlai/core/params.py", line 822, in add_model_subargs
    agent = load_agent_module(model)
  File "/home/fsx/anaconda3/envs/torch1.13/lib/python3.9/site-packages/parlai/core/loader.py", line 188, in load_agent_module
    my_module = importlib.import_module(module_name)
  File "/home/fsx/anaconda3/envs/torch1.13/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'projects.msc'
```

**Additional context**
[MSC dataset guide](https://parl.ai/projects/msc/)

**Comment by klshuster** [comment]
can you try using `python -m parlai.scripts.eval_model`?

**Comment by unknowed-ER** [comment]
The same error occurred.
'''
(torch1.13) fsx@fsx:~$ python -m parlai.scripts.eval_model -mf zoo:msc/msc3B_1024/model -t msc -dt valid -bs 16 --previous-persona-type raw_history
Traceback (most recent call last):
  File "/home/fsx/anaconda3/envs/torch1.13/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/fsx/anaconda3/envs/torch1.13/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/fsx/anaconda3/envs/torch1.13/lib/python3.9/site-packages/parlai/scripts/eval_model.py", line 305, in <module>
    EvalModel.main()
  File "/home/fsx/anaconda3/envs/torch1.13/lib/python3.9/site-packages/parlai/core/script.py", line 129, in main
    return cls._run_args(None)
  File "/home/fsx/anaconda3/envs/torch1.13/lib/python3.9/site-packages/parlai/core/script.py", line 100, in _run_args
    opt = parser.parse_args(args=args)
  File "/home/fsx/anaconda3/envs/torch1.13/lib/python3.9/site-packages/parlai/core/params.py", line 1169, in parse_args
    self.add_extra_args(args)
  File "/home/fsx/anaconda3/envs/torch1.13/lib/python3.9/site-packages/parlai/core/params.py", line 948, in add_extra_args
    self.add_model_subargs(model, partial)
  File "/home/fsx/anaconda3/envs/torch1.13/lib/python3.9/site-packages/parlai/core/params.py", line 822, in add_model_subargs
    agent = load_agent_module(model)
  File "/home/fsx/anaconda3/envs/torch1.13/lib/python3.9/site-packages/parlai/core/loader.py", line 188, in load_agent_module
    my_module = importlib.import_module(module_name)
  File "/home/fsx/anaconda3/envs/torch1.13/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'projects.msc'
'''

**Comment by unknowed-ER** [comment]
> can you try using `python -m parlai.scripts.eval_model`?

The same error occurred.
```
(torch1.13) fsx@fsx:~$ python -m parlai.scripts.eval_model -mf zoo:msc/msc3B_1024/model -t msc -dt valid -bs 16 --previous-persona-type raw_history
Traceback (most recent call last):
  File "/home/fsx/anaconda3/envs/torch1.13/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/fsx/anaconda3/envs/torch1.13/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/fsx/anaconda3/envs/torch1.13/lib/python3.9/site-packages/parlai/scripts/eval_model.py", line 305, in <module>
    EvalModel.main()
  File "/home/fsx/anaconda3/envs/torch1.13/lib/python3.9/site-packages/parlai/core/script.py", line 129, in main
    return cls._run_args(None)
  File "/home/fsx/anaconda3/envs/torch1.13/lib/python3.9/site-packages/parlai/core/script.py", line 100, in _run_args
    opt = parser.parse_args(args=args)
  File "/home/fsx/anaconda3/envs/torch1.13/lib/python3.9/site-packages/parlai/core/params.py", line 1169, in parse_args
    self.add_extra_args(args)
  File "/home/fsx/anaconda3/envs/torch1.13/lib/python3.9/site-packages/parlai/core/params.py", line 948, in add_extra_args
    self.add_model_subargs(model, partial)
  File "/home/fsx/anaconda3/envs/torch1.13/lib/python3.9/site-packages/parlai/core/params.py", line 822, in add_model_subargs
    agent = load_agent_module(model)
  File "/home/fsx/anaconda3/envs/torch1.13/lib/python3.9/site-packages/parlai/core/loader.py", line 188, in load_agent_module
    my_module = importlib.import_module(module_name)
  File "/home/fsx/anaconda3/envs/torch1.13/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'projects.msc'
```

**Comment by klshuster** [comment]
hmm, you may want to install from source? I'm not sure why else this error would show up -- it works fine for me locally
