### ISSUE TITLE
Set GPU for BB2 models

### ISSUE THREAD

**Issue by thies1006** [facebookresearch/ParlAI#4950]
**Bug description**
When I try to set the GPU the model crashes.

**Reproduction steps**
`python -m parlai.scripts.interactive --model-file zoo:blenderbot2/blenderbot2_400M/model --gpu 2 --search-server http://127.0.0.1`

**Expected behavior**
At least the corresponding model (blenderbot2) should run on GPU the given GPU and no error should be raised. 
The question remains where the accompanying models would run (query generator etc), e.g. should all models run on the same GPU (if GPU is given)?

**Logs**
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tertiary/thies/ParlAI_new/ParlAI/parlai/scripts/interactive.py", line 123, in <module>
    Interactive.main()
  File "/tertiary/thies/ParlAI_new/ParlAI/parlai/core/script.py", line 129, in main
    return cls._run_args(None)
  File "/tertiary/thies/ParlAI_new/ParlAI/parlai/core/script.py", line 101, in _run_args
    return cls._run_from_parser_and_opt(opt, parser)
  File "/tertiary/thies/ParlAI_new/ParlAI/parlai/core/script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "/tertiary/thies/ParlAI_new/ParlAI/parlai/scripts/interactive.py", line 118, in run
    return interactive(self.opt)
  File "/tertiary/thies/ParlAI_new/ParlAI/parlai/scripts/interactive.py", line 84, in interactive
    agent = create_agent(opt, requireModelExists=True)
  File "/tertiary/thies/ParlAI_new/ParlAI/parlai/core/agents.py", line 468, in create_agent
    model = create_agent_from_opt_file(opt)
  File "/tertiary/thies/ParlAI_new/ParlAI/parlai/core/agents.py", line 421, in create_agent_from_opt_file
    return model_class(opt_from_file)
  File "/tertiary/thies/ParlAI_new/ParlAI/parlai/agents/rag/rag.py", line 186, in __init__
    self._generation_agent.__init__(self, opt, shared)  # type: ignore
  File "/tertiary/thies/ParlAI_new/ParlAI/parlai/agents/bart/bart.py", line 72, in __init__
    super().__init__(opt, shared)
  File "/tertiary/thies/ParlAI_new/ParlAI/parlai/core/torch_generator_agent.py", line 520, in __init__
    self.model = self.build_model()
  File "/tertiary/thies/ParlAI_new/ParlAI/projects/blenderbot2/agents/blenderbot2.py", line 969, in build_model
    model = BlenderBot2FidModel(self.opt, self.dict)
  File "/tertiary/thies/ParlAI_new/ParlAI/projects/blenderbot2/agents/modules.py", line 840, in __init__
    super().__init__(
  File "/tertiary/thies/ParlAI_new/ParlAI/projects/blenderbot2/agents/modules.py", line 98, in __init__
    self.memory_decoder = MemoryDecoder(opt)
  File "/tertiary/thies/ParlAI_new/ParlAI/projects/blenderbot2/agents/sub_modules.py", line 296, in __init__
    base_agent = create_agent_from_model_file(
  File "/tertiary/thies/ParlAI_new/ParlAI/parlai/core/agents.py", line 347, in create_agent_from_model_file
    return create_agent_from_opt_file(opt)
  File "/tertiary/thies/ParlAI_new/ParlAI/parlai/core/agents.py", line 421, in create_agent_from_opt_file
    return model_class(opt_from_file)
  File "/tertiary/thies/ParlAI_new/ParlAI/parlai/agents/bart/bart.py", line 71, in __init__
    opt = self._initialize_bart(opt)
  File "/tertiary/thies/ParlAI_new/ParlAI/parlai/agents/bart/bart.py", line 97, in _initialize_bart
    compare_init_model_opts(opt, opt)
  File "/tertiary/thies/ParlAI_new/ParlAI/parlai/core/agents.py", line 273, in compare_init_model_opts
    opt['init_model'] = modelzoo_path(opt['datapath'], opt['init_model'])
  File "/tertiary/thies/ParlAI_new/ParlAI/parlai/core/build_data.py", line 519, in modelzoo_path
    my_module.download(datapath)
  File "/tertiary/thies/ParlAI_new/ParlAI/parlai/zoo/bart/build.py", line 69, in download
    ConversionScript.main(**args)
  File "/tertiary/thies/ParlAI_new/ParlAI/parlai/core/script.py", line 127, in main
    return cls._run_kwargs(kwargs)
  File "/tertiary/thies/ParlAI_new/ParlAI/parlai/core/script.py", line 92, in _run_kwargs
    return cls._run_from_parser_and_opt(opt, parser)
  File "/tertiary/thies/ParlAI_new/ParlAI/parlai/core/script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "/tertiary/thies/ParlAI_new/ParlAI/parlai/agents/bart/convert_fairseq_to_parlai.py", line 140, in run
    self.print_agent_act()
  File "/tertiary/thies/ParlAI_new/ParlAI/parlai/agents/bart/convert_fairseq_to_parlai.py", line 490, in print_agent_act
    print(self.agent.act())
  File "/tertiary/thies/ParlAI_new/ParlAI/parlai/core/torch_agent.py", line 2157, in act
    response = self.batch_act([self.observation])[0]
  File "/tertiary/thies/ParlAI_new/ParlAI/parlai/core/torch_agent.py", line 2253, in batch_act
    output = self.eval_step(batch)
  File "/tertiary/thies/ParlAI_new/ParlAI/parlai/core/torch_generator_agent.py", line 933, in eval_step
    beam_preds_scores, beams = self._generate(
  File "/tertiary/thies/ParlAI_new/ParlAI/parlai/core/torch_generator_agent.py", line 1214, in _generate
    encoder_states = model.encoder(*self._encoder_input(batch))
  File "/secondary/thies/.virtualenvs/parlai/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/tertiary/thies/ParlAI_new/ParlAI/parlai/agents/transformer/modules/encoder.py", line 352, in forward
    tensor, mask = self.forward_embedding(input, positions, segments)
  File "/tertiary/thies/ParlAI_new/ParlAI/parlai/agents/transformer/modules/encoder.py", line 259, in forward_embedding
    tensor = self.embeddings(input)
  File "/secondary/thies/.virtualenvs/parlai/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/secondary/thies/.virtualenvs/parlai/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 158, in forward
    return F.embedding(
  File "/secondary/thies/.virtualenvs/parlai/lib/python3.8/site-packages/torch/nn/functional.py", line 2199, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:2 and cuda:0! (when checking argument for argument index in method wrapper__index_select)
```

**Additional context**
I used the code from today.

Edit: tried with option `--model-parallel False` as well with the same result.

**Comment by klshuster** [comment]
why are you trying to set the gpu?
