### ISSUE TITLE
Error while handling separate train/valid/test data in jsonfile format

### ISSUE THREAD

**Issue by tunde99** [facebookresearch/ParlAI#4960]
**Bug description**
Given 3 json files in the same directory 

> /home/tunaja/mydata

> mydata_test.json  
>mydata_train.json  
>mydata_valid.json

I got an error when I tried to load them using the command below: 

**Logs**
`python parlai/scripts/display_data.py --task jsonfile --jsonfile-datapath /home/tunaja/mydata --jsonfile-datatype-extension true
`
```
16:03:35 | creating task(s): jsonfile
16:03:38 | [loading data from json file into task: /home/tunaja/mydata_train.jsonl ]
Traceback (most recent call last):
  File "/home/tunaja/miniconda3/envs/bb1/lib/python3.8/site-packages/parlai/core/worlds.py", line 1397, in _create_task_agents
    task_agents = my_module.create_agents(opt)  # type: ignore
AttributeError: module 'parlai.tasks.jsonfile.agents' has no attribute 'create_agents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "parlai/scripts/display_data.py", line 121, in <module>
    DisplayData.main()
  File "/home/tunaja/miniconda3/envs/bb1/lib/python3.8/site-packages/parlai/core/script.py", line 129, in main
    return cls._run_args(None)
  File "/home/tunaja/miniconda3/envs/bb1/lib/python3.8/site-packages/parlai/core/script.py", line 101, in _run_args
    return cls._run_from_parser_and_opt(opt, parser)
  File "/home/tunaja/miniconda3/envs/bb1/lib/python3.8/site-packages/parlai/core/script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "parlai/scripts/display_data.py", line 116, in run
    return display_data(self.opt)
  File "parlai/scripts/display_data.py", line 75, in display_data
    world = create_task(opt, agent)
  File "/home/tunaja/miniconda3/envs/bb1/lib/python3.8/site-packages/parlai/core/worlds.py", line 1448, in create_task
    world = create_task_world(opt, user_agents, default_world=default_world)
  File "/home/tunaja/miniconda3/envs/bb1/lib/python3.8/site-packages/parlai/core/worlds.py", line 1412, in create_task_world
    task_agents = _create_task_agents(opt)
  File "/home/tunaja/miniconda3/envs/bb1/lib/python3.8/site-packages/parlai/core/worlds.py", line 1400, in _create_task_agents
    return create_task_agent_from_taskname(opt)
  File "/home/tunaja/miniconda3/envs/bb1/lib/python3.8/site-packages/parlai/core/teachers.py", line 2669, in create_task_agent_from_taskname
    task_agents = teacher_class(opt)
  File "/home/tunaja/miniconda3/envs/bb1/lib/python3.8/site-packages/parlai/tasks/jsonfile/agents.py", line 66, in __init__
    super().__init__(opt, shared)
  File "/home/tunaja/miniconda3/envs/bb1/lib/python3.8/site-packages/parlai/tasks/jsonfile/agents.py", line 57, in __init__
    super().__init__(opt, shared)
  File "/home/tunaja/miniconda3/envs/bb1/lib/python3.8/site-packages/parlai/core/teachers.py", line 1691, in __init__
    super().__init__(opt, shared)
  File "/home/tunaja/miniconda3/envs/bb1/lib/python3.8/site-packages/parlai/core/teachers.py", line 675, in __init__
    self.data = data_class(
  File "/home/tunaja/miniconda3/envs/bb1/lib/python3.8/site-packages/parlai/core/teachers.py", line 862, in __init__
    self._load(data_loader, opt['datafile'])
  File "/home/tunaja/miniconda3/envs/bb1/lib/python3.8/site-packages/parlai/core/teachers.py", line 907, in _load
    for i, episode in enumerate(self._read_episode(data_loader(datafile))):
  File "/home/tunaja/miniconda3/envs/bb1/lib/python3.8/site-packages/parlai/core/teachers.py", line 888, in _read_episode
    for entry, new in data_loader:
  File "/home/tunaja/miniconda3/envs/bb1/lib/python3.8/site-packages/parlai/core/teachers.py", line 1704, in setup_data
    for conv in conversations:
  File "/home/tunaja/miniconda3/envs/bb1/lib/python3.8/site-packages/parlai/utils/conversations.py", line 226, in <genexpr>
    return (self._parse(line) for line in self._load_raw(datapath))
  File "/home/tunaja/miniconda3/envs/bb1/lib/python3.8/site-packages/parlai/utils/conversations.py", line 212, in _load_raw
    raise RuntimeError(
RuntimeError: Conversations at path /home/tunaja/mydata_train.jsonl not found. Double check your path.
```

**Additional context**
I followed the loading instruction [here](https://parl.ai/docs/tutorial_task.html#handling-separate-train-valid-test-data)

**Expected behavior**
I successfully loaded only the train json file mydata_train.json using the command below:

**Logs**
`python parlai/scripts/display_data.py --task jsonfile --jsonfile-datapath /home/tunaja/mydata/mydata_train.json --ne 2`

```
15:57:13 | creating task(s): jsonfile
15:57:17 | [loading data from json file into task: /home/tunaja/mydata/mydata_train.json ]
- - - NEW EPISODE: mydata/mydata_train.json - - -
Lol  “I copy jokes like everyone else because I’m a loser. Idk why you’re so mad.”  -You
   Dude now I'm confused ..why the quotation marks with different text in between them ?
- - - NEW EPISODE: mydata/mydata_train.json - - -
I'm starting to need less weed to get through the day.. It's small progress, but I'll take it.
   That's a good attitude to have. I'm sure you'll get there in no time.
15:57:17 | loaded 9017 episodes with a total of 9017 examples```

**Comment by tunde99** [comment]
Found a way around this issue by renaming (i) the datapath properly (ii) the files to have a .jsonl extension as referenced [here](https://github.com/facebookresearch/ParlAI/issues/4855#issuecomment-1303854911)

`python parlai/scripts/display_data.py --task jsonfile --jsonfile-datapath /home/tunaja/mydata/mydata --jsonfile-datatype-extension true --ne 2 -dt valid
`
```
21:51:15 | creating task(s): jsonfile
21:51:17 | [loading data from json file into task: /home/tunaja/mydata/mydata_valid.jsonl ]
- - - NEW EPISODE: mydata/mydata_valid.jsonl - - -
Our purpose is to suffer. And I'm fucking done with it
   That's a bit extreme.
- - - NEW EPISODE: mydata/mydata_valid.jsonl - - -
need to get that nigger to a gym asap
   Yeah we need his best
21:51:17 | loaded 1097 episodes with a total of 1097 examples
```

So, I will proceed to close the issue.
