### ISSUE TITLE
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

### ISSUE THREAD

**Issue by hongcheng79** [facebookresearch/ParlAI#4976]
I follow the tutorial from https://parl.ai/docs/tutorial_fast.html (Setting a baseline)
by executing the following command

> parlai build_dict --task convai2 --dict-file dictfile
> parlai train --dict-file dictfile --model transformer/generator \
>     --task convai2 --num-epochs 1.0 --batchsize 64 --n-layers 8  \
>     --embedding-size 250 --ffn-size 1000 --optimizer adam --learningrate 1e-3
> 

Encounter runtime error during the training
14:33:17 | num_epochs completed:1.0 time elapsed:487.2017171382904s
14:33:17 | creating task(s): convai2
14:33:17 | loading fbdialog data: /home/chc/miniconda3/envs/parlai/lib/python3.8/site-packages/data/ConvAI2/valid_self_original.txt
14:33:17 | running eval: valid
Traceback (most recent call last):
  File "/home/chc/miniconda3/envs/parlai/bin/parlai", line 8, in <module>
    sys.exit(main())
  File "/home/chc/miniconda3/envs/parlai/lib/python3.8/site-packages/parlai/__main__.py", line 14, in main
    superscript_main()
  File "/home/chc/miniconda3/envs/parlai/lib/python3.8/site-packages/parlai/core/script.py", line 325, in superscript_main
    return SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "/home/chc/miniconda3/envs/parlai/lib/python3.8/site-packages/parlai/core/script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "/home/chc/miniconda3/envs/parlai/lib/python3.8/site-packages/parlai/scripts/train_model.py", line 1060, in run
    return self.train_loop.train()
  File "/home/chc/miniconda3/envs/parlai/lib/python3.8/site-packages/parlai/scripts/train_model.py", line 1017, in train
    self.final_valid_report = self._run_eval(
  File "/home/chc/miniconda3/envs/parlai/lib/python3.8/site-packages/parlai/scripts/train_model.py", line 709, in _run_eval
    task_report = self._run_single_eval(
  File "/home/chc/miniconda3/envs/parlai/lib/python3.8/site-packages/parlai/scripts/train_model.py", line 649, in _run_single_eval
    valid_world.parley()
  File "/home/chc/miniconda3/envs/parlai/lib/python3.8/site-packages/parlai/core/worlds.py", line 880, in parley
    batch_act = self.batch_act(agent_idx, batch_observations[agent_idx])
  File "/home/chc/miniconda3/envs/parlai/lib/python3.8/site-packages/parlai/core/worlds.py", line 848, in batch_act
    batch_actions = a.batch_act(batch_observation)
  File "/home/chc/miniconda3/envs/parlai/lib/python3.8/site-packages/parlai/core/torch_agent.py", line 2244, in batch_act
    output = self.eval_step(batch)
  File "/home/chc/miniconda3/envs/parlai/lib/python3.8/site-packages/parlai/core/torch_generator_agent.py", line 901, in eval_step
    beam_preds_scores, beams = self._generate(
  File "/home/chc/miniconda3/envs/parlai/lib/python3.8/site-packages/parlai/core/torch_generator_agent.py", line 1223, in _generate
    b.advance(score[i], _ts)
  File "/home/chc/miniconda3/envs/parlai/lib/python3.8/site-packages/parlai/core/torch_generator_agent.py", line 1599, in advance
    self.partial_hyps[path_selection.hypothesis_ids.long()],
**RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)**

I am using conda-devenv (https://github.com/ESSS/conda-devenv) to maintain the conda environment and currently my version as follow
- parlai                    1.7.1
- cudatoolkit               11.7.0
- cudnn                     8.4.1.50
- pytorch-cuda              11.7
- torch                     1.13.1
- torchaudio                0.12.1
- torchtext                 0.14.1
- torchvision               0.14.1

My OS and hardware as follow
- Linux 6.1.11-76060111-generic
- Nvidia Driver Version: 525.85.05
- NVIDIA Corporation GA104M [GeForce RTX 3080 Mobile / Max-Q 16GB] (rev a1)

**Comment by hongcheng79** [comment]
Some observation, I didn't encounter error for "Skip generation & larger eval batchsize", "Dynamic batching" and "FP16"

**Comment by klshuster** [comment]
The fix is here: https://github.com/facebookresearch/ParlAI/pull/4887

You may want to downgrade pytorch or pull the fix into your parlai install

**Comment by krisstud** [comment]
I had the 1.7.1 release (exact clone) installed in my conda env using `python setup.py develop`. When i came across this error i cloned the latest files from main with the fix into another folder and ran `python setup.py develop`, without success. Deleting the ParlAI folder created under `username/.local/lib/python3.x/site-packages/parlai` and installing from the latest clone worked.
