### ISSUE TITLE
Internal subfolder for custom tasks got no attribute 'create_agents' error

### ISSUE THREAD

**Issue by liulaisusan** [facebookresearch/ParlAI#4997]
**Bug description**
I am using the internal subfolder for custom tasks following the [tutorial](https://parl.ai/docs/tutorial_task.html#dialogteacher). But when I run `parlai display_data -t internal:tutorial_task`, got no attribute 'create_agents' error.

**Reproduction steps**
- Installation: In Conda virtual environment with python=3.9. Tried both `pip install parlai` and `python setup.py develop`
- Create a task called 'tutorial_task' under `ParlAI/parlai_internal` with `build.py` and `agents.py` as following:
```python
#build.py
import parlai.core.build_data as build_data
import os
from parlai.core.build_data import DownloadableFile  # This is omitted in tutorial

RESOURCES = [
    DownloadableFile(
        'https://rajpurkar.github.io/SQuAD-explorer/dataset/train-v1.1.json',
        'train-v1.1.json',
        '<checksum for this file>',
        zipped=False,
    ),
    DownloadableFile(
        'https://rajpurkar.github.io/SQuAD-explorer/dataset/dev-v1.1.json',
        'dev-v1.1.json',
        '<checksum for this file>',
        zipped=False,
    ),
]


def build(opt):
    dpath = os.path.join(opt['datapath'], 'SQuAD')
    version = None

    if not build_data.built(dpath, version_string=version):
        print('[building data: ' + dpath + ']')
        if build_data.built(dpath):
            # An older version exists, so remove these outdated files.
            build_data.remove_dir(dpath)
        build_data.make_dir(dpath)

        # Download the data.
        for downloadable_file in RESOURCES[:2]:
            downloadable_file.download_file(dpath)

        # Mark the data as built.
        build_data.mark_done(dpath, version_string=version)
```

```python
#agents.py
import os
from iopath import PathManager
import json
from parlai.core.teachers import ParlAIDialogTeacher, DialogTeacher
from .build import build

def _path(opt, filtered):
    # build the data if it does not exist
    build(opt)
    # set up path to data (specific to each dataset)
    dt = opt['datatype'].split(':')[0]
    return os.path.join(opt['datapath'], 'Twitter', dt + '.txt')

class DefaultTeacher(DialogTeacher):
    def __init__(self, opt, shared=None):
        self.datatype = opt['datatype']
        build(opt)  # NOTE: the call to build here
        suffix = 'train' if opt['datatype'].startswith('train') else 'dev'
        # whatever is placed into datafile will be passed as the argument to
        # setup_data in the next section.
        opt['datafile'] = os.path.join(
            opt['datapath'], 'SQuAD', suffix + '-v1.1.json')
        self.id = 'squad'
        super().__init__(opt, shared)

    def setup_data(self, path):
        print('loading: ' + path)
        with PathManager.open(path) as data_file:
            self.squad = json.load(data_file)['data']
        for article in self.squad:
            # each paragraph is a context for the attached questions
            for paragraph in article['paragraphs']:
                # each question is an example
                for qa in paragraph['qas']:
                    question = qa['question']
                    answers = tuple(a['text'] for a in qa['answers'])
                    context = paragraph['context']
                    yield (context + '\n' + question, answers), True
```
Run with `parlai display_data -t internal:tutorial_task`
 
**Expected behavior**
It should display data of SQuAD

**Logs**
Please paste the command line output:

```
loading: /Users/su/Desktop/MasterThesis/ParlAI/data/SQuAD/train-v1.1.json
Traceback (most recent call last):
  File "/Users/su/Desktop/MasterThesis/ParlAI/parlai/core/worlds.py", line 1397, in _create_task_agents
    task_agents = my_module.create_agents(opt)  # type: ignore
AttributeError: module 'parlai_internal.tasks.tutorial_task.agents' has no attribute 'create_agents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/parlai_env/bin/parlai", line 33, in <module>
    sys.exit(load_entry_point('parlai', 'console_scripts', 'parlai')())
  File "/Users/su/Desktop/MasterThesis/ParlAI/parlai/__main__.py", line 14, in main
    superscript_main()
  File "/Users/su/Desktop/MasterThesis/ParlAI/parlai/core/script.py", line 325, in superscript_main
    return SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "/Users/su/Desktop/MasterThesis/ParlAI/parlai/core/script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "/Users/su/Desktop/MasterThesis/ParlAI/parlai/scripts/display_data.py", line 116, in run
    return display_data(self.opt)
  File "/Users/su/Desktop/MasterThesis/ParlAI/parlai/scripts/display_data.py", line 75, in display_data
    world = create_task(opt, agent)
  File "/Users/su/Desktop/MasterThesis/ParlAI/parlai/core/worlds.py", line 1448, in create_task
    world = create_task_world(opt, user_agents, default_world=default_world)
  File "/Users/su/Desktop/MasterThesis/ParlAI/parlai/core/worlds.py", line 1412, in create_task_world
    task_agents = _create_task_agents(opt)
  File "/Users/su/Desktop/MasterThesis/ParlAI/parlai/core/worlds.py", line 1400, in _create_task_agents
    return create_task_agent_from_taskname(opt)
  File "/Users/su/Desktop/MasterThesis/ParlAI/parlai/core/teachers.py", line 2669, in create_task_agent_from_taskname
    task_agents = teacher_class(opt)
  File "/Users/su/Desktop/MasterThesis/ParlAI/parlai_internal/tasks/tutorial_task/agents.py", line 41, in __init__
    super().__init__(opt, shared)
  File "/Users/su/Desktop/MasterThesis/ParlAI/parlai/core/teachers.py", line 675, in __init__
    self.data = data_class(
  File "/Users/su/Desktop/MasterThesis/ParlAI/parlai/core/teachers.py", line 862, in __init__
    self._load(data_loader, opt['datafile'])
  File "/Users/su/Desktop/MasterThesis/ParlAI/parlai/core/teachers.py", line 907, in _load
    for i, episode in enumerate(self._read_episode(data_loader(datafile))):
  File "/Users/su/Desktop/MasterThesis/ParlAI/parlai/core/teachers.py", line 888, in _read_episode
    for entry, new in data_loader:
  File "/Users/su/Desktop/MasterThesis/ParlAI/parlai_internal/tasks/tutorial_task/agents.py", line 46, in setup_data
    with PathManager.open(path) as data_file:
TypeError: open() missing 1 required positional argument: 'path'
```

**Additional context**
I am new to ParlAI. I want to create my own tasks, agents, and models. Currently, I am following the [internal subfolder](https://github.com/facebookresearch/ParlAI/tree/main/example_parlai_internal) method. But maybe there's a better solution. It will be great if someone could tell me the best way to do so.

**Comment by liulaisusan** [comment]
Problem solved. I found the issue is I imported the wrong `PathManager`. It should be `parlai.utils.io`. This is kind confusing because in [tutorial](https://parl.ai/docs/tutorial_task.html#dialogteacher) is was not clarified.
