### ISSUE TITLE
The docker is no work

### ISSUE THREAD

**Issue by aijianiula0601** [facebookresearch/ParlAI#5035]
https://www.parl.ai/docs/tutorial_quick.html
The docker provided here still cannot run directly after entering it, and some dependencies need to be installed by itself. The environment of this project is difficult to configure. Please provide a workable environment docker.

I want to run the run.py in  ”~/ParlAI/parlai/crowdsourcing/tasks/pairwise_per_turn_eval“

**Comment by aijianiula0601** [comment]
Starting to map topics to episodes.
Finished mapping topics to episodes.
Starting to map personas to topics.
Finished mapping personas to topics.
npm WARN server@1.0.0 No description
npm WARN server@1.0.0 No repository field.
npm WARN server@1.0.0 No license field.
[2023-05-17 18:22:48,673][sh.command][INFO] - <Command '/bin/rm -rf /root/mephisto-data/data/data/runs/NO_PROJECT/6/build/router'>: starting process
[2023-05-17 18:22:48,878][sh.command][INFO] - <Command '/bin/rm -rf /root/mephisto-data/data/data/runs/NO_PROJECT/6/build/router', pid 1269>: process started
[2023-05-17 18:22:49,241][sh.command][INFO] - <Command '/bin/rm -rf /root/mephisto-data/data/data/runs/NO_PROJECT/6/build/router', pid 1269>: process completed
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm ERR! Linux 4.9.70-040970-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
npm ERR! Linux 4.9.70-040970-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
npm ERR! Linux 4.9.70-040970-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
npm ERR! Linux 4.9.70-040970-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/anaconda3/lib/python3.8/site-packages/mephisto/abstractions/blueprints/parlai_chat/webapp/npm-debug.log
[05/17/23 18:22:55] ERROR    Encountered error while launching run, shutting down                                                                                                                                                                                                                              operator.py:302
                             Traceback (most recent call last):
                               File "/root/anaconda3/lib/python3.8/site-packages/mephisto/operations/operator.py", line 287, in launch_task_run_or_die
                                 built_dir = live_run.architect.prepare()
                               File "/root/anaconda3/lib/python3.8/site-packages/mephisto/abstractions/architects/local_architect.py", line 134, in prepare
                                 self.server_dir = build_router(
                               File "/root/anaconda3/lib/python3.8/site-packages/mephisto/abstractions/architects/router/build_router.py", line 114, in build_router
                                 task_builder.build_in_dir(local_server_directory_path)
                               File "/root/anaconda3/lib/python3.8/site-packages/mephisto/abstractions/blueprints/parlai_chat/parlai_chat_task_builder.py", line 169, in build_in_dir
                                 self.rebuild_core()
                               File "/root/anaconda3/lib/python3.8/site-packages/mephisto/abstractions/blueprints/parlai_chat/parlai_chat_task_builder.py", line 48, in rebuild_core
                                 raise Exception(
                             Exception: please make sure npm is installed, otherwise view the above error for more info.
[2023-05-17 18:22:55,805][mephisto.operations.operator][ERROR] - Encountered error while launching run, shutting down
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/mephisto/operations/operator.py", line 287, in launch_task_run_or_die
    built_dir = live_run.architect.prepare()
  File "/root/anaconda3/lib/python3.8/site-packages/mephisto/abstractions/architects/local_architect.py", line 134, in prepare
    self.server_dir = build_router(
  File "/root/anaconda3/lib/python3.8/site-packages/mephisto/abstractions/architects/router/build_router.py", line 114, in build_router
    task_builder.build_in_dir(local_server_directory_path)
  File "/root/anaconda3/lib/python3.8/site-packages/mephisto/abstractions/blueprints/parlai_chat/parlai_chat_task_builder.py", line 169, in build_in_dir
    self.rebuild_core()
  File "/root/anaconda3/lib/python3.8/site-packages/mephisto/abstractions/blueprints/parlai_chat/parlai_chat_task_builder.py", line 48, in rebuild_core
    raise Exception(
Exception: please make sure npm is installed, otherwise view the above error for more info.
                    ERROR    Could not shut down architect: shutdown called before deploy                                                                                                                                                                                                                      operator.py:308
                             Traceback (most recent call last):
                               File "/root/anaconda3/lib/python3.8/site-packages/mephisto/operations/operator.py", line 287, in launch_task_run_or_die
                                 built_dir = live_run.architect.prepare()
                               File "/root/anaconda3/lib/python3.8/site-packages/mephisto/abstractions/architects/local_architect.py", line 134, in prepare
                                 self.server_dir = build_router(
                               File "/root/anaconda3/lib/python3.8/site-packages/mephisto/abstractions/architects/router/build_router.py", line 114, in build_router
                                 task_builder.build_in_dir(local_server_directory_path)
                               File "/root/anaconda3/lib/python3.8/site-packages/mephisto/abstractions/blueprints/parlai_chat/parlai_chat_task_builder.py", line 169, in build_in_dir
                                 self.rebuild_core()
                               File "/root/anaconda3/lib/python3.8/site-packages/mephisto/abstractions/blueprints/parlai_chat/parlai_chat_task_builder.py", line 48, in rebuild_core
                                 raise Exception(
                             Exception: please make sure npm is installed, otherwise view the above error for more info.

                             During handling of the above exception, another exception occurred:

                             Traceback (most recent call last):
                               File "/root/anaconda3/lib/python3.8/site-packages/mephisto/operations/operator.py", line 306, in launch_task_run_or_die
                                 live_run.architect.shutdown()
                               File "/root/anaconda3/lib/python3.8/site-packages/mephisto/abstractions/architects/local_architect.py", line 190, in shutdown
                                 assert self.running_dir is not None, "shutdown called before deploy"
                             AssertionError: shutdown called before deploy
[2023-05-17 18:22:55,815][mephisto.operations.operator][ERROR] - Could not shut down architect: shutdown called before deploy
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/mephisto/operations/operator.py", line 287, in launch_task_run_or_die
    built_dir = live_run.architect.prepare()
  File "/root/anaconda3/lib/python3.8/site-packages/mephisto/abstractions/architects/local_architect.py", line 134, in prepare
    self.server_dir = build_router(
  File "/root/anaconda3/lib/python3.8/site-packages/mephisto/abstractions/architects/router/build_router.py", line 114, in build_router
    task_builder.build_in_dir(local_server_directory_path)
  File "/root/anaconda3/lib/python3.8/site-packages/mephisto/abstractions/blueprints/parlai_chat/parlai_chat_task_builder.py", line 169, in build_in_dir
    self.rebuild_core()
  File "/root/anaconda3/lib/python3.8/site-packages/mephisto/abstractions/blueprints/parlai_chat/parlai_chat_task_builder.py", line 48, in rebuild_core
    raise Exception(
Exception: please make sure npm is installed, otherwise view the above error for more info.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/mephisto/operations/operator.py", line 306, in launch_task_run_or_die
    live_run.architect.shutdown()
  File "/root/anaconda3/lib/python3.8/site-packages/mephisto/abstractions/architects/local_architect.py", line 190, in shutdown
    assert self.running_dir is not None, "shutdown called before deploy"
AssertionError: shutdown called before deploy
                    ERROR    Ran into error while launching run:                                                                                                                                                                                                                                               operator.py:522
                             Traceback (most recent call last):
                               File "/root/anaconda3/lib/python3.8/site-packages/mephisto/operations/operator.py", line 518, in launch_task_run
                                 return self.launch_task_run_or_die(
                               File "/root/anaconda3/lib/python3.8/site-packages/mephisto/operations/operator.py", line 312, in launch_task_run_or_die
                                 raise e
                               File "/root/anaconda3/lib/python3.8/site-packages/mephisto/operations/operator.py", line 287, in launch_task_run_or_die
                                 built_dir = live_run.architect.prepare()
                               File "/root/anaconda3/lib/python3.8/site-packages/mephisto/abstractions/architects/local_architect.py", line 134, in prepare
                                 self.server_dir = build_router(
                               File "/root/anaconda3/lib/python3.8/site-packages/mephisto/abstractions/architects/router/build_router.py", line 114, in build_router
                                 task_builder.build_in_dir(local_server_directory_path)
                               File "/root/anaconda3/lib/python3.8/site-packages/mephisto/abstractions/blueprints/parlai_chat/parlai_chat_task_builder.py", line 169, in build_in_dir
                                 self.rebuild_core()
                               File "/root/anaconda3/lib/python3.8/site-packages/mephisto/abstractions/blueprints/parlai_chat/parlai_chat_task_builder.py", line 48, in rebuild_core
                                 raise Exception(
                             Exception: please make sure npm is installed, otherwise view the above error for more info.
[2023-05-17 18:22:55,822][mephisto.operations.operator][ERROR] - Ran into error while launching run:
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/mephisto/operations/operator.py", line 518, in launch_task_run
    return self.launch_task_run_or_die(
  File "/root/anaconda3/lib/python3.8/site-packages/mephisto/operations/operator.py", line 312, in launch_task_run_or_die
    raise e
  File "/root/anaconda3/lib/python3.8/site-packages/mephisto/operations/operator.py", line 287, in launch_task_run_or_die
    built_dir = live_run.architect.prepare()
  File "/root/anaconda3/lib/python3.8/site-packages/mephisto/abstractions/architects/local_architect.py", line 134, in prepare
    self.server_dir = build_router(
  File "/root/anaconda3/lib/python3.8/site-packages/mephisto/abstractions/architects/router/build_router.py", line 114, in build_router
    task_builder.build_in_dir(local_server_directory_path)
  File "/root/anaconda3/lib/python3.8/site-packages/mephisto/abstractions/blueprints/parlai_chat/parlai_chat_task_builder.py", line 169, in build_in_dir
    self.rebuild_core()
  File "/root/anaconda3/lib/python3.8/site-packages/mephisto/abstractions/blueprints/parlai_chat/parlai_chat_task_builder.py", line 48, in rebuild_core
    raise Exception(
Exception: please make sure npm is installed, otherwise view the above error for more info.
                    INFO     operator shutting down                                                                                                                                                                                                                                                            operator.py:413
[2023-05-17 18:22:55,827][mephisto.operations.operator][INFO] - operator shutting down

**Comment by klshuster** [comment]
cc @mojtaba-komeili

**Comment by mojtaba-komeili** [comment]
The Docker image contains some of the necessary packages to run core parlai, and a few other more common module. Node.js, which is required by our crowdsourcing tasks are not included at the moment. However you can easily add it to your container environment.
* If you running an Interactive ParlAI shell, run `apt install nodejs npm`.
* Or alternatively build a new Dockerfile that looks something like this:
```
FROM ghcr.io/facebookresearch/parlai
apt install nodejs npm
```
And use that instead.
