### ISSUE TITLE
Problems  memnn_luatorch_cpu/full_task_train.py

### ISSUE THREAD

**Issue by craclog** [facebookresearch/ParlAI#510]
Hello, I'm trying to run example: 
`python memnn_luatorch_cpu/full_task_train.py -t babi:task10k:1 -nt 8`

But there is error message about Hogwild.

```
[ training ]
lua thread bound to tcp://*:5557
lua thread bound to tcp://*:5558
lua thread bound to tcp://*:5559
lua thread bound to tcp://*:5560
lua thread bound to tcp://*:5561
lua thread bound to tcp://*:5562
lua thread bound to tcp://*:5563
[ exs: 1577 | time: 1s | mean_rank: 5.70 | resp_loss: 0.82 | rank_loss: 0.16 ]
[ exs: 4136 | time: 2s | mean_rank: 3.37 | resp_loss: 0.81 | rank_loss: 0.10 ]
[ exs: 6639 | time: 3s | mean_rank: 3.42 | resp_loss: 0.82 | rank_loss: 0.10 ]
[synchronizing]
Traceback (most recent call last):
  File "memnn_luatorch_cpu/full_task_train.py", line 117, in <module>
    main()
  File "memnn_luatorch_cpu/full_task_train.py", line 95, in main
    world_train.synchronize()
AttributeError: 'HogwildWorld' object has no attribute 'synchronize'

```

As far as I know, Hogwild is a skill about multi-threading. Right?(I'm not sure)
so i run
`python memnn_luatorch_cpu/full_task_train.py -t babi:task10k:1`
this, but similar error occured like this:

```
[synchronizing]
Traceback (most recent call last):
  File "memnn_luatorch_cpu/full_task_train.py", line 117, in <module>
    main()
  File "memnn_luatorch_cpu/full_task_train.py", line 95, in main
    world_train.synchronize()
AttributeError: 'DialogPartnerWorld' object has no attribute 'synchronize'

```

**Comment by alexholdenmiller** [comment]
Thanks for reporting @craclog--I've got a fix for the AttributeError but I'm still tracking down a bug in training convergence.

**Comment by alexholdenmiller** [comment]
fix up

**Comment by alexholdenmiller** [comment]
Just FYI: we want to add a pytorch version of this #516
