### ISSUE TITLE
seq2seq module Parameter init code error

### ISSUE THREAD

**Issue by hsgodhia** [facebookresearch/ParlAI#533]
Hey
 
It seems in line
https://github.com/facebookresearch/ParlAI/blob/master/parlai/agents/seq2seq/modules.py#L422

self.weight being a Parameter object cannot be initialized like that, it throws the following error

```
Traceback (most recent call last):
  File "examples/train_model.py", line 237, in <module>
    TrainLoop(setup_args()).train()
  File "examples/train_model.py", line 124, in __init__
    self.agent = create_agent(opt)
  File "/home/harshals/ParlAI/parlai/core/agents.py", line 324, in create_agent
    return model_class(opt)
  File "/home/harshals/ParlAI/parlai/agents/seq2seq/seq2seq.py", line 204, in __init__
    longest_label=self.states.get('longest_label', 1))
  File "/home/harshals/ParlAI/parlai/agents/seq2seq/modules.py", line 39, in __init__
    attn_type=opt['attention'], attn_length=opt['attention_length'])
  File "/home/harshals/ParlAI/parlai/agents/seq2seq/modules.py", line 203, in __init__
    self.o2e = RandomProjection(hidden_size, emb_size)
  File "/home/harshals/ParlAI/parlai/agents/seq2seq/modules.py", line 418, in __init__
    self.reset_parameters()
  File "/home/harshals/ParlAI/parlai/agents/seq2seq/modules.py", line 422, in reset_parameters
    self.weight.normal_(std=0.1)
  File "/usr/local/lib/python3.6/site-packages/torch/autograd/variable.py", line 67, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Parameter' object has no attribute 'normal_'
```
triggered when my hidden state and embedding size (-hs 1024 -esz 300) is different

I believe this should fix
`self.weight.data.normal_(0.1)`

**Comment by alexholdenmiller** [comment]
Hi @hsgodhia, which version of torch are you using (`python -c 'import torch; print(torch.__version__)'`)?

**Comment by hsgodhia** [comment]
Hi.

I am using pytorch 0.30 and python 3.6

**Comment by alexholdenmiller** [comment]
Great I think the new functions are just in newer torch, I updated in #534 (merged) and that should fix it
