### ISSUE TITLE
Can we keep a mturk task from outside parlai/mturk/tasks?

### ISSUE THREAD

**Issue by deshraj** [facebookresearch/ParlAI#576]
Hi @JackUrb, I have a few questions regarding the mturk evaluation:

1. This link (http://parl.ai/static/docs/mturk.html#running-a-task) says that 

> to run an MTurk task, first ensure that the task directory is in `parlai/mturk/tasks/`. 

 Is it by design? I tried to keep my task in some other directory (outside root parlai directory) and tried to import parlai as a package but that doesn't seem to work. Basically I am trying to use ParlAI as one of the dependency for one of my project for Human In the loop evaluation.

2. How easy/hard it is to provide support for keeping the mturk task anywhere?

**Comment by JackUrb** [comment]
This is by design within the ParlAI platform, as it allows use of the default ParlAI datapath (say you want to load up a model like in the QA_data_collection task, it uses the ParlAI datapath to locate and load the squad agent) and would make it easier to convert whatever you create into a ParlAI task, however it isn't necessarily required. You should be able to import and use ParlAI-MTurk elsewhere so I'm not 100% sure what is blocking you. Can you further explain what the issue with your import is?

You should be able to use:
```
from parlai.core.params import ParlaiParser
from <your_task_dir>.worlds import <your_world_files>
from parlai.mturk.core.mturk_manager import MTurkManager
```
as long as you've installed the parlai package, and then your run file should be able to be similar to the ones in the existing demos.

**Comment by deshraj** [comment]
Thanks @JackUrb for the reply. 

Here is the error log:

```
deshraj at DESHRAJs-MacBook-Pro in ~/Documents/model_eval/model_eval/tasks/visdial_evaluator on master [!]
$ python run.py -nc 1 --sandbox --debug --verbose
[ optional arguments: ]
[  datapath: /Users/deshraj/Documents/model_eval/env/lib/python3.6/site-packages/data ]
[  length_penalty: 0.5 ]
[ Mechanical Turk: ]
[  mturk_log_path: /Users/deshraj/Documents/model_eval/env/lib/python3.6/site-packages/logs/mturk ]
[  task: None ]
[  num_conversations: 1 ]
[  unique_worker: False ]
[  unique_qual_name: None ]
[  reward: 0.0 ]
[  is_sandbox: True ]
[  is_debug: True ]
[  verbose: True ]
[  hard_block: False ]
[  log_level: 20 ]
[  block_qualification:  ]
[  count_complete: False ]
[  allowed_conversations: 0 ]
[  max_connections: 30 ]
[ Dictionary Arguments: ]
[  dict_file: None ]
[  dict_initpath: None ]
[  dict_language: english ]
[  dict_max_ngram_size: -1 ]
[  dict_minfreq: 0 ]
[  dict_maxtokens: -1 ]
[  dict_nulltoken: __NULL__ ]
[  dict_starttoken: __START__ ]
[  dict_endtoken: __END__ ]
[  dict_unktoken: __UNK__ ]
[  dict_maxexs: -1 ]
[  dict_tokenizer: split ]
[  dict_lower: False ]

You are going to allow workers from Amazon Mechanical Turk to be an agent in ParlAI.
During this process, Internet connection is required, and you should turn off your computer's auto-sleep feature.
Enough HITs will be launched over time up to a max of 1.5 times the amount requested until the desired number of conversations start.
Please press Enter to continue...

Setting up MTurk server...
Heroku: Collecting files...
Traceback (most recent call last):
  File "run.py", line 89, in <module>
    main()
  File "run.py", line 36, in main
    mturk_manager.setup_server()
  File "/Users/deshraj/Documents/model_eval/env/lib/python3.6/site-packages/parlai/mturk/core/mturk_manager.py", line 745, in setup_server
    self.task_files_to_copy)
  File "/Users/deshraj/Documents/model_eval/env/lib/python3.6/site-packages/parlai/mturk/core/server_utils.py", line 213, in setup_server
    task_files_to_copy=task_files_to_copy
  File "/Users/deshraj/Documents/model_eval/env/lib/python3.6/site-packages/parlai/mturk/core/server_utils.py", line 92, in setup_heroku_server
    task_directory_path
  File "/Users/deshraj/Documents/model_eval/env/lib/python3.6/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/Users/deshraj/Documents/model_eval/env/lib/python3.6/site-packages/sh.py", line 774, in __init__
    self.wait()
  File "/Users/deshraj/Documents/model_eval/env/lib/python3.6/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/Users/deshraj/Documents/model_eval/env/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:

  RAN: /bin/mv /Users/deshraj/Documents/model_eval/env/lib/python3.6/site-packages/parlai/mturk/core/heroku_server_8c6eac4d-visdialevaluator/html /Users/deshraj/Documents/model_eval/env/lib/python3.6/site-packages/parlai/mturk/core/heroku_server_8c6eac4d-visdialevaluator/task

  STDOUT:


  STDERR:
mv: rename /Users/deshraj/Documents/model_eval/env/lib/python3.6/site-packages/parlai/mturk/core/heroku_server_8c6eac4d-visdialevaluator/html to /Users/deshraj/Documents/model_eval/env/lib/python3.6/site-packages/parlai/mturk/core/heroku_server_8c6eac4d-visdialevaluator/task: No such file or directory
```

It looks like there doesn't exist the `html` directory. After hacking into the codebase, I realized that the html files are not copied when `setup.py install` is run. I have created the PR #581 which fixes this. Please let me know if there are changes required.
