### ISSUE TITLE
AttributeError: 'module' object has no attribute 'create_agents'

### ISSUE THREAD

**Issue by aleSuglia** [facebookresearch/ParlAI#682]
Hi there,

I am experiencing some errors while using ParlAI with Python 3.4.5 In particular I got the following exception:
```
[loading fbdialog data:cornell_movie/CornellMovie/train.txt]
Traceback (most recent call last):
  File "/tmp/asuglia/ParlAI/parlai/core/agents.py", line 429, in _create_task_agents
    create_agent = getattr(my_module, 'create_agents')
AttributeError: 'module' object has no attribute 'create_agents'
```
Another related exception is raised in this case:
```
Traceback (most recent call last):
  File "parlai_exporter.py", line 76, in <module>
    main(args)
  File "parlai_exporter.py", line 64, in main
    dataset = read_dataset_data(datasets[dataset_id])
  File "parlai_exporter.py", line 28, in read_dataset_data
    world = create_task(opt, agent)
  File "/tmp/asuglia/ParlAI/parlai/core/worlds.py", line 992, in create_task
    world = create_task_world(opt, user_agents)
  File "/tmp/asuglia/ParlAI/parlai/core/worlds.py", line 967, in create_task_world
    world_class, task_agents = _get_task_world(opt, user_agents)
  File "/tmp/asuglia/ParlAI/parlai/core/worlds.py", line 937, in _get_task_world
    task_agents = _create_task_agents(opt)
  File "/tmp/asuglia/ParlAI/parlai/core/agents.py", line 433, in _create_task_agents
    return create_task_agent_from_taskname(opt)
  File "/tmp/asuglia/ParlAI/parlai/core/agents.py", line 395, in create_task_agent_from_taskname
    task_agents = teacher_class(opt)
  File "/tmp/asuglia/ParlAI/parlai/tasks/cornell_movie/agents.py", line 26, in __init__
    super().__init__(opt, shared)
  File "/tmp/asuglia/ParlAI/parlai/core/teachers.py", line 832, in __init__
    super().__init__(opt, shared)
  File "/tmp/asuglia/ParlAI/parlai/core/teachers.py", line 401, in __init__
    cands=self.label_candidates(), **kwargs)
  File "/tmp/asuglia/ParlAI/parlai/core/teachers.py", line 495, in __init__
    self._load(data_loader, opt['datafile'])
  File "/tmp/asuglia/ParlAI/parlai/core/teachers.py", line 570, in _load
    for episode in self._read_episode(data_loader(datafile)):
  File "/tmp/asuglia/ParlAI/parlai/core/teachers.py", line 513, in _read_episode
    for entry, new in data_generator:
  File "/tmp/asuglia/ParlAI/parlai/core/teachers.py", line 920, in setup_data
    conv_id = int(line[:space_idx])
```
This happens when I try to use the Cornell Movie dialogue datasets. Seems to me that on Python 3.6 there are no problems.

Do you have any clues about this problem?

Cheers,
Alessandro

**Comment by alexholdenmiller** [comment]
Hi Alessandro, the first exception is expected and is actually caught if not for the second one. I don't see anything obvious about why `conv_id = int(line[:space_idx])` would fail on an earlier version of python.

Could you run your command again with `python -m pdb -c c`, and see if anything looks weird about the contents of `line`?

**Comment by alexholdenmiller** [comment]
We are all using Python 3.6 so we haven't experienced this particular issue

**Comment by fizzxed** [comment]
On python 3.6
`python examples/display_data.py -t opensubtitles:v2009 -dt train`
Gives me a similar error, but 
`python examples/display_data.py -t opensubtitles:v2009 -dt train:stream`
does not. Any ideas why?

**Comment by alexholdenmiller** [comment]
thank you @fizzxed that's reproing for me, I'll fix it

**Comment by alexholdenmiller** [comment]
both should be fixed now, thanks for flagging!
