### ISSUE TITLE
Seq2Seq on Reddit movie task throws RuntimeError midway through training

### ISSUE THREAD

**Issue by atalreja** [facebookresearch/ParlAI#721]
Hi, when running the following command with python 3.6.5 and pytorch 0.3.1 

```python examples/train_model.py -t "#moviedd-reddit" -dt train:stream -bs 1 -clen 3 -m seq2seq -mf /tmp/s2s -ltim 30 -vtim 30 -stim 30 -vcut 0.95 --dict-maxtokens 50000``` 

The model starts to train but after a few printouts it fails with the following error stack

```Traceback (most recent call last):
  File "examples/train_model.py", line 275, in <module>
    TrainLoop(setup_args()).train()
  File "examples/train_model.py", line 252, in train
    stop_training = self.validate()
  File "examples/train_model.py", line 176, in validate
    valid_world=self.valid_world)
  File "examples/train_model.py", line 106, in run_eval
    valid_world.parley()
  File "/home/atalreja/code/ParlAI/parlai/core/worlds.py", line 286, in parley
    acts[1] = agents[1].act()
  File "/home/atalreja/code/ParlAI/parlai/agents/seq2seq/seq2seq.py", line 570, in act
    return self.batch_act([self.observation])[0]
  File "/home/atalreja/code/ParlAI/parlai/agents/seq2seq/seq2seq.py", line 546, in batch_act
    predictions, text_cand_inds = self.predict(xs, ys, cands, valid_cands, is_training)
  File "/home/atalreja/code/ParlAI/parlai/agents/seq2seq/seq2seq.py", line 459, in predict
    _, scores, _ = self.model(xs, ys)
  File "/home/atalreja/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/atalreja/code/ParlAI/parlai/agents/seq2seq/modules.py", line 73, in forward
    y_in = ys.narrow(1, 0, ys.size(1) - 1)
RuntimeError: invalid argument 5: out of range at /pytorch/torch/lib/THC/generic/THCTensor.c:468
```

I think it might have to do with the context length setting because I was trying different values for that. Sorry for the lack of details, I'll continue trying different options

Thanks!

**Comment by alexholdenmiller** [comment]
Thanks for reporting! I'm able to reproduce and will work on a fix

**Comment by alexholdenmiller** [comment]
fixed, please pull and try again!

**Comment by alexholdenmiller** [comment]
feel free to reopen if you find any more issues

**Comment by atalreja** [comment]
Thanks for a super prompt fix! Really appreciate it. Unsure if this belongs in the same issue but I'm now trying to use that model to rank candidates so I can get a measure similar to the one from the convai2 example [here](https://github.com/facebookresearch/ParlAI/blob/2ecbdcc5802586d042e9c0d874b77969b1a40392/projects/convai2/baselines/seq2seq/eval_hits.py)

To do that i'm using the command 
```python examples/eval_model.py -t "#moviedd-reddit" -m seq2seq -mf /tmp/s2s --dict-file /tmp/s2s.dict -rc True -bs 1--gpu 0 -tr 48```

which is failing almost immediately with the following trace:

```
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "examples/eval_model.py", line 20, in <module>
    eval_model(opt, print_parser=parser)
  File "/home/atalreja/code/ParlAI/parlai/scripts/eval_model.py", line 74, in eval_model
    world.parley()
  File "/home/atalreja/code/ParlAI/parlai/core/worlds.py", line 286, in parley
    acts[1] = agents[1].act()
  File "/home/atalreja/code/ParlAI/parlai/agents/seq2seq/seq2seq.py", line 591, in act
    return self.batch_act([self.observation])[0]
  File "/home/atalreja/code/ParlAI/parlai/agents/seq2seq/seq2seq.py", line 567, in batch_act
    predictions, text_cand_inds = self.predict(xs, ys, cands, valid_cands, is_training)
  File "/home/atalreja/code/ParlAI/parlai/agents/seq2seq/seq2seq.py", line 472, in predict
    out = self.model(xs, ys=None, cands=cands, valid_cands=valid_cands)
  File "/home/atalreja/anaconda3/envs/baselines/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/atalreja/code/ParlAI/parlai/agents/seq2seq/modules.py", line 88, in forward
    hidden, enc_out, attn_mask)
  File "/home/atalreja/code/ParlAI/parlai/agents/seq2seq/modules.py", line 342, in forward
    _preds, score, _h = self.decoder(starts, cands_hn, enc_out, attn_mask)
  File "/home/atalreja/anaconda3/envs/baselines/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/atalreja/code/ParlAI/parlai/agents/seq2seq/modules.py", line 254, in forward
    xes = F.dropout(self.lt(xs), p=self.dropout, training=self.training)
  File "/home/atalreja/anaconda3/envs/baselines/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/atalreja/anaconda3/envs/baselines/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 103, in forward
    self.scale_grad_by_freq, self.sparse
  File "/home/atalreja/anaconda3/envs/baselines/lib/python3.6/site-packages/torch/nn/_functions/thnn/sparse.py", line 59, in forward
    output = torch.index_select(weight, 0, indices.view(-1))
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
```

I looked through the previous issues about running out of memory / cuda memory and tried setting the `-tr` flag but that doesn't seem to have stopped it. Not sure if I'm going about this the completely right way. Thanks!

**Comment by alexholdenmiller** [comment]
Hey sorry missed this notification, so the candidate ranking code is very memory-inefficient currently, and since the candidate set for this dataset is quite large this model is not going to be able to handle it. You'll have to run on CPU (very slowly), choose a different model for ranking, or submit a PR for a memory-friendly implementation.

Since this model doesn't do ranking during training, even a well-trained version does not seem to do very well on ranking anyways, so I wouldn't recommend using this model for that.
