### ISSUE TITLE
parlai support for Chinese

### ISSUE THREAD

**Issue by haow85** [facebookresearch/ParlAI#765]
I want parlai to support Chinese ，so I did the following modification:

In core.dict.py I changed the nltk tokenizer to be :

`self.word_tok = nltk.tokenize.stanford_segmenter.StanfordSegmenter()`
and 
`group.set_defaults(dict_tokenizer='nltk')`

The program reported an error related to generator type error, so in agents.drqa.py , I fixed it by adding：

`inputs['document'] = list(inputs['document'])
inputs['question'] = list(inputs['question'])`

before `inputs = vectorize(self.opt, inputs, self.word_dict, self.feature_dict)` . Later, I encountered the following problem  when I ran `python interactive -m drqa -mf squad.mdl`:

[creating task(s): parlai.agents.local_human.local_human:LocalHumanAgent]
Enter Your Message: Blue is a color. \n What is blue ?
Traceback (most recent call last):
  File "interactive.py", line 53, in <module>
    interactive(setup_args().parse_args())
  File "interactive.py", line 42, in interactive
    world.parley()
  File "/root/miniconda2/envs/py36/lib/python3.6/site-packages/parlai-0.1.0-py3.6.egg/parlai/core/worlds.py", line 286, in parley
    acts[1] = agents[1].act()
  File "/root/miniconda2/envs/py36/lib/python3.6/site-packages/parlai-0.1.0-py3.6.egg/parlai/agents/drqa/drqa.py", line 182, in act
    cuda=self.opt['cuda'])
  File "/root/miniconda2/envs/py36/lib/python3.6/site-packages/parlai-0.1.0-py3.6.egg/parlai/agents/drqa/utils.py", line 130, in batchify
    x1_f = torch.zeros(len(docs), max_length, features[0].size(1))
RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)
(py36) [root@5426d00374dc scripts]# 

How do I fix this ? BTW, is there any trained Chinese models similar to squad.mdl ?_

**Comment by alexholdenmiller** [comment]
I'm guessing your fix to the generator error broke it--features[0].size(1) for some reason is now a single-dimensional tensor instead of two-dimensional. Master doesn't break on that line. Can you report the generator error?

**Comment by haow85** [comment]
If I do not transform input['document'] and input['question'] into lists , I obtain the following error : 

[creating task(s): parlai.agents.local_human.local_human:LocalHumanAgent]
Enter Your Message: Blue is a color. \n What is blu e?
Traceback (most recent call last):
  File "interactive.py", line 53, in <module>
    interactive(setup_args().parse_args())
  File "interactive.py", line 42, in interactive
    world.parley()
  File "/root/miniconda2/envs/py36/lib/python3.6/site-packages/parlai-0.1.0-py3.6.egg/parlai/core/worlds.py", line 286, in parley
    acts[1] = agents[1].act()
  File "/root/miniconda2/envs/py36/lib/python3.6/site-packages/parlai-0.1.0-py3.6.egg/parlai/agents/drqa/drqa.py", line 178, in act
    ex = self._build_ex(self.observation)
  File "/root/miniconda2/envs/py36/lib/python3.6/site-packages/parlai-0.1.0-py3.6.egg/parlai/agents/drqa/drqa.py", line 294, in _build_ex
    inputs = vectorize(self.opt, inputs, self.word_dict, self.feature_dict)
  File "/root/miniconda2/envs/py36/lib/python3.6/site-packages/parlai-0.1.0-py3.6.egg/parlai/agents/drqa/utils.py", line 70, in vectorize
    features = torch.zeros(len(ex['document']), len(feature_dict))
TypeError: object of type 'generator' has no len()

**Comment by alexholdenmiller** [comment]
Try changing len(ex[‘document’]) to len(document), let me know if that works!

**Comment by haow85** [comment]
I replaced all ex['document'] in drqa.utils.py with document, and undid the list transformation applied in drqa.drqa.py , but still I got the following error related to PyTorch tensor dimensions ：

Enter Your Message: Blue is a color . \n What is color ?
Traceback (most recent call last):
  File "interactive.py", line 53, in <module>
    interactive(setup_args().parse_args())
  File "interactive.py", line 42, in interactive
    world.parley()
  File "/root/miniconda2/envs/py36/lib/python3.6/site-packages/parlai-0.1.0-py3.6.egg/parlai/core/worlds.py", line 286, in parley
    acts[1] = agents[1].act()
  File "/root/miniconda2/envs/py36/lib/python3.6/site-packages/parlai-0.1.0-py3.6.egg/parlai/agents/drqa/drqa.py", line 182, in act
    cuda=self.opt['cuda'])
  File "/root/miniconda2/envs/py36/lib/python3.6/site-packages/parlai-0.1.0-py3.6.egg/parlai/agents/drqa/utils.py", line 130, in batchify
    x1_f = torch.zeros(len(docs), max_length, features[0].size(1))
RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)

**Comment by alexholdenmiller** [comment]
hi @haow85, did you have any luck resolving? my guess is that on line 70 of drqa/utils.py (`features = torch.zeros(len(ex['document']), len(feature_dict))`), one of those two arguments is zero, so it's making a one-dimensional tensor instead of two

**Comment by haow85** [comment]
My docker image was broken a couple of days ago, so I reinstalled the system including pytorch. Now I miss the aforementioned problem, but I have the following new issue : 

/usr/local/miniconda/envs/py36/lib/python3.6/site-packages/parlai-0.1.0-py3.6.egg/parlai/core/dict.py:200: DeprecationWarning: 
The StanfordTokenizer will be deprecated in version 3.2.5.
Please use nltk.parse.corenlp.CoreNLPTokenizer instead.'
  self.word_tok = nltk.tokenize.stanford_segmenter.StanfordSegmenter()
Traceback (most recent call last):
  File "interactive.py", line 56, in <module>
    interactive(setup_args().parse_args())
  File "interactive.py", line 40, in interactive
    agent = create_agent(opt, requireModelExists=True)
  File "/usr/local/miniconda/envs/py36/lib/python3.6/site-packages/parlai-0.1.0-py3.6.egg/parlai/core/agents.py", line 344, in create_agent
    model = model_class(opt)
  File "/usr/local/miniconda/envs/py36/lib/python3.6/site-packages/parlai-0.1.0-py3.6.egg/parlai/agents/drqa/drqa.py", line 106, in __init__
    word_dict = DrqaAgent.dictionary_class()(opt)
  File "/usr/local/miniconda/envs/py36/lib/python3.6/site-packages/parlai-0.1.0-py3.6.egg/parlai/agents/drqa/drqa.py", line 54, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/miniconda/envs/py36/lib/python3.6/site-packages/parlai-0.1.0-py3.6.egg/parlai/core/dict.py", line 200, in __init__
    self.word_tok = nltk.tokenize.stanford_segmenter.StanfordSegmenter() 
  File "/usr/local/miniconda/envs/py36/lib/python3.6/site-packages/nltk/tokenize/stanford_segmenter.py", line 79, in __init__
    verbose=verbose)
  File "/usr/local/miniconda/envs/py36/lib/python3.6/site-packages/nltk/internals.py", line 721, in find_jar
    searchpath, url, verbose, is_regex))
  File "/usr/local/miniconda/envs/py36/lib/python3.6/site-packages/nltk/internals.py", line 716, in find_jar_iter
    raise LookupError('\n\n%s\n%s\n%s' % (div, msg, div))
LookupError: 

===========================================================================
  NLTK was unable to find stanford-segmenter.jar! Set the CLASSPATH
  environment variable.

  For more information, on stanford-segmenter.jar, see:
    <https://nlp.stanford.edu/software>
===========================================================================

**Comment by alexholdenmiller** [comment]
hm it looks like you need to install a separate java .jar for the stanford segmenter now in your new version of nltk. I know CoreNLP requires something similar (e.g. in the DrQA main repo: https://github.com/facebookresearch/DrQA/blob/master/install_corenlp.sh). I expect that the nlp.stanford.edu site has the jar you need.

**Comment by alexholdenmiller** [comment]
I'm going to close this for now, feel free to reopen if you have any more comments!
