### ISSUE TITLE
cuda run time error : out of memory  when training the personaseq2seq

### ISSUE THREAD

**Issue by zhaoguangxiang** [facebookresearch/ParlAI#828]
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zhaoguangxiang/ParlAI/examples/train_model.py", line 28, in <module>
    TrainLoop(opt).train()
  File "/home/zhaoguangxiang/ParlAI/parlai/scripts/train_model.py", line 256, in train
    stop_training = self.validate()
  File "/home/zhaoguangxiang/ParlAI/parlai/scripts/train_model.py", line 180, in validate
    valid_world=self.valid_world)
  File "/home/zhaoguangxiang/ParlAI/parlai/scripts/train_model.py", line 108, in run_eval
    valid_world.parley()
  File "/home/zhaoguangxiang/ParlAI/parlai/core/worlds.py", line 666, in parley
    batch_act = self.batch_act(agent_idx, batch_observations[agent_idx])
  File "/home/zhaoguangxiang/ParlAI/parlai/core/worlds.py", line 639, in batch_act
    batch_actions = a.batch_act(batch_observation)
  File "/home/zhaoguangxiang/ParlAI/projects/personachat/persona_seq2seq.py", line 2257, in batch_act
    predictions, text_cand_inds = self.predict(xs, xs_persona, ys, cands, zs)
  File "/home/zhaoguangxiang/ParlAI/projects/personachat/persona_seq2seq.py", line 2057, in predict
    encoder_output_persona, hidden_persona, hidden, attn_mask)
  File "/home/zhaoguangxiang/ParlAI/projects/personachat/persona_seq2seq.py", line 1999, in _score_candidates
    preds, scores = self.hidden_to_idx(output, is_training=False)
  File "/home/zhaoguangxiang/ParlAI/projects/personachat/persona_seq2seq.py", line 1475, in hidden_to_idx
    scores = F.log_softmax(scores)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/functional.py", line 786, in log_softmax
    return torch._C._nn.log_softmax(input, dim)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58

**Comment by alexholdenmiller** [comment]
You'll probably need to reduce your batchsize with `-bs X` to stay within the bounds of your particular GPU's capacity.

**Comment by zhaoguangxiang** [comment]
Thank you , the bug is fixed.
