### ISSUE TITLE
use shared copy of agents for validation rather than original

### ISSUE THREAD

**Issue by ar-ms** [facebookresearch/ParlAI#838]
Hello, I have some problems trying to validate my model on personachat.

During the training the persona is provided in observation['text'], but at some point after the validation, it return to training, but this time the persona is not anymore provided, is that normal ?

I'm using the train file located in projects, following command:
`python -m projects.convai2.baselines.kvmemnn.train`

This is the tracelog:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/arms/research/ParlAI/projects/convai2/baselines/kvmemnn/train.py", line 45, in <module>
    TrainLoop(parser.parse_args()).train()
  File "/home/arms/research/ParlAI/parlai/scripts/train_model.py", line 248, in train
    world.parley()
  File "/home/arms/research/ParlAI/parlai/core/worlds.py", line 240, in parley
    acts[1] = agents[1].act()
  File "/home/arms/research/ParlAI/projects/personachat/kvmemnn/arms.py", line 493, in act
    return self.batch_act([self.observation])[0]
  File "/home/arms/research/ParlAI/projects/personachat/kvmemnn/arms.py", line 453, in batch_act
    predictions = self.predict(xs, cands, persona, ys, is_training)
  File "/home/arms/research/ParlAI/projects/personachat/kvmemnn/arms.py", line 301, in predict
    pred = self.model(xs, cands, persona, ys)
  File "/home/arms/venv3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/arms/research/ParlAI/projects/personachat/kvmemnn/arms.py", line 94, in forward
    encoded_persona = torch.stack(encoded_persona)
RuntimeError: expected a non-empty list of Tensors
```

and this is the received observations dict:
```
[{'episode_done': False,
  'id': 'convai2:self',
  'label_candidates': ('yeah i work at a garden center in our community so '
                       'they like that',
                       'll , yes definitely . have you ever been ?',
                       'that must be cool . love movies . ever been on set ?',
                       'i check out new vendors who sell meals from trucks .',
                       'do you have tiny fingers then',
                       'pizza is good . hard to make . haha',
                       'me too . i work at a beach bar , not too many of those '
                       'in the mountains .',
                       'yes i do ! how about you ?',
                       'wow , i was just about to say my favorite genre is '
                       'rock',
                       'no its an anime book i like watching anime on tv too',
                       "i'dn't know , all i've is a parrot and a mother .",
                       'neat , i am actually in nursing school right now !',
                       'that is important . i did meditation on an app on my '
                       'phone before .',
                       'oh i ove them ! i want one',
                       "nice i hope you don't judge me too badly",
                       'you have to build up to it . why cannot you ?',
                       'no worries . i learned to be independent . but i '
                       'really enjoy being looked at .',
                       'nice . what do you teach ? i like to read so i do that '
                       'daily .',
                       'no its actually a movie',
                       'that is great ! i love children'),
  'labels': ('that is great ! i love children',),
  'reward': 0,
  'text': 'sorry 3 other kids , pregnant brain . they are 3 , 5 , and 7'}]
```

**Comment by ar-ms** [comment]
Just solved the issue, the problem is due to the fact that when it's time to predict, the actually trainning observation is override by the prediction obersation, then once the training start again as observations was override, observe() cannot prepend the previously seen observations. It was just a small verification to add to check if the actual episode is done in order to launch the prediction. I will do a pull request.

**Comment by jaseweston** [comment]
ah, yes it uses the same model so it doesn't change the state.. i guess it only affects 1 episode, then gets reset. during batching though it's slightly tricker to end all the episodes.. @alexholdenmiller  ? another option is save and then reset the state somehow, or else create a new agent with share

**Comment by alexholdenmiller** [comment]
right that's true, the agent can forget the state from before the validation. I've been thinking about this too--we could use `share` to create the validation agent, but that only works if the model parameters are shared with sub-agents, but currently only models supporting hogwild do that. We could make it more mandatory but that adds some complexity. The TorchAgent could handle this, though. Happy to take a look at a PR, though! We could at least fix this for non-batching.

**Comment by alexholdenmiller** [comment]
merged! you can now use -vshare to turn it on since many models will break when it's turned on, but I expect to default this to True in the future
