### ISSUE TITLE
First example in the README.md does not work

### ISSUE THREAD

**Issue by alexanderkjeldaas** [facebookresearch/ParlAI#91]
The following is the output from running the first example from the README.md:

```
$ python display_data.py -t babi:task1k:1
[task:babi:task1k:1]
[download_path:/somewhere/code/ParlAI/downloads]
[datatype:train]
[numthreads:1]
[batchsize:1]
[no_images:False]
[datapath:/somewhere/code/ParlAI/data]
[parlai_home:/somewhere/code/ParlAI]
[num_examples:10]
Traceback (most recent call last):
  File "display_data.py", line 42, in <module>
    main()
  File "display_data.py", line 29, in main
    agent = RepeatLabelAgent(opt)
  File "/somewhere/code/ParlAI/parlai/agents/repeat_label/agents.py", line 27, in __init__
    super().__init__(opt)
TypeError: super() takes at least 1 argument (0 given)
```

**Comment by ajfisch** [comment]
Hi,
Only Python 3 is supported at this time.
