### ISSUE TITLE
Following the guide for amazon mturk

### ISSUE THREAD

**Issue by Rainiwinkler** [facebookresearch/ParlAI#947]
When I try to set up my first amazonMTurk task, I come until the following point, where I should type in the following command:

`python run.py -nh 2 -r 0.05 --sandbox --verbose`

Normally it should load the database, but in my case two different error messages are displayed:
`PS C:\py3\ParlAI\parlai\mturk\tasks\model_evaluator> python run.py -nh 2 -r 0.05 --sandbox --verbose
Please install 3rd-party dependencies by running: pip install boto3 joblib websocket-client sh
>`

And the other is this one:

`PS C:\py3\ParlAI\parlai\mturk\tasks\model_evaluator> python run.py -nh 2 -r 0.05 --sandbox --verbose
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    from parlai.core.params import ParlaiParser
  File "C:\py3\ParlAI\parlai\core\params.py", line 16, in <module>
    from parlai.core.agents import get_agent_module, get_task_module
  File "C:\py3\ParlAI\parlai\core\agents.py", line 40, in <module>
    from parlai.core.build_data import modelzoo_path
  File "C:\py3\ParlAI\parlai\core\build_data.py", line 15, in <module>
    import requests
  File "C:\py3\ParlAI\requests\__init__.py", line 43, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'`

Does anyone have an idea how I can fix that? Thank you very much. It would be great to publish a task for training my bot

**Comment by JackUrb** [comment]
As in the error:
"Please install 3rd-party dependencies by running: pip install boto3 joblib websocket-client sh"
You'll have to enter the pip install command on the command line

**Comment by Rainiwinkler** [comment]
When I enter "pip install boto3 joblib websocket-client sh" in the command line, it says that all 
requirements are satisfied

    Requirement already satisfied: boto3 in c:\py3\lib\site-packages (1.7.52)
    Requirement already satisfied: joblib in c:\py3\lib\site-packages (0.12.0)
    Requirement already satisfied: websocket-client in c:\py3\lib\site-packages (0.48.0)
    Requirement already satisfied: sh in c:\py3\lib\site-packages (1.12.14)
    Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in c:\py3\lib\site-packages (from boto3) (0.9.3)
    Requirement already satisfied: botocore<1.11.0,>=1.10.52 in c:\py3\lib\site-packages (from boto3) 
    (1.10.52)
    Requirement already satisfied: s3transfer<0.2.0,>=0.1.10 in c:\py3\lib\site-packages (from boto3) 
    (0.1.13)
    Requirement already satisfied: six in c:\py3\lib\site-packages (from websocket-client) (1.11.0)
    Requirement already satisfied: python-dateutil<3.0.0,>=2.1; python_version >= "2.7" in c:\py3\lib\site- 
   packages (from bo
    tocore<1.11.0,>=1.10.52->boto3) (2.7.3)
    Requirement already satisfied: docutils>=0.10 in c:\py3\lib\site-packages (from 
   botocore<1.11.0,>=1.10.52->boto3) (0.14)

What else can be the reason why it doesn't work?

**Comment by AbdullaRifai** [comment]
Hello I am also having the same issue and when I try installing urllib3 I get the following 
`Requirement already satisfied: urllib3 in c:\users\rifai\appdata\local\programs\python\python37\lib\site-packages (1.25.9)`

So If there is no error why does it keep prompting me to install third party dependencies. Thanks in advance.

**Comment by JackUrb** [comment]
@AbdullaRifai do `which python` and `which pip` point to the same location?

**Comment by AbdullaRifai** [comment]
@JackUrb Yes

**Comment by JackUrb** [comment]
So if run `python` in your terminal, and then execute `import urllib3` in the shell, this import works fine, but `python <some parlai_mturk script>` fails? I can't really say what's wrong here - this failure occurs when trying to execute `import urllib3` so the python executable that you're running ParlAI-MTurk scripts from isn't able to find where `urllib3` is installed.

**Comment by AbdullaRifai** [comment]
`python parlai/mturk/tasks/acute_eval/fast_eval.py --ids  example_model_1,example_model_2,example_model_log,example_dataset -t blended_skill_talk`

`python parlai/mturk/tasks/acute_eval/fast_eval.py --id-pairs  example_model_1:example_model_2,example_model_1:example_model_log,example_dataset:example_model_2 -t blended_skill_talk`

I am trying to execute one of the two, and after searching for urllib3 I have found that is located in the following path **C:\Users\rifai\anaconda3\Lib\site-packages\jedi\third_party\typeshed\third_party\3\six\moves\urllib** I think that the installation of the library has been successful as no errors were shown, but not sure why those two commands keep prompting me with this message: "Please install 3rd-party dependencies by running: pip install boto3 joblib websocket-client sh"

**Comment by JackUrb** [comment]
FastEval requires all of the dependencies for ParlAI-MTurk, do you also have `boto3`, `joblib`, `websocket-client`, and `sh`. It looks to me like you're running on windows, and I'm pretty sure that `sh` isn't compatible with windows.

**Comment by AbdullaRifai** [comment]
Yeah I think it might be the `sh`  or the dependencies, I'll keep looking at it. Thanks for the input.

**Comment by SparshAgrawal1** [comment]
When I try to run the chat services it shows me the error "Please install 3rd-party dependencies by running: pip install joblib websocket-client sh" and whenever I try to install it via pip, it shows that requirement is already satisfied. Is the problem the problem with windows itself that we have to use pbs instead of sh or there is some emthod to resolve it?

**Comment by JackUrb** [comment]
Hi @SparshAgrawal1 - is the issue you're discussing about the MTurk integration? If not you should open a new issue.
