### ISSUE TITLE
AttributeError: module 'parlai.agents.drqa.agents' has no attribute 'DrqaAgent

### ISSUE THREAD

**Issue by bittlingmayer** [facebookresearch/ParlAI#99]
Following error when I try to run `python examples/display_model.py -m drqa -t "#opensubtitles" -dt valid`:

```
DrqaAgent

    Warning: no model found for 'en'

    Only loading the 'en' tokenizer.

Traceback (most recent call last):
  File "examples/display_model.py", line 42, in <module>
    main()
  File "examples/display_model.py", line 29, in main
    agent = create_agent(opt)
  File "/Users/bittlingmayer/Desktop/aca/ParlAI/parlai/core/agents.py", line 105, in create_agent
    model_class = getattr(my_module, class_name)
AttributeError: module 'parlai.agents.drqa.agents' has no attribute 'DrqaAgent
```

**Comment by bittlingmayer** [comment]
Related: When I try memnn, the following happens:

```
MemnnAgent
Traceback (most recent call last):
  File "examples/display_model.py", line 42, in <module>
    main()
  File "examples/display_model.py", line 29, in main
    agent = create_agent(opt)
  File "/Users/bittlingmayer/Desktop/aca/ParlAI/parlai/core/agents.py", line 104, in create_agent
    my_module = importlib.import_module(module_name)
  File "/Users/bittlingmayer/Desktop/aca/ParlAI/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'parlai.agents.memnn'
```

ir_baseline works.

**Comment by ajfisch** [comment]
`display_model.py` is only setup to work with the simple `repeat_label` and `ir_baseline` agents. There is some work to do to make all agents compatible with single display and train scripts, this is on the roadmap.

Note that the `examples/drqa` directory has separate scripts for eval, interactive, and train.

As for the missing 'en' model, you can install this with `python -m spacy download en`. (But not necessary... as for the provided drqa implementation the 'en' tokenizer is enough.)

**Comment by bittlingmayer** [comment]
Thanks much, all clear
